- lib/bolt_spec/run.rb
Inventory can be huge when read from a file and so the Inventory deletes
the version key to avoid copying the whole inventory. This will cause
BoltSpec to copy the inventory before creating an Inventory instance to
avoid mutating the callers inventory hash.
> (GH-1614) Deep copy config and inventory for the BoltSpec Runner

- CHANGELOG.md
- lib/bolt/inventory/inventory.rb
- spec/bolt/inventory/inventory_spec.rb
- spec/integration/inventory_spec.rb
This updates the inventory to only validate groups once all targets have
been expanded. Previously, when calling `get_targets` and creating each
target, the inventory would add that target to the necessary group and
then validate all groups with `@groups.validate`. This resulted in large
inventories taking an exponentially long time to load. Now, groups are
only validated once all targets have been created and added to groups.
> (maint) Validate inventory more efficiently

- CHANGELOG.md
- bolt-modules/boltlib/lib/puppet/functions/write_file.rb
- bolt-modules/boltlib/spec/functions/write_file_spec.rb
- spec/fixtures/modules/write_file/plans/init.pp
- spec/integration/modules/write_file_spec.rb
This adds a new `write_file` plan function that writes content to a
specified file on the given targets. Internally, the function uses the
`file::write` function to write content to a tempfile on `localhost` and
then uses the `upload_file` function to upload the tempfile to the
destination on the given targets.
Closes #1597
> (GH-1597) Add write_file plan function

- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/linux.yaml
- .github/workflows/modules.yaml
- .github/workflows/windows.yaml
- CHANGELOG.md
This updates the GitHub workflows to ignore markdown files at the root
of the repository, which were not caught by the glob pattern in the
`paths-ignore` field.
> (maint) Ignore markdown files in root for CI

- CHANGELOG.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/config.rb
- spec/bolt/cli_spec.rb
This adds support for a `--puppetfile` CLI option which accepts a
relative or absolute path to a Puppetfile to use when installing
modules with `bolt puppetfile install`. When using this flag, modules
will be installed to the current Boltdir. If a relative path is passed
to the option, it will be relative to the current Boltdir.
Closes #1612
> (GH-1612) Add --puppetfile CLI option

- CHANGELOG.md
- Puppetfile
The latest puppetlabs-reboot version updates the deprecated `nodes`
parameter to `targets`. This is a breaking change for users who
explicitly set the parameter, either in the `run_plan` plan function or
on the CLI. Users will need to update the `nodes` parameter to be
`targets` instead. Calling the plan using `-t` or with
`run_plan('reboot', $mytargets)` will both behave the same and do not
need to be updated.
> (maint) Bump puppetlabs-reboot module

- lib/bolt/pal.rb
- spec/bolt/cli_spec.rb
- spec/fixtures/modules/sample/plans/documented_param_typo.pp
Previously if there was a descrepency between the @param descriptions in plan metadata and the actual parameters in the plan signature there would be an unhandled exception trying to extract parameter descriptions. With this commit if there is a @param description that describes a parameter that is not in the plan function signature a warning is raised and the @param metadata is ignored.
> (maint) Warning instead of exceptiong whith invalid @param metadata

- CHANGELOG.md
- documentation/bolt_installing.md
This adds documentation for installing Bolt on MacOS 10.15.
Related PRs:
Closes #1445
> (GH-1445) Package Bolt for MacOS 10.15

- documentation/writing_plans.md
This is to address user feedback:
> While I definitely appreciate the cleverness of the “$ecret!” string in the “Passing sensitive data to tasks” section, it may be better to use a string that does not start with $ as that’s also how Puppet variable names start and this could be confusing for those less well-versed in Puppet.
FYI: `$ecret!` is also used a lot in the code, too. I figure the code isn't user-facing though.
> (Docs) Using a more generic password in the docs

- documentation/bolt_connect_puppetdb.md
This updates the PuppetDB docs to show the correct `server_urls` key
instead of `server-urls`.
> (docs) Fix incorrect server-urls key in PuppetDB connect docs

- spec/Dockerfile
This updates the Dockerfile for building images used in spec tests to
install the `apt-transport-https` package. The `puppet5` repo was
recently updated to pull packages from the `https` site, causing several
integration tests that installed packages from this collection to fail.
Adding the `apt-transport-https` package allows `apt` to download
packages from the `https` site.
> (maint) Update Docker container to install apt-transport-https

- documentation/CHANGELOG.md
Removing the unused changelog symlink in /documentation
> (Docs) Removing symlink for changelog

- documentation/reference.md.erb
This fixes the title in the Bolt functions reference doc to follow the
standard sentence case format.
> (maint) Fix title capitalization in Bolt functions reference doc

- CONTRIBUTING.md
- Rakefile
- developer-docs/releasing-bolt.md
- scripts/generate_changelog.rb
This adds a rake task that executes a script to generate changelog
entries from commit messages. To execute the rake task, run `rake
'changelog[VERSION]'`, where `VERSION` is the new tag.
The script filters commits listed by the `git log` command and parses
them based on valid `!` labels. The list of valid labels are `feature`,
`bug`, `removal`, and `deprecation`. The label is followed by the
formatted changelog entry.
Closes #1555 
A commit message with a changelog entry would look like this:
```
<commit message>
!feature
* **Added a rake task to generate changelog entries** ([#1555](https://github.com/puppetlabs/bolt/issues/1555))
Added a rake task that generates changelog entries from commit messages.
```
> (GH-1555) Automatically generate changelog from commit notes

- bolt.gemspec
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
This adds support for initializing a Bolt project with a set of
specified modules and their dependencies. A new CLI option `--modules`
accepts a comma-separated list of module names (e.g. `puppetlabs-apt`).
Bolt uses the `puppetfile-resolver` gem to parse the list of modules
provided at the CLI and then resolves a dependency graph for the
modules. If any of the specified modules or their dependencies are
missing, the command errors and the project directory is not created. If
the dependency graph is resolved successfully, the list of modules and
dependencies are written to a Puppetfile in the new project directory
and `bolt puppetfile install` is immediately run against this
Puppetfile.
Closes #1574
> (GH-1574) Initialize a Bolt project with modules

- CHANGELOG.md
- lib/bolt/config/transport/winrm.rb
- lib/bolt/transport/winrm.rb
- lib/bolt/transport/winrm/connection.rb
- spec/bolt/config/transport/winrm_spec.rb
- spec/bolt/inventory/inventory_spec.rb
This pull request adds an option for the winrm transport named `basic-auth-only`, which is by default set to false, but if set to true will force basic auth by passing the corresponding `basic_auth_only` option to the winrm gem.
If there is an easier solution to my issue than to force basic auth, I would gladly welcome any advice.
I set up winRM to use with basicAuth on a machine at our site. I was able to connect properly using plain winRM powershell commands where I can pass the auth method via `-Authentication Basic`. For bolt this was not possible, the connection failed with an `AUTH_ERROR` all the time.
I looked into the code and saw that bolt offers no option to enforce basic_auth, while the winrm gem offers this option via `basic_auth_only`.
> Enable to use basic_auth_only option from winrm gem

- Puppetfile
This bumps the `ruby_task_helper` and `python_task_helper` modules to
the latest versions, which add `debug` and `debug_statements` helper
methods.
Closes #1647
> (GH-1647) Bump task helper module versions

- lib/bolt/analytics.rb
- lib/bolt/config.rb
- spec/bolt/analytics_spec.rb
- spec/bolt/config_spec.rb
- spec/integration/apply_spec.rb
- spec/integration/transport/winrm_spec.rb
By default Bolt has 3 configuration file locations that get merged
together: project level, user level, and global. Project level config is
configurable (yo dawg...) using the `--configfile` CLI flag, but the 
user level and global configs are hard coded to
`~/.puppetlabs/etc/bolt/bolt.yaml` and `/etc/puppetlabs/bolt/bolt.yaml`
respectively. When `getlogin` returns nil loading the user level config
file will fail and error out trying to load `~`. This change catches the 
error and doesn't try to load user level config.
We also try to load a hard coded `~` path for analytics, at
`~/.puppetlabs/bolt/analytics.yaml`. Because loading the homedir will
typically only fail if getlogin isn't set when running Bolt through the 
Orchestrator or in other automated environments, we opt to disable …
> (GH-1671) Handle cases where loading paths with ~ fails

- lib/bolt/config.rb
This updates config validation to properly validate that a specified
Hiera config file exists. Previously, the config was accessing the wrong
value in the config data hash, preventing Bolt from validating that the
file exists.
!bug
* **Validate that a specified Hiera config file exists**
([#1692](https://github.com/puppetlabs/bolt/pulls/1692))
Bolt was not properly validating that a Hiera config file specified
with the `hiera-config` option in a `bolt.yaml` existed.
> (maint) Validate hiera-config setting

- .github/rulesets.yaml
- .github/workflows/release-notes.yaml
This adds a workflow that checks that at least one commit in a pull
request has a valid release note label. It uses the `rulesets` action to
match each commit's message against a regex, ensuring that at least one
commit matches the regex. This is used to ensure that release notes are
added to pull requests where needed and can be picked up by the
changelog rake task.
> (maint) Add workflow for release note labels on commits

- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
As part of the push to get orchestrator on 2.x it is expected that a bolt-server request will always expects a `status` and `value` key in the response. In most cases the Bolt::Result will have these keys. In the case where there is an error that is not target/action execution specific (in this case with a request schema validation error), return an error that has the `status` and `value` keys.
This commit also updates a stray `result` key to `value` in the scrub_stack_trace method.
> (PE-28373) Always return a result-like error result

- documentation/using_plugins.md
- lib/bolt/plugin/puppetdb.rb
- spec/bolt/plugin/puppetdb_spec.rb
When trying to implement some more complex inventory files using PuppetDB i ran into an issue when trying to use the `target_mapping` feature of the `puppetdb` plugin based on this example: https://puppet.com/docs/bolt/latest/using_plugins.html#example-usage-2
Running this as my inventory as shown in the example:
```yaml
version: 2
groups:
- name: puppetdb_wsus
targets:
- _plugin: puppetdb
query: "inventory[certname] { facts.osfamily = 'windows' }"
target_mapping:
name: certname
```
I kept getting an error: 
```
$ bolt inventory show --targets puppetdb_wsus
Could not find fact certname for node xxx
Could not find fact certname for node yyy
Could not find fact certname for node zzz
```
I dug into it a bit by querying the `fact-path` API in PuppetDB:
```bash
$ curl -s -k -X GET     --cacert …
```
> Fixed documentation for using the puppetdb plugin with certname fact

- documentation/bolt_installing_modules.md
An example puppetfile used to demonstrate installing modules in a Bolt
project included an outdated version of the `puppetlabs-facts` module.
When users copy-paste the example the outdated module would override
versions that ship with Bolt and cause other tasks and plans (such as
puppet_agent::install) to fail. This removes the module from the example
Puppetfile.
I also verified there were no other conflicting modules in our documentation :+1:
> (maint) Remove outdated facts module from bolt puppetfile example

- documentation/applying_manifest_blocks.md
- documentation/bolt.ditamap
- documentation/bolt_types_reference.md
- documentation/writing_plans.md
This adds reference documentation for the various data type functions
available in plans.
> **Note:** This commit includes two options for the reference docs. The
first includes the data type functions in the existing `Bolt functions`
reference doc, while the second introduces a new `Bolt data types`
reference doc.
Closes #1685
> (GH-1685) Add data type functions reference docs

- .rubocop.yml
- Rakefile
- resources/plugins.md
- resources/plugins.yaml
* This adds a yaml file with a list of plugins that generates a
markdown file of plugins via the `plugin_list` rake task.
* The markdown is generated dynamically via data from the plugins.yaml
file.
> Add new 3rd party plugin list

- Rakefile
- documentation/bolt_command_reference.md.erb
- lib/bolt/bolt_option_parser.rb
This updates the command reference page to only show the description and
usage for each command. Previously, the entire help text banner was
displayed.
The rake task that generates the reference uses named capture groups to
extract the relevant data from the help text banner.
> (maint) Only show descriptions and usages on command reference page

- resources/plugins.md
Adds two 3rd party plugins:
- [Consul Inventory Plugin](https://github.com/magec/puppetlabs-consul_inventory)
- [Hetzner Cloud Inventory Plugin](https://github.com/magec/puppetlabs-hcloud_inventory)
> Add 3rd party plugins to plugins list

- bolt-modules/boltlib/lib/puppet/datatypes/target.rb
- documentation/bolt_types_reference.md
- documentation/writing_plans.md
- lib/bolt/inventory/target.rb
- lib/bolt/target.rb
- spec/bolt/target_spec.rb
- spec/pal/target_spec.rb
This adds two functions to the `Target` data type in plans:
- `transport`
Returns the transport used to connect to the target.
- `transport_config`
Returns a hash of the merged transport config for the target,
including defaults, config set in a `bolt.yaml`, and config set at
the group and target level in an `inventory.yaml` or plan.
Closes #1686 
!feature
* **Added `transport` and `transport_config` functions to `Target` data
type** ([#1686](#1686))
The `Target` data type now supports a `transport` function, which
returns the transport used to connect to the target, and a
`transport_config` function, which returns a hash of merged
configuration for the target's transport.
> (GH-1686) Add transport and transport_config functions to Target type

- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/linux.yaml
- .github/workflows/modules.yaml
- .github/workflows/release-notes.yaml
- .github/workflows/windows.yaml
- Rakefile
This bumps the `checkout` action used in the CI workflows to `v2`.
> (maint) Bump checkout action to v2

- lib/bolt/util.rb
- spec/bolt/util_spec.rb
The internet suggests replacing `clone` with `dup` to avoid copying the `frozen?` bit.
> Bolt::Util.deep_clone fails with frozen hashes

- lib/bolt/executor.rb
- lib/bolt/result.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/remote.rb
- spec/bolt/executor_spec.rb
- spec/bolt/result_set_spec.rb
- spec/bolt/result_spec.rb
Closes #1724, #1718 
Seems that sometimes Results are created without actions, causing exceptions to be thrown when referenced from the Human outputter.
**TODO**
- Should i put a guard in the human outputter to check for `nil` actions? https://github.com/puppetlabs/bolt/blob/master/lib/bolt/outputter/human.rb#L101
- Need to add tests for the `remote` transport. There doesn't seem to be any. I'm thinking the easiest course of action would be to write some unit tests that mock out the executor.  **Does this sound right?**
- Integration tests i could probably write based off of the `local` transport. **Does this sound right?**
> (GH-1724) Fix bug in remote transport from nil results

- scripts/generate_changelog.rb
This makes two trivial changes to the changelog script:
- Add an extra newline after the last changelog entry. Previously,
headers were printed on the line immediately after the last entry.
- Use the commit message's raw body in `git log` pretty formatting.
Previously, only the commit message's body was being used. This would
cause any commit messages that had a release note label as the subject
of the commit to pass CI but be skipped in the changelog script.
> (maint) Fix formatting and regex in changelog script

- Rakefile
- bolt_spec_spec/Rakefile
- bolt_spec_spec/functions/with_datatype.pp
- bolt_spec_spec/spec/functions/with_datatype_spec.rb
- bolt_spec_spec/spec/spec_helper.rb
- lib/bolt/shell/bash.rb
- lib/bolt_spec/bolt_context.rb
- lib/bolt_spec/plans.rb
This creates a new helper module `BoltSpec::BoltContext` which provides
the `in_bolt_context` method. This method makes Bolt datatypes and
functions available to a block allowing code that references Bolt
constructs to be tested. The Plans module was already doing all of this
work, creating a mock executor, stubbing run_* functions, and setting
default config, inventory, and modulepath values. This moves all of that
logic into a common BoltContext module so that it can be generally
useful as opposed to being coupled with testing Bolt plans. This allows
things like Puppet functions that refer to the `TargetSpec` datatype to
be tested without having to wrap them in a Bolt plan for testing.
Closes #1688
!feature
* **Add Boltspec helper to load Bolt constructs** …
> (GH-1688) Add BoltSpec helper to load bolt constructs

- lib/bolt/shell/bash.rb
The Bash shell was raising WaitWritable errors due to incorrect assumptions
about the behavior of select/wait_writable on Windows. Specifically, when
the IO buffer is full, IO.select will still indicate that the stream is
writable. Our subsequent call to write_nonblock will then raise
WaitWritable which we don't handle.
We now anticipate that condition by passing `exception: false` to 
write_nonblock, indicating that it should return a :wait_writable symbol 
rather than raise an error, and we treat that as having written 0 bytes, 
sending us back through our IO.select loop again.
> (maint) Handle WaitWritable errors on Windows

- documentation/using_plugins.md
This could use a second pair of eyes. I'm not sure whether the key names/locations (which also use underscores) also need edits
> (docs) Plugins edits

- .github/workflows/docs.yaml
- .github/workflows/linux.yaml
- .github/workflows/modules.yaml
- .github/workflows/windows.yaml
Previously, the gem caches for jobs run through github actions were
based purely on a hash of the Gemfile and bolt.gemspec. This meant the
caches were only refreshed when we explicitly changed a dependency of
Bolt. Given that we do so relatively infrequently, that meant we could
miss updated versions of our gem dependencies. We now tie the gem cache
to the content of lib/bolt/version.rb, which changes every release. That
ensures we will update the gems we're testing against at least once a
week or so.
This also standardizes the way we handle installing bundler and caching
gems. The location we use for the bundler cache varied by job as did the
order in which we handled installing bundler and unpacking gems. We now
always follow the order a) install bundler, b) try to download the gem …
> (maint) Periodically expire gem cache

- lib/bolt/transport/orch.rb
Third arg should be a map w/key `action`.
> (maint) Fix invocation for constructing Result from exception in pcp

- lib/bolt/catalog.rb
- spec/fixtures/apply/basic/plans/fact_merge.pp
- spec/integration/apply_compile_spec.rb
If a target has a fact that shares a name with a plan variable, a
target variable, or both, then the fact should take precedence when
passed in to apply. Previously, defining a fact with the same name as
another variable would cause a redefinition error in the apply block,
where now referencing the variable will refer to the fact value.
Closes #1725
!bug
* **Target facts with the same name as a plan or Target variable should
not raise an error** ([#1725](https://github.com/puppetlabs/bolt/issues/1725))
Previously, defining a fact with the same name as
another variable would cause a redefinition error in the apply block,
where now referencing the variable will refer to the fact value.
> (GH-1725) Target facts should take precedence in apply

- CHANGELOG.md
- bolt.gemspec
- developer-docs/releasing-bolt.md
- scripts/generate_changelog.rb
This updates the `generate_changelog` script to add acknowledgements for
external contributors as part of the release note for the contribution.
Closes #1749 
> (GH-1749) Add external contributions to changelog

- lib/bolt/bolt_option_parser.rb
- lib/bolt/config/transport/docker.rb
- lib/bolt/config/transport/local.rb
- lib/bolt/config/transport/ssh.rb
- lib/bolt/config/transport/winrm.rb
- lib/bolt/shell/bash.rb
- lib/bolt/shell/bash/tmpdir.rb
- lib/bolt/shell/powershell.rb
- lib/bolt/shell/powershell/snippets.rb
- lib/bolt/transport/docker.rb
- lib/bolt/transport/docker/connection.rb
- spec/bolt/inventory/inventory_spec.rb
- spec/integration/transport/ssh_spec.rb
- spec/shared_examples/transport.rb
!feature
* **`--no-cleanup` option to leave behind temporary files**
([#1729](https://github.com/puppetlabs/bolt/issues/1729))
The `--no-cleanup` flag or `cleanup: false` transport option can now
be set to instruct Bolt not to clean up on a target after it's
finished. This is useful for debugging what Bolt is doing on a system.
> (GH-1729) Add option to skip clean up of tmpdir

- Rakefile
- bolt-modules/prompt/Rakefile
- bolt-modules/prompt/lib/puppet/functions/prompt.rb
- bolt-modules/prompt/spec/functions/prompt_spec.rb
- bolt-modules/prompt/spec/spec_helper.rb
- lib/bolt/executor.rb
- lib/bolt/plugin/prompt.rb
- spec/bolt/executor_spec.rb
This adds a `prompt` plan function that displays a user-specified prompt
message and accepts a response from `STDIN`. The function pauses
execution of a plan until a response is provided and returns the
response as a `String`, or a `Sensitive` type if the `sensitive => true`
option is set.
Closes #1755 
!feature
* **Add `prompt` plan function**
([#1755](https://github.com/puppetlabs/bolt/issues/1755))
The new `prompt` plan function lets you pause plan execution and
prompt the user for input.
> (GH-1755) Add `prompt` plan function

- documentation/bolt_configuration_reference.md.erb
The recent net-ssh gem release includes several Bolt-related changes,
including support for `StrictHostKeyChecking` option from OpenSSH
config, performance improvements, and support for ed25519 formatted ssh
keys.
Closes #733
!feature
* **OpenSSH config option StrictHostKeyChecking now honored**
Setting `StrictHostKeyChecking` in your ssh config will now be loaded
and merged with config along with other OpenSSH settings
!feature
* **Support for ed25519 SSH keys**
Key exchange algorithm curve25519sha256 is now supported
> (maint) Update net-ssh to 6.0.2

- documentation/using_plugins.md
- lib/bolt/plugin/env_var.rb
- spec/bolt/plugin/env_var_spec.rb
This patch adds two (optional) opts for the `env_var` plugin:
* `default` provides a value to use when the environment variable `var` isn't set
* `optional` allows the env_var to return nil instead of failing when the environment variable `var` isn't set
> (GH-1768) Add 'optional' and 'default' opts

- lib/bolt/apply_target.rb
- spec/fixtures/apply/puppet_types/plans/target.pp
- spec/integration/apply_compile_spec.rb
Add a to_s method to the ApplyTarget class that returns the safe name for coercing into a string in an apply block.
> (maint) Add a to_s method to ApplyTarget

- bolt-modules/boltlib/lib/puppet/functions/run_task_with.rb
- bolt-modules/boltlib/spec/functions/run_task_with_spec.rb
- lib/bolt/executor.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/orch.rb
- spec/bolt/executor_spec.rb
This adds a new plan function `run_task_with` that runs a task on a set
of targets with target-specific parameters. It accepts a lambda that
returns a `Hash` of parameters to pass to the task run on a particular
target.
As an example, a task might expect a parameter with a value that is set
by a target's `facts`. The `run_task_with` function would have a lambda
that assigns this parameter with the appropriate fact:
```
$results = run_task_with('my_task', $targets) |$t| {
{ 'osfamily' => $t.facts['osfamily'] }
}
```
Similar to the `run_task` plan function, `run_task_with` also accepts
an optional `description` parameter, as well as three metaparameters:
- `_catch_errors`
- `_noop`
- `_run_as`
Closes #1673 
!feature
* **Added `run_task_with` plan function** …
> (GH-1673) Add run_task_with plan function

- lib/bolt/apply_target.rb
- lib/bolt/target.rb
- spec/bolt/target_spec.rb
At a time in the past, Bolt::Target implemented both eql? and hash,
allowing Target objects to be uniqed and used as Hash keys. With the
switch over to inventory v2, Bolt::Target objects are generally considered
identical as long as they have the same name, so it makes even more
sense to be able to uniq them, etc. However, the current implementation
lacks the hash method that makes that behavior work.
We now implement hash() for both Bolt::Target and Bolt::ApplyTarget so
that plan authors can treat Target objects the same as target names.
!bug
* **Target objects of the same name are now identical** ([#1773](https://github.com/puppetlabs/bolt/issues/1773))
Target objects will now be considered identical in all cases if they
have the same name. This allows uniq to operate on arrays of …
> (GH-1773) Implement hash() method for Target

- lib/bolt/shell/bash.rb
Previously, when using run-as with stdin, both the local and SSH
transports would fail with a "broken pipe" error if the task exited
before all of stdin could be written. This happens if stdin is larger
than the pipe buffer and the task doesn't read stdin. We now anticipate
that error and simply stop trying to write stdin if it's encountered.
!bug
* **Fixed 'broken pipe' errors with SSH and local transports**
([#1769](https://github.com/puppetlabs/bolt/issues/1769))
The SSH and local transports could experience broken pipes when
using run-as while running a task that accepted input on stdin but
didn't read it.
> (GH-1769) Don't fail when writing stdin to a task that has exited

- Puppetfile
This bumps the `gcloud_inventory` module to 0.1.1, which includes a bug
fix that makes the `resolve_reference` task private.
!bug
* **Set `gcloud_inventory::resolve_reference` task to private** (#1783)
The `gcloud_inventory::resolve_reference` task has been set to private
and will no longer appear when using `bolt task show`.
> (maint) Bump gcloud_inventory module to 0.1.1

- lib/bolt/transport/base.rb
Previously the debug logging in the base transport class would attept to interpolate a task object into a string instead of using the Task#name method. This resulted in difficult to read debug logs. This commit updates the debug logging to use the task name.
> (maint) Log task name with debug logging

- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- lib/bolt/rerun.rb
- lib/bolt/result.rb
- lib/bolt/result_set.rb
- lib/bolt/shell/powershell.rb
- lib/bolt/transport/winrm/connection.rb
- lib/bolt_server/transport_app.rb
- spec/bolt/rerun_spec.rb
- spec/bolt/result_spec.rb
- spec/bolt_server/transport_app_spec.rb
- spec/integration/result_set_spec.rb
- spec/integration/ssh_spec.rb
- spec/integration/winrm_spec.rb
Previously, we treated non-UTF-8 task output as simply non-JSON output,
putting it in a hash under the `_output` key. This violated a key
constraint of the task specification (task output must always be UTF-8)
and caused problems when we tried to print the result as JSON (either as
output or for logging).
We now explicitly check for non-UTF-8 characters when interpreting the
result and we throw away stdout entirely and replace it with an error if
it is invalid.
Non-UTF-8 characters are generally allowed from commands and scripts.
However, they still can't be printed or converted to JSON. We now define a
"safe_value" that is the scrubbed version of the input and use that for
printing and JSON.
This commit removes the status_hash method and replaces it in all cases with
the to_data method …
> (GH-1759) Handle non-UTF-8 results

- lib/bolt/pal.rb
`bolt plan show <plan>` was failing when passed a project-level
plan due to the fact that the project path is a Pathname rather than a
string, unlike most modules. We now convert the path to a string in
`get_plan_info` so that any code interacting with the plan data can
treat it as if it came from any other module.
!bug
* **Fix `bolt plan show <plan>` for project-level plans**
([#1799](https://github.com/puppetlabs/bolt/pull/1799))
This command was throwing errors due to a type mismatch that is now
resolved.
> (maint) Fix plan show for project plans

- Gemfile
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
This adds a warning that Bolt may be installed as a gem when bundled
content is missing. Bolt checks if any modules other than `aggregate`,
`canary`, and `puppetdb_fact` are installed at `Bolt::PAL::MODULES_PATH`
to determine if it may be a gem install.
This warning can be disabled by setting the `BOLT_GEM` environment
variable.
Closes #1779 
!feature
* **Warn when Bolt is installed as a gem**
([#1779](https://github.com/puppetlabs/bolt/issues/1779))
Bolt now issues a warning when it detects that it may have been
installed as a gem. This warning can be disabled by setting the
`BOLT_GEM` environment variable.
To install Bolt reliably and with all of its dependencies, it should
be [installed as a package](https://puppet.com/docs/bolt/latest/bolt_installing.html).
> (GH-1779) Warn when Bolt is installed as a gem

- .github/workflows/linux.yaml
This removes the step to install docker-compose during pre-test setup
for the linux CI workflow. Previously, the linux virtual environment did
not have a version of docker-compose installed that supported the
`--parallel` flag. docker-compose has since been updated to a version
that does support this flag, so it's no longer necessary to download and
install docker-compose during pre-test setup.
> (maint) Remove docker-compose download from linux CI

- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/linux.yaml
- .github/workflows/modules.yaml
- .github/workflows/windows.yaml
- lib/bolt/config.rb
- lib/bolt/config/transport/docker.rb
- lib/bolt/config/transport/local.rb
- lib/bolt/config/transport/orch.rb
- lib/bolt/config/transport/remote.rb
- lib/bolt/config/transport/ssh.rb
- lib/bolt/config/transport/winrm.rb
- lib/bolt/inventory/group.rb
- schemas/README.md
- schemas/bolt-config.schema.json
- schemas/bolt-inventory.schema.json
- schemas/bolt-project.schema.json
- schemas/bolt-transport-definitions.json
This adds JSON schemas that can be used to validate `bolt.yaml`,
`inventory.yaml`, and `project.yaml` files.
Closes #1795 
!feature
* **Added JSON schemas for validating Bolt configuration files**
([#1795](https://github.com/puppetlabs/bolt/issues/1795))
JSON schemas are now available for validating `bolt.yaml`,
`inventory.yaml`, and `project.yaml` files.
> (GH-1795) Add JSON schemas for Bolt configuration files

- bolt-modules/boltlib/types/planresult.pp
This commit adds `ApplyResult` to the list of valid variants allowable as a `PlanResult`.
!bug
* **Make an `ApplyResult` a valid `PlanResult`**
([#1807](#1807))
Plans may now return `ApplyResult`s outside of a `ResultSet`.
closes https://github.com/puppetlabs/bolt/issues/1807
> (GH-1807) Make an `ApplyResult` a valid `PlanResult`

- .gitignore
- lib/bolt/bolt_option_parser.rb
- spec/bolt/cli_spec.rb
- spec/integration/lookup_spec.rb
As part of the [#1364](https://github.com/puppetlabs/bolt/pull/1364) work to
standardize how we expand configured paths we expand all paths
configured in files relative to the project directory, and stated that
all paths set on the CLI would be expanded relative to the directory
Bolt was run from. However, only some CLI paths (inventoryfile and 
puppetfile) were expanded this way, while others (hiera-config and 
private-key) were expanded relative to the project
directory. This standardizes paths passed on the CLI to be expanded
relative to the cwd. This is accomplished by expanding the path in our 
CLI option handler, so that the config object only sees the path as
absolute and does not try to expand it relative to the project.
!bug
* **Expand filepaths passed on the CLI relative to the …
> (maint) Expand filepaths passed on the CLI relative to cwd

- Puppetfile
- documentation/bolt_installing.md
This adds documentation for installing Bolt on Ubuntu 20.04.
Closes #1782 
**NOTE:** The download link in the docs won't work until the puppet-tools-release-focal repo is available, which won't be published until at least one package is available for distribution.
!feature
* **Packages for Ubuntu 20.04 now available**
([#1782](https://github.com/puppetlabs/bolt/issues/1782))
Bolt packages are now available for Ubuntu 20.04.
> (GH-1782) Build and ship Bolt for Ubuntu 20.04

- acceptance/setup/common/pre-suite/010_install_ruby.rb
`--no-rdoc` and `--no-ri` were removed in favor of `--no-document` in
ruby 2.6, which is default on OSX 15. This updates our acceptance test
suite setup script to use --no-document when installing gems on OSX. The
`--no-document` option was added in Ruby 2.0, so should work for all
Bolt platforms.
> (maint) Use --no-document instead of --no-rdoc

- bolt-modules/file/lib/puppet/functions/file/exists.rb
- bolt-modules/file/lib/puppet/functions/file/join.rb
- bolt-modules/file/lib/puppet/functions/file/read.rb
- bolt-modules/file/lib/puppet/functions/file/readable.rb
- bolt-modules/file/lib/puppet/functions/file/write.rb
The file module includes several helpful functions for interacting with
files locally. Previously the documentation didn't clearly specify that
the functions only act on disk and cannot be run against remote targets.
The function documentation now clarifies what exactly each function is
running "under the hood", and states that the functions are limited to
localhost.
> (maint) Add details to file function descriptions

- spec/integration/transport/winrm_spec.rb
- spec/lib/bolt_spec/conn.rb
- spec/spec_helper.rb
Bolt still read some local files while running spec tests, which would cause several tests to fail locally but pass in CI. This makes two changes to fix failing tests:
* Don't load local `project.yaml` file. This is accomplished by adding a stub in `spec_helper.rb` that will return an empty project when Bolt tries to load a project from the local path. This is a different pattern from the one we use for ignoring bolt.yaml, which is stubbed in `BoltSpec::Integration` helper. This works because the config object is typically stubbed in unit tests, and integration tests use the helper. Plus, the config object is initialized with its data, making it easy to pass in empty data. Passing data to initialize the project object is possible, but it's instantiated in multiple places in Bolt and would …
> (GH-1792) Ignore local project.yaml and expand ssh key fixture path

- .rubocop.yml
- lib/bolt/bolt_option_parser.rb
- lib/bolt/inventory.rb
- lib/bolt/inventory/inventory.rb
- lib/bolt/pal/yaml_plan.rb
- lib/bolt_spec/plans/mock_executor.rb
- spec/integration/plugin/task_spec.rb
This adds a couple new cops that are now enabled by default in Rubocop
to the Rubocop config file.
> (maint) Configure new default Rubocop cops

- bolt-modules/boltlib/lib/puppet/datatypes/resourceinstance.rb
- bolt-modules/boltlib/lib/puppet/datatypes/target.rb
- bolt-modules/boltlib/lib/puppet/functions/set_resources.rb
- bolt-modules/boltlib/spec/functions/set_resources_spec.rb
- bolt-modules/boltlib/types/planresult.pp
- documentation/bolt_types_reference.md
- documentation/experimental_features.md
- lib/bolt/applicator.rb
- lib/bolt/apply_target.rb
- lib/bolt/inventory/inventory.rb
- lib/bolt/inventory/target.rb
- lib/bolt/resource_instance.rb
- lib/bolt/target.rb
- spec/bolt/resource_instance_spec.rb
- spec/bolt/target_spec.rb
This adds a new `ResourceInstance` data type to the plan language and a
corresponding `Bolt::ResourceInstance` implementation class.
The `ResourceInstance` data type stores observed state, desired state  and
events for a single resource on a target. Resources are identified by a
combination of their target, type, and title, and can have their observed
state, desired state, and events set and overwritten.
This data type does not modify or interact with resources on a target in
any way.
Closes #1781 
!feature
* **Added `ResourceInstance` data type**
([#1781](#1781))
The new `ResourceInstance` data type is available for use in plans and
can be used to store the observed state, desired state, and events for
a target's resource.
!feature
* **Added `set_resources` plan function** …
> (GH-1781) Add ResourceInstance data type

- schemas/README.md
We now have proxies set up to distribute the JSON schemas from
forgeapi.puppet.com. This updates the documentation for using the JSON
schemas from the Forge.
> (maint) Distribute JSON schemas from Puppet Forge

- lib/bolt_server/pe/pal.rb
Attempting to use a modulepath from bolt.yaml in PE plans has exposed some issues that we are not ready to tackle yet. For example there is no interpolation for $basemodulepath. This commit prevents bolt-server from attempting to load a modulepath from bolt.yaml in an environment. Note this commit does not attempt to change BoltServer::PE::PAL to take advantage of the work done in the PAL we use in orchestrator to leverage threadsafe Puppet features.
> (PE-28674) No longer look for modulepath in bolt.yaml for PE plans

- .github/workflows/linux.yaml
- documentation/bolt_configuration_reference.md.erb
- documentation/experimental_features.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/config/transport/ssh.rb
- lib/bolt/node/output.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/exec_connection.rb
- schemas/bolt-transport-definitions.json
- spec/Dockerfile
- spec/bolt/transport/ssh/exec_connection_spec.rb
- spec/integration/transport/ssh_spec.rb
The SSH transport uses the net-ssh ruby library to establish an SSH
connection. While robust, the library is limited in it's OpenSSH
configuration and key exchange algorithm support. Users can now specify
an SSH command to run and Bolt will shell out to SSH, allowing users to
use all local OpenSSH configuration to connect.
This creates 2 new configuration options: `ssh-command` and
`copy-command`, which can be set in confg files, inventory files, or
specified on the CLI. Each option is an array which defines the command
to use when executing commands or copying files respectively.
`ssh-command` additionally enables using the 'external ssh' connection,
while `copy-command` does nothing if `ssh-command` is not set. Both
options accept either a string or array.
The external ssh connection …
> (GH-1780) Allow users to shell out to SSH

- documentation/experimental_features.md
This fixes a broken code block in the experimental features page and
removes a couple of redundant anchors.
> (maint) Fix formatting issue in experimental features

- documentation/bolt_examples.md
- documentation/getting_started_with_bolt.md
For consistency, this styles the prereq blocks to match other Puppet documentation. For example, https://puppet.com/docs/pe/latest/viewing_packages_in_use.html
> (docs) Editing styling on "Before you begin" blocks

- documentation/bolt_configuration_reference.md.erb
This updates the external SSH column in the bolt configuration reference
page to have 'yes' in stead of a check mark in the column for options
that are supported by the external ssh transport
> (maint) Make external SSH column content valid

- documentation/bolt.ditamap
- documentation/bolt_installing.md
- documentation/bolt_installing_modules.md
- documentation/module_structure.md
- Move modules to a new section
- Change page title: "Directory structure" to "Module structure"
- Renamed file "directory_structure.md to "module_structure.md"
- I'll add a redirect for this to the web repo
- Change page title: "Modules" to "Installing modules"
- Updated Installing modules instructions
Closes #1802 
> (docs)(GH-1802) Rework modules pages

- lib/bolt/apply_result.rb
This commit updates the missing keys error for an ApplyResult to format the list of missing keys with the correct separator.
> (maint) Fix formatting for missing keys in apply report

- lib/bolt/applicator.rb
Right now the plugin tarbal doesn't contain the puppet data types defined in the module directory `types` with extension `.pp`. As a result of that puppet code that requires these puppet data types not only for catalog compilation but also for run-time type checking, cannot run in a bolt apply block. 
This is related to  https://tickets.puppetlabs.com/browse/PUP-7197.
> (BOLT-1549) Add puppet data types to plugin tarbal

- documentation/bolt_known_issues.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/config.rb
- lib/bolt/shell/bash.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/transport/winrm/connection.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config/transport/local_spec.rb
- spec/integration/transport/ssh_spec.rb
- spec/integration/transport/winrm_spec.rb
Since splitting the shell implementation from the transport connecting
to the shell, we now open a new thread with input, output, and error
streams for every connection. With concurrency defaulting to 100 this
often means 300+ file descriptors are open in Bolt's ruby process when
running against many targets, which exceeds the common FD limit of 256.
We now set concurrency to 1/3 the file descriptor limit if the limit is
below 300, otherwise it's set to 100. We also warn the user that
concurrency is set low, and provide instructions on how to increase the
ulimit or concurrency. We also raise a helpful error message when the
EMFILE error is thrown instructing the user on how to increase their FD
limit. Lastly this adds a section in the known issues documentation about
the error, also with …
> (GH-1789) Rescue EMFILE error with helpful message

- Puppetfile
We manually released a version of python-task-helper that contained a
virtual environment in it. We had to update the version of the helper to
republish to the forge. This bumps the version to the new module that
doesn't contain a venv.
> (maint) Bump python-task-helper to 0.4.3

- bolt-modules/boltlib/lib/puppet/datatypes/applyresult.rb
- bolt-modules/boltlib/lib/puppet/datatypes/result.rb
- bolt-modules/boltlib/lib/puppet/datatypes/resultset.rb
- bolt-modules/boltlib/lib/puppet/datatypes/target.rb
- spec/bolt/catalog_spec.rb
- spec/spec_helper.rb
This adds the `Puppet::Pops::Types::PuppetObject` interface to Bolt data
types and their associated classes. Previously, Bolt's data types were
missing this interface, which could lead to Puppet attempting to access
already-deserialized objects with the `[]` operator during the
deserialization process when local references are present. Since Bolt's
implementation classes do not implement the `[]` operator, and doing so
is undesirable, adding the `PuppetObject` interface is needed for
deserialization.
Closes #1836 
!bug
* **Add `PuppetObject` interface to Bolt data types**
([#1836](https://github.com/puppetlabs/bolt/issues/1836))
Bolt data types would sometimes not be deserialized correctly when
using `apply` blocks in plans. All Bolt data types now implement the
`PuppetObject` interface …
> (GH-1836) Add PuppetObject interface to Bolt data types

- documentation/bolt_installing.md
- lib/bolt/analytics.rb
- spec/bolt/analytics_spec.rb
This updates the analytics client to load its configuration from
`~/.puppetlabs/etc/bolt/analytics.yaml` by default instead of
`~/.puppetlabs/bolt/analytics.yaml`.
By default, Bolt will first look for the config file at the new
location and load it if it exists. If it does not exist, Bolt will fall
back to the old location and load it if it exists. If it does not exist
at either location, Bolt will write the config file to the new location.
If a user has a config file at both the old and new locations, it will
display a helpful warning that the old location is deprecated.
Closes #1843 
!feature
* **Analytics configuration loaded from user-level config directory** (#1843)
Analytics configuration is now written to and loaded from
`~/.puppetlabs/etc/bolt/analytics.yaml` by default. Bolt will …
> (GH-1843) Load analytics config from user-level config directory

- documentation/applying_manifest_blocks.md
- documentation/bolt.ditamap
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
This updates the `bolt apply` command to warn a user when they are
applying a manifest that only consists of definitions without declaring
anything.
This also updates the 'Applying manifest blocks' documentation to document
using the `bolt apply` command. It also reorganizes the structure of the
page to create separate sections for the `bolt apply` command and the
`apply` plan function.
Lastly, this adds support for the `--hiera-config` option to the 
`bolt apply` command.
Closes #1785
!feature
* **Warn when applying manifests that only contain definitions** (#1785)
Applying a manifest that only contains definitions with the `bolt apply`
command will now display a warning that no changes will be applied to
the targets.
!feature
* **Support `--hiera-config` option when using `bolt apply`** …
> (GH-1785) Warn when applying a manifest that only contains definitions

- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
- bolt-modules/boltlib/spec/fixtures/modules/sensitive/plans/complex.pp
- bolt-modules/boltlib/spec/fixtures/modules/sensitive/plans/init.pp
- bolt-modules/boltlib/spec/fixtures/modules/sensitive/plans/no_api.pp
- bolt-modules/boltlib/spec/functions/run_plan_spec.rb
- bolt-modules/boltlib/spec/functions/run_task_spec.rb
- bolt-modules/boltlib/spec/functions/run_task_with_spec.rb
- documentation/writing_plans.md
- lib/bolt/pal.rb
- spec/bolt/cli_spec.rb
- spec/integration/parsing_spec.rb
This updates the `run_plan` function to wrap parameters marked as
`Sensitive` in the Sensitive wrapper type. Previously, indicating a plan
parameter as `Sensitive` would cause a plan to fail, as the parameter is
passed as a `String` type.
Plan authors could get around this limitation
by accepting `String` parameters and then wrapping them as `Sensitive`,
but GUIs that expose plan parameters would still display these
parameters as strings. Now, Bolt will check the type expression for each
parameter on plan startup and wrap any parameters marked as `Sensitive`
as such.
Only parameters with a parameterized or non-parameterized `Sensitive`
type are automatically wrapped. Additionally, these parameters will only
be automatically wrapped for plans run via an API call, as plans run
from another …
> (GH-1790) Wrap Sensitive plan parameters as Sensitive wrapper type

- lib/bolt/config.rb
- lib/bolt/project.rb
- spec/bolt/config_spec.rb
- spec/bolt/project_spec.rb
- spec/spec_helper.rb
Bolt is sometimes run in processes where no homedir is defined, causing
the expansion of `~` to fail. This was previously taken care of in most
places in #1676 but missed the default project directory at
`~/.puppetlabs/bolt`. Now when we try to load the path if it fails it
will fall back to the system-wide configuration path at
`/etc/puppetlabs/bolt` as the default project directory.
!bug
* **Fall back to system-wide config path if homedir expansion fails**
We now fall back to `/etc/puppetlabs/bolt` as the default project
directory if expanding the homedir fails.
> (GH-1829) Use system project directory if homedir isn't defined

- lib/bolt/applicator.rb
- lib/bolt/catalog.rb
- lib/bolt/pal.rb
- spec/bolt/applicator_spec.rb
- spec/fixtures/projects/named/manifests/notify.pp
- spec/fixtures/projects/named/plans/apply.pp
- spec/integration/apply_compile_spec.rb
Previously, we failed to thread the project context through to the
applicator and on to the catalog compiler. This meant that project-level
classes, defines, functions, types, etc couldn't be used in an apply
block or with `bolt apply`.
!bug
* **Project-level content can now be used in apply blocks**
([#1836](https://github.com/puppetlabs/bolt/issues/1836))
Project-level classes and defines can now be used in `apply` blocks
and `bolt apply`.
> (GH-1848) Load project-level content during apply compilation

- documentation/bolt_types_reference.md
The ResultSet datatype reference was missing the `ok_set` function.
> (maint) Add ok_set to ResultSet reference doc

- bolt-modules/boltlib/lib/puppet/datatypes/resourceinstance.rb
- spec/fixtures/modules/resources/plans/add_event.pp
- spec/integration/resource_instance_spec.rb
The add_event function on the ResourceInstance datatype didn't correctly
wrap the events hash in an array, causing the function to fail. The
expected return type of the function is now `Array[Hash[String[1],
Data]]]`.
!bug
* **Correct ResourceInstance.add_event return type**
Previously the `add_event` function had a typo that prevented it from
successfully returning. It now correctly expects an
`Array[Hash[String[1], Data]]]`.
> (maint) Fix add_event return type

- bolt-modules/boltlib/lib/puppet/functions/run_task.rb
- bolt-modules/boltlib/lib/puppet/functions/run_task_with.rb
- bolt-modules/boltlib/spec/fixtures/modules/test/tasks/undef.json
- bolt-modules/boltlib/spec/fixtures/modules/test/tasks/undef.sh
- bolt-modules/boltlib/spec/functions/run_task_spec.rb
- bolt-modules/boltlib/spec/functions/run_task_with_spec.rb
- documentation/writing_tasks.md
- spec/bolt/cli_spec.rb
This updates the `run_task` function to use a task parameter default
when a parameter is specified but has a value of `Undef`. Previously, if
a parameter was specified with a value of `Undef`, the default would not
be used and the `Undef` value would be passed to the task.
Closes #1847 
!feature
* **Use task parameter default when specified parameter is `Undef`**
([#1847](https://github.com/puppetlabs/issues/1847))
Task parameters that are specified with a value of `Undef` will now
use the default parameter value if one is defined in the task's
metadata.
> (GH-1847) Use task parameter default when parameter is `Undef`

- .rubocop.yml
In rubocop 0.84 a new cop, `Lint/DeprecatedOpenSSLConstant`, was added
that needed to be configured to either 'true' or 'false' in
`.rubocop.yml` otherwise rubocop would raise a warning. This adds the
cop and enables it.
> (maint) Add Lint/DeprecatedOpenSSLConstant cop

- .rubocop.yml
- bolt-modules/boltlib/spec/functions/run_script_spec.rb
- spec/bolt/pal/yaml_plan/loader_spec.rb
- spec/bolt/pal/yaml_plan_spec.rb
- spec/integration/transport/docker_spec.rb
- spec/integration/transport/winrm_spec.rb
- spec/integration/yaml_plan_spec.rb
This adds a few new default cops introduced in Rubocop 0.85. The
`Lint/MixedRegexpCaptureTypes` and `Style/RedundantRegexpCharacterClass`
cops are disabled as they appear to be buggy.
> (maint) Add new cops from RuboCop 0.85

- bolt-modules/boltlib/lib/puppet/functions/set_resources.rb
- bolt-modules/boltlib/spec/functions/set_resources_spec.rb
- documentation/experimental_features.md
- lib/bolt/resource_instance.rb
This updates the `set_resources` plan function to accept a
`resource_type` key as part of the resource data hash, in addition to
`type`.
When creating a `ResourceInstance` object from a hash, a `type` key is
expected. However, when using resource data hashes returned from an
apply block, the resource's type is set under the `resource_type` key.
This made it impossible to directly use this hash to create a
`ResourceInstance` object, as the hash did not have the required `type`
key. The `set_resources` function now falls back to using the
`resource_type` key if the `type` key is not present.
It's important to note that calling `ResourceInstance.new` with a hash
that has a `resource_type` key instead of a `type` key will still raise
an exception.
To keep the behavior of …
> (GH-1872) Accept `resource_type` key in `set_resources` plan function

- bolt-modules/boltlib/lib/puppet/datatypes/resourceinstance.rb
- documentation/bolt_types_reference.md
- lib/bolt/resource_instance.rb
- spec/bolt/resource_instance_spec.rb
This adds a `[]` function to the `ResourceInstance` data type that
directly accesses the `state` hash and returns the value for the
specified attribute. If the attribute is missing, the function will
return `nil`.
Closes #1873 
!feature
* **Added `[]` function to the `ResourceInstance` data type**
([#1873](https://github.com/puppetlabs/bolt/issues/1873))
The `[]` function can be used to directly access the `state` hash for
a `ResourceInstance` object and return the specified attribute.
> (GH-1873) Add `[]` function to ResourceInstance data type

- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
This updates the `run_plan` function to not check if a plan parameter
has a `Sensitive` type if the parameter is not recognized by the plan.
Previously, if a parameter was passed to a plan that the plan was not
expecting, the `run_plan` function would attempt to check the
parameter's type expression to determine whether it should be wrapped as
`Sensitive`. Since the parameter is unrecognized, it would raise an
error when attempting to access its type expression.
!bug
* **Raise correct error when passing unknown plan parameters** (#1886)
Bolt was raising an obscure error when a plan received an unknown
parameter. It now raises the correct error indicating that the
parameter is unknown.
> Do not check if unrecognized plan parameters are sensitive

- Rakefile
- bolt-modules/boltlib/spec/functions/apply_prep_spec.rb
- bolt-modules/boltlib/spec/functions/remove_from_group_spec.rb
- bolt-modules/boltlib/spec/functions/resolve_references_spec.rb
- documentation/bolt_configuration_reference.md.erb
- documentation/experimental_features.md
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/inventory/group.rb
- lib/bolt/project.rb
- lib/bolt_spec/bolt_context.rb
- lib/bolt_spec/run.rb
- schemas/bolt-project.schema.json
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/inventory/inventory_spec.rb
- spec/bolt/project_spec.rb
- spec/bolt/rerun_spec.rb
- spec/integration/project_spec.rb
- spec/integration/transport/local_spec.rb
- spec/integration/transport/ssh_spec.rb
- spec/integration/transport/winrm_spec.rb
- spec/lib/bolt_spec/config.rb
- spec/lib/bolt_spec/integration.rb
- spec/spec_helper.rb
This makes several changes to how Bolt loads config. We now load bolt
configuration options (eg. concurrency), excluding transport config
options, from `bolt-project.yaml` if that file is present in the project
directory and has non-project config keys (e.g. 'format'). If both
`bolt-project.yaml` and `bolt.yaml` are present in the root of the
project directory and `bolt-project.yaml` has config keys `bolt.yaml`
will be ignored, regardless of how bolt determines the project
directory. This means that users can specify `--configfile
path/to/bolt.yaml`, and if there's a `bolt-project.yaml` with config
next to it it will not be loaded. If only `bolt.yaml` is present, it
will be loaded normally including transport config. Users using
`bolt-project.yaml` should specify transport configuration …
> (GH-1842) Load config from bolt-project.yaml

- documentation/bolt_configuration_reference.md.erb
- lib/bolt/config/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- schemas/bolt-transport-definitions.json
- spec/bolt/config/transport/ssh_spec.rb
- spec/bolt/transport/ssh/connection_spec.rb
This adds the following SSH transport configuration options:
- `encryption-algorithms`
- `host-key-algorithms`
- `kex-algorithms`
- `mac-algorithms`
Each of these options accepts an array of preferred algorithms to use when
establishing a connection using the SSH transport. When a `*-algorithms`
option is set, `net-ssh` is configured to only attempt to establish a
connection to the target using algorithms in the list.
Each `*-algorithms` option accepts a special `defaults` item, which will
automatically add all of default, supported algorithms for `net-ssh` to
the list. For example, the following config:
```yaml
ssh:
encryption-algorithms:
- defaults
```
Would expand to the following:
```yaml
ssh:
encryption-algorithms:
- aes-256-ctr
- aes-192-ctr
- aes-128-ctr
```
Starting with the …
> (GH-1862) Specify preferred  algorithms for SSH transport connections

- lib/bolt/applicator.rb
- lib/bolt/catalog.rb
- spec/bolt/applicator_spec.rb
There's a [PR](puppetlabs/puppet#8193) to Puppet
to handle empty apply statements correctly. Until that's in, an empty
apply block will be considered unacceptable and an error will be raised,
since there's no use cases for empty apply blocks.
Closes #1880
!bug
* **Empty apply blocks now error correctly** ([#1880](#1880))
This raises an appropriate error when an apply block is empty, instead
of an undefined method error.
> (GH-1880) Raise error for empty apply block 

- lib/bolt/shell/powershell/snippets.rb
- lib/bolt/transport/local/connection.rb
- spec/integration/local_spec.rb
Powershell will [exit
1](PowerShell/PowerShell#11461) whenever the $LASTEXITCODE is greater
than 0, regardless of what the code is, whenever running a bare command.
Powershell exits with the correct exit code when executing files, or
when `exit $LASTEXITCODE` is appended to the command being run (as in
the [execute_process
snippet](https://github.com/puppetlabs/bolt/blob/0d44ce739d4dafcb6d27abd894e230894fdd50e0/lib/bolt/shell/powershell/snippets.rb#L19),
meaning this is only an issue when running commands through Bolt, and
not tasks or scripts. This appends a Powershell snippet to exit with
the correct exit code to commands running on Windows using the local
transport.
Closes #1846
!bug
* **Return correct exit code when running commands in powershell** ([1846](#1846))
Bolt will now …
> (GH-1846) Exit with correct exit code when running on Windows with local transport

- bolt.gemspec
- lib/bolt/applicator.rb
- lib/bolt/catalog.rb
This commit updates the catalog compiler to use updates to PAL api to enable node definitions in plans and deserialized bolt types in apply blocks without relying on using public methods. This includes a refactor to clean up the compile_catalog method and make it more readable.
> (PUP-10476) Use updated PAL api for catalog compilation

- spec/integration/local_spec.rb
Windows tests for the local transport were failing with the command
`bolt command run 'puppet apply --trace --detailed-exitcodes -e "notify
{foo: }"'` with `Unknown argument(s) {foo:, }`. This switches the quotes
so that powershell properly parses the command. It also only runs the
test on a single valid host, 'localhost', to avoid unexpected errors running on host `local://foo`.
> (maint) Fix exit code test

- lib/bolt/applicator.rb
- spec/fixtures/apply/basic/lib/puppet/functions/load_error.rb
- spec/integration/apply_error_spec.rb
When compiling Bolt apply catalogs we only log the error message if the
error is a Puppet error or a ruby StandardError. If an error is raised
that isn't either of those types, it fails silently, and as there's
often not anything on stdout all that's raised is a JSON parse error.
Now, if the STDOUT of `bolt_catalog` is not valid JSON we log whatever
is on STDERR and include a helpful message for the ApplyError. This
should account for any case where `bolt_catalog` wasn't successful and
so didn't print JSON to STDOUT, and ensures we only print STDERR when
it's useful and not redundant with other error messages.
Closes #1881
!bug
* **Log error for unhandled catalog compilation errors** ([#1881](https://github.com/puppetlabs/bolt/issues/1881))
We now log whatever is on STDERR when catalog …
> (GH-1881) Log STDERR when STDOUT from bolt_catalog is not JSON

- documentation/bolt_known_issues.md
- documentation/experimental_features.md
This adds a section to the experimental features page under external SSH
about how to use the external SSH configuration option to enable SSH
configuration that isn't supported by the Ruby net-ssh library. It
includes an example of both defining the command to include the
configuration, and an example with configuration defined in
`~/.ssh/config`. It also removes the OpenSSH 7.8 key format known issue,
as it is no longer an issue since we ship Bolt with the gems to support
the new format.
Closes #733
> (GH-733) Document connecting with configuration not supported by net-ssh

- bolt-modules/file/lib/puppet/functions/file/read.rb
The documented example for using file::read plan function to read a file
from a module on the modulepath erroneously included `/files/`. This
changes the example from the path `example/files/VERSION` to
`example/VERSION`.
> (maint) Fix file::read from module example

- bolt-modules/file/lib/puppet/functions/file/exists.rb
- bolt-modules/file/lib/puppet/functions/file/readable.rb
The documented example for using file::readable and file::exists plan
functions to read a file from a module on the modulepath erroneously
included `/files/`. This changes the example from the path
`example/files/VERSION` to `example/VERSION`.
> (maint) Fix file plan function examples

- bolt.gemspec
- lib/bolt/config.rb
- lib/bolt/outputter.rb
- lib/bolt/outputter/rainbow.rb
- spec/bolt/outputter/rainbow_spec.rb
This adds a new output format option `rainbow` which behaves like the
human outputt except that it will colorize success messages with rainbow
colors instead of green if the system supports it. This works by adding
a new outputter class `Bolt::Outputter::Rainbow` that inherits from the
`Bolt::Outputter::Human` class and overrides the `colorize` and
`print_summary` functions. The colorize function in the rainbow class
will color messages labelled as `:green` or `:rainbow` with rainbow
colors using an algorithm copied from the [lolcat
project](https://github.com/busyloop/lolcat) (which is licensed for free
modification and reuse). The `print_summary` function is overridden to
colorize success messages that aren't colorized in the Human class.
This option can be configured on the cli with …
> (fun) Add rainbow output format

- Rakefile
- documentation/bolt.ditamap
- documentation/bolt_configuration_reference.md.erb
- documentation/bolt_defaults_reference.md.erb
- documentation/bolt_transports_reference.md.erb
- documentation/configuring_bolt.md
- lib/bolt/config.rb
- lib/bolt/inventory/group.rb
- lib/bolt/project.rb
- schemas/bolt-defaults.schema.json
- spec/bolt/config_spec.rb
- spec/bolt/project_spec.rb
- spec/lib/bolt_spec/integration.rb
This adds support for a new config file named `bolt-defaults.yaml`. This
file is loaded from both the system-wide and user-level config
directories, and contains similar config options to a `bolt.yaml` file
(except for project-specific config such as `inventoryfile`).
When a user has a `bolt-defaults.yaml` file alongside a `bolt.yaml` file
in the system-wide or user-level directories, it is loaded instead of
the `bolt.yaml` file and warns the user that the `bolt.yaml` file has
been ignored.
If a user has a `bolt.yaml` file present in either the system-wide or
user-level directories, Bolt will issue a warning that the file is
deprecated and to use a `bolt-defaults.yaml` file instead.
Closes #1845 
!feature
* **Add `bolt-defaults.yaml` configuration file** ([#1845](#1845))
Bolt now supports …
> (GH-1845) Add `bolt-defaults.yaml` configuration file

- .gitignore
When I installed modules from the `Puppetfile`, several were not ignored.  Add them to `.gitignore`.
> (maint) Ignore new additions to Puppetfile

- spec/Dockerfile.puppetserver
This updates the Docker image used in CI tests from
`puppetserver-standalone` to `puppetsever`, as `puppetserver-standalone`
no longer exists.
> (maint) Update puppetserver-standalone to puppetserver in CI

- lib/bolt/cli.rb
Previously if the `rainbow` formatter was specified plan events were not outputted.
> (maint) Subscribe rainbow outputter for plan events

- lib/bolt/shell/powershell.rb
Fixes the powershell mkdir command to correctly handle paths with spaces in them. When passed to the command line, paths have to be quoted, the previous code did not handle this.
This uses double quotes instead of single quotes to allow string interpolation to happen when it is finally passed to PowerShell.
Closes #1927
> (GH-1927) Fix powershell mkdir method

- lib/bolt/inventory/inventory.rb
- lib/bolt/inventory/target.rb
- spec/bolt/inventory/inventory_spec.rb
- spec/integration/inventory_spec.rb
Previously, the default config for 'localhost' was merged as part of the
group data collected for that target, making it effectively group-level
data. Because all targets are considered part of the 'all' group
top-level config would override localhost's default config, which made
it difficult to set defaults for all targets except localhost. This
modifies how we load localhost defaults to now merge them as part of
initializing the `Bolt::Inventory::Target` object, meaning that any time
a target with name 'localhost' is created (either via the inventory or
by `Target.new` in a plan) it will pick up the localhost defaults at the
target level. This means that now the only way to override the defaults
is to set that config at the target-level.
Closes #1904
!bug
* **Consider localhost default …
> (GH-1904) Localhost default config overrides group-level config

- documentation/bolt_running_plans.md
- documentation/bolt_running_tasks.md
- documentation/experimental_features.md
- documentation/module_structure.md
- lib/bolt/applicator.rb
- lib/bolt/cli.rb
- lib/bolt/pal.rb
- lib/bolt/project.rb
- spec/bolt/pal_spec.rb
- spec/bolt/project_spec.rb
- spec/fixtures/projects/embedded/Boltdir/bolt-project.yaml
- spec/fixtures/projects/local/bolt-project.yaml
Previously, we would infer the project name from the directory name if
no name was specified in the bolt-project.yaml. This behavior proved to
be confusing for users, so we now require `name` to be specified
in bolt-project.yaml and otherwise will warn and not load project
content.
We previously recognized `<author>-<name>` directory names as valid
project names (using only the `<name>` portion) as that is a common
repo naming scheme for modules. As the project name must now be
specified explicitly, we instead require it be simply the name portion.
!deprecation
* **Project names must be explicitly specified** ([#1871](https://github.com/puppetlabs/bolt/issues/1871))
Proejct names must now be specified in `bolt-project.yaml` in order
for project-level content to be loaded, rather than the …
> (GH-1871) Don't infer project name from directory name

- documentation/bolt_project_directories.md
- documentation/experimental_features.md
- lib/bolt/project.rb
This rewords our documentation to not use the phrase 'whitelist',
preferring just 'list' and rewording to describe what the list does
rather than using the term 'whitelist'.
> (MAINT) Remove whitelist terminology from bolt documentation

- documentation/bolt_installing.md
- documentation/bolt_project_directories.md
- documentation/migrating_inventory_files.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- spec/integration/project_spec.rb
This adds a `--project` CLI flag as an alias for `--boltdir`. If both
options are specified on the command line the rightmost option will be
used. `--project` behaves exactly like `--boltdir`. It also updates
documentation to use `--project` in place of `--boltdir`, since we
consistently refer to the concept as a 'project' in the documentation
and don't often use 'Boltdir'.
This additionally replaces `Boltdir` with `project` for all Bolt CLI flag descriptions.
Closes #1931
!feature
* **Add --project as an alias for the --boltdir CLI flag** ([1931](https://github.com/puppetlabs/bolt/issues/1931))
New CLI flag `--project` can be used in place of `--boltdir`.
> (GH-1931) Add '--project' as an alias for '--boltdir'

- schemas/bolt-project.schema.json
This removes the term 'whitelist' from our json schemas.
Realized too late I missed this on Nick's PR
> (maint) Remove 'whitelist' from schemas

- documentation/writing_plans.md
This adds a section to the 'Writing plans' doc that describes how to add
documentation to plans.
Closes #1933 
> (GH-1933) Add documentation for self-documenting plans

- lib/bolt/shell/bash.rb
- lib/bolt/transport/docker.rb
- spec/shared_examples/transport.rb
Previously, uploading a file to a directory on some transports would
cause the file to be renamed to match the name of the directory, ie.
`bolt file upload file.txt /dir` would result in a file called
`/dir/dir`. This happened because we create a tempfile that we move into
place, and we computed the name of the tempfile using the basename of
the destination, assuming it was always a file. We now use the basename
of the source file as the name of the tempfile, which preserves the name
when the destination is a directory and still causes the file to be
written with the propery destination name if the destination is a file.
!bug
* **Upload files with the correct name when destination is a directory** ([#1928](https://github.com/puppetlabs/bolt/issues/1928))
Files uploaded to directories will …
> (GH-1928) Upload files to directories with the correct name

- lib/bolt/config.rb
- spec/bolt/config_spec.rb
- spec/fixtures/modules/inventory/plans/transport.pp
- spec/integration/target_spec.rb
This fixes a bug introduced by #1923 that would not set the
default transport when using the `--transport` CLI option. Previously,
when normalizing the CLI overrides during config initialization, the
`OPTIONS` hash was used to slice out potential config options from the
CLI overrides hash. However, the `OPTIONS` hash does not include the
`transport` option, so the transport override would not be picked up.
This adds `transport` as an additional key to slice out of the overrides
hash.
> (bug) Fix --transport bug

- .gitignore
- Rakefile
- documentation/bolt.ditamap
- documentation/templates/privilege_escalation.md.erb
- lib/bolt/config/transport/local.rb
- lib/bolt/config/transport/options.rb
- lib/bolt/config/transport/ssh.rb
- lib/bolt/shell/bash.rb
This adds a net new page to the docs titled `Escalating privilege with
Bolt` which details how Bolt builds the command to change users, how to
configure that command, and what limitations Bolt has with respect to
escalating privilege.
The page also includes a list of escalation-related configuration
options and command line flags, which are generated from Bolt itself the
same way the command line reference and configuration reference pages
are generated. The generation of the options on that page is done as
part of the `docs:config_reference` rake task. In order for this to
work, the run-as configuration options stored in
`Bolt::Config::Transport::SSH::OPTIONS` and
`Bolt::Config::Transport::Local::OPTIONS` had to be moved from those
constants to …
> (GH-1867) Document how privilege escalation works in Bolt

- documentation/templates/privilege_escalation.md.erb
The docs job does not ship the privilege escalation docs due to a jump
from a h1 to h3 without an intermediary h2. This updates the template to
use the correct heading sizes.
> (bug) Fix broken headers in privilege escalation template

- bolt-modules/boltlib/lib/puppet/functions/run_command.rb
- bolt-modules/boltlib/lib/puppet/functions/run_script.rb
- lib/bolt/shell/bash.rb
- lib/bolt/shell/powershell.rb
- lib/bolt/transport/docker.rb
- lib/bolt/transport/orch.rb
- spec/bolt/shell/bash_spec.rb
- spec/shared_examples/transport.rb
Previously, we had no way to specify environment variables when running
commands or scripts. There are many reasons a user might need to set
environment variables:
* To set up the execution context for a command
* To pass arguments to scripts that expect them as env vars
* To pass secrets to commands rather than passing them as args
We now support passing `_env_vars` to `run_command()` and `run_script()`
which will set the passed variables when running the command or script.
!feature
* **Set environment variables for commands and scripts** ([#1899](https://github.com/puppetlabs/bolt/issues/1899))
The `run_command()` and `run_script()` plan functions now support an
`_env_vars` argument which accepts a Hash of environment variable
declarations to set when running the command/script.
> (GH-1899) Accept env_vars for commands and scripts

- .github/workflows/docs.yaml
- .github/workflows/linux.yaml
- .github/workflows/modules.yaml
- .github/workflows/windows.yaml
- Gemfile
- bolt.gemspec
- lib/bolt/outputter.rb
- lib/bolt/outputter/rainbow.rb
Given we dont want to ship the paint gem with PE this commit makes the gem optional. The gem will only attempt to be loaded when the rainbow outputter is requested. The paint gem will ship with bolt packages and is included in the Gemfile, but is ommited from the gemspec.
> (packaging) Make the paint gem required by the rainbow outputter optional

- lib/bolt/pal.rb
- spec/fixtures/modules/error/plans/inner.pp
- spec/fixtures/modules/error/plans/outer.pp
- spec/integration/plan_spec.rb
This updates the error raised by a plan failure to include the location
of the plan failure, including the filepath, line, and column of the
error's source. This information is included in both the error message
and under the `details` key of the error hash. Previously, this
information was discarded by Bolt when rescuing an error raised by
Puppet, resulting in only the cause of the error to be included in the
message.
Closes #1932 
!feature
* **Add location of plan failures in error messages**
([#1923](https://github.com/puppetlabs/bolt/issues/1923))
Errors raised by plan failures now include the location of the plan
failure, including the filepath, line, and column.
> (GH-1932) Add location of plan failures in error messages

- .rubocop.yml
A new cop was added to rubocop 0.86.0 titled 'Style/RedundantFetchBlock'
which "identifies places where fetch(key) { value } can be replaced by
fetch(key, value)"
((link)[https://docs.rubocop.org/rubocop/0.86/cops_style.html#styleredundantfetchblock]).
Rubocop warns if this cop isn't configured, so this commit enables the
cop to both silence the warning and standardize `fetch` usage.
> (maint) Address rubocop warning about Style/RedundantFetchBlock

- lib/bolt/cli.rb
- spec/fixtures/projects/embedded/plans/init.pp
- spec/integration/project_spec.rb
This modifies how projects specified with `--project` or `--boltdir` are
found. Previously the provided path would be used as the path to the
project, where bolt configuration was expected to be found. However with
embedded projects - those that store files in `Boltdir` - users would
specify the parent directory of `Boltdir` expect the project to be
loaded as if they were executing Bolt from that parent directory. This
modifies how we handle project directories first looks for a `Boltdir`
in the specified directory, and if none is present use the specified
directory as the project root.
!bug
* **Load projects with an embedded Boltdir when specified on the CLI**
We now look for a `Boltdir` in the directory specified by `--project`
or `--boltdir` and use that if present. If not, we use the …
> (bug-fix) Find embedded projects specified on the CLI

- documentation/templates/privilege_escalation.md.erb
This adds a new section to the 'Escalating privilege' document that
describes why limiting sudo rules to specific commands on Bolt targets
will often cause Bolt to fail. It describes how Bolt users must
essentially be granted arbitrary execution, and advises managing
privilege on a per-user basis or using PE to more granularly grant
permissions.
Closes #1867
> (GH-1867) Add docs about sudo rules on targets

- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/logger.rb
- spec/bolt/cli_spec.rb
- spec/integration/apply_compile_spec.rb
This adds a new `--log-level` CLI option that accepts a log level. When
using this option, any existing configuration for the console's log
level will be overridden with the specified level. The `--log-level`
option cannot be used in conjunction with the `--debug` option.
This also adds a warning that the `--debug` option is deprecated and
that Bolt will set `--log-level debug` instead.
Closes #1920 
Supersedes #1921 
!feature
* **Added `--log-level` CLI option** ([#1920](https://github.com/puppetlabs/bolt/issues/1920))
The new `--log-level` CLI option can be used to override the console's
log level. It accepts the following log levels: `debug`, `info`,
`notice`, `warn`, `error`, `fatal`, `any`.
> (GH-1920) Add --log-level CLI option

- .rubocop.yml
- bolt.gemspec
- lib/bolt/shell/bash.rb
- spec/lib/bolt_spec/bolt_server.rb
- spec/lib/bolt_spec/puppetdb.rb
This configures the following cops which are enabled by default in
Rubocop >= 0.87:
- `Style/AccessorGrouping`
- `Style/BisectedAttrAccessor`
- `Style/RedundantAssignment`
This also enables the `Style/RedundantRegexpCharacterClass` cop, which
was previously disabled due to a bug in Rubocop.
> (maint) Configure new default cops for Rubocop 0.87

- Rakefile
- bolt.gemspec
- documentation/templates/bolt_configuration_reference.md.erb
- documentation/templates/bolt_defaults_reference.md.erb
- documentation/templates/bolt_project_reference.md.erb
- documentation/templates/bolt_transports_reference.md.erb
- lib/bolt/config.rb
- lib/bolt/config/options.rb
- lib/bolt/config/transport/options.rb
- schemas/Rakefile
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-inventory-base.json
- schemas/bolt-inventory.schema.json
- schemas/bolt-project.schema.json
- schemas/bolt-transport-definitions.json
This contains changes that enable generating the JSON schemas using a
rake task using data contained in the `Bolt::Config::Options` and
`Bolt::Config::Transport::TRANSPORT_OPTIONS` constants.
A new Rakefile `schemas/Rakefile` contains rake tasks that generate
each of the JSON schemas. These tasks can be run using the following
command:
```shell
$ rake -f schemas/Rakefile schemas
```
This also updates the `Bolt::Config::OPTIONS` and
`Bolt::Config::Transport::TRANSPORT_OPTIONS` constants to include
additional data for each option that is included in the JSON schemas.
The additional keys are direct equivalents to keys recognized by the
JSON Schema standard, Draft 07. The constants also include several
metadata keys such as `:_example` and `:_default`, which are used to
generate docuemntation …
> (GH-1900) Generate JSON schemas with plugin references

- lib/bolt/config.rb
- spec/bolt/config_spec.rb
This adds some validation checks for the `inventory-config` option in
the `bolt-defaults.yaml` file. Previously, setting this option to a
value other than a hash would result in an unhelpful error, as Bolt was
assuming that the value would always be a hash. Additionally, if the
value was a plugin reference, the plugin reference would be merged with
the top-level config, potentially resulting in config values being
overwritten and resulting in the entire config hash being considered a
plugin reference.
Now, Bolt will first check that the `inventory-config` option is a hash
and is not a plugin reference before continuing with loading config.
!bug
* **Validate `inventory-config` option in `bolt-defaults.yaml`**
Bolt now checks that the `inventory-config` option in a
`bolt-defaults.yaml` file …
> (bug) Validate 'inventory-config' option in bolt-defaults.yaml

- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- bolt-modules/boltlib/spec/functions/apply_prep_spec.rb
- lib/bolt/applicator.rb
- spec/bolt/applicator_spec.rb
Implement feature request #1934
> (GH-1934) Add support for selective sync of plugins to target nodes

- documentation/bolt_project_directories.md
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/project.rb
- spec/bolt/cli_spec.rb
- spec/bolt/project_spec.rb
- spec/lib/bolt_spec/files.rb
This updates the `Bolt::Project` class to raise an error if the
specified project directory is world-writable. This change is meant to
prevent malicious users from modifying project content that could alter
how Bolt runs and any secure information it might use.
Users who wish to override this behavior and force Bolt to load a
project from a world-writable directory can set the `BOLT_PROJECT`
environment variable to the project directory path.
Closes #1894 
!feature
* **Do not load projects from world-writable directories**
([#1894](https://github.com/puppetlabs/bolt/issues/1894))
Bolt now raises an error when attempting to load a project from a
world-writable directory. Users who wish to override this behavior and
run a project from a world-writable directory should can set the …
> (GH-1894) Do not load projects from world-writable directories

- lib/bolt/config/options.rb
This adds support for configuring log files in a `bolt-defaults.yaml`
file. Previously, log files could only be configured in a `bolt.yaml`
or `bolt-project.yaml` file.
!feature
* **Support configuring log files in `bolt-defaults.yaml`**
The system-wide and user-level default configuration file,
`bolt-defaults.yaml`, now supports configuring log files using the
`log` option.
> Add support for configuring log in bolt-defaults.yaml

- Rakefile
- documentation/experimental_features.md
- documentation/templates/bolt_transports_reference.md.erb
- lib/bolt/bolt_option_parser.rb
- lib/bolt/config/transport/options.rb
- lib/bolt/config/transport/ssh.rb
- lib/bolt/logger.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/exec_connection.rb
- schemas/bolt-transport-definitions.json
- spec/bolt/transport/ssh/exec_connection_spec.rb
- spec/integration/logging_spec.rb
- spec/integration/transport/ssh_spec.rb
This PR accomplishes 3 main tasks:
* It renames `external-ssh` to `native-ssh`, to make the purpose of the configuration option and documentation more intuitive and clear
* It adds a new `native-ssh` SSH configuration option which is used to enable shelling out to SSH rather than using the Ruby net-ssh library. Previously this option was toggled based on the presence of `ssh-command` configuration, which overloaded the option to both enable native ssh and provide the command that should be used to connect via SSH. This makes it so that if `native-ssh` is not set, `ssh-command` will be ignored
* Lastly it adds a new `warn_once` logging utility, which stores warn_once warnings in an instance variable on the `Bolt::Logger` class and verifies each warning type of warning is only printed once …
> (GH-1938) Add native-ssh config option and warn_once logging utility

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
- spec/integration/plugin/module_spec.rb
- spec/integration/plugin/task_spec.rb
- spec/integration/yaml_plan_spec.rb
Previously when we created a new instance of the `Bolt::CLI` object we
also loaded the default `Bolt::Config` object in order to create a
default outputter to print errors with. This caused any errors loading
config or the default project to be unhandled and backtrace. The error
was especially annoying because it used the default project path at
`~/.puppetlabs/bolt`, regardless of whether that was the actual project
that would be used during the Bolt run.
This commit moves the same behavior of the default outputter directly
into the CLI (namely printing any error messages to stdout, in red if
it's a tty) so that we no longer need to load the default project for
every invocation of Bolt. This makes it so any errors that occur when
loading config are printed, and their exit code returned, …
> (GH-1917) Don't create Bolt Config object before loading config

- CONTRIBUTING.md
The Ruby Installer deprecated the ruby.devkit package and bundles devkit inside the main ruby package. This updates the instructions with the correct identifiers and explains this a bit better.
> (maint) Update Contributing windows doc

- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/linux.yaml
- .github/workflows/modules.yaml
- .github/workflows/windows.yaml
- CONTRIBUTING.md
- README.md
- acceptance/README.md
- acceptance/lib/acceptance/bolt_setup_helper.rb
- developer-docs/adding-gem-dependencies.md
- developer-docs/releasing-bolt.md
- documentation/applying_manifest_blocks.md
- documentation/bolt.ditamap
- documentation/bolt_installing_modules.md
- documentation/bolt_options.md
- documentation/experimental_features.md
- documentation/migrating_inventory_files.md
- documentation/running_bolt_commands.md
- resources/plugins.md
- scripts/generate_changelog.rb
This updates documentation, scripts and github workflows to point to the
'main' branch instead of 'master'.
> (GH-1901) Change 'master' references to 'main'

- lib/bolt/apply_result.rb
- lib/bolt/shell/powershell/snippets.rb
- spec/bolt/apply_result_spec.rb
- spec/integration/apply_error_spec.rb
Correctly detects the Puppet Agent install path on Windows during the initialization steps in a WinRM connection. It then uses the correct install path to amend the environment PATH variable.
The error text was modified to more clearly state we looked in known locations but could not find a valid install path.
> (GH-1967) Detect puppet agent install path on windows

- lib/bolt/project.rb
Previously, when passing the Bolt project to Puppet to turn into a
module, we were exposing the "path" variable as a Pathname instance.
Puppet expects the path will always be a string and fails in at least
one case if it receives another value. Since we just use Pathname for
our own internal tracking, we now turn it into a string in the `to_h`
method for Puppet's consumption.
!bug
* **Don't fail for tasks referring to project-level files**
Tasks with a `files` key that refers to files that exist at the
project level will now load properly rather than throwing an error.
> (maint) Don't expose Pathname object to Puppet

- documentation/bolt_inventory_reference.md
The inventory reference page erroneously listed `puppet_agent` as the
feature to indicate the agent is already installed on targets. The
correct name for the feature is `puppet-agent`. This corrects the
document.
> (maint) Fix puppet-agent feature documentation

- documentation/bolt_known_issues.md
This adds links to GitHub issues for each of the issues listed on the
'Known issues' doc. It also updates several of the issues to provide
more context on the issue and clearer instructions on any applicable
workarounds.
> (GH-1973) Add GH issue links to 'Known issues' doc

- bolt-modules/boltlib/lib/puppet/datatypes/target.rb
- documentation/using_plugins.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/logger.rb
- lib/bolt/pal/yaml_plan/evaluator.rb
- lib/bolt/plugin/module.rb
- lib/bolt/project.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/logger_spec.rb
- spec/bolt/pal/yaml_plan/evaluator_spec.rb
- spec/integration/apply_compile_spec.rb
- spec/integration/yaml_plan_spec.rb
Previously, we had no way to track how many users were experiencing
warnings for deprecated features, or which deprecated features were
being used. This commit adds a new class method `deprecation_warning` to
the `Bolt::Logger` class, which sends an analytics event with which type
of warning was issued then calls `warn_once` for the deprecation. This
also changes existing deprecation warnings to use the new deprecation
method, and audits existing warnings to determine if they should use
`warn_once` or `deprecation_warning`.
Closes #1964
> (GH-1964) Add deprecation warning utility

- lib/bolt/config.rb
- lib/bolt/outputter/rainbow.rb
The Paint gem detects the OS and what terminal it is running in and makes some decisions about what color scheme is supported. On windows it assumes no color is supported unless the `ANSICON` or `ConEmuANSI` enviroment variables are set. Until that gem is updated to detect Windows 10 and treat it as valid, we can force the Paint gem to work by setting the mode manually.
We could instruct the user to set `ANSICON` to true or `ConEmuANSI` to ON and get rainbow formatting (not ideal but ) or set either of those variables ourselves in the code (I don't think that is acceptable).
Instead if we set `Paint.mode` to `TRUE_COLOR` (`0xFFFFFF`) if we are on Windows, the user does not have to do anything. This works in PowerShell 5.1, 6, 7, WSL, and even in cmd.exe on Windows 10. We need to detect OS …
> (maint) Support Rainbow format on windows

- pwsh_module/pwsh_bolt.psm1.erb
Removes a work in progress implementation of formatted objects from the generated PowerShell module. This would cause the module to fail to import on a PowerShell 2 host.
> (maint) Remove PowerShell Classes from module

- documentation/bolt_installing.md
This corrects a line on our installing Bolt documentation page for
checking the user's Powershell version from `$PSTableVersion` to
`$PSVersionTable`.
> (docs) Correct Powershell version command

- documentation/bolt_connect_puppetdb.md
- lib/bolt/config/options.rb
- lib/bolt/puppetdb/client.rb
- lib/bolt/puppetdb/config.rb
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
- spec/bolt/puppetdb/client_spec.rb
- spec/bolt/puppetdb/config_spec.rb
This adds support for a `connect_timeout` and `read_timeout` option
in `puppetdb` config. The `connect_timeout` value is used to set the
connection timeout for the HTTP client that connects to PuppetDB, while
`read_timeout` is used to set the receive timeout for the HTTP client.
The value for each of these options must be a positive integer. If the
options are not set, both are set to the default values defined by the
`httpclient` Ruby library (currently 60 seconds).
!feature
* **Configure connection and read timeout length in PuppetDB client**
([#1994](#1994))
Users can now configure the connection and read timeout length for the
PuppetDB client with the `connect_timeout` and `read_timeout`
options under the `puppetdb` config option.
> (GH-1994) Configure timeouts in PuppetDB client

- .rubocop.yml
- lib/bolt/catalog.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/inventory/group.rb
- lib/bolt/inventory/inventory.rb
- lib/bolt/outputter/rainbow.rb
- lib/bolt/pal.rb
- lib/bolt/plugin/puppetdb.rb
- lib/bolt/util.rb
- lib/bolt_server/transport_app.rb
- lib/bolt_spec/plans/action_stubs.rb
- libexec/bolt_catalog
This adds configuration for several new default cops introduced in
Rubocop 0.88. It also enables the `Style/BisectedAttrAccessor` cop,
which was previously disabled due to a bug.
> (maint) Configure new default cops for Rubocop 0.88

- lib/bolt/shell/bash.rb
- spec/fixtures/modules/env_var/plans/command.pp
- spec/integration/run_as_spec.rb
Previously we passed `-E` to the sudo command built in the bash shell if
the operation required environment variables to be passed. Prior to #1899
this was needed because we set environment variables when invoking sudo
and required it to preserve them so they would be visible to the command
being invoked. We now pass the environment variables as arguments to
sudo, making the flag unnecessary and raising errors for users who don't
have permissions to preserve the environment.
Closes #1993
!feature
* **Environment preservation permission no longer required when using run-as** ([1993](https://github.com/puppetlabs/bolt/issues/1993))
Bolt no longer passes the `-E` flag to sudo when building commands
using 'run-as', which allows users who do not have permission to use the
flag to use Bolt.
> (GH-1993) Remove -E from bash commands

- documentation/bolt_configure_orchestrator.md
Most of the docs changes are happening on the PE side,
but this updates the doc to recommend Puppet tasks and
plans where possible.
> (GH-1936) Docs - connecting Bolt to PE

- Gemfile
This groups together the bolt server gems in the Gemfile to allow a user to omit these gems if they want. This decreases the amount installed and speeds up the time it takes to bundle install this project on windows.
> (maint) Group bolt server gems

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
This fixes a bug introduced in #1917 that caused errors raised before
config is loaded to be re-raised and rescued by `Bolt::CLI#parse` and
sent to the outputter. This resulted in a `NoMethodError` being raised,
as the outputter relies on the config being loaded when it is
instantiated.
This seperates the logic that was in the `#parse` method into three
separate methods. The `#parse_command` method handles parsing and
validating the command, the `#load_config` method loads the project and
config, and the `#finalize_setup` method finishes configuring Bolt and
issuing any warnings from the previous steps.
Splitting the logic into separate methods allows us to handle errors
raised before and after config is loaded differently.
!bug
* **Do not re-rescue errors raised before config is loaded** …
> (bug) Do not re-rescue errors raised before config is loaded

- spec/fixtures/hiera/plan_hiera.yaml
- spec/fixtures/hiera/plan_hiera_interpolations.yaml
- spec/integration/lookup_spec.rb
Previously, Bolt would use the same Hiera hierarchy for lookups both
inside apply blocks and outside apply blocks, and simply removed facts
and vars from the PAL ScriptCompiler to prevent users from using
interpolations in their hierarchies for lookups outside apply blocks.
This meant that hierarchies that used interpolations would error even if
the user wasn't looking up data that included an interpolation. To
mitigate this, we added a separate hierarchy under the key
`plan_hierarchy` in puppetlabs/puppet#8232. This PR adds integration
level tests to verify that the plan hierarchy is loaded and used
correctly, and marks them as pending since this feature won't be
available in Bolt until Puppet 6.18 ships.
> (GH-1835) Add tests for plan_hierarchy lookups

- Rakefile
This updates the path to the changelog script in the changelog rake task
to be relative to the current directory instead of the parent directory.
> (bug) Fix changelog script path in rake task

- lib/bolt/transport/winrm/connection.rb
- spec/fixtures/modules/error/plans/winrm_disconnect.pp
- spec/integration/winrm_spec.rb
Previously, losing connection to WinRM (for instance, due to the
service being stopped or restarted) would cause a stacktrace and a
deadlock. This happened because we manage the output from the command in
a thread which wasn't handling exceptions. The stack trace came from the
exception bubbling up, with the default behavior of Thread being to
print all exceptions that escape the thread. The deadlock came from our
failure to close the out/err streams that the shell was waiting on.
We now ensure the out/err streams are always closed and we disabled the
"report_on_exception" behavior to avoid an unnecessary stack trace, as
our own code will handle the exception at the next level up.
> (GH-1982) Handle WinRM connection loss

- documentation/bolt_installing_modules.md
The Forge instructions are going to recommend using
`bolt project init` + `--modules` for new users. This updates the
Bolt docs to expand on this command.
!no-release-notes
> (FORGE-559)(DOCS) Update modules doc

- Puppetfile
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- modules/secure_env_vars/plans/init.pp
- spec/bolt/cli_spec.rb
- spec/integration/parsing_spec.rb
This adds the `--env-var` cli flag, which accepts a string that contains
an equals sign and parses it into a key-value pair to set as an
environment variable on the target. This flag is only available when
running commands or scripts, and can be specified multiple times with
different environment variables. If the same key is specified multiple
times the last instance will take precedence. This doesn't interact with
`_env_var` specified in plans since the flag can only be used when
running commands and scripts.
Closes #1980
!feature
* **Specify remote environment variables using --env-var** ([1980](https://github.com/puppetlabs/bolt/issue/1980))
Users can now set environment variables on targets when running
commands and scripts using the CLI flag `--env-var`.
> (GH-1980) Add --env-var cli flag

- .github/workflows/schemas.yaml
- spec/bolt/config/options_spec.rb
- spec/bolt/config/transport/options_spec.rb
- spec/lib/bolt_spec/options.rb
This adds tests to ensure that the config options hashes include
`:type` and `:description` keys, which are required to correctly
generate Bolt's JSON schemas.
It also includes a workflow for generating the JSON schemas and
checking if there were any changes from the schemas that were committed.
If there are changes, the workflow fails and notifies the user that they
should run the `schemas:all` Rake task and commit the changes.
Closes #1997 
> (GH-1997) Add tests for JSON schemas

- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
- documentation/configuring_bolt.md
It's unclear from the existing documentation whether `_run_as` will
override existing configuration for a target, and how the plan function
option will be used in sub-plans (plans called from another plan where
`run_plan` has `_run_as` set). This clarifies that `_run_as` will take
precedence over existing target configuration, and that it will be
applied to all connections created from an function call, including
sub-plans and even sub-sub-plans where the initial plan has `_run_as`
specified.
Note: I'm a bit dubious of the formatting of the multiline strings in the docs here. Suggestions welcome!
> (docs) Clarify `_run_as` precedence and behavior

- documentation/applying_manifest_blocks.md
Feedback is that the word "manifest" might be contributing
to discovery issues. I haven't removed the term from the doc,
but I've renamed the doc so it's easier to find in the hierarchy.
I've also made some of the language in the doc a little more direct.
!no-release-notes
> (Docs) Slight rename and simplify language

- developer-docs/bolt_spec-run.md
- developer-docs/kerberos.md
- documentation/README.md
- documentation/bolt_examples.md
- documentation/bolt_installing.md
- documentation/bolt_options.md
- documentation/bolt_types_reference.md
- documentation/getting_started_with_bolt.md
- documentation/inventory_file_v2.md
- documentation/running_bolt_commands.md
- documentation/running_bolt_from_docker_image.md
- documentation/running_bolt_in_docker.md
- documentation/troubleshooting.md
- documentation/writing_plans.md
- documentation/writing_plugins.md
This modifies the documentation to prefer bolt-project.yaml,
bolt-defaults.yaml, and inventory.yaml over bolt.yaml. This mostly
includes instructing users to create a `bolt-project.yaml` instead of a
`bolt.yaml` file to create a Bolt project (both of which work at this
time), and specifying which file certain configuration options should
belong it. It doesn't update the documented default files or remove
bolt.yaml documentation, as bolt.yaml is still technically default and
has not been removed.
Closes #1841
> (GH-1841) Prefer bolt-*.yaml and inventory.yaml to bolt.yaml in documentation

- documentation/writing_yaml_plans.md
- lib/bolt/pal/yaml_plan/evaluator.rb
- lib/bolt/pal/yaml_plan/step.rb
- lib/bolt/pal/yaml_plan/step/message.rb
- spec/bolt/pal/yaml_plan/evaluator_spec.rb
- spec/bolt/pal/yaml_plan/step_spec.rb
- spec/bolt/pal/yaml_plan_spec.rb
This adds a YAML plan message step that prints a message. Messages are
printed to `stdout` when using the `human` output format and `stderr`
when using the `json` output format.
!feature
* **YAML plan message step**
([#2038](https://github.com/puppetlabs/bolt/issues/2038))
YAML plans now support a message step that prints a message.
> (GH-2038) Add YAML plan message step

- Puppetfile
This bumps the puppetlabs-service module to 1.3.0 to include the
'enable' and 'disable' actions.
!feature
* **Service task now supports 'enable' and 'disable' when available**
The builtin Bolt service task now supports 'enable' and 'disable' for
agentless targets if the actions are available on the target.
> (maint) Bump service module to include enable feature

- bolt-modules/dir/Rakefile
- bolt-modules/dir/lib/puppet/functions/dir/children.rb
- bolt-modules/dir/spec/functions/dir/children_spec.rb
- bolt-modules/dir/spec/spec_helper.rb
- rakelib/tests.rake
This adds a new builtin Bolt module `dir` that contains utilities for
interacting with directories during a Bolt plan, analagous to Ruby's
`Dir` class. It currently has just one function, `children`, which lists
the contents of a given directory and returns an ordered list of bare
filenames. This is used in the `facts::external` plan to get the list of
scripts to run to generate facts from.
The function accepts either an absolute path, a path relative to the
root of the active Bolt project, or a module and subpath. All of these
are only accepted as strings. If none are found, an error is raised.
!feature
* **New dir::children plan function**
New plan function `dir::children` returns an array containing all of
the filenames in the given directory, similar to Ruby's `Dir.children()`
> (GH-1981) Add dir::children plan function

- documentation/inventory_file_v2.md
Feedback from community Slack suggests we should be clearer
about how `uri`, `alias`, and `name` work in inventory files.
I've moved the examples up in the doc and added some extra
clarification.
> (Docs) Clarify inventory name, alias, uri

- documentation/running_bolt_commands.md
- lib/bolt/executor.rb
This catches existing file errors that are raised when creating the
destination directory for file downloads in the
`Bolt::Executor#download_file` method. Previously, if any portion of the
destination directory was an existing file, Bolt would error and emit a
backtrace. This catches those errors and adds additional information
that the destination directory could not be created.
Any similar errors raised when files are being downloaded by the
individual transports are already caught and handled by the transport.
!bug
* **Handle existing file errors when downloading files**
Bolt now handles existing file errors raised when creating the
destination directory for file downloads. Previously, if a file
already existed somewhere on the destination directory path, Bolt
would raise an error with …
> (bug) Catch existing file errors when downloading files

- documentation/applying_manifest_blocks.md
- documentation/writing_yaml_plans.md
This adds a section to the 'Writing YAML plans' docs that describes how
to use Puppet code from a module in a YAML plan. It also adds a link to
this section in the 'Applying Puppet manifests' doc.
Closes #2032 
> (GH-2032) Document using Puppet Forge modules in YAML plans

- lib/bolt/catalog.rb
- spec/bolt/catalog_spec.rb
This fixes a bug in catalog compilation that was caused by modifying the
order of plan variables in the catalog request. This bug was caused by
the following conditions being met:
- A plan variable has the same name as a target variable
- The plan variable references the same complex data as a variable that
was listed earlier in the plan (for example, it references a target's
config)
When Puppet serializes data with local references, it replaces any
repeated, complex data with a local reference. Then, when this data is
deserialized, Puppet will examine the variables in order and resolve any
local references it comes across. If a local reference appears before
the data it references, Puppet will be unable to resolve the reference
and will raise an error.
In short, Puppet expects that any …
> (GH-2025) Do not modify order of plan variables in catalog compilation

- documentation/templates/bolt_configuration_reference.md.erb
- documentation/templates/bolt_defaults_reference.md.erb
- documentation/templates/bolt_project_reference.md.erb
- documentation/templates/bolt_transports_reference.md.erb
This adds 'Available values' to the configuration reference pages for
every option that has a restricted list of available values, which is
indicated by the presence of the `:enum` key in the configuration
options hash.
> (docs) Add available values for options to configuration references

- lib/bolt/cli.rb
Previously, the code for this command was executing and exiting *before*
the point where we would send a data point about its invocation to
google analytics. That meant it appeared that nobody had ever used this
command. We now fold it into an existing case expression after the
analytics report has been sent.
> (maint) Report screen_view for `bolt plan convert` command

- lib/bolt/project.rb
This moves the name segment regex `/^[a-z][a-z0-9_]*$/` to a constant in
the project class, `Bolt::Project::NAME_SEGMENT_REGEX`. It also updates
the regex to use `\A`/`\Z` in place of `^`/`$`, as the latter does not
properly match against multi-line strings.
!bug
* **Reject multi-line project names**
Previously, Bolt would accept a multi-line string as a project name,
causing multiple errors. Bolt will now reject multi-line strings as
project names.
> (maint) Add name segment regex constant in Bolt::Project

- lib/bolt/project.rb
Reverts puppetlabs/bolt#2063
This constant is already defined at Bolt::Module::MODULE_NAME_REGEX, we should just use that instead.
> Revert "(maint) Add name segment regex constant in Bolt::Project"

- documentation/experimental_features.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/module.rb
- lib/bolt/project.rb
- pwsh_module/command.tests.ps1
- rakelib/pwsh.rake
- spec/bolt/cli_spec.rb
This adds a new `bolt plan new` command for generating a project-level
YAML plan. The command accepts a single argument, the name of the plan
that should be generated. If the given name is a valid plan name, and
the plan does not yet exist, Bolt will generate the necessary
directories under `<project>/plans` as well as the YAML plan file. Bolt
will then display the path to the plan, as well as commands to show and
run the plan.
The generated plan includes a single parameter and a couple simple plan
steps, comments describing each portion of the plan, and a link to the
'Writing YAML plans' documentation. The intent behind the generated plan
is to show users the structure of a YAML plan and provide helpful
information to get started with writing a plan.
This also fixes a bug where …
> (GH-2004) Add 'bolt plan new' CLI command

- .rubocop.yml
- lib/bolt/bolt_option_parser.rb
- lib/bolt/executor.rb
- lib/bolt/plugin/prompt.rb
- lib/bolt_spec/plans/action_stubs.rb
- libexec/apply_catalog.rb
- libexec/bolt_catalog
- libexec/custom_facts.rb
- libexec/query_resources.rb
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
- spec/bolt/plugin/prompt_spec.rb
- spec/integration/inventory_spec.rb
This configures several new Rubocop cops released in Rubocop 0.89. Only
a handful of cops actually impact existing Bolt code, namely:
- Lint/MissingSuper
- Style/ExplicitBlockArgument
- Style/GlobalStdStream
- Style/OptionalBooleanParameter
- Style/SingleArgumentDig
- Style/StringConcatenation
I disabled cops that didn't seem useful, or would require more than 5
minutes of code rewriting to silence. The only cop I left enabled that
resulted in code changes was `Style/GlobalStdStream`, which prefers
`$stdout` to `STDOUT`. I left all other cops that didn't impact existing
code enabled.
> (maint) Configure new Rubocop cops

- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/project.rb
- pwsh_module/command.tests.ps1
- rakelib/pwsh.rake
- spec/bolt/cli_spec.rb
This PR modernizes the behavior for the `bolt project init` command in a
few ways:
- Previously, `bolt project init` with no arguments would create an
empty `bolt.yaml`file in the current working directory. It now creates
a file `bolt-project.yaml` in the current working directory, with the
content:
```
---
name: <cwd_basename>
```
where `cwd_basename` is the name of the directory.
- Previously the command took an optional argument `[directory]` with a
path to where to create the project. The command no longer accepts the
directory as an argument. It instead has an optional argument `[name]`
which specifies the name of the project.
```
$ bolt project init myproject
$ cat bolt-project.yaml
---
name: myproject
```
- If `bolt-project.yaml` or `bolt.yaml` exist, we warn and do not modify the …
> (GH-2003) 'bolt project init' now creates bolt-project.yaml

- bolt-modules/out/lib/puppet/functions/out/message.rb
- lib/bolt/outputter.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- spec/bolt/outputter/outputter_spec.rb
This allows users to pass any data type to the `out::message()` plan
function and send it to the configured outputter for printing. This
adds a formatting function to the outputter that all messages pass
through, which formats known Bolt datatypes and classes nicely for
readable printing. Any unhandled types are stringified and passed to the
outputter. Printing is still left entirely to the outputter, but
formatting is shared among all outputter that inherit from the base
outputter class `Bolt::Outputter`. This ensures a consistent experience
across outputters.
Closes #2012
!feature
* **Print objects using out::message()** ([#2012](https://github.com/puppetlabs/bolt/issues/2012))
Users can now print any valid data type using the plan function
`out::message()`.
> (GH-2012) Print objects using out::message

- bolt-modules/ctrl/lib/puppet/functions/ctrl/do_until.rb
- bolt-modules/ctrl/spec/functions/ctrl/do_until_spec.rb
This adds an `interval` option to the `ctrl::do_until` plan function. It
accepts a numeric value specifying the number of seconds to sleep
before repeating the block again.
Closes #2072 
!feature
* **Set interval for repeating block in `ctrl::do_until` plan function**
([#2072](https://github.com/puppetlabs/bolt/issues/2072))
The `ctrl::do_until` plan function now accepts an `interval` option.
This option accepts a numeric value that specifies the number of
seconds to wait before repeating the block.
> (GH-2072) Add 'interval' option to 'ctrl::do_until' function

- documentation/experimental_features.md
This removes Bolt projects from the experimental features doc, which was
missed when projects were moved out of experimental.
> (docs) Remove bolt projects from experimental features page

- lib/bolt/analytics.rb
- spec/bolt/analytics_spec.rb
When Bolt loads the anayltics config file, it uses the `YAML.load`
method. If the file is empty, or otherwise cannot be parsed as YAML,
this method returns `false`. This causes an error when Bolt checks the
loaded config for the `disabled` key, as the returned value is not a
hash.
This updates the `Bolt::Analytics.load_config` method to return an empty
hash when the analytics config file cannot be parsed as YAML.
!bug
* **Do not error when analytics configuration file is empty**
Empty analytics configuration files would cause Bolt to raise a
`NoMethodError`. Now, if an analytics configuration file is empty,
Bolt will instead rewrite the file.
> (bug) Return empty hash when analytics file is empty

- lib/bolt/cli.rb
- lib/bolt/pal.rb
- lib/bolt_server/pe/pal.rb
When we print the modulepath for users when listing tasks or plans, we
previously would calculate the modulpath by subtracting the
Bolt-packaged modulepaths `boltlib` and `modules` from the full
modulepath. This erroneously removes `modules` from the modulepath if it
is listed in the user's path though, which is confusing. This modifies
the modulepath to be calculated from the original modulepath the user
supplied, so that any supplied modulepaths aren't incorrectly removed.
!bugfix
* **Include modules/ in displayed modulepath if it's in the user-configured modulepath**
Bolt now includes `<bolt-installation-directory>/modules` in the displayed
modulepath if the user has the path as a component of their configured
modulepath. If installed as a package on *nix,
bolt-installation-directory …
> (bugfix) Don't remove Bolt modulepaths from the modulepath when listing

- lib/bolt/pal/yaml_plan/evaluator.rb
- spec/bolt/pal/yaml_plan/evaluator_spec.rb
This fixes a bug in the YAML plan message step, which was passing
arguments to the `out::message` plan function incorrectly. Previously,
the message was passed directly to the plan function. If the message was
an object such as an array or hash, the object would be splatted and
passed to the `out::message` plan function as multiple arguments. Now,
the message is passed as a single element array to the plan function,
allowing the function to be called correctly.
!bug
* **Correctly pass objects to YAML plan message step**
Bolt was incorrectly passing objects used in the YAML plan `message`
step, resulting in an error. Any objects used in YAML plan `message`
steps are now correctly passed and printed to the console.
> (bug) Pass YAML plan message argument in array

- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
This commit adds a new endpoint to list all tasks to bolt-server,
similar to the /plans endpoint that already exists. Tasks are
returned as an array where each element in the array is of the
form `{"name":"<TASK_NAME>"}`
> (PE-29929) Add /tasks endpoint to bolt-server

- documentation/writing_plans.md
This updates several `run_*` function calls in the example plans of the
'Writing plans' doc to use a consistent format for specifying plan,
task, and parameter names. Previously, the doc was inconsistent in how
it showed specifying plan, task, and parameter names, switching between
quoted and unquoted names.
This also fixes a `run_plan` function call that was specifying the
`**puppetdb_fact**` plan, instead of `puppetdb_fact`.
> (docs) Update run_* function calls in 'Writing plans' docs

- lib/bolt/pal.rb
- spec/bolt/cli_spec.rb
This fixes a minor bug in `Bolt::PAL.get_plan_info` that incorrectly
built the parameter hash for YAML plans, resulting in an inaccurate
usage line in `bolt plan show <plan>` output.
Previously, if a YAML plan parameter did not have a default value,
the parameter hash would receive a value of `nil` for the parameter's
default value. When this hash is received by the outputter to display
the plan info, it would check whether the parameter had a default value
key specified to determine whether it should display the parameter as
optional or required in the usage line. Since parameters for YAML plans
would always have this key, the outputter would show all parameters as
optional. Now, the default value key is only added if there is a default
value for the parameter.
!bug
* **Show YAML plan …
> (bug) Show YAML plan parameters without defaults as required

- documentation/bolt_installing_modules.md
- documentation/troubleshooting.md
In addition to shuffling some content around in the modules doc. I added a couple sentences to the "Install a module to an existing project" section intro about dependencies. 
I also snuck in a change to the troubleshooting page title.
> (Docs) Installing modules shuffle and edit

- documentation/bolt.ditamap
This gives the plans and tasks parent pages short titles in the
navigation, while preserving the longer titles on the actual pages.
I've had some feedback that the long titles make it harder for users
to find these pages. This should make it easier to quickly find the
docs in the sidebar while retaining the longer titles on the pages,
which I feel offer important contextual information.
> (Docs) Update side nav titles for plans and tasks

- lib/bolt/config.rb
Previously, we always defined a default `bolt-debug.log` and tried to
write to it. That would fail if the user had no project and also had
not created the default project directory.
We now check whether the project directory exists and only try to write
a debug log if it does. This is largely an interim solution and we
should eventually handle and prevent the cases where we might run
without an extant project directory.
!bug
* **Don't fail if bolt-debug.log can't be created**
([#2115](https://github.com/puppetlabs/bolt/issues/2115))
This fixes a bug introduced in Bolt 2.24.0 where Bolt would fail
when trying to create the `bolt-debug.log` file if the Bolt project
didn't exist.
> (GH-2068) Only write a debug log if the project exists

- Puppetfile
- spec/integration/apply_spec.rb
Puppet agent 4.1.1 includes several updates we'd like to pick up,
including:
- Stopping agent runs if Puppet is upgraded mid-run
- Adding a puppet_agent::run plan to run the agent on remote targets
This allows users to run the agent without Bolt erroring due to a
non-zero exit code.
Closes #2022
!feature
* **Add puppet_agent::run plan to run the agent** ([#2022](https://github.com/puppetlabs/bolt/issues/2022)
The puppet_agent::run plan will run the agent if it's available and
returns a resultset including agents that failed and the results from
runs that succeeded.
> (GH-2022) Pickup puppet agent 4.1.1

- bolt.gemspec
This temporarily pins Puppet to 6.17.0 until we can merge in
puppetlabs/bolt#2051 and puppetlabs/bolt#2074, as the Puppet 6.18.0
release includes changes that rely on these being merged. Without
pinning Puppet to 6.17.0, Bolt will fail when run from source.
> (maint) Pin Puppet to 6.17.0

- pwsh_module/command.tests.ps1
- pwsh_module/pwsh_bolt.psm1.erb
- pwsh_module/pwsh_bolt_internal.ps1
- rakelib/pwsh.rake
The `-params` parameter was originally typed an `[object]` to allow both string `action=status name=spooler` and hashtable values `@{ action = 'status'; name = 'spooler' }`. This succeeded with hashtables but failed with strings because PowerShell parses `action=status name=spooler` into two groups of parameter-value pairs: `action=status` and `name=spooler`. PowerShell then (rightly) fails to bind the second set of params to any of the existing parameter sets and produces an error. The fix for this is to make `-params` have the `ValueFromRemainingArguments` attribute which will pull in all of the task params and store it in `-params`.
This fix however falls into a subtle trap in the switch statement in `Get-BoltCommandLine`. In PowerShell switch statements unwrap arrays and since we …
> (GH-2118) Fix Invoke-BoltTask -params

- lib/bolt_spec/run.rb
This updates `BoltSpec::Run` to initialize Bolt's logger as part of
initializing the `BoltRunner`. Previously, the logger was not
initialized, which would cause BoltSpec to fail whenever Bolt attempted
to log a message to the `trace` level, which is not a level recognized
by default in the `Logging` class. This fix ensures that `BoltSpec::Run`
will always initialize the logger in the same manner as Bolt itself.
!bug
* **Initialize logger in `BoltSpec::Run`**
([#2117](https://github.com/puppetlabs/bolt/issues/2117))
Bolt now initializes the logger when using `BoltSpec::Run` methods.
Previously, the logger was not initialized with Bolt's custom log
levels, causing `BoltSpec::Run` to raise an error when it encountered
a message being logged to one of these custom levels.
> (GH-2117) Initialize logger in BoltSpec::Run

- documentation/bolt_installing.md
- documentation/projects.md
- lib/bolt/config.rb
- lib/bolt/config/options.rb
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
- spec/bolt/config_spec.rb
We now allow users to set a log config to the string "disable" to indicate
that the file should be disabled if it was defined at a previous level of
the config hierarchy. This also allows users to disable the default
bolt-debug.log file.
This behavior actually worked already, but only incidentally as we happened
to skip over any logs whose config wasn't a Hash. We now explicitly check
for the string "disable" and otherwise fail if the value isn't a Hash.
!feature
* **Disable log files by setting them to `disable`**
([#2120](https://github.com/puppetlabs/bolt/issues/2120))
Log files can now be disabled if they were set at a previous level
of the hierarchy. This also allows the default `bolt-debug.log` file
to be disabled.
> (GH-2120) Disable log files when set to "disable"

- lib/bolt/bolt_option_parser.rb
This fixes some typos in the `project show` help text, which
erroneously said how to show a list of tasks and how to run
a task.
> (maint) Fix 'project show' help text

- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/inventory.rb
- lib/bolt/project.rb
- spec/bolt/config_spec.rb
- spec/integration/yaml_plan_spec.rb
This will now log the path that a project is loaded from at `info`
level. This also moves the message listing loaded config files to
`debug`. Lastly this adds a message when Bolt is searching for a project
and doesn't find one at the path stating that the path won't be loaded
as a project.
This also does some restructuring of how logs are gathered from project
and config loading and passed back to the CLI to be logged. Because the
project and config are loaded before the logger is configured (because
log configuration is in the config), we need to store up those logs and
pass them back to the CLI so they can be logged once everything is set
up. Previously we just had a `warnings` instance variable on the config
class that inherited from the project class, got read and logged. The
same …
> (GH-1995) Log where projects are loaded from

- bolt-modules/boltlib/lib/puppet/datatypes/result.rb
- documentation/bolt_types_reference.md
- documentation/writing_tasks.md
- lib/bolt/result.rb
- spec/bolt/result_spec.rb
- spec/fixtures/apply/puppet_types/plans/sensitive_result.pp
- spec/fixtures/apply/sensitive/tasks/init.sh
- spec/integration/apply_compile_spec.rb
When constructing a Bolt::Result from the output of a task, we now look
for a _sensitive key and wrap it in Puppet's Sensitive type if found.
This prevents the data from being printed on the CLI.
!feature
* **Allow task output to be treated as sensitive**
([#2086](https://github.com/puppetlabs/bolt/issues/2086))
Tasks can now return a _sensitive key in their output which can
contain an arbitrary value which will be treated as sensitive by
Bolt. This means that it won't be printed to the console or log at
any log level, and plans will need to use unwrap() to get the value.
> (GH-2086) Treat the _sensitive key as sensitive

- bolt-modules/boltlib/lib/puppet/functions/download_file.rb
- bolt-modules/boltlib/spec/functions/download_file_spec.rb
- bolt-modules/dir/lib/puppet/functions/dir/children.rb
- bolt-modules/dir/spec/functions/dir/children_spec.rb
- bolt.gemspec
- lib/bolt/applicator.rb
- lib/bolt/catalog.rb
- lib/bolt/pal.rb
- lib/bolt/project.rb
- spec/bolt/catalog_spec.rb
- spec/bolt/cli_spec.rb
- spec/bolt/pal_spec.rb
This adds a method `load_as_module?` to the `Bolt::Project` class to use
in Puppet to determine whether to load the project as a module.
Previously, `bolt_project` would only be set if the project was named,
which isn't necessary for a valid project, and Puppet would only load
the project as a module if the setting was set. Puppet can now use
`load_as_module?` to determine whether to load the project as a module,
which lets us always set the `bolt_project` Puppet setting. This lets us
use that setting to access the project from within Bolt plan functions
for things like getting the project path to set the destination to
download files to.
This PR also removes the now-unnecessary `bolt_project_data` Puppet
setting, which was an interim means of accessing the project path from
plan …
> (GH-2051) Always set `bolt_project` Puppet setting

- lib/bolt/pal.rb
This updates `Bolt::PAL#in_bolt_compiler` to set the `set_local_facts`
option for the script compiler to `false`. Setting this will disable
setting facts, trusted facts, and server facts in the script compiler's
scope.
Changes made to Puppet in puppetlabs/puppet#8063 updated the script
compiler to never set facts in the script compiler's scope. However,
this resulted in breaking changes to PAL's public API. The work in
puppetlabs/puppet#8268 reverses these changes and adds the
`set_local_facts` option to allow users to disable setting facts if they
wish. By default, `set_local_facts` is set to `true`.
> (maint) Do not set facts for script compiler scope

- lib/bolt/bolt_option_parser.rb
This updates the `bolt plan convert` help text to state that the
converted plan is printed to the console, not written to a file. It also
clarifies that YAML plans are converted to Puppet language plans, as
"Bolt plan" is ambiguous.
> (maint) Update plan convert help text

- documentation/bolt_installing.md
Fixes #2042 
!feature
* **Packages for Fedora 32**
([#2042](https://github.com/puppetlabs/bolt/issues/2042))
Bolt packages are now available for Fedora 32.
> (GH-2042) Support Bolt on Fedora 32

- spec/fixtures/hiera/data/hierarchy.yaml
- spec/fixtures/hiera/data/plan_hierarchy.yaml
- spec/fixtures/hiera/modules/test/plans/plan_lookup.pp
- spec/integration/lookup_spec.rb
These tests were marked pending until Puppet 6.18 was released with the
needed Puppet-side changes to enable plan_hiera. This re-enables them
and adds the necessary fixtures.
> (maint) Unpend plan_hiera tests

- lib/bolt/pal.rb
- spec/fixtures/projects/named/modules/test_project/plans/init.pp
!feature
* **Bolt will now warn if a project has the same name as a module**
([#2108](https://github.com/puppetlabs/bolt/issues/2108))
Any module with the same name as the Bolt project will be ignored,
and Bolt will now issue a warning to indicate that.
> (GH-2108) Warn when Bolt project shadows module of the same name

- developer-docs/bolt-api-servers.md
This commit fixes the incorrect positioning of a code block ending
that was including a markdown heading.
> (maint) fix improper nesting in bolt-server api doc

- lib/bolt/result.rb
- spec/bolt/result_spec.rb
This updates `Bolt::Result.for_task` to ensure that an error object
returned from a task has the correct format. Previously, any error
object returned from a task was accepted as-is, even if it did not have
the expected `msg`, `kind`, and `detail` keys. Now, a `msg` key is
required, and Bolt will raise a helpful error if the error object is
missing this key. If either the `kind` or `details` keys are missing
from the error object, Bolt will automatically add reasonable default
values of `bolt/error` and `{}` to the error object.
!bug
* **Ensure task error objects have correct format**
([#2112](https://github.com/puppetlabs/bolt/issues/2112))
Bolt now ensures that error objects returned from a task have the
correct format and include a `msg` key. Bolt will also automatically
add `kind` and …
> (GH-2112) Ensure task error objects have correct format

- documentation/writing_plans.md
- documentation/writing_yaml_plans.md
Updates the "writing plans" docs to give more information about
the different options for debugging plans.
I've also made some style changes re stdout, stderr, stdin. These are abbreviations, so the way we usually deal with them is by giving the full term the first time they're used, with the abbreviation in brackets, and then thereafter using the abbreviation. No need for backticks.
closes GH-2007
> (GH-2007)(Docs) Debugging

- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/config/options.rb
- lib/bolt/project.rb
- lib/bolt/puppetfile.rb
- lib/bolt/puppetfile/installer.rb
- lib/bolt/puppetfile/module.rb
- rakelib/pwsh.rake
- schemas/bolt-project.schema.json
- spec/bolt/cli_spec.rb
- spec/bolt/project_spec.rb
- spec/bolt/puppetfile/installer_spec.rb
- spec/bolt/puppetfile/module_spec.rb
- spec/bolt/puppetfile_spec.rb
This adds a new Bolt command `bolt module install` that installs a list of
modules declared in the project's configuration file, as well as all of
their dependencies. This command will resolve all dependencies for the
declared modules, generate a Puppetfile with specifications for each
module, and then install the modules to the project's `.modules`
directory.
As part of this work, the project configuration file,
`bolt-project.yaml`, now accepts a new `modules` key. This key accepts
an array of module declarations, where each declaration is a map that
must include the module's name under the `name` key. The `name` key is
the only supported key at this time.
The installed modules can be found in a new `.modules` directory within
the project. This directory is not currently added to the …
> (GH-2082) Add 'module install' command to install module dependencies

- .rubocop.yml
This adds the following new cops introduced as defaults in Rubocop 0.90:
- `Lint/DuplicateRequire` (enabled)
- `Lint/EmptyFile` (enabled)
- `Lint/TrailingCommaInAttributeDeclaration` (enabled)
- `Lint/UselessMethodDefinition` (disabled)
- `Style/CombinableLoops` (enabled)
- `Style/KeywordParametersOrder` (enabled)
- `Style/RedundantSelfAssignment` (enabled)
- `Style/SoleNestedConditional` (disabled)
This also sorts the cops in the Rubocop configuration file and adds
links to the relevant documentation for categories of cops.
> (maint) Add new cops for Rubocop 0.90

- pwsh_module/command.tests.ps1
This commit comments out the hashtable test for the Invoke-BoltTask params parameter as the exact order of the returned JSON can vary. This is commented out so that project work can continue, while https://github.com/puppetlabs/bolt/issues/2148 is tasked on fixing the test.
> (maint) Comment Invoke-BoltTask params test

- developer-docs/bolt-api-servers.md
- lib/bolt_server/base_config.rb
- lib/bolt_server/config.rb
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
- spec/lib/bolt_spec/bolt_server.rb
This commit adds routes to bolt server for serving plan metadata from bolt-projects managed with code manager.
> (PE-29493) Add project_plans endpoints to bolt-server

- developer-docs/bolt-api-servers.md
- lib/bolt_server/base_config.rb
- lib/bolt_server/config.rb
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
- spec/lib/bolt_spec/bolt_server.rb
Add new endpoints to bolt-server capable of listing tasks and task metadata from bolt projects.
> (PE-29495) Serve task metadata from bolt-projects managed with code manager

- documentation/writing_plans.md
An example uses a non existing method on a ResultSet. This commit updates the example to use an existing method.
> (docs) Fix typo in writing_plans page

- lib/bolt/analytics.rb
- lib/bolt/config.rb
- lib/bolt/project.rb
- lib/bolt/rerun.rb
- spec/bolt/analytics_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/executor_spec.rb
- spec/bolt/project_spec.rb
- spec/integration/logging_spec.rb
This cleans up how we handle failures when Bolt fails to write a file to
the current project. We now attempt to create the project directory if
it is the default directory and does not exist. If that creation fails,
we warn and continue without a Bolt project - this effectively means
that Bolt has default configuration, and that logfiles and rerun files
will not be written. If any individual file can't be written to the
project, we warn once and continue. If multiple files can't be written,
we warn for the first file that isn't writeable and not for subsequent
files.
When users explicitly configure a logfile that is unwriteable we now
error.
When users explicitly configure a project that is unwriteable, we now
error.
Closes #2116
!bug
* **Handle project file writing errors more …
> (GH-2116) Handle file writing errors

- developer-docs/bolt-api-servers.md
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
Include whether plans/task from a bolt-project have been allowlisted in bolt-project.yaml
> (PE-30023) Add additional "allowed" metadata key for project

- .github/workflows/release-notes.yaml
This commit updates the commit message tag check to only run when the commit touches a file that contains a change to bolt source code. This excludes files in tests, bolt-server source, and other files that where changes will not need to be added to the changelog.
> (maint) Only require release notes tag for bolt source code

- pwsh_module/command.tests.ps1
The ConvertTo-JSON cmdlet respects JSON ordering in Powershell 5.1 and
7.1, but not version 7.0. This caused the test that verifies passing a
JSON object to Invoke-BoltTask to fail, as the ordering of JSON
parameters was wrong and the test simply verifies the resulting Bolt
command as a string. This updates the test to accept the JSON object
elements in any order. Because users and their tasks don't care about
the order, it doesn't make sense to fix this in the code itself - just
to update the test to also not care about the order.
Closes #2148
> (GH-2148) Fix JSON ordering in pester test

- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
- spec/integration/plan_spec.rb
This adds the `bolt module generate-types` and `bolt module show`
subcommands, which are analagous to `bolt puppetfile generate-types` and
`bolt puppetfile show-modules` respectively. These commands have the
exact same behavior as the puppetfile subcommands. The environment
variable `BOLT_MODULE_FEATURE` must be set to use the `bolt module`
subcommand. The puppetfile commands aren't deprecated yet - we'll do
that closer to 3.0. This also doesn't include a release note, as we're
launching the module feature dark until the entire workflow is complete.
Closes #2131
> (GH-2131) Add bolt module subcommands

- .github/workflows/litmus_smoke.yaml
This adds a new Github workflow that verifies that Litmus executes using
the latest version of Bolt. Since Litmus relies on Bolt to work, this
verifies that any changes in Bolt won't break Litmus before we merge.
This sets up a matrix of Ubuntu and Windows platforms and runs the tests
on each, where the test on Ubuntu uses a remote target and the Windows
test verifies Litmus against localhost. Both tests simply run the Litmus
acceptance tests using the Bolt version that triggered the action to run 
(so the PR branch).
> (maint) Add Litmus smoke tests

- documentation/projects.md
Updates a link to Bolt project configuration reference page from
`bolt_configuration_reference.md#project_configuration_options` to
`bolt_project_reference.md`.
> (docs) Update bolt project configuration reference link

- .github/workflows/litmus_smoke.yaml
This disables gem caching in the Litmus smoke tests, as it was causing
issues with setting up the test environment.
> (maint) Disable gem caching in Litmus smoke tests

- lib/bolt/inventory.rb
Commit 546b5554 replaced all calls to `Logging.logger` with a wrapper
method `Bolt::Logger.logger` that initializes logging before returning a
logger object, to ensure that the log methods we need are created.
However, commit 23bb8b33 was in flight at the same time and added a
*new* call to `Logging.logger`. These two changes logically conflicted
but not in a way that could be identified by Git. We therefore wound up
with an undesired call directly to `Logging.logger`, which can cause
failures related to the logging not being initialized when using Bolt as
a library.
This commit changes the `Logging.logger` call to the proper
`Bolt::Logger.logger`.
> (GH-2166) Ensure logging is initialized in inventory

- lib/bolt/cli.rb
This detection was broken since we added the secure_env_vars module as a
built-in, but didn't add it to the list of "expected" built-ins. That
caused Bolt to always believe there was "non-gem install" content
present and so it would never warn that the user had an incomplete
install.
!bug
* **Fix warning when running from a gem install**
Bolt again properly detects when it's being run from a gem install
and emits a warning.
> (maint) Properly detect gem install again

- documentation/troubleshooting.md
Users often have to disable SSL in order to connect to WinRM targets.
> (docs) Adding step for troubleshooting WinRM

- scripts/generate_changelog.rb
This checks whether the changelog includes any new features,
deprecations or removals and increments the y version if so, and the z
version if not. It still allows the version to be set explicitly if
needed, for major releases or cases where the heuristic is wrong.
> (maint) Automatically compute next version number

- bolt.gemspec
We updated puppet-runtime to use version 0.4.0 of the
puppetfile-resolver gem before updating dependency version here, causing
CI to fail. This updates the gem dependency version so that CI
environments work.
> (maint) Bump puppetfile-resolver version to pick up gem

- lib/bolt/cli.rb
- lib/bolt/config/options.rb
- lib/bolt/project.rb
- lib/bolt/puppetfile.rb
- lib/bolt/puppetfile/module.rb
- schemas/bolt-project.schema.json
- spec/bolt/cli_spec.rb
- spec/bolt/puppetfile/module_spec.rb
- spec/bolt/puppetfile_spec.rb
This adds support for specifying version requirements for a module
declaration under the `modules` key of a project config file. To specify
a version, the module declaration should have a `version_requirement`
key. Version requirements should be valid according to semantic-puppet,
and includes support for specific versions (`1.0.0`), version shorthand
(`1.x`), and version ranges (`>= 1.0.0 < 3.0.0`).
Depends on https://github.com/puppetlabs/puppet-runtime/pull/371
Closes #2168 
> (GH-2168) Add version requirements for module declarations

- lib/bolt_server/transport_app.rb
This commit updates bolt-server metadata endpoints for serving project content to not create a bolt-debug.log file at the root of the project directory.
> (PE-30092) Dont write a bolt-debug.log when listing project content

- rakelib/docs.rake
- rakelib/schemas.rake
- schemas/bolt-project.schema.json
This updates the docs rake task to not include the `bolt module` command
on the command references page, and updates the schemas rake task to not
include the `modules` option in the `bolt-project.yaml` schema.
> (maint) Remove module command and config from docs

- documentation/running_bolt_commands.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/util.rb
- spec/bolt/cli_spec.rb
This adds support for reading a command from a file or `stdin` using
the `bolt command run` command. To read a command from a file,
pass the path to the file with the `@` symbol:
```shell
$ bolt command run @script.sh --targets targets
```
The filepath is expanded relative to the current working directory.
To read a command from `stdin`, pass a single dash `-` as the command
and then pipe the command to Bolt:
```shell
$ echo whoami | bolt command run - --targets targets
```
!feature
* **Read command from a file or `stdin` using `bolt command run`**
([#2125](https://github.com/puppetlabs/bolt/issues/2125))
The `bolt command run` command can now read a command from a file or
`stdin`.
> (GH-2125) Read command from a file or stdin

- .rubocop.yml
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/module_installer.rb
- lib/bolt/project.rb
- lib/bolt/puppetfile.rb
- lib/bolt/puppetfile/module.rb
- spec/bolt/cli_spec.rb
- spec/bolt/module_installer_spec.rb
- spec/bolt/puppetfile_spec.rb
This adds a new `bolt module add` command that adds a new module to the
project. The command accepts a single module name, resolves its
dependencies, updates the project configuration file and `Puppetfile`,
and installs the project's modules.
If the project configuration file already includes a declaration for the
new module, Bolt will display a helpful message and exit successfully
without doing anything.
When resolving modules, Bolt will first attempt to resolve the new
module with each of the installed modules pinned to a specific version.
This is intended to prevent any installed modules from being updated
unintentionally. If resolving with this approach fails, Bolt falls back
to re-resolving all of the module declarations with the new module,
which may result in insalled modules …
> (GH-2134) Add 'bolt module add' command

- .github/workflows/release-notes.yaml
- Dockerfile.bolt-server
This commit updates the base alpine image for the bolt-server container used in internal testing to avoid segfaults that started occuring with the old version.
> (maint) Update base image for bol-tserver container

- config/transport_service_config.rb
- lib/bolt_server/acl.rb
- lib/bolt_server/base_config.rb
- spec/bolt_server/acl_spec.rb
- spec/bolt_server/config_spec.rb
- spec/fixtures/api_server_configs/global-bolt-server.conf
- spec/fixtures/api_server_configs/global-plan-executor.conf
- spec/fixtures/api_server_configs/local-bolt-server.conf
- spec/fixtures/api_server_configs/local-plan-executor.conf
We are replacing bolt-server.conf's `whitelist` key with an `allowlist`
key, in our effort to remove harmful terminology from bolt-server, and
this commit updates bolt-server to read from that new value instead.
> (PE-30034) Remove harmful bolt-server terminology

- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/project.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/project_spec.rb
- spec/integration/plan_spec.rb
- spec/lib/bolt_spec/project.rb
This updates `Bolt::Project` and `Bolt::Config` to use a new modulepath
when `modules` is configured in `bolt-project.yaml`. This work is part
of the new module management workflow.
When `modules` is configured, the default modulepath is `['modules']`
and the full modulepath will have `.modules` appended to it, whether
Bolt uses the default modulepath or the user-configured modulepath. If
the user-configured modulepath includes `.modules`, Bolt will error and
display a helpful message that the modulepath cannot be configured with
`.modules` as it is automatically appended.
If `modules` is not configured, Bolt's behavior remains the same and the
default modulepath is `['modules', 'site-modules', 'site']`.
This also adds new `BoltSpec::Project` library functions that will
create a temporary …
> (GH-2182) Use new modulepath when 'modules' is configured

- documentation/applying_manifest_blocks.md
- documentation/bolt_running_plans.md
- documentation/bolt_running_tasks.md
- documentation/configuring_bolt.md
- documentation/experimental_features.md
- documentation/module_structure.md
- documentation/writing_yaml_plans.md
This clarifies that while Bolt sets a default data dir and default Hiera
config file, it does not have any content in that Hiera config and will
not load any Hiera data unless the user configures it to.
> (docs) Clarify Hiera data loading docs

- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/module_installer.rb
- spec/bolt/cli_spec.rb
- spec/bolt/module_installer_spec.rb
This adds a new `--[no-]resolve` flag, which defaults to true, that will
allow users to install the Puppetfile without resolving the modules
enumerated in `modules` key in Bolt config. No release notes as
this will ship dark until the full workflow is implemented.
Closes #2186
> (GH-2186) Add resolve and force options for module subcommand

- documentation/writing_plans.md
This commit updates the documentation around using Puppet's built-in
logging functions within Bolt plans. Since the mapping for Puppet's
logging was changed, the docs should be updated to match the new levels
that logging functions will log at.
> (maint) Update docs on Puppet logging functions

- lib/bolt/outputter/human.rb
- spec/bolt/outputter/human_spec.rb
This updates the `puppetfile show-modules` and `module show` output to
be a bit more readable by indenting the module tables to offset them
from the group headings, and colorizing the group headings to clarify
that they are headings.
> (maint) Prettify module show output

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
This change causes Bolt to error if any additional arguments are
provided to the `bolt module install` command. This is to prevent
potential confusion for users who might use the command to install a
single module, e.g. `bolt module install puppetlabs/apt`. The error
includes a suggestion to use `bolt module add` instead.
> (GH-2208) Error with extra arguments to 'bolt module install'

- lib/bolt/config/options.rb
- lib/bolt/project.rb
- spec/bolt/project_spec.rb
This adds support for the 'modules' key accepting strings in addition to
hashes as part of the modules array. If a module in the array is a
barestring it will be converted to the hash `{ name: <string> }`,
similar to how targets accept a string and treat it as the URI. This
provides a nice shorthand for users listing modules manually. The `bolt
module add` command will still add the hash version.
> (maint) Have modules key accept strings

- CONTRIBUTING.md
This makes some very minor modifications to our contributing document,
updating some outdated language around inventory plugins and linking to
how to create Bolt content before enumerating what changes might be
acceptable to Bolt proper.
> (GH-2092) Update CONTRIBUTING.md

- documentation/applying_manifest_blocks.md
- documentation/writing_plans.md
Had a chat with Cas and Barr about this. Because puppet log functions in Bolt do not map 1:1, it seems better to recommend out::message instead. To try and make that a bit clearer, I've simplified the hierarchy a bit and moved the bit about Puppet log functions down a bit. I also added this info to the apply doc, seeing as though people who are used to applying Puppet code might be confused about why their log functions aren't working as expected.
> (maint) docs - Clarify puppet log functions

- lib/bolt/puppetfile.rb
- spec/bolt/puppetfile_spec.rb
This updates `Bolt::Puppetfile.resolve` to show a list of unknown
modules and unknown module dependencies when unable to resolve modules.
Previously, if resolving modules failed due to an unknown module, only
the unknown modules specified by the user would be shown. Now, Bolt will
use the dependency graph returned by `puppetfile-resolver` to build a
list of unknown modules specified by the user and unknown modules that
are listed as dependencies of another module.
!bug
* **Show unknown module dependencies when failing to resolve modules**
Bolt now shows the names of unknown module dependencies if it is
unable to resolve modules due to an unknown module. Previously, Bolt
would only show the names of unknown modules that were specified by
the user.
> (bug) Show unknown modules and dependencies when failing to resolve

- lib/bolt/puppetfile.rb
- spec/bolt/puppetfile_spec.rb
Reverts puppetlabs/bolt#2220
We found that just changing 'allow_missing_modules' to false results in a more clear and quick error message from PuppetfileResolver than trying to manually figure out which modules are missing and error. This reverts the existing PR - the change itself will be in a separate PR.
> Revert "(bug) Show unknown modules and dependencies when failing to resolve"

- lib/bolt/puppetfile.rb
- spec/bolt/puppetfile_spec.rb
This fixes a bug in `Bolt::Puppetfile.resolve` that would allow the
resolver to return a dependency graph with missing module dependencies.
This would result in a graph that was difficult to parse and create a
helpful error for the user that informed them if any modules or their
dependencies could not be found. The resolver now does not permit any
missing module dependencies, which will cause the resolver to error as
soon as it encounters a missing module and notify the user that it could
not be found.
!bug
* **Show missing module dependencies when resolving modules**
Bolt now correctly displays the names of missing module dependencies
when resolving module dependencies errors. Previously, if a module
dependency was missing, Bolt did not display the name of the missing
module.
> (bug) Do not allow missing modules when resolving module dependencies

- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/project.rb
- lib/bolt/project_migrator.rb
- lib/bolt/project_migrator/modules.rb
- pwsh_module/command.tests.ps1
- rakelib/docs.rake
- rakelib/pwsh.rake
- rakelib/schemas.rake
- schemas/bolt-project.schema.json
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/project_migrator/modules_spec.rb
- spec/bolt/project_migrator_spec.rb
- spec/bolt/project_spec.rb
- spec/integration/plan_spec.rb
This adds the `bolt module` subcommands to the Powershell cmdlets module
as `Add-BoltModule`, `Register-BoltModuleTypes`, `Install-BoltModule`,
and `Get-BoltModule`. This call directly into the respective `bolt
module` subcommands and should exhibit the same behavior.
This additionally fixes up the parameters to some Bolt commands in the
powershell module, ensuring that parameters are only included if they
are valid and marking them as optional or required appropriately.
Closes #2135
---
This removes the feature flag for the `bolt module` command, now that
the workflow is ready to be marked experimental and shipped. The module
workflow is now only enabled by the presence of the `modules` key in a
`bolt-project.yaml` file.
!feature
* **New Bolt module subcommand**
The new …
> (GH-2135) Add Powershell 'module' subcommands and un-feature-flag

- .gitignore
Bolt includes the 'puppetlabs-stdlib' module in the Puppetfile, so if
you're developing Bolt and install the Puppetfile it will show up in the
git diff. This adds the module to the gitignore so that devs don't
accidentally commit the module to the repo.
> (maint) Add stdlib to the .gitignore

- documentation/applying_manifest_blocks.md
- documentation/bolt_installing_modules.md
- documentation/bolt_running_tasks.md
- documentation/inspecting_tasks.md
- documentation/module_structure.md
- lib/bolt/pal.rb
- lib/bolt_spec/plans/mock_executor.rb
- spec/bolt/outputter/human_spec.rb
This standardizes referring to the modulepath as 'modulepath', not
module path, in our documentation and code. This is just for clarify, and
avoid having to decide how to refer to the path of modules when writing
docs.
> (docs) Standardize docs on modulepath, not module path

- lib/bolt/catalog.rb
- lib/bolt/cli.rb
- lib/bolt/executor.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/logger.rb
- lib/bolt/plugin/module.rb
- lib/bolt/shell/bash.rb
In some places, we were passing keyword arguments as a hash as the last
argument to the method. This syntax is deprecated in Ruby 2.7 in favor
of explicitly passing them as keyword arguments using the ** operator.
Unfortunately, it's hard to programmatically find places where this
issue occurs since it depends on the definitin of the method, so this
commit is just a first stab.
> (GH-2217) Explicitly pass kwargs to methods that accept them

- lib/bolt/pal.rb
Previously, `bolt module show` would prefix the list of installed
project dependencies with the full path to the `.modules` directory.
Since that directory is meant to be fully managed and internal, we now
replace the explicit path with a label indicating that these are the
project dependency modules.
> (maint) Group label for project dependencies in bolt module show

- rakelib/pwsh.rake
When the logging changes were implemented in 7b063c640cc7f6f57450247d82db18138cba71d7, we missed added the `trace` level to the validate_set in pwsh.
> (maint) Fix logging levels

- lib/bolt/puppetfile/module.rb
- spec/bolt/project_migrator/modules_spec.rb
- spec/bolt/puppetfile/module_spec.rb
This prevents a module's version requirement in `bolt-project.yaml` from
being set to the string `:latest` when migrating a project. Previously,
if a Puppetfile had a module specification with either a version
`:latest` or no version at all, the module's version requirement would
be set to `:latest`, which is not valid. Now, in these instances the
module will not have a version requirement in the `bolt-project.yaml`.
> (GH-2226) Do not set module version to latest when migrating

- lib/bolt/outputter.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- lib/bolt/project_migrator.rb
- spec/bolt/project_migrator_spec.rb
This modifies the 'Project could not be migrated completely' message
when project migration fails to be printed in red, letting the user know
at a glance that something went wrong. After migrating a project it's
easy to not read the output if it all looks successful at a glance.
Printing in red emphasizes that something in the migration needs the
users attention, and potentially manual migration.
> (maint) Print unsuccessful migration in red

- documentation/bolt.ditamap
- documentation/developer_updates.md
This adds a 'Developer updates' page to the docs. This page is used to
keep users updated on what the team is working on and why we're making
certain decisions.
This includes a developer update for the new module management feature.
> (GH-2183) Add developer updates page

- Puppetfile
This adds the `puppetlabs-http_request` module as a bundled module.
This also updates a few other bundled modules to the latest versions.
!feature
* **HTTP request task**
([#2103](https://github.com/puppetlabs/bolt/issues/2103))
Bolt now ships with the `http_request` module, which includes the
`http_request` task for making HTTP requests.
> (GH-2103) Add http_request module to bundled modules

- documentation/bolt.ditamap
- documentation/bolt_installing_modules.md
- documentation/managing_modules.md
- documentation/modules.md
- documentation/projects.md
- Adds "Managing modules" page
- Add experimental callouts on various pages to link to the
managing modules page.
- Edits to "Bolt projects" page to add .modules and a note to
the Puppetfile description. Also added `bolt project init` to section
on creating a Bolt project.
> (GH-2183) Document new module workflow

- documentation/bolt.ditamap
- documentation/managing_modules.md
- lib/bolt/config.rb
- lib/bolt/module_installer.rb
- lib/bolt/outputter/json.rb
- lib/bolt/pal.rb
- lib/bolt/project.rb
- lib/bolt/project_migrator/modules.rb
- lib/bolt/puppetfile.rb
- spec/bolt/cli_spec.rb
- spec/bolt/project_migrator/modules_spec.rb
When generating the Puppetfile from the list of modules in
`bolt-project.yaml`, we now add the line `moduledir '.modules'` to
prevent R10K and old versions of Bolt from deleting the `modules/`
directory and installing modules from the Puppetfile to the wrong
location. This essentially ensures that using the new module management
workflow is safe with legacy tools, as the Puppetfile knows to install
modules to the new modules directory `.modules/` instead of installing
to `modules/` which should now be treated as a place for users' custom
modules. This line is only added when generating a new Puppetfile using
the new module management workflow - behavior is not modified if using
`bolt project init --modules`, which still uses the old workflow.
This additionally documents configuring the …
> (GH-2234) Add moduledir to generated Puppetfile

- lib/bolt/pal.rb
- spec/fixtures/modules/yaml/plans/invalid.yaml
- spec/integration/yaml_plan_spec.rb
Previously when raising an error from a plan run in Bolt we would only
check if the error had a `file` method and use that to determine whether
the error was from Puppet or not. If the error was from Puppet we could
assume other methods on the error, like line and pos. However,
when yaml plans were syntactically invalid and failed to parse this
would raise a Psych::SyntaxError, which has a `file` method but not a
`pos` method. This would cause a stacktrace when we assumed the error
was a Puppet error and tried to call `pos` on it.
This change modifies the details hash to only add each key if the
corresponding method exists on the error. We can't be sure this will
catch all relevant details from an error (for example if the `pos`
exists on an error but is accessed by a method `position`), …
> (GH-2197) Error gracefully when yaml plans fail to parse

- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- lib/bolt/project_migrator/modules.rb
- lib/bolt/puppetfile.rb
- spec/bolt/project_migrator/modules_spec.rb
- spec/bolt/puppetfile_spec.rb
We currently hardcode an error message when Puppetfile Resolver
successfully resolves a Puppetfile but with validation errors. This
updates the message to print the list of validation errors when
Puppetfile Resolver encounters them.
This additionally adds a format for migrate steps that fail, coloring
them red to indicate failure but maintaining the indent.
> (maint) Surface Puppetfile Resolver validation errors

- documentation/writing_tasks.md
This adds a note to the 'Debugging Tasks' section of the docs under the
ruby section that the library we recommend, 'pry-remote', does not work
with common pry libraries 'pry-nav' and 'pry-byebug'. This issues is
[known](https://github.com/Mon-Ouie/pry-remote/issues/35#issuecomment-20290739)
and does not seem likely to be resolved.
I opted not to include this in our known issues page since this isn't an
issue with Bolt itself.
Closes #2167
> (GH-2167) Add note that pry-remote and pry-nave do not work together

- .rubocop.yml
- lib/bolt/pal.rb
- lib/bolt/shell/bash.rb
- lib/bolt/transport/ssh/connection.rb
This adds configuration for new cops introduced in Rubocop 0.93.
> (maint) Update cops for Rubocop 0.93

- lib/bolt/inventory.rb
This change updates how Bolt logs which inventory file it loaded.
Previously, if Bolt loaded the default inventory file, it would log that
it loaded the file, even if the file does not exist. Now, if the default
inventory file does not exist, Bolt will instead notify the user that it
tried to load the file, but that it does not exist.
!bug
* **Log when default inventory file cannot be loaded**
([#2207](https://github.com/puppetlabs/bolt/issues/2207))
Bolt now logs that it tried but failed to load the default inventory
file when the default inventory file does not exist. Previously, Bolt
would log that it loaded the default inventory file, even when it was
unable to do so.
> (GH-2207) Log when default inventory file cannot be loaded

- bolt-modules/boltlib/lib/puppet/functions/write_file.rb
This updates the `write_file` function documentation to list the
function's parameters in the correct order and to show the parameters in
the example function call in the correct order.
> (GH-2254) Fix parameter order for write_file function docs

- documentation/bolt.ditamap
- documentation/supported_plugins.md
- documentation/using_plugins.md
This updates the 'Using plugins' page to describe using plugins in more
detail. It also moves the list of bundled plugins to a new 'Supported
plugins' page.
> (docs) Update 'Using plugins' page, add 'Supported plugins' page

- developer-docs/bolt-api-servers.md
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
This endpoint's meant to be used by Orchestrator's project file metadata
store. It returns the given file's metadata and the metadata of all its
children in the same format as Puppetserver's /file_metadatas endpoint
(https://puppet.com/docs/puppet/6.17/http_api/http_file_metadata.html#search).
In fact, if project_ref were an environment, then the /project_file_metadatas
endpoints would return the same result as the /file_metadatas endpoint
when "links" is set to "follow", "checksum_type" to "sha256", and
"recurse" to "yes".
> (PE-30227) Add project_file_metadatas endpoint to bolt-server

- Puppetfile
This bumps several bundled modules to their latest versions.
* **Update bundled modules to latest versions**
The following bundled modules have been updated to their latest
versions:
- [facts 1.1.0](https://forge.puppet.com/puppetlabs/facts)
- [augeas_core 1.1.1](https://forge.puppet.com/puppetlabs/augeas_core)
- [scheduled_task 2.2.1](https://forge.puppet.com/puppetlabs/scheduled_task)
- [sshkeys_core 2.1.0](https://forge.puppet.com/puppetlabs/sshkeys_core)
- [zfs_core 1.1.0](https://forge.puppet.com/puppetlabs/zfs_core)
- [cron_core 1.0.4](https://forge.puppet.com/puppetlabs/cron_core)
- [yumrepo_core 1.0.7](https://forge.puppet.com/puppetlabs/yumrepo_core)
- [package 1.3.0](https://forge.puppet.com/puppetlabs/package)
- [stdlib 6.5.0](https://forge.puppet.com/puppetlabs/stdlib)
> (maint) Bump bundled modules

- documentation/running_bolt_commands.md
- documentation/templates/bolt_command_reference.md.erb
This updates the 'Running basic Bolt commands' page. It reorganizes the
page to first cover command syntax and then commands that interact with
targets. Each command example includes both a Unix shell command and a
PowerShell cmdlet.
> (GH-2079) Update Bolt commands docs

- lib/bolt/cli.rb
- lib/bolt/module_installer.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- lib/bolt/project_migrator.rb
- lib/bolt/project_migrator/base.rb
- lib/bolt/project_migrator/config.rb
- lib/bolt/project_migrator/inventory.rb
- lib/bolt/project_migrator/modules.rb
- lib/bolt/puppetfile/module.rb
- spec/bolt/module_installer_spec.rb
- spec/bolt/project_migrator/config_spec.rb
- spec/bolt/project_migrator/inventory_spec.rb
- spec/bolt/project_migrator/modules_spec.rb
- spec/bolt/project_migrator_spec.rb
This adds a new message to the outputter that describes changes made to
a Puppetfile when using the `bolt module add` / `Add-BoltModule`
command. The message will display which modules have been added,
removed, upgraded, and downgraded. Upgraded and downgraded modules will
have their old version and new version displayed, while added and
removed modules display the version of the module that was added or
removed.
!feature
* **Print changes made to Puppetfile when adding modules**
([#2230](https://github.com/puppetlabs/bolt/issues/2230))
The `bolt module add` command and `Add-BoltModule` cmdlet now display
a message describing changes made to the Puppetfile, including modules
that have been added, removed, upgraded, or downgraded.
> (GH-2230) Print Puppetfile diff when using 'module add'

- lib/bolt/module_installer.rb
- lib/bolt/puppetfile.rb
- spec/bolt/cli_spec.rb
- spec/bolt/puppetfile_spec.rb
This fixes a bug in the `Bolt::ModuleInstaller` class that does not
correctly pass the managed moduledir to `Bolt::Puppetfile#write`. This
resulted in Bolt generating Puppetfiles with the `bolt module install`
command that did not include the `moduledir` directive.
!bug
* **Add moduledir directive to generated Puppetfile**
Puppetfiles generated using the `bolt module install` command did not
include the `moduledir` directive.
> Add moduledir directive to Puppetfile with 'module install'

- lib/bolt/cli.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- spec/bolt/outputter/human_spec.rb
- spec/bolt/outputter/json_spec.rb
This improves the output for the `bolt inventory show` command.
When using the `human` outputter, Bolt will now display each target's source
alongside the target. If the target was loaded from inventory, it will
show the path to the inventory file; if the target is an adhoc target,
it will say it was not loaded from inventory. The output will also show
where inventory was loaded from, and tell the user if the inventory file
it attempted to load does not exist. Lastly, the target count now lists
the total number of targets, the number loaded from inventory, and the
number of adhoc targets.
When using the `json` outputter, Bolt will now include `inventory` and
`adhoc` keys. The `inventory` key includes a list of targets loaded from
inventory, the number of targets loaded from inventory, and …
> (GH-2205) Improve 'bolt inventory show' output

- .github/workflows/linux.yaml
- bolt-modules/prompt/lib/puppet/functions/prompt.rb
This adds documentation on unwrapping a sensitive value returned by the
`prompt` plan function.
> Document unwrapping a sensitive value from 'prompt' function

- lib/bolt/outputter/human.rb
- spec/bolt/outputter/human_spec.rb
- spec/integration/inventory_spec.rb
Previously, the inventoryfile passed to the outputter for printing when
running `bolt inventory show` with the Human outputter could be either a
string or a Pathname, depending on whether the user had configured the 
inventory location (string) or was using the default project inventory
(Pathname). We erroneously assumed it would always be a
Pathname, which resulted in a 'method not found' error when we tried
calling `exist?` on the parameter. This uses the `File.exist?` method to
verify the path exists which will work for either object passed to the 
method.
!bug
* **Fix 'method not found' error running 'bolt inventory show'**
Previously, when running 'bolt inventory show' with a configured
inventory path and the human format a 'method not found' error was 
raised. This now correctly …
> (bug-fix) Use file methods instead of Pathname methods in the outputter

- documentation/applying_manifest_blocks.md
- documentation/bolt_connect_puppetdb.md
- documentation/bolt_installing.md
- lib/bolt/config/options.rb
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
I grepped through the docs and found a couple of lingering terms
that we need to change. Most are just examples. One is a DB
filename that is going to change soon. I'm on the fence about merging
this now or waiting for the Puppet 7 release when all of the other docs
changes (and a lot of the engineering work) will land.
> (Docs) Harmful terminology changes

- .rubocop.yml
- Gemfile
- bolt.gemspec
This bumps the maximum allowed Puppet gem version to 6.19, while still allowing for 6.18 to be installed as there are no required changes for us to pick up in the new Puppet version.
> (maint) Bump puppet version to 6.19.0

- guides/module.txt
- guides/modulepath.txt
This adds a new 'module' topic guide. It gives a brief description of
what a module is and how Bolt can manage a project's modules.
This also adds a new 'modulepath' topic guide that describes what the
modulepath is, precedence of modules on the modulepath, and how Bolt
adds directories to the modulepath.
> (GH-2219) Add 'module' and 'modulepath' topic guides

- lib/bolt_server/schemas/partials/task.json
This commit updates the task metadata schema in bolt server to accept either an environment or project source for a task.
> (PE-30382) Add project to task schema in bolt-server

- documentation/logs.md
This clarifies that `--verbose` doesn't indicate a log level but
instructs Bolt to output more data through the outputter. Since #955,
the Bolt outputter and logger have a clear division of responsibility:
the outputter is responsible for user-facing messages, like progress and
results, while the logger is responsible for log messages like
warnings, errors, and logs from plans. Verbose is an outputter-specific
concept that prints more messages (or fewer with `--no-verbose`) through
the outputter.
> (docs) Verbose is an output level, not logging

- bolt-modules/boltlib/lib/puppet/functions/facts.rb
- documentation/bolt_types_reference.md
- documentation/writing_plans.md
This adds notes to documentation for the `facts` plan function that the
function does not retrieve facts and only returns what is set on the
target in inventory. It describes how to retrieve and set facts by
running the `facts` or `puppetdb_fact` plan.
> (GH-2259) Explicitly describe retrieving facts for a target

- bolt-modules/boltlib/lib/puppet/functions/puppetdb_query.rb
- documentation/templates/plan_functions.md.erb
- rakelib/docs.rake
This adds the `apply` function to the function reference doc. It also
slightly reformats by removing most bolded subheaders and listing params
and options in tables, improving the readability of the page.
> (GH-2260) Add 'apply' function to function reference

- .github/workflows/linux.yaml
- spec/bolt/puppetdb/client_spec.rb
- spec/bolt_server/file_cache_spec.rb
- spec/lib/bolt_spec/bolt_server.rb
This adds a `wait_until_available` method to `BoltSpec::BoltServer` that
will wait until puppetserver is running and accepting requests.
This fixes an issue where tests might be run too soon after the
puppetserver container was started and before it was ready to accept
requests, causing the tests to fail.
> (GH-2268) Add 'wait_until_available' method for puppetserver tests

- lib/bolt/module_installer.rb
- spec/bolt_server/app_integration_spec.rb
- spec/lib/bolt_spec/bolt_server.rb
This adds a message to the module installer that informs the user that
Bolt is generating types after installing modules.
> (GH-2295) Add 'Generating types' message to module installer

- guides/logging.txt
This adds a brief guide to logging in Bolt, clarifying that there are
two output methods that are separate, and both configurable. This should
help clarify the difference between `--verbose` and `--log-level` for
users.
Note: This is from the hack day, I just forgot to demo + push
Closes #2281
> (GH-2281) Add logging guide

- lib/bolt/config/transport/options.rb
Because we don't include `<port>` at the end of service-urls, users
might assume that they don't need to specify a port.
> (Docs) Add port to service-urls

- documentation/applying_manifest_blocks.md
This supersedes #2136
"This PR adds some additional points to the docs on using hiera with bolt
apply, specifically how to use the target name as part of a hiera path."
> (docs) Document using target name in Hiera configuration

- lib/bolt/pal/yaml_plan.rb
- lib/bolt/pal/yaml_plan/evaluator.rb
- lib/bolt/pal/yaml_plan/loader.rb
- spec/fixtures/modules/yaml/plans/eval_error_bare_string.yaml
- spec/fixtures/modules/yaml/plans/eval_error_scalar_literal.yaml
- spec/fixtures/modules/yaml/plans/eval_error_sub_plan.yaml
- spec/integration/yaml_plan_spec.rb
This adds the file path and line number of an error for evaluated code
in a YAML plan. Previously, if evaluated code resulted in an error, the
error would include no file path and the line number of the error within
the code itself (as though the code were in its own file). This made
these errors less helpful, as they did not correctly indicate where an
error in a YAML plan had occurred.
!feature
* **Include file and line number in YAML plan code evaluation errors**
([#2278](https://github.com/puppetlabs/bolt/issues/2278))
Errors raised when evaluating code in a YAML plan now include the path
to the YAML plan and the line number that the error occurred on in the
plan.
!removal
* **Folded scalar values in YAML plans no longer evaluated**
Folded scalar values in YAML plans are no longer …
> (GH-2278) Include file and line number in YAML plan eval errors

- documentation/troubleshooting.md
- pwsh_module/pwsh_bolt_internal.ps1
This updates the PowerShell module to not override the `SSL_CERT_FILE`
and `SSL_CERT_DIR` environment variables if they are already set.
Previously, the PowerShell module would always override these
environment variables, which could lead to SSL errors if a user
attempted to provide a cert on the command line.
are not already set.
!bug
* **Do not override SSL variables in PowerShell module**
([#2171](https://github.com/puppetlabs/bolt/issues/2171))
The PowerShell module no longer overrides the `SSL_CERT_FILE` and
`SSL_CERT_DIR` environment variables if they are already set.
> (GH-2171) Do not override SSL variables in PowerShell module

- bolt.gemspec
Previously we had pinned Bolt to depend on Puppet >= 6.18.0 <=6.19.0
because when Puppet released 6.19.0 we picked it up before we had made
Bolt-side changes necessary to be compatible with the new Puppet
version. We restricted the Puppet gem to not pick up new versions so
that we could actively make similar updates in the future without
needing to do so immediately. However, this meant that some gems which
depend on Bolt and Puppet ended up resolving to an old version of Bolt,
which broke their use of the gem. This change means we'll pick up Z
releases of Puppet, but can still make any changes in Bolt we need to
before picking up the Y release.
!bug
* **Allow Puppet 6.19.1 as a dependency**
This let's Bolt use Puppet 6.19.1 as a dependency.
> (bug) Allow Bolt to use Puppet 6.19.z releases

- lib/bolt/module_installer.rb
- lib/bolt/module_installer/specs/forge_spec.rb
- lib/bolt/module_installer/specs/git_spec.rb
- spec/bolt/module_installer/specs/forge_spec_spec.rb
- spec/bolt/module_installer/specs/git_spec_spec.rb
This updates the regex used to validate module names for Forge and Git
specifications. Previously, the regex for validating the owner segment
of the module name was `[a-z][a-z0-9_]`, which is the same regex used
for module name segments. However, owner names follow different
requirements and can only include letters (uppercase and lowercase) and
digits.
!bug
* **Fix module name validation for Forge and Git module specifications**
([#2314](https://github.com/puppetlabs/bolt/issues/2314))
Forge and Git module specifications now correctly validate the
module's name and permit uppercase letters in the owner segment of the
module name. Previously, if the owner segment of a module name
included uppercase letters, Bolt would raise an error.
> (GH-2314) Fix module name regex for Forge/Git specifications

- Puppetfile
The recent release of the puppetlabs-facts module includes updates to
the facts task to use the new `puppet fact show` when used with Puppet
versions where it's available, and remove `facter -p` when it's not
available.
> (maint) Pick up puppetlabs-facts 1.2.0

- documentation/running_bolt_commands.md
- pwsh_module/command.tests.ps1
- pwsh_module/pwsh_bolt_internal.ps1
This commit changes the default argument parsing inside Invoke-BoltCommandline to not add single quotes to every argument. It also special cases the `params` and `execute` parameters to quote the input specifically.
> (GH-2272) Fix complicated quoting in PowerShell Cmdlets

- .rubocop.yml
- lib/bolt/pal.rb
- lib/bolt/plugin.rb
- lib/bolt/project_migrator/inventory.rb
- lib/bolt/puppetdb/config.rb
- lib/bolt/shell/powershell.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/remote.rb
- lib/bolt_server/file_cache.rb
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
- spec/fixtures/scripts/bolt_cli_loader.rb
- spec/lib/bolt_spec/bolt_server.rb
This picks up new cops introduced in rubocop 1.2.0 and modifies code to
fit the new cops.
> (maint) Bump rubocop to 1.2.0

- lib/bolt/shell/powershell.rb
- spec/integration/transport/winrm_spec.rb
When using `powershell.exe -Command`, PowerShell sets the exit code of `powershell.exe` based on the `success status` of the **last statement**  executed in the command string.
- If the **last statement** is a PowerShell command (think cmdlet/function/etc) success is determined from `$?` which is `0` if `$true` or `1` if `$false`.
- If the **last statement** executed is an external program (not PowerShell code), `1` is returned if the exit code is anything but `0`. This means an exit code of `42` is still a `1` at the end of the execution.
- This does not happen with PowerShell scripts executed with `-File` command and that use a `exit <NUMBER>` to return a success status.
When executing `bolt command run 'foo'`, we are effectively doing a `powershell.exe -Command 'foo'`. This means the …
> (GH-1650) Handle exit codes greater than 1 in winrm transport

- documentation/experimental_features.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/plan_creator.rb
- spec/bolt/cli_spec.rb
- spec/bolt/plan_creator_spec.rb
This adds the flag `--pp` to the `bolt plan new` command, which
instructs the command to generate a new Puppet language plan instead of
a YAML plans. The YAML plan is still default, and the plans themselves
are equivalent. This additionally move the `plan new` handler from the 
CLI class into it's own `PlanCreator` class in order to separate
concerns.
!feature
* **'bolt plan new' now accepts '--pp' flag to generate Puppet plan**
The 'bolt plan new' command now accepts a '--pp' flag to generate
a Puppet plan.
> (feature) Add bolt plan new --pp flag

- lib/bolt/executor.rb
- lib/bolt/task/run.rb
- spec/bolt/plugin/module_spec.rb
- spec/integration/plugin/module_spec.rb
Since plugins are simply tasks run through the executor, we would log
their runs like any other task. This included printing the results at
info level. This is a problem for tasks that return secrets, such as the
PKCS7 plugin. Instead of logging plugin output, plugins now use their
own method on the executor `run_task_with_minimal_logging()` to run
the plugin task without printing the result.
!bug
* **Don't log task output from plugins**
Bolt will not log the output from plugin tasks, to avoid printing
sensitive information to logs.
> (bug) Don't log task output from plugins

- lib/bolt/shell/powershell.rb
- spec/integration/transport/winrm_spec.rb
Reverts puppetlabs/bolt#2196
This change is suppressing STDOUT output from being returned to Bolt, which is a breaking change in behavior. This isn't going to be simple to fix, so we're reverting this for now while we work on a solution.
> Revert "(GH-1650) Handle exit codes greater than 1 in winrm transport"

- bolt-modules/boltlib/spec/functions/run_plan_spec.rb
- bolt-modules/boltlib/spec/functions/run_task_spec.rb
- bolt-modules/boltlib/spec/functions/run_task_with_spec.rb
- lib/bolt/cli.rb
- lib/bolt/error.rb
- lib/bolt/inventory/group.rb
- lib/bolt/outputter/human.rb
- lib/bolt/plan_creator.rb
- lib/bolt/project.rb
- lib/bolt/project_migrator/config.rb
- lib/bolt/util.rb
- spec/bolt/cli_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/bolt/plan_creator_spec.rb
When running certain commands or raising certain errors, Bolt will
output a command to run. This change checks whether Bolt is running in
PowerShell or not, and sets the command in the output to a PowerShell
cmdlet if it is or a *nix shell command if it is not.
> Show PowerShell cmdlets in output when running in PowerShell

- scripts/generate_changelog.rb
This fixes a minor bug in the changelog task that does not reset the `z`
segment of the version when the `y` segment is incremented. This results
in the changelog computing the wrong version when a new `y` version is
computed.
> (bug) Fix version computing in changelog task

- .rubocop.yml
- acceptance/setup/git/pre-suite/010_install_git.rb
- bolt-modules/boltlib/lib/puppet/functions/catch_errors.rb
- lib/bolt_spec/plans/mock_executor.rb
- rakelib/pwsh.rake
- spec/integration/transport/winrm_spec.rb
Rubocop released 1.3.0, this adds new cops to our rubocop config and
updates code to adhere to those cops. This includes just three cops:
Duplicate code branches (so if or case statements where the body of the
statement is the same for multiple conditions) which resulted in all of
the code changes, as well as a cop to catch empty classes an nil
lambdas.
> (maint) Update rubocop to 1.3.0

- lib/bolt/pal.rb
- lib/bolt/pal/yaml_plan.rb
- spec/bolt/pal/yaml_plan_spec.rb
This updates Bolt to error when a YAML plan includes a plan step with
the wrong type. Previously, a YAML plan with a non-Hash step would still
execute. Now, if a step is anything except a Hash, the plan will error
and Bolt will provide a helpful error message.
!bug
* **Error with invalid YAML plan step type**
([#2309](https://github.com/puppetlabs/bolt/issues/2309))
Bolt now errors if a YAML plan step is not a hash. Previously, YAML
plans would execute even if a plan step was not a hash.
> (GH-2309) Error with invalid YAML plan step type

- lib/bolt/transport/orch.rb
- lib/bolt/transport/orch/connection.rb
- spec/integration/transport/orch_spec.rb
Given we allow reading orchestrator.conf in the orchestrator-client library, only add a default port to the service-url if one is specified in the pcp config from bolt transport config.
> (GH-2304) Do not require `service-url` for pcp config

- scripts/ci.ps1
- spec/fixtures/scripts/bolt_cli_loader.rb
Github Actions environment [recently deprecated the use of set-env] in
their Windows environment due to a security vulnerability. We were using
this command to set the `BOLT_WINRM_PASSWORD` env var to a generated
password in our CI environment provisioning script. The script now
appends the env var and value to a file located at `$ENV:GITHUB_ENV`,
which Github Actions uses to set environment variables. This should set
the variable correctly without making us restructure how we provision
and run Github Actions.
This also fixes up some rubocop errors from the latest update
> (maint) Don't use set-env to set env vars in Github Actions

- developer-docs/bolt-api-servers.md
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
This commit adds a new `project_inventory_targets` endpoint to bolt-server that parses a project inventory and returns a list of hashes describing targets parsed from that inventory.
> (PE-30464) Implement `project_inventory_targets` in bolt-server

- documentation/projects.md
- lib/bolt/cli.rb
- lib/bolt/config/options.rb
- lib/bolt/outputter/human.rb
- lib/bolt/pal.rb
- schemas/bolt-project.schema.json
- spec/fixtures/scripts/bolt_cli_loader.rb
- spec/integration/project_spec.rb
The `plans` and `tasks` options in `bolt-project.yaml` now accept glob
patterns in addition to plan and task names. Plans and tasks that match
a glob pattern will be show in `bolt plan|task show` and
`Get-Bolt(Plan|Task)` output.
!feature
* **Filter project plans and tasks with glob patterns**
([#2180](https://github.com/puppetlabs/bolt/issues/2180))
The `plans` and `tasks` options in `bolt-project.yaml` now support
glob patterns in addition to plan and task names. Plans and tasks that
match a glob pattern will appear in `bolt plan|task show` and
`Get-Bolt(Plan|Task)` output.
> (GH-2180) Filter project tasks and plans with glob patterns

- documentation/writing_plugins.md
- lib/bolt/executor.rb
- lib/bolt/task/run.rb
- spec/bolt/plugin/module_spec.rb
- spec/integration/plugin/module_spec.rb
This change logs plugin task output at `trace` level. A previous change
suppressed plugin task output, making it difficult for plugin authors to
debug their plugin tasks.
!feature
* **Log plugin task output at `trace` level**
([#2336](https://github.com/puppetlabs/bolt/issues/2336))
Plugin task output is now logged at `trace` level.
> (GH-2336) Log plugin task output at trace level

- lib/bolt/bolt_option_parser.rb
- lib/bolt/config.rb
- lib/bolt/config/options.rb
- lib/bolt/config/transport/base.rb
- lib/bolt/config/transport/local.rb
- lib/bolt/config/transport/ssh.rb
- lib/bolt/config/validator.rb
- lib/bolt/plugin.rb
- lib/bolt/project.rb
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
- spec/bolt/cli_spec.rb
- spec/bolt/config/validator_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/plugin_spec.rb
- spec/bolt/project_spec.rb
- spec/bolt/transport/ssh/exec_connection_spec.rb
- spec/integration/config/validator_spec.rb
This adds a new `Bolt::Config::Validator` class which validates config
against a schema. The validator will recurse through the config and
schema, validating each value against the corresponding definition in
the schema. If validation fails for a given value, the validator will
add a message to a list of errors. After the entire config has been
validated, and if any invalid values were detected, the validator will
raise an error that lists all of the invalid values.
The validator provides basic validation for config values, such as type
checking, ensuring required keys are present, and that items in an array
are unique. It does not provide more complex validation such as ensuring
a file exists at a given path or that a URL can be reached.
!feature
* **Improved config validation** …
> (GH-2337) Validate config using schemas

- libexec/apply_catalog.rb
- libexec/custom_facts.rb
- libexec/query_resources.rb
- spec/integration/apply_spec.rb
In the Bolt inventory, the Target object's host can be set either by
specifying `uri` or by specifying `host` under the transport
configuration for that target. This means that Target's will not always
have a `uri` specified. Target's will always have a `name` specified,
which is typically how users refer to the target anyway. This updates
the query_resource, custom_fact, and apply_catalog tasks we use when
applying Puppet catalogs or querying Puppet resources to set the Target
`name` as the Puppet certname instead of the `uri`. This is so that
Target's without a URI can use these tasks without failing, and also so
that certname is a bit more predictable for users.
Closes #2346
!bug
* **Targets without a uri can now use apply() and get_resources()** …
> (GH-2346) Use target name as Puppet certname

- documentation/templates/privilege_escalation.md.erb
The WinRM transport does not - and will not - support something akin to
a `run-as` command. This is because the way WinRM works is by connecting
with the user that has permissions to perform the actions, not by
elevating or changing to another user after connection. Put another way,
WinRM operates with a session level token and has no functionality to
change to another user after authentication.
Instead of escalating the user once connected, users can pass
credentials to scripts or plans running on the targets and use them
directly in commands. There are a number of ways to do this, each ideal
for different use cases. This adds a section to the 'Escalating
Privilege' document that describes the different ways to pass
credentials securely to either a script or plan to be used for …
> (GH-2140) Document escalating privilege in powershell scripts on Windows

- lib/bolt/config.rb
- spec/bolt/config_spec.rb
This adds the `transport` option to the schemas used to validate
`bolt-default.yaml` and `bolt.yaml` configuration files. Previously, the
schemas did not include the `transport` option, preventing it from being
automatically validated.
> Add 'transport' to schema when validating config

- lib/bolt/util.rb
- spec/bolt/util_spec.rb
This updates the `Bolt::Util.read_yaml_hash` method to not error with a
stacktrace when handling Psych errors that do not include a line number.
Previously, if a Psych error did not include a line number, such as the
`Psych::DisallowedClass` error, Bolt would raise an undefined method
error with a stacktrace.
> (GH-2355) Do not error when Psych errors do not have a line number

- developer-docs/bolt-api-servers.md
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
This endpoint will eventually accept a request body. Since it's
unidiomatic for 'GET' endpoints to accept a request body, we change the
project_inventory_targets to a 'POST' endpoint instead.
> (PE-30464) Change 'GET' => 'POST' for project_inventory_targets

- lib/bolt/config/options.rb
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
This updates the schema for the `log` config option to allow `disable`
as a valid value for the `console` key. Setting this value will disable
logging to the console.
> (GH-2372) Disable console logging in config

- documentation/developer_updates.md
Puppet 7 agent and platform are scheduled for release tomorrow, and
while we're planning to hold off on picking up Puppet 7 in Bolt packages
until later the `puppet_agent::install` task will pick up Puppet 7 by
default once it's available. This should be fine for most users, but if
anything does break this developer update provides useful instructions
for how to use Puppet 6 agents instead for both apply_prep and direct
task use.
> (docs) Add developer update on how to use Puppet 6 agents

- documentation/applying_manifest_blocks.md
- documentation/supported_plugins.md
- documentation/writing_plans.md
This moves our documentation about the `plan_hierarchy` Hiera config key
to the Writing Plans in the Puppet Language document. Users will only
need to know about `plan_hierarchy` when writing plans, and are more
likely to look for how to use Hiera data in plans (particularly outside
of apply blocks) in the document that isn't about apply blocks. This
also updates the example to be more expressive and close(ish) to a real
world use case.
This additionally standardizes uses of "lookup" to "look up", unless
referencing the plan function "lookup()".
Closes #2321
> (GH-2321) Move plan_hierarchy docs to writing plans doc

- bolt-modules/boltlib/spec/fixtures/modules/sensitive_test/plans/complex.pp
- bolt-modules/boltlib/spec/fixtures/modules/sensitive_test/plans/init.pp
- bolt-modules/boltlib/spec/fixtures/modules/sensitive_test/plans/no_api.pp
- bolt-modules/boltlib/spec/functions/run_plan_spec.rb
- bolt.gemspec
'Sensitive' is a reserved word in Puppet 7 and cannot be used as a plan
name. We have a plan named 'sensitive' used for testing the `run_plan`
plan function. This renames the test fixture to 'sensitive_test'.
We will continue to ship Bolt with the puppet 6 gem, but we shouldn't
need to limit the maximum version of the Puppet gem for now. It seems
like Bolt is compatible with Puppet 7, and we don't have any breaking
changes going in to Puppet that we need to gate against. This also means
tools that use Bolt as a dependency won't be limited to using Puppet 6.x.
> (GH-2338) Rename 'sensitive' plan in tests

- bolt.gemspec
Puppet modules contain a [number of useful
directories](https://puppet.com/docs/puppet/6.19/modules_fundamentals.html#module_structure)
that provide features that can be used when applying puppet code using
Bolt. We don't package several directories (such as `spec/`) because we
don't need to, but there were a few useful directories missing from our
filelist in `bolt.gemspec`. This adds:
- `data/` to provide default parameter data if any module begins to include it
- `facts.d/` to provide an external facts users may expect from a
packaged module
- `functions/` to provide custom puppet language functions
- `manifests/` to provide module classes
- `templates/` in case any module manifests use templates to generate
content
- `types/` for resource type aliases
This ensures that the modules …
> (GH-2368) Add missing module directories to gemspec

- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
This commit updates the bolt-server task metadata endpoint to generate the updated query parameter for requesting file_content from projects in puppetserver.
> (SERVER-2914) Update bolt-server to generate correct ps param for file metadata

- documentation/bolt_known_issues.md
This adds a known issue where the `facts` task fails when running Facter
3 on Windows targets. The failure is caused by a bug in Facter 3 that
results in a sigsegv (11) signal when attempting to resolve Puppet
facts.
> (GH-2344) Document Facter 3 failure on Windows as known issue

- lib/bolt/analytics.rb
- lib/bolt/cli.rb
- spec/bolt/analytics_spec.rb
- spec/bolt/cli_spec.rb
This adds two new GA dimensions to the data we send for user screenviews
when Bolt is run on the CLI: puppet plan count and yaml plan count.
These dimensions simply count the number of files in the project's
`plans` directory (including subdirs) to provide analytics for how many
project-level plans in each language the user has. The dimension is a
user-level metric, meaning that whenever the values for a particular
user change they will get updated in GA and the old value will be
removed. This poses a problem for users with multiple projects, as each
time they run Bolt from a different project their values will get
updated. However the tradeoff is that we get per-project values as
opposed to aggregated values, and we don't get multiple values when a
user adds a new plan.
Closes #2302 …
> (GH-2302) Send analytics about how many plan types exist in each project

- .gitignore
- documentation/bolt.ditamap
- documentation/templates/packaged_modules.md.erb
- rakelib/docs.rake
This adds a generated page to Bolt docs that lists the modules that are
shipped with Bolt packages. The list of modules is read directly from
Bolt's Puppetfile, while descriptions are retrieved from each module's
metadata or README file.
> (GH-2382) Add 'Packaged modules' docs page

- lib/bolt/config.rb
- lib/bolt/puppetdb/config.rb
For Puppet 7 we are dropping the `win32/dir` dependency as we only used
constants from it, which we replaced with environment variables (see:
https://github.com/puppetlabs/puppet/pull/8314).
This would become breaking in bolt when it switches to Puppet 7 and the
win32 gems are no longer pulled.
For AIO bolt, the Puppet change won't break anything since bolt uses its
own runtime which still packages the win32 gems, but it would still be
an improvement in speed if the dependency is dropped.
The `win32/dir` gem also monkey patches some `Dir` methods, most notably
`glob` and `pwd` to use backslashes which end up causing more trouble as
Ruby uses `/` as the default separator for Windows.
Switch to using the `ALLUSERSPROFILE` environment variable instead of
the `Dir::COMMON_APPDATA` constant, …
> (PUP-10653) Remove dependency on win32/dir

- documentation/projects.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- pwsh_module/command.tests.ps1
- spec/bolt/cli_spec.rb
- spec/integration/yaml_plan_spec.rb
This adds deprecation warnings for the `--boltdir`, `--configfile`,
`--puppetfile`, and `--description` command line flags. Whenever users
use any of these command line options - and only if the option is
specified on the CLI - a warning should be printed. This doesn't update
spec tests or other internal references to deprecated options, but it
does update the help text to not include deprecated flags.
Closes #2362
!deprecation
* **Add deprecation warnings for boltdir, configfile, puppetfile, and description** ([#2362](https://github.com/puppetlabs/bolt/issues/2362))
We are planning to remove the `--boltdir`, `--configfile`,
`--puppetfile`, and `--description` command line flags in the next major
version of Bolt. This adds deprecation warnings that are printed when
users specify any of …
> (GH-2362) Deprecate boltdir, configfile, puppetfile, and description CLI flags

- .rubocop.yml
- lib/bolt/analytics.rb
- lib/bolt/cli.rb
- lib/bolt/outputter/rainbow.rb
- lib/bolt/shell/bash.rb
- rakelib/pwsh.rake
- spec/integration/logging_spec.rb
- spec/integration/target_spec.rb
- spec/integration/transport/winrm_spec.rb
This adds configuration for the new default cop in Rubocop 1.4.0,
`Style/RedundantArgument`, and updates files where there were
violations.
> (maint) Pick up new cops in Rubocop 1.4.0

- documentation/inventory_file_v2.md
- lib/bolt/project_manager.rb
- spec/bolt/project_manager_spec.rb
The `bolt project init` and `New-BoltProject` commands now create an
`inventory.yaml` file with an example inventory commented out. If a
directory already includes an `inventory.yaml` file, Bolt will not
create a new one.
!feature
* **Create `inventory.yaml` file when creating new projects**
([#2364](https://github.com/puppetlabs/bolt/issues/2364))
The `bolt project init` and `New-BoltProject` commands now create an
`inventory.yaml` file in the new project.
> (GH-2364) Create inventory.yaml when creating new projects

- lib/bolt/cli.rb
- lib/bolt/config.rb
- spec/bolt/config_spec.rb
Previously we tried to use `Bolt::Util.file_stat` to verify that a
configured inventoryfile existed before warning that CLI options may be
overridden by the inventoryfile. This would stacktrace if the file did
not exist. We now validate that the file exists and can be read when
loading config if `inventoryfile` is configured, validate
`default_inventoryfile` if the file exists, and use `File.exist?` in the
CLI when seeing if we need to warn that inventoryfile may override CLI
options. This provides more standard errors and prevents stacktracing.
> (maint) Validate inventoryfile config

- lib/bolt/config.rb
- lib/bolt/config/validator.rb
- lib/bolt/project.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config/validator_spec.rb
- spec/integration/config/validator_spec.rb
- spec/lib/bolt_spec/options.rb
This updates the config validator to issue warnings for unknown
config options. When the validator encounters an unknown option, it
stores a warning indicating where the unknown option is specified, which
is later issued by the logger. Options are only reported as unknown if
the schema for the option defines the `:properties` key but _not_ the
`:additionalProperties` key.
!feature
* **Warn about unknown configuration options**
([#2376](https://github.com/puppetlabs/bolt/issues/2376))
Bolt now issues a warning when it detects an unknown configuration
option. The warning will indicate where the configuration option is
located.
> (GH-2376) Warn about unknown configuration options

- documentation/configuring_bolt.md
- documentation/migrating_inventory_files.md
- documentation/templates/bolt_configuration_reference.md.erb
- documentation/templates/bolt_defaults_reference.md.erb
- documentation/templates/bolt_project_reference.md.erb
- lib/bolt/config.rb
- lib/bolt/config/options.rb
- lib/bolt/config/validator.rb
- lib/bolt/project.rb
- spec/bolt/config/validator_spec.rb
- spec/bolt/project_spec.rb
This deprecates the `inventoryfile` config option, which is slated for
removal in Bolt 3.0.
!deprecation
* **Deprecate `inventoryfile` configuration option**
([#2363](https://github.com/puppetlabs/bolt/issues/2363))
The `inventoryfile` configuration option has been deprecated and will
be removed in Bolt 3.0. Users should move contents from non-default
inventory files to the `inventory.yaml` file in a Bolt project, or can
use the `--inventoryfile` command-line option to load a non-default
inventory file.
> (GH-2363) Deprecate inventoryfile config option

- documentation/using_plugins.md
- lib/bolt/config.rb
- lib/bolt/config/options.rb
- lib/bolt/project_manager/config_migrator.rb
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
- spec/bolt/config_spec.rb
- spec/bolt/plugin_spec.rb
- spec/integration/plugin/module_spec.rb
- spec/integration/plugin/task_spec.rb
This updates Bolt to issue a deprecation warning when a config file
includes the `plugin_hooks` option, which has been renamed to
`plugin-hooks`. When config is set for both of these options, Bolt
will issue another warning that `plugin_hooks` will be ignored.
!deprecation
* **Deprecate `plugin_hooks` in favor of `plugin-hooks`**
([#2358](#2358))
The `plugin_hooks` configuration option has been deprecated in favor
of `plugin-hooks`.
> (GH-2358) Deprecate 'plugin_hooks' in favor of 'plugin-hooks'

- bolt-modules/boltlib/lib/puppet/datatypes/applyresult.rb
- documentation/bolt_types_reference.md
- lib/bolt/apply_result.rb
- spec/bolt/apply_result_spec.rb
This adds a new `value()` function to the `ApplyResult` data type, which
returns a hash with the Puppet report under a `report` key.
!feature
* **Added `value()` function to `ApplyResult` datatype**
([#2370](https://github.com/puppetlabs/bolt/issues/2370))
The `ApplyResult` datatype has a new `value()` function that returns a
hash that includes the Puppet report from an apply under the `report`
key.
> (GH-2370) Add value() function for ApplyResult datatype

- lib/bolt/config.rb
- lib/bolt/config/options.rb
- lib/bolt/project_manager/config_migrator.rb
- schemas/bolt-config.schema.json
- schemas/bolt-project.schema.json
- spec/bolt/project_manager/config_migrator_spec.rb
- spec/integration/apply_spec.rb
- spec/integration/config/validator_spec.rb
This updates Bolt to issue a deprecation warning when a config file
includes the `apply_settings` option, which has been renamed to
`apply-settings`. When config is set for both of these options, Bolt
will issue another warning that `apply_settings` will be ignored.
!deprecation
* **Deprecate `apply_settings` in favor of `apply-settings`**
([#2357](https://github.com/puppetlabs/bolt/issues/2357))
The `apply_settings` configuration option has been deprecated in favor
of `apply-settings`.
> (GH-2357) Deprecate 'apply_settings' in favor of 'apply-settings'

- lib/bolt_server/base_config.rb
- lib/bolt_server/config.rb
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
This commit updates the transport app and config classes used in bolt-server
to allow the codedir for environments to be configurable.
Three new conf settings have been added:
environments-codedir
environmentpath
basemodulepath
> (PE-30686) Make codedir in bolt-server configurable

- acceptance/tests/apply_plan_ssh.rb
- acceptance/tests/bolt_apply.rb
This disables apply acceptance tests on Debian 8, as puppet7 packages
are not available for this platform and the tests install the latest
Puppet packages as part of `apply_prep`.
This enables apply acceptance tests for macOS 10.15, as packages for
that platform have been available for a while now.
> (maint) Disable apply acceptance tests on Debian 8, enable on macOS 1015

- lib/bolt/cli.rb
- lib/bolt/shell/powershell.rb
- spec/bolt/shell/powershell_spec.rb
- spec/bolt/transport/ssh/connection_spec.rb
This adds a deprecation warning when users run Bolt from Powershell
version less than 3, and for each target users run against in Powershell
less than 3. This only applies to the shell Bolt is run from or
connected to, not all Powershell versions on the machine. A warning is
issued for each target the user connects to with a deprecated version so
that users know which targets have deprecated PS versions.
Closes #2365
!deprecation
* **Deprecate Powershell 2 support** ([2365](https://github.com/puppetlabs/bolt/issues/2365))
Support for Powershell 2 on both Bolt targets and controllers is
deprecated, and will be dropped in Bolt 3.0.
> (GH-2365) Deprecate Powershell 2 support

- lib/bolt/plugin.rb
- lib/bolt/plugin/module.rb
- spec/bolt/plugin_spec.rb
When set to true, the returned Bolt::Plugin object will load
plugins on-demand. This is what Bolt is already doing and hence
the default behavior.
When set to false, the returned Bolt::Plugin object will raise a new
PluginLoadingDisabled error indicating that plugin loading is disabled.
However, users can still add their statically loaded plugins via
Bolt::Plugin#add_plugin.
> (PE-30636) Add load_plugins option to Bolt::Plugin.setup

- documentation/troubleshooting.md
- lib/bolt/shell/bash.rb
- spec/bolt/shell/bash_spec.rb
Exit code 126 indicates that a file Bolt has written to the temporary
directory can't be executed because the user Bolt is running as doesn't
have permission to execute it. This can be caused by a variety of
issues, but one common cause is that administrators have mounted the
default tmpdir with `noexec`, meaning that users can't execute files in
the tmpdir. The recommended workaround for this is to configure an
alternative `tmpdir` for the transport(s) being used, or to contact the
administrator about modifying the permissions (though usually they're in
place for a reason). This appends a brief message that `noexec` may be
the issue to stderr output whenever exit code 126 is returned. This is
appended for bash shells. The message directs users
to our troubleshooting doc, which has been …
> (GH-2379) Suggest noexec may be an issue with exit code 126

- documentation/developer_updates.md
- documentation/templates/bolt_configuration_reference.md.erb
- documentation/templates/bolt_defaults_reference.md.erb
- documentation/templates/bolt_project_reference.md.erb
- lib/bolt/config.rb
- lib/bolt/config/options.rb
- rakelib/docs.rake
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
- spec/integration/config/validator_spec.rb
This adds the `notice` log level back to the config schema, which was
removed in #2098. Because we now use the schema for config validation,
the absence of `notice` as a valid option resulted in Bolt raising an
error for any user that had that log level configured. Now, Bolt will
instead issue a deprecation warning that the log level is deprecated and
will be removed in 3.0.
!bug
* **Support `notice` log level**
Log levels can now be set to `notice`. Previously, Bolt would raise an
error saying that `notice` was not a supported log level.
!deprecation
* **Deprecate `notice` log level**
The `notice` log level is deprecated and will be removed in Bolt 3.0.
Use the `info` log level instead.
> (bug) Add 'notice' log level to schema and deprecate

- lib/bolt_server/plugin.rb
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
Update bolt-servers `project_inventory_targets` to raise informative errors when unsupported or unknown plugins are encountered in a project's inventoryfile.
> (PE-30638) Raise PluginNotSupported error for unsupported plugins

- lib/bolt_server/plugin/puppet_connect_data.rb
- spec/bolt_server/plugin/puppet_connect_data_spec.rb
This adds a basic implementation of the puppet_connect_data plugin that
takes a data hash and looks up keys in the hash. The data is expected to
be supplied as a map in the following structure:
{
"key1": {
"value": "value1"
},
"key2": {
"value": "value2"
}
}
The plugin will fail if no value is supplied for the key. It
specifically does *not* validate that each value map has a 'value' key,
as that validation should be done prior to passing the value to the
plugin constructor.
Currently, this plugin is not loaded anywhere.
> Add puppet_connect_data plugin for bolt_server

- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
Prior to this commit, an error was raised upon inventory sync for
inventory files that were in a non-standard location, but projects
that did not contain an inventory file returned a 200. This commit
also adds a check for the presense of the inventory file.
> (PE-30716) raise error when inventory file is absent

- .github/workflows/docs.yaml
- .github/workflows/linux.yaml
- .github/workflows/modules.yaml
- .github/workflows/schemas.yaml
- .github/workflows/windows.yaml
- spec/Dockerfile
- spec/docker-compose.yml
- spec/integration/apply_spec.rb
- spec/lib/bolt_spec/conn.rb
- spec/lib/bolt_spec/puppet_agent.rb
This includes several changes to Bolt's spec tests and CI environment:
- **Fix broken apply integration tests**
With the release of Puppet 7, the `puppet_agent::install` task now
installs `puppet7` packages by default. This broke several of the
apply integration tests that expected `puppet6` packages, or attempted
to downgrade to the `puppet6` repo after having already installed the
`puppet7` repo. This fixes the tests to assume `puppet7` is installed.
Additionally, the apply integration tests were refactored slightly to
make it easier to tell what is happening in setup, testing, and
teardown for each spec test. Previously, the agent package was
repeatedly installed and uninstalled between spec tests and inventory
was sourced in multiple different ways. Now, agentful targets have the …
> (maint) Fix broken apply integration tests

- documentation/bolt.ditamap
- documentation/configuring_bolt.md
- documentation/templates/bolt_transports_reference.md.erb
- documentation/upgrading_to_bolt_3.md
- lib/bolt/config.rb
- lib/bolt/project.rb
This adds a deprecation warning for bolt.yaml at the project-level, and
updates the existing deprecation warning at the user/system level to
point to documentation on how to update their Bolt files.
Closes #2000
!deprecation
* **Deprecate bolt.yaml** ([#2000](https://github.com/puppetlabs/issues/2000))
The `bolt.yaml` configuration file is now deprecated, both at
project-level and user/system-level.
> (GH-2000) Deprecate bolt.yaml

- documentation/getting_started_with_bolt.md
The new module workflow is now stable, and as part of moving it out of
experimental we now add a `modules` key to `bolt-project.yaml` when
users run `bolt project init` or `New-BoltProject`. Our getting started
guide instructs users to use the project init command to create their
project, which enables the new workflow. As part of the new module
workflow the `site-modules/` directory is not on the modulepath by
default, and instead we expect users to use the `modules/` directory for
any custom modules they are developing. This updates the getting started
guide to instruct users to create their new module inside the `modules/`
directory within their project instead of in the `site-modules/`
directory.
Closes #2417
> (GH-2417) Update getting started to use module workflow

- developer-docs/bolt-api-servers.md
- lib/bolt_server/schemas/connect-data.json
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
This commit updates the `project_inventory_targets` endpoint to accept data from puppet connect and uses it to enable the connect plugin.
> (PE-30656) Allow project_inventory_targets to use PuppetConnectData

- documentation/getting_started_with_bolt.md
Updates the deprecated `source` key for the file upload step in YAML
plans to `upload` key. I opted to leave the `src` parameter name the
same, as I think it's more descriptive and clear for new YAML plan
authors.
Closes #2424
> (GH-2424) Update 'source' to 'upload' in Getting started

- lib/bolt/shell/powershell.rb
- spec/integration/transport/local_spec.rb
- spec/shared_examples/transport.rb
This modifies the PowerShell shell to write commands to a file for 
execution when running over the local transport. This uses the same
logic we use when running commands greater than the max command length
to wrap the command in a script. This enables two necessary behaviors:
returning correct exit codes and allowing users to run commands with
pipes.
PowerShell will always exit 0 or 1 when running commands directly, even
when the command returns a different exit code (for example, running
`puppet agent --detailed-exitcodes`). However when executing a file with
`-File`, PowerShell will return the exit code returned by the script
[source](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1#-command).
Wrapping the …
> (GH-2299) Write Windows local transport commands to file

- documentation/developer_updates.md
- lib/bolt/config/transport/local.rb
- lib/bolt/config/transport/options.rb
- lib/bolt/inventory/target.rb
- lib/bolt/target.rb
- lib/bolt/transport/local.rb
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-inventory.schema.json
- spec/bolt/inventory/inventory_spec.rb
- spec/bolt/transport/local_spec.rb
- spec/integration/local_spec.rb
This introduces the `bundled-ruby` config option for the local
transport. The option enables merging default config values currently
used just for a target with name `localhost`. Those default config
values are:
```
config:
local:
interpreters:
'.rb' => RbConfig.ruby # This is Bolt's bundled Ruby
features:
- puppet-agent
```
The default config values are merged at the target config level, meaning
they are overridden by target-level config but not group-level config.
The 'features' array is appended, not overridden, and is a set so the
value will not be added twice.  The `localhost` target additionally
defaults to using the `local` transport as part of the "magic config",
however the `bundled-ruby` option will only apply to targets that are
already configured to use the local transport. …
> (GH-2400) Add bundled-ruby option for local transport

- documentation/bolt_known_issues.md
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/config/options.rb
- lib/bolt/module_installer.rb
- lib/bolt/module_installer/resolver.rb
- lib/bolt/project.rb
- lib/bolt/project_manager/config_migrator.rb
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
- spec/bolt/config_spec.rb
- spec/bolt/module_installer_spec.rb
- spec/bolt/project_manager/config_migrator_spec.rb
- spec/integration/module_installer_spec.rb
- spec/lib/bolt_spec/project.rb
This adds a new `module-install` config option that is meant to replace
`puppetfile`. The config option accepts the same sub-options as
`puppetfile` does.
Currently, this config option is not respected when resolving module
dependencies, as changes need to be made to the `puppetfile-resolver`
library to support proxies and an alternate Forge. However, this config
is still passed to r10k, which will respect it when installing modules
from a Puppetfile.
If a user has `module-install` configured and then runs `bolt module
add|install` or `Add|Install-BoltModule`, Bolt will issue a warning
letting the user know that the config option will not be respected when
resolving modules, and then provides a link to a known issue with more
information.
This also adds a handful of warnings that are …
> (GH-2303) Add module-install config option

- documentation/bolt_inventory_reference.md
This adds documentation for the `plugin_hooks` option to the inventory
reference, as `plugin_hooks` is a valid option for groups and targets.
> (GH-2445) Document 'plugin_hooks' option for inventory

- documentation/vscode_and_bolt.md
- schemas/bolt-yaml-plan.schema.json
This adds a new JSON schema for YAML plans. This schema can be used in
VS Code and other editors that support YAML language servers to perform
schema validation on YAML plans.
!feature
* **Added JSON schema for YAML plans**
([#2046](https://github.com/puppetlabs/bolt/issues/2046))
Bolt now offers a JSON schema for validating YAML plans.
> (GH-2046) Add YAML plan JSON schema

- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/config/options.rb
- lib/bolt/module_installer.rb
- lib/bolt/outputter.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- lib/bolt/outputter/logger.rb
- lib/bolt/outputter/rainbow.rb
- lib/bolt/project_manager.rb
- lib/bolt/project_manager/module_migrator.rb
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
- spec/bolt/cli_spec.rb
- spec/bolt/module_installer/installer_spec.rb
- spec/bolt/module_installer_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/bolt/outputter/json_spec.rb
- spec/bolt/outputter/rainbow_spec.rb
- spec/bolt/project_manager/module_migrator_spec.rb
- spec/bolt/project_manager_spec.rb
- spec/bolt/rerun_spec.rb
- spec/lib/bolt_spec/integration.rb
(feature) Print spinner to the console for long operations
This introducs a spinner which spins while Bolt performs long
operations. Currently the spinner is added for installing modules,
running plans, and running tasks.
The spinner works by creating a new thread and continuously printing a
series of messages, where each message includes a backspace and the 
next character from an array of characters. The spinner is a function of
the outputters, which each have their own `start_spin` and `stop_spin`
functions that open and close the spinner thread respectively.
The spinner is enabled by default, and can be disabled by setting
`spinner: false` in any of `bolt.yaml`, `bolt-project.yaml`, or
`bolt-default.yaml`.
Closes #606
!feature
* **CLI spinner for long running operations**
Bolt now has …
> (feature) Print spinner to the console for long operations

- .github/workflows/docs.yaml
- .github/workflows/linux.yaml
- .github/workflows/litmus_smoke.yaml
- .github/workflows/modules.yaml
- .github/workflows/pwsh.yaml
- .github/workflows/schemas.yaml
- .github/workflows/windows.yaml
- bolt.gemspec
This temporarily pins the bundler gem to 2.1.4, as bundler 2.2.0 is
failing to pull in a dependency for the Litmus CI tests ([this
issue](https://github.com/rubygems/rubygems/issues/4123)). This should
be reverted once the issue is fixed.
> (maint) Temporarily pin bundler to 2.1.4

- documentation/templates/bolt_transports_reference.md.erb
This adds a section to the Bolt transport configuration reference page
documenting which OpenSSH configuration options are picked up by Bolt.
OpenSSH configuration takes lowest precedence of all Bolt configuration,
so is overridden if values for corresponding configs (like `port`) are
conifgured in Bolt. These options are read, parsed, and applied by the
net-ssh library we use.
I got this list from https://github.com/puppetlabs/bolt/pull/1588/files and verified that the [Net::SSH::Config class](https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/config.rb) hasn't changed since that writing.
Closes #2436
> (GH-2436) Document OpenSSH config options used by Bolt

- documentation/applying_manifest_blocks.md
- documentation/bolt.ditamap
- documentation/running_bolt.md
- documentation/running_bolt_commands.md
- documentation/running_bolt_network.md
This adds a new document with information specifically helpful to
running Bolt when targetting network devices. For now I opted to just
include running mulitline commands using `@file`, and expect we will
build this file up as more use cases arise. The example demonstrates
configuring a virtual access point for a Fortinet device.
This also moves the documentation for using network device modules from
the 'Applying Puppet code' document to the new network device document,
and includes a 'Related Information' link on the 'Applying Puppet code'
page.
Closes #2109
> (GH-2109) Document running multiline commands against Network devices

- lib/bolt/config/options.rb
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
- spec/integration/validator_spec.rb
Closes #2461 
It looks like the `_plugin: true` validator definition wasn't propagated down into the sub-keys of the `puppetdb` hash. This change allows each of those sub-keys to contain `_plugin` references themselves.
> (GH-2461) Fix to allow puppetdb config to contain plugin references

- lib/bolt/plugin/puppetdb.rb
- spec/bolt/plugin/puppetdb_spec.rb
We validate that the PuppetDB plugin that ships with Bolt only contains
valid keys in the plugin class itself (not through schema validation).
We missed adding `_cache` as a valid key to the PuppetDB plugin options,
which resulted in an error when users try to configure a cache for the
PuppetDB plugin. This adds `_cache` as a valid key for the PuppetDB
plugin.
!bug
* **Allow caching for PuppetDB plugin**
Previously, our configuration validation would raise an error if users
supplied `_cache` to the PuppetDB plugin. Cache is now configurable
for the plugin.
> (bug) Allow _cache in PuppetDB plugin options

- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/module_installer/puppetfile_spec.rb
- spec/bolt/module_installer_spec.rb
- spec/bolt/plan_creator_spec.rb
- spec/bolt/project_manager/config_migrator_spec.rb
- spec/bolt/project_manager_spec.rb
- spec/bolt/project_spec.rb
- spec/integration/apply_spec.rb
- spec/integration/cache_spec.rb
- spec/integration/module_installer_spec.rb
- spec/integration/plan_spec.rb
- spec/integration/project_manager_spec.rb
- spec/integration/project_spec.rb
- spec/integration/validator_spec.rb
- spec/lib/bolt_spec/project.rb
This updates the `BoltSpec::Project` method `with_project` to be more
transparent. Previously, the method used some magic to configure a
project by calling the `project_config` method. Additionally, the method
would also set several instance variables for spec tests to use.
The `with_project` method now includes a few keyword arguments that can
be used to modify the project directory structure that it creates:
- `config`
A hash of config to write to `bolt-project.yaml`. If `nil`, writes a
default config file with the project name set.
- `inventory`
A hash of inventory data to write to `inventory.yaml`. If `nil`,
writes an empty inventory file.
- `boltdir`
A boolean. When true, creates the project inside a `Boltdir`.
The `with_project` method now yields a `Bolt::Project` instance for the …
> (GH-2428) Update with_project method to be more transparent

- lib/bolt/project.rb
- spec/bolt/project_spec.rb
- spec/integration/project_spec.rb
This limits the warning that project content won't be loaded if the
project doesn't have a name to only be raised if the project has a
`tasks/`, `plans/`, or `files/` directory.
!bug
* **Only warn that project content won't be loaded if there's project content**
Bolt will now only warn that project content won't be loaded if the
proejct directory has a `tasks/`, `plans/`, or `files/` directory that
may contain content.
> (GH-2438) Don't warn that project content won't be loaded if there's no project content

- lib/bolt/config.rb
- lib/bolt/config/transport/ssh.rb
- lib/bolt/inventory/group.rb
- spec/bolt/config_spec.rb
- spec/bolt/inventory/group_spec.rb
This removes some redundant validation for the `Bolt::Config` class that
is handled by the validator.
> (GH-2454) Remove redundant config validation

- lib/bolt/config/options.rb
- lib/bolt/config/transport/options.rb
- lib/bolt/validator.rb
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-inventory.schema.json
- spec/integration/validator_spec.rb
- spec/lib/bolt_spec/options.rb
There was a bug in the configuration schema that warned when users would
set any configuration under the remote transport key. The key now
accepts a hash with any keys and values and does not warn.
Closes #2477
!bug
* **Fix bug warning about keys under 'remote' transport** ([#2477](https://github.com/puppetlabs/bolt/issues/2477))
Bolt now will not warn when keys are configured for the `remote`
transport in inventory.
> (GH-2477) Allow any keys under `remote` transport config

- lib/bolt/validator.rb
- rakelib/schemas.rake
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-inventory.schema.json
- spec/bolt/validator_spec.rb
- spec/integration/validator_spec.rb
This updates the validator to allow plugins for all items and suboptions
of a given option if that option supports plugins. Items and suboptions
do not need to explicitly set the `:_plugin` key to enable this
behavior.
!bug
* **Support plugins for suboptions under options that allow plugins**
All suboptions for config options that support plugins once again
support plugins. For example, the `key-data` suboption for the
`private-key` option can use plugins again.
> (bug) Support plugins for suboptions when superoption supports plugins

- bolt.gemspec
- documentation/bolt_installing_modules.md
- documentation/bolt_known_issues.md
- lib/bolt/cli.rb
- lib/bolt/module_installer/resolver.rb
- spec/integration/module_installer_spec.rb
Reverts puppetlabs/bolt#2479
Puppetfile Resolver has a minimum ruby version of 2.5.3, which requires us to use an updated CI environment in Jenkins that uses Bundler 2.2.1, which may be incompatible for downstream projects (see https://github.com/puppetlabs/bolt/pull/2460). We're reverting this change for now to get a bug fix out, and will update after the holiday break.
> Revert "(GH-2478) Support module-install config when resolving modules"

- spec/bolt/catalog_spec.rb
- spec/bolt/cli_spec.rb
- spec/bolt_spec/plan_spec.rb
- spec/bolt_spec/run_spec.rb
- spec/integration/apply_compile_spec.rb
- spec/integration/apply_error_spec.rb
- spec/integration/device_spec.rb
- spec/integration/local_spec.rb
- spec/integration/logging_spec.rb
- spec/integration/output_spec.rb
- spec/integration/parsing_spec.rb
- spec/integration/plan_spec.rb
- spec/integration/project_spec.rb
- spec/integration/resource_instance_spec.rb
- spec/integration/result_set_spec.rb
- spec/integration/run_as_spec.rb
- spec/integration/shareable_task_spec.rb
- spec/integration/target_spec.rb
- spec/integration/task_param.rb
- spec/integration/winrm_spec.rb
We construct paths to fixtures throughout spec tests, and now that there
is One True `fixtures_path()` helper, this moves any fixture path
consturction to use the method. This is more readable and concise, and
provides uniformity in the spec tests.
Note: I tried not to have this overlap with #2484 
> (maint) Standardize on using fixtures_path

- spec/bolt/project_manager/config_migrator_spec.rb
- spec/bolt/project_spec.rb
- spec/fixtures/linuxdev/bolt-kerberos-test.sh
- spec/integration/lookup_spec.rb
- spec/integration/plugin/module_spec.rb
- spec/integration/plugin/task_spec.rb
- spec/lib/bolt_spec/project.rb
This removes `bolt.yaml` and replaces it with `bolt-project.yaml` file
infrastructure for any tests that aren't explicitly testing behavior
around the presence of `bolt.yaml`. This mostly includes refactoring the
plugin integration test to use `with_project` instead of their own
custom functions.
This also edits the `with_project` spec test helper to set the project
name by default, and merge in the provided config over top of `{ 'name'
=> name }` if config is passed to the helper. This ensures the project
always has a name, and that the name can be overridden by the config 
hash if need be.
Closes #2429
> (GH-2429) Remove bolt.yaml from spec tests

- spec/bolt/config_spec.rb
- spec/bolt/plugin_spec.rb
- spec/bolt_server/transport_app_spec.rb
- spec/integration/apply_compile_spec.rb
- spec/integration/apply_spec.rb
- spec/integration/validator_spec.rb
This removes deprecated config options from our spec tests and replaces
them with the 'new' config option if applicable.
> (GH-2448) Remove deprecated config options from spec tests

- lib/bolt/outputter/human.rb
- lib/bolt/outputter/rainbow.rb
- spec/bolt/outputter/human_spec.rb
Previously, we neglected to check if stdout was an interactive terminal
before printing the spinner. This caused the spinner to print a series
of characters in CI environments. While configurable, this is clearly
wrong. We now only print the spinner after checking that `$stdout` is a
TTY.
Closes #2500
!bug
* **Only print spinner when stdout is a TTY** ([#2500](https://github.com/puppletabs/bolt/issues/2500))
We now only print the spinner when the STDOUT stream is a TTY.
> (GH-2500) Only print spinner if stdout is a TTY

- spec/integration/inventory_spec.rb
This adds a test to ensure that the `plugin-hooks` config option is
picked up by targets, which use the `plugin_hooks` field.
> (GH-2447) Ensure plugin-hooks config picked up by targets

- lib/bolt_server/schemas/partials/task.json
This commit adds "both" as a valid value for input_method in
bolt-server's task schema
> (maint) Allow "both" in bolt-server task schema

- lib/bolt/cli.rb
- spec/integration/inventory_spec.rb
This fixes a bug introduced in #2395 that adds the `localhost` target to
the inventory by default. This results in any use of the `all` group
when running in PowerShell to include the `localhost` target in
inventory. Now, Bolt will not add the `localhost` target to inventory by
default.
!bug
* **Do not add `localhost` target to the `all` group by default in
PowerShell**
([#2505](https://github.com/puppetlabs/bolt/issues/2505))
Bolt no longer adds the `localhost` target to the `all` group by
default. Previously, when running Bolt in PowerShell, the `localhost`
target would be added to the `all` group unintentionally.
> (GH-2505) Do not add localhost to the all group by default in PowerShell

- bolt.gemspec
This pins the `puppetfile-resolver` gem to 0.4.0. Currently, the gem
build & stage job will fail because `puppetfile-resolver` will be
resolved to 0.5.0, which requires Ruby >= 2.5.3.
> (maint) Pin puppetfile-resolver to 0.4.0

- .rubocop.yml
- spec/bolt/module_installer/resolver_spec.rb
This enables cops that were added to Rubocop 1.7.0. Enabling the cops
didn't result in any new errors, so just the configuration file change
is needed.
There was a separate issue where an integration test verifying the
Puppetfile resolver error when dependencies fail to resolve now fails
for a different module than the one the test checks. The failure is
still as expected, so this updates the check to just check for the error
message and not the module name.
> (maint) Enable Rubocop 1.7.0 cops

- .github/workflows/docs.yaml
- .github/workflows/linux.yaml
- .github/workflows/litmus_smoke.yaml
- .github/workflows/modules.yaml
- .github/workflows/pwsh.yaml
- .github/workflows/schemas.yaml
- .github/workflows/windows.yaml
- bolt.gemspec
We have a CI test that verifies that Litmus works with each Bolt PR by
adding a gem declaration to the Gemfile of
[puppetlabs/puppetlabs-package](https://github.com/puppetlabs/puppetlabs-package)
that pulls in the Bolt PR as a gem and runs tests in the module.
Installing gems in the module was hanging in Github Actions when Bundler 2.2.0
was released, due to [this
issue](https://github.com/rubygems/rubygems/issues/4123). We originally
pinned all of Bolt back to bundler < 2.2.0, however now the Jenkins CI
environment has been updated to only include Bundler 2.2.1. In order to
be able to test and build Bolt in Jenkins we need to unpin the bundler
version so we can use 2.2.1.
The original issue has also been fixed now, so we can unpin bundler
entirely.
> (maint) Unpin bundler for Bolt

- documentation/bolt_installing.md
This updates our documentation on PowerShell execution policy when
installing Bolt on Windows. Since Bolt's PowerShell module is now
signed, users on Bolt >= 2.21.0 will likely not need to change their
script execution policy to use Bolt.
**Note:** The text for this is taken directly from [James' comment](https://github.com/puppetlabs/bolt/issues/2013#issuecomment-675027455) in the issue.
> (GH-2013) Update docs on PowerShell execution policy

- lib/bolt/inventory.rb
- lib/bolt/inventory/group.rb
- lib/bolt/inventory/inventory.rb
- rakelib/schemas.rake
- schemas/bolt-inventory.schema.json
- spec/bolt/inventory/inventory_spec.rb
- spec/bolt/transport/local_spec.rb
- spec/integration/inventory_spec.rb
- spec/lib/bolt_spec/env_var.rb
This change allows an entire inventory to be a plugin reference. For
exmaple, the following inventory was previously invalid:
```yaml
---
_plugin: yaml
filepath: /path/to/inventory_partial.yaml
```
A top-level plugin like this used to be invalid as Bolt automatically
added `'name' => 'all'` to the top of the loaded inventory, which would
cause a plugin to receive a `name` parameter and (likely) error. Now,
Bolt will resolve a top-level plugin reference, validate that the
resolved data does not include a `name` key, and then merge in `'name'
=> 'all'`.
!bug
* **Allow entire inventory to be specified with a plugin**
([#2475](https://github.com/puppetlabs/bolt/issues/2475))
Inventory files can now be specified with a plugin. For example, the
following inventory file is now valid:
```yaml
--- …
```
> (GH-2475) Allow entire inventory to be a plugin reference

- lib/bolt/inventory/group.rb
- spec/bolt/inventory/inventory_spec.rb
- spec/integration/inventory_spec.rb
We need this for the upcoming PuppetConnectData plugin where we want to
enforce the semantic that "this key resolves to nil" == "this key was
not specified".
> (PE-30862) Delete transport config keys that resolved to nil

- .github/workflows/linux.yaml
- spec/Dockerfile
- spec/docker-compose.yml
- spec/integration/apply_spec.rb
- spec/integration/device_spec.rb
- spec/integration/parallel_spec.rb
- spec/integration/plan_spec.rb
This updates the Dockerfile and Docker compose files to provision the
agentful containers used in spec tests with the appropriate
`puppet-agent` package. Previously, the `puppet-agent` packages were
installed as part of the spec tests themselves.
> (GH-2452) Provision Docker containers with puppet-agent package

- documentation/supported_plugins.md
This commit updates the supported plugins docs to point to the yaml plugin on forge instead of a non-existent header tag on the page.
> (maint) Fix yaml plugin reference link

- bolt.gemspec
Loading `puppet_pal` fails on Windows with FFI 1.14.2 with `cannot load such file -- ffi_c`. This doesn't cause issues in our package builds, which use the Bolt package built using Puppet runtime gems which pulls in FFI 1.13.1, but it does cause our component acceptance tests to fail which build the gem from `puppetlabs/bolt.git` `main` branch. This pins FFI until we can safely upgrade it. This seems most related to a change that removes `win32/stdint.h` in [FFI 1.14.0](https://github.com/ffi/ffi/blob/master/CHANGELOG.md#1140--2020-12-18), but could be related to something else.
[Pasing Jenkins build with this change](https://jenkins-master-prod-1.delivery.puppetlabs.net/view/__experimental%20automatic/job/experimental_auto_bolt_vanagon-integration-component_main_project-main/12/) …
> (maint) Pin ffi to avoid test failures

- documentation/bolt_installing_modules.md
- documentation/modules.md
- lib/bolt/cli.rb
- lib/bolt/config/options.rb
This deprecates the `puppetfile` CLI commands and the `puppetfile`
configuration option. If any configuration file includes the
`puppetfile` option or if the user runs any `puppetfile` command,
Bolt will issue a deprecation warning telling the user to update
their project to use the module management feature with a link to
documentation.
!deprecation
* **Deprecate `puppetfile` in favor of `module-install`**
([#2361](https://github.com/puppetlabs/bolt/issues/2361))
The `puppetfile` configuration option has been deprecated in favor of
`module-install` and will be removed in Bolt 3.0. Users should update
their projects to use the module management feature, which uses the
`module-install` option.
* **Deprecate `puppetfile` commands**
([#2361](https://github.com/puppetlabs/bolt/issues/2361)) …
> (GH-2361) Deprecate puppetfile commands and config option

- documentation/writing_plugins.md
- lib/bolt/module.rb
- lib/bolt/plugin.rb
- spec/bolt/module_spec.rb
- spec/integration/plugin/module_spec.rb
This change adds support for project-level plugins. When Bolt loads
plugins, it now checks whether the project is a named project and is
loaded as a module. If the project is named, and contains a
`bolt_plugin.json` file, it is added as a plugin module in Bolt. All
plugin hooks are supported for project-level plugins.
!feature
* **Support for project-level plugins**
([#2517](https://github.com/puppetlabs/bolt/issues/2517))
Bolt now supports project-level plugins. Similar to module plugins,
project-level plugins are implemented as tasks that use specific hooks
and are referred to using the name of the project.
> (GH-2517) Support project-level plugins

- documentation/bolt_types_reference.md
We currently document Bolt's custom types on the Type Reference page,
but don't document type aliases shipped in Boltlib. This adds a new
`Type Aliases` section to the type reference doc that enumerates the
TargetSpec and PlanResult types, and describes what they alias.
> (docs) Document type aliases on type reference page

- bolt.gemspec
This updates the gemspec to pin ffi to < 1.14.0, which includes some
breaking changes on Windows. Previously, ffi was pinned to ~> 1.13.0,
which caused our packaging pipeline to fail, as bolt-runtime only
includes ffi 1.9.25.
> (maint) Pin ffi to < 1.14.0

- spec/bolt/pal/yaml_plan/evaluator_spec.rb
- spec/bolt/pal/yaml_plan/loader_spec.rb
- spec/bolt/pal/yaml_plan/step_spec.rb
- spec/fixtures/modules/sample/plans/yaml.yaml
- spec/fixtures/modules/yaml/plans/command.yml
- spec/fixtures/modules/yaml/plans/subdir/init.yaml
- spec/fixtures/modules/yaml/plans/upload.yaml
This replaces deprecated YAML plan keys `source` with `upload` and
`target` with `targets` in the spec tests, so that these tests continue
to work once the deprecated keys are removed.
> (GH-2450) Remove deprecated yaml plan keys from spec tests 

- .rubocop.yml
This enables cops that are new in 1.8.0.
> (maint) Enable Rubocop 1.8.0 cops

- bolt.gemspec
- lib/bolt/config/transport/options.rb
- lib/bolt/config/transport/orch.rb
- lib/bolt/transport/orch/connection.rb
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-inventory.schema.json
- spec/bolt/config/transport/orch_spec.rb
- spec/integration/transport/orch_spec.rb
This adds a `read-timeout` configuration setting for the PCP transport,
which accepts an integer and passes the configuration to
`OrchestratorClient.new()`. Although the option is an integer, it
should be nil if a value is not provided, as there's no static default
for `Net::Http::Persistent#read_timeout`, so we should not set one
unless it's configured. This allows users to configure either failing
quickly if the Orchestrator is busy (such as during code deploys), or to
extend the time if they'd like to wait for the jobs to finish.
`read-timeout` configures the length of time to wait for a response from
the Orchestrator before raising a timeout error when making HTTP
requests.
Relies on:
!feature
* **Add read-timeout configuration option for PCP transport** …
> (GH-2518) Add read-timeout config for PCP transport

- documentation/templates/bolt_configuration_reference.md.erb
- documentation/templates/bolt_defaults_reference.md.erb
- documentation/templates/bolt_project_reference.md.erb
- documentation/templates/bolt_transports_reference.md.erb
- documentation/using_plugins.md
This updates the `Using Plugins` document to tell users that not all 
configuration options are pluggable, and how to request a new option be
made pluggable. This also updates the configuration reference templates
to add a `Pluggable` list item for configuration options that are 
pluggable. The `Using Plugins` page points to this reference for users
that want to see which options are pluggable.
> (docs) List which config options are pluggable

- documentation/applying_manifest_blocks.md
- lib/bolt/applicator.rb
- lib/bolt/config/options.rb
- libexec/bolt_catalog
- schemas/bolt-config.schema.json
- schemas/bolt-project.schema.json
- spec/integration/apply_spec.rb
This enables setting the `log_level`, `trace`, and `evaltrace` Puppet
settings under the `apply-settings` configuration option.
!feature
* **Support additional Puppet settings in `apply-settings`**
([#2516](https://github.com/puppetlabs/bolt/issues/2516))
The `log_level`, `trace`, and `evaltrace` Puppet settings can now be
configured under the `apply-settings` configuration option. These
settings will be applied when executing an apply block.
> (GH-2516) Support log_level, trace, evaltrace in apply-settings

- documentation/inventory_file_v2.md
- documentation/using_plugins.md
On the inventory page, we list bundled plugins, but some of the links for those
plugins go to the "Using plugins" page instead of linking to their entries in
supported plugins. These are links that we overlooked when we reshuffled the
plugins pages.
**Changes:**
- Remove the table on the inventory page and link to supported plugins instead.
- Add a general link to the supported plugins page from the Using plugins page.
- Rename the "Using plugins" inventory example entry to "Inventory file using
plugins".
Closes #2562
> (GH-2562) Fix linking issues on plugins pages

- Puppetfile
There was an issue with the `puppet_agent` module not properly trying
all GPG keys in module version 4.3.0, which has been fixed in 4.4.0.
This updates the module, and also updates other modules with newer
versions.
> (maint) Bump puppet module versions

- lib/bolt/catalog.rb
- spec/bolt/catalog_spec.rb
- spec/fixtures/apply/basic/plans/collisions.pp
- spec/integration/apply_compile_spec.rb
This updates the `Bolt::Catalog.compile_catalog` method to pass target
and plan variables to the catalog compiler, which will then deserialize
plan variables and shadow any variables that collide with facts of the
same name. This change fixes a bug where a plan variable 'foo' that
collided with a fact 'foo' would not be passed to the compiler, so any
plan variable 'bar' that had a local reference to 'foo' would not be
deserialized correctly.
Blocked by https://github.com/puppetlabs/puppet/pull/8412
!bug
* **Correctly shadow fact/variable collisions in apply blocks**
([#2111](https://github.com/puppetlabs/bolt/issues/2111))
Bolt now correctly shadows target and plan variables that collide with
facts of the same name when running apply blocks.
> (GH-2111) Shadow fact/variable collisions in PAL catalog compiler

- bolt.gemspec
This pins the `puppetlabs_spec_helper` gem to `<= 2.15.0`, as greater
versions have a dependency on `pathspec < 1.1.0`, which requires Ruby
2.7 or higher.
> (maint) Pin puppetlabs_spec_helper to <= 2.15.0

- bolt-modules/boltlib/lib/puppet/functions/parallelize.rb
- lib/bolt/cli.rb
- lib/bolt/executor.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/rainbow.rb
- spec/bolt/executor_spec.rb
- spec/integration/plan_spec.rb
Previously the spinner would spin for the entirety of a plan or task
run, starting and stopping from the Bolt CLI manager. This meant that if
the user was prompted during a plan run the spinner would spin in the
area of the terminal the user was supposed to input text. While this
didn't write to stdin or impact user input, it was annoying and
definitely wrong.
This modifies the spinner to be started and stopped from the executor,
impacting calls from the command line and plan functions. The executor
only starts and stops the spinner as part of `with_node_logging()`,
which affects `run_*` functions and `wait_until_available`. The spinner
still spins for module management and project updating commands, which
are unaffected by this change. The spinner will only be started and
stopped if Bolt …
> (GH-2511) Only spin while executing run_* plan functions

- spec/bolt/module_installer/specs/git_spec_spec.rb
This updates the branch used for git_spec spec tests to use the `main`
branch instead of `master`, as the `master` branch has been renamed to
`main` for that repository.
> (maint) Update puppetlabs-yaml branch to main in spec tests

- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- pwsh_module/command.tests.ps1
- rakelib/pwsh.rake
- resources/bolt_bash_completion.sh
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
This removes support for deprecated command-line options:
- `--boltdir`
- `--configfile`
- `--debug`
- `--description`
- `--puppetfile`
This also removes the `Bolt::Config.from_file` factory method, since it
is only used when using the `--configfile` command-line option.
!removal
* **Remove deprecated command-line options**
([#2559](#2559))
The `--boltdir`, `--configfile`, `--debug`, `--description`, and
`--puppetfile` command-line options have been removed.
> (GH-2559) Remove deprecated command-line options

- documentation/bolt_installing_modules.md
- lib/bolt/config/options.rb
- lib/bolt/module_installer.rb
- lib/bolt/module_installer/resolver.rb
- lib/bolt/module_installer/specs/forge_spec.rb
- lib/bolt/module_installer/specs/git_spec.rb
- schemas/bolt-project.schema.json
- spec/bolt/module_installer/resolver_spec.rb
- spec/bolt/module_installer/specs/forge_spec_spec.rb
- spec/bolt/module_installer/specs/git_spec_spec.rb
- spec/integration/module_installer_spec.rb
This adds support for a new `resolve` key for both Forge and git module
specs in `bolt-project.yaml`. It also adds support for a `name` key for
git module specs, which is required when setting the `resolve` key to
`false`.
When `resolve` is `false`, Bolt will skip dependency resolution for the
module. This allows users to include modules that would otherwise break
Bolt's dependency resolution in their Bolt projects, avoiding the need
to manually manage a Puppetfile. This includes modules with broken
metadata and git modules hosted in a repository other than a public
GitHub repository.
If a unresolved module shares the name of another module's dependency,
Bolt will error indicating that there is a name conflict. This is in
line with r10k's behavior when installing a Puppetfile that has …
> (GH-2522) Add 'resolve' key to modules config

- documentation/troubleshooting.md
- lib/bolt/cli.rb
- lib/bolt/shell/powershell.rb
- lib/bolt/shell/powershell/snippets.rb
!removal
* **Descriptive title of changes** ([#2561](https://github.com/puppetlabs/bolt/issues/2561))
Remove PowerShell 2.0 support
Acceptance Critera:
Bolt works on a target and localhost with PowerShell versions 3.0 and 5.1 (lowest and highest supported at the moment)
> (GH-2561) Remove PowerShell 2.0

- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/config/options.rb
- schemas/bolt-config.schema.json
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
- spec/bolt/config_spec.rb
- spec/bolt_server/transport_app_spec.rb
This removes support for deprecated config options:
- `apply_settings`
- `inventoryfile`
- `plugin_hooks`
- `puppetfile`
!removal
* **Remove deprecated configuration options**
([#2553](https://github.com/puppetlabs/bolt/issues/2553))
The `apply_settings`, `inventoryfile`, `plugin_hooks`, and
`puppetfile` configuration options have been removed.
> (GH-2553) Remove deprecated config options

- Puppetfile
This pulls in updates to the Puppet modules that include allowing them
to be used with Puppet 7.x. Updates are to the maximum Puppet version,
not the minimum, so this is safe to merge to the 2.x series.
!feature
* **Bolt modules usable with Puppet 7.x**
Modules owned by the Bolt team now have a maximum Puppet version of 8,
so are usable with Puppet 7 on the Bolt controller.
> (maint) Update Puppet modules

- documentation/running_bolt_in_docker.md
- lib/bolt/config.rb
- lib/bolt/config/options.rb
- lib/bolt/logger.rb
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
- spec/bolt/applicator_spec.rb
- spec/bolt/executor_spec.rb
- spec/integration/yaml_plan_spec.rb
This removes the 'notice' log level, which means Bolt will error if the
logger is configured to 'notice' either via the command line or
configuration files.
!removal
* **Remove 'notice' log level**
Bolt no longer accepts 'notice' as a log level, via the command line
or configuration. Use 'info' instead.
> (GH-2560) Remove 'notice' log level

- documentation/README.md
- documentation/configuring_bolt.md
- documentation/experimental_features.md
- documentation/inventory_file_v2.md
- documentation/module_structure.md
- documentation/projects.md
- documentation/upgrading_to_bolt_3.md
- Update some docs that still refer to the old modulepath
- Remove references to bolt.yaml
- Updates Bolt 3.0 welcome page (I have some more updates to this one in a future PR)
Part of #2409
> (Docs) 3.0 docs updates - modulepath, bolt.yaml

- lib/bolt/plugin/module.rb
This removes support for the `public-key` and `private-key` parameters
in the pkcs7 plugin. Previously, Bolt would change these parameters to
the correct `public_key` and `private_key` parameters.
!removal
* **Remove support for `private-key`, `public-key` parameters in pkcs7
plugin**
([#2555](https://github.com/puppetlabs/bolt/issues/2555))
Support for the `private-key` and `public-key` parameters in the pkcs7
plugin has been removed. Use the `private_key` and `public_key`
parameters instead.
> (GH-2555) Remove public-key, private-key params for pkcs7 plugin

- acceptance/tests/apply_plan_ssh.rb
- acceptance/tests/bolt_apply.rb
- documentation/bolt_installing.md
This removes the install documentation for Debian 8, and additionally
removes some unneeded logic for skipping Debian 8 in our acceptance
tests. This is related to puppetlabs/ci-job-configs#7562 which removes
testing and building on Debian 8.
!removal
* **Remove support for Debian 8**
Bolt will no longer build or test packages for the Debian 8 platform.
> (GH-2556) Remove support for Debian 8

- lib/bolt/pal/yaml_plan/evaluator.rb
- lib/bolt/pal/yaml_plan/step.rb
- lib/bolt/pal/yaml_plan/step/upload.rb
- spec/bolt/pal/yaml_plan/evaluator_spec.rb
- spec/integration/yaml_plan_spec.rb
This removes support for the `source` and `target` keys in YAML plan
steps. Previously, the `source` key could be used as an action instead
of `upload`, while `target` could be used instead of `targets`.
!removal
* **Remove `source` and `target` YAML plan step keys**
([#2554](https://github.com/puppetlabs/bolt/issues/2554))
Support for the `source` and `target` keys in YAML plans has been
removed. Use `upload` and `targets` instead.
> (GH-2554) Remove source, target YAML plan step keys

- documentation/writing_plans.md
This fixes an example for `get_targets` in the Writing Plans doc to use
a `TargetSpec` parameter instead of four separate target names.
Fixes #2591 
> (GH-2591) Fix get_targets example in docs

- spec/Dockerfile.puppetdb
We published PuppetDB 7.0.1 containers yesterday, which seem to not stay
alive as the 6.x containers did. This pins back to 6.13.1 until we can 
diagnose the issue
> (maint) Pin PuppetDB container back

- .rubocop.yml
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- lib/bolt_server/transport_app.rb
- spec/bolt/applicator_spec.rb
- spec/bolt_server/app_integration_spec.rb
- spec/bolt_server/transport_app_spec.rb
This configures Rubocop to automatically enable new cops, with the
understanding that we almost always enable new cops and can manually
disable new ones if they are added that we don't want to adopt. This
also updates the codebase to adhere to the newly added cops in Rubocop
1.9.0.
> (maint) Configure Rubocop to enable new cops

- lib/bolt/config.rb
- lib/bolt/config/options.rb
- lib/bolt/project.rb
- lib/bolt/project_manager.rb
- lib/bolt/project_manager/module_migrator.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/project_manager/module_migrator_spec.rb
- spec/bolt/project_spec.rb
This updates Bolt to use the new default modulepath `['modules']` and
append the `.modules/` directory to the end of both the default
modulepath and configured modulepath.
!feature
* **Update default modulepath**
([#2549](https://github.com/puppetlabs/bolt/issues/2549))
Bolt's default modulepath is now `['modules']` instead of
`['modules', 'site', 'site-modules']`. Bolt will also automatically
append the project's `.modules/` directory to all modulepaths,
whether a project uses the default modulepath or a configured
modulepath.
> (GH-2549) Use new default modulepath

- lib/bolt/shell/powershell/snippets.rb
This formats the exception written to stderr so that the line and char position is written to bolt. This position is the actual location inside the script that the bolt task is executing, instead of a relative location inside the code block we 'send' over with all of our helper functions.
Note that this uses the `$host.UI` to 'write' the message we want. This works both in our winrm and local transports because both have a PSHost implementation. This could fail if somehow we don't have access to a `$host`, but this is not a common use case with our transports.
This also formats the message shown in a different order than what is shown normally. It prioritizes the exception type and position first, then shows the exception message. This may not be the best presentation of this information, …
> (GH-2509) Improve Bolt PowerShell Task Error Formatting

- bolt.gemspec
This updates the version of Puppet used by Bolt to the 7.x series.
!feature
* **Ship with Puppet 7**
([#2547](https://github.com/puppetlabs/bolt/issues/2547))
The Bolt gem and Bolt packages now ship with Puppet 7.
> (GH-2547) Use Puppet 7

- lib/bolt/config/transport/local.rb
- lib/bolt/config/transport/options.rb
- lib/bolt/transport/local.rb
- spec/bolt/transport/local_spec.rb
The local transport's `bundled-ruby` configuration option, which
determines whether to use the Ruby bundled with Bolt packages for local
targets, now defaults to 'true' instead of 'false'. The option can still
be configured as before.
!feature
* **Local transport's 'bundled-ruby' option defaults to true**
The local transport's `bundled-ruby` configuration option, which
determines whether to use the Ruby bundled with Bolt packages for local
targets, now defaults to 'true' instead of 'false'. The option can still
be configured as before.
> (GH-2552) bundled-ruby transport config now defaults to true

- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- documentation/upgrading_to_bolt_3.md
This adds a warning to the `apply_prep` function that is logged when a
target has puppet-agent < 6 installed. While puppet-agent < 6 may still
be compatible with Bolt, we no longer officially support or test it.
!deprecation
* **Drop support for puppet-agent < 6.0.0 on targets**
([#2422](https://github.com/puppetlabs/bolt/issues/2422))
Bolt no longer supports puppet-agent versions earlier than 6.0.0.
While applying Puppet code to targets with earlier versions of the
puppet-agent package installed may still succeed, Bolt no longer
guarantees compatibility.
> (GH-2422) Warn when puppet-agent version is < 6

- lib/bolt/pal.rb
- spec/bolt/cli_spec.rb
This adds the name of the plan to the `missing_plan_parameter` warning,
which is logged when a plan documents a parameter that is not present in
the plan's signature. This makes it easier for users to locate which
plan documents a missing parameter.
!bug
* **Include plan name in `missing_plan_parameter` warnings**
([#2588](https://github.com/puppetlabs/bolt/issues/2588))
The `missing_plan_parameter` warning now includes the name of the plan
that the message was logged for.
> (GH-2588) Add plan name to missing_plan_parameter warning

- Puppetfile
This updates the puppetlabs/stdlib module to 6.6.0.
!feature
* **Ship with puppetlabs/stdlib 6.6.0**
Bolt packages now ship with the latest version of the
puppetlabs/stdlib module.
> (maint) Update puppetlabs/stdlib to 6.6.0

- spec/bolt_server/file_cache_spec.rb
This test has been failing intermittently since bumping Ruby to 2.7 in
the repo. This bumps the number of expected mutex locks in the Bolt
server file cache from 2 to 3.
> (maint) Bump the number of expected bolt_server file cache mutex locks

- .rubocop.yml
- bolt.gemspec
We accidentally bumped the minimum ruby version in the bolt.gemspec from
ruby 2.7 to ruby 2.5. While Bolt will ship with Ruby 2.7 packages, Bolt
server will continue to ship with 2.5 and we will rely on PE testing to
catch any issues that arise from that.
> (maint) Required ruby version 2.5

- modules/puppet_connect/README.md
- modules/puppet_connect/Rakefile
- modules/puppet_connect/plans/test_input_data.pp
- modules/puppet_connect/spec/plans/test_input_data.rb
- modules/puppet_connect/spec/spec_helper.rb
This plan's used to test that the Puppet Connect input data is complete,
meaning that all consuming inventory targets are connectable.
> (PE-31005) Add puppet_connect::test_input_data plan

- lib/bolt/version.rb
This resets the version in `Bolt::VERSION` to 2.44.0 from 3.0.0-rc. This
is required for the release pipeline to bump and tag the Bolt repo
successfully.
> (maint) Reset version to 2.44.0

- acceptance/setup/common/pre-suite/032_configure_windows_profile.rb
This adds a step that adds the Bolt installation path to the PATH environment variable. This happens after the bolt msi install, so that subsequent commands will know where to find bolt.
> (maint) Ensure Bolt PATH environment variable in beaker

- documentation/bolt_installing.md
The puppet-bolt brew package is hosted in a [Puppet homebrew
repo](https://github.com/puppetlabs/homebrew-puppet) and is not shipped
as part of the core Homebrew repo ([see this for
context](https://github.com/Homebrew/homebrew-core/pull/28439)). Since
it's in our own namespace and not the core namespace, we need to include
that namespace in the installation instructions.
> (docs) Include namespace in Brew install instructions

- documentation/bolt_installing.md
This clarifies that latest Bolt only supports OSX 10.14 and 10.15, and
that older OSX platforms can install Bolt 2.0.0 through either
installation method.
Closes #2549
> (GH-2549) Clarify Bolt supported OSX versions

- pwsh_module/pwsh_bolt.psd1.erb
- pwsh_module/pwsh_bolt_internal.ps1
- (maint) Remove last of bolt pwsh function
- (maint) Update PowerShell manifest to RootModule
Acceptance Criteria:
Setup:
1. Install Bolt 3.0 on test machine
1. Clone this PR on your machine
1. Execute `be rake pwsh:generate_module` on your machine
1. Replace `$env:ProgramFiles\WindowsPowerShell\Modules\PuppetBolt\PuppetBolt.psd1` and `$env:ProgramFiles\WindowsPowerShell\Modules\PuppetBolt\PuppetBolt.psm1` on test machine with generated files from your machine
Testing:
1. Execute any bolt powershell command in a new[*] powershell shell on test machine
2. There should be no errors loading the PuppetBolt module
3. The Bolt PowerShell cmdlets should still correctly find the bolt executables
[*] A new shell is needed to have the PATH environment variable populated before executing `bolt`. …
> (maint) Bolt PowerShell module metadata cleanup

- documentation/applying_manifest_blocks.md
- documentation/bolt_types_reference.md
This adds documentation for the keys that are in an `ApplyResult` report
hash, including an example of accessing the log messages in a report.
> (GH-2463) Document ApplyResult report keys

- documentation/using_plugins.md
The default `puppet_agent::install` task goes out to the internet and downloads things. This breaks in "air gapped" environments. I thought it would be an interesting example to add to the documentation in order to showcase the `plugin-hooks` feature using existing tasks.
> Added documentation on how to configure Bolt to install Puppet agent without internet

- documentation/writing_tasks.md
This adds documentation for constraints around task parameter names and
types.
> (GH-2240) Document task parameter constraints

- documentation/bolt_installing_modules.md
- lib/bolt/cli.rb
This fixes a bug where Bolt would not install a Puppetfile with `bolt
module install --no-resolve` if the `modules` key is not configured or
is an empty array.
!bug
* **Install Puppetfile without `modules` configured**
Bolt now correctly installs a Puppetfile with `bolt module install
--no-resolve` and `Install-BoltModule -NoResolve` even if the
`modules` key is not configured or is an empty array.
> (bug) Install Puppetfile without 'modules' configured

- pwsh_module/command.tests.ps1
- pwsh_module/pwsh_bolt.psd1.erb
- pwsh_module/pwsh_bolt.psm1.erb
- pwsh_module/pwsh_bolt_internal.ps1
This removes the PowerShell cmdlets to call `bolt --version` on windows platforms. This was originally done for speed reasons, but can be removed to support cross platform use of the module since the ruby runtime will be patched to run faster on windows.
> (GH-2636) Fix PowerShell Cmdlet Version detection

- documentation/inventory_files.md
- Add more links to reference docs.
- Add a small section on `config`
- Move versioning info down in the page
> (Docs) Improve inventory file documentation

- documentation/analytics.md
- documentation/bolt.ditamap
- documentation/bolt_installing.md
- documentation/running_bolt_in_docker.md
- documentation/troubleshooting.md
This cleans up the 'Install Bolt' docs page. It adds a table to quickly
reference supported platforms and also moves install commands for Linux
distributions under separate headers for easy linking. It also breaks
out the analytics section into its own dedicated page so it's easier to
find the information. Lastly, the navigation was updated to have
"Installing Bolt" as a navigation title.
> (docs) Clean up install docs

- .gitignore
This updates the `.gitignore` file to ignore all contents in the
`modules/` directory except for built-in modules (aggregate, canary,
puppet_connect, puppetdb_fact).
> (maint) Ignore non-built-in modules

- Puppetfile
- lib/bolt/cli.rb
- rakelib/tests.rake
This commit updates the Puppetfile bolt uses during packaging steps to include
the puppet_connect module so that it isn't overwritten by r10k during builds
> (maint) Update Puppetfile to include puppet_connect module

- documentation/writing_tasks.md
- lib/bolt/shell/powershell.rb
- lib/bolt/shell/powershell/snippets.rb
This commit adds the bolt task target directory to the PSModulePath environment variable for the currently executing session. This will allow Bolt tasks to ship powershell modules that can be automatically imported during runtime instead of having to calculate relative paths.
To use this feature add any powershell module to the `files` metadata in the task.json file:
```
"files": [
"<BOLT MODULE NAME>/files/<PWSH MODULE NAME>/"
],
```
Then inside your Bolt PowerShell task start using the content from that PowerShell module without having to write `Import-Module` statements with fully qualified paths to the temp directory Bolt operates in.
> (GH-2633) Add Bolt Task directory to PSModulePath

- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
- spec/fixtures/modules/sample/tasks/sensitive_task_output.sh
Orchestrator's transport API expects unwwrapped sensitive task output,
so we unwrap the sensitive task output in bolt-server to satisfy that
invariant.
> (PE-31148) Unwrap sensitive task output in bolt-server

- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/linux.yaml
- .github/workflows/litmus_smoke.yaml
- .github/workflows/modules.yaml
- .github/workflows/pwsh.yaml
- .github/workflows/release-notes.yaml
- .github/workflows/schemas.yaml
- .github/workflows/windows.yaml
This updates the CI jobs to use the `ruby/setup-ruby` action as the
`actions/setup-ruby` action is now deprecated. The new action handles
installing and caching gems, so those steps in each job have been
removed.
> (maint) Update CI to use ruby/setup-ruby action

- lib/bolt/shell/bash.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/docker.rb
- lib/bolt/transport/docker/connection.rb
- spec/integration/transport/docker_spec.rb
This refactors the Docker transport to use the same code paths that
other transports do, in an effort to prove the viability of making
transports pluggable. The behavior of the transport should not change at
all.
The `Bolt::Transport::Docker` class now inherits from the `Simple`
transport class, and only overloads the `with_connection` function to
create a new `Bolt::Transport::Docker::Connection` instance and yield
it.
The `Bolt::Transport::Docker::Connection` class provides the functions
that the shell classes need to interact with Docker containers:
`connect`, `upload_file`, `download_file`, and `execute`. These are the 
functions we're hoping are needed for a stable API for making transports
pluggable. This update largely consists of renaming functions to match
the API, but also …
> (maint) Refactor the Docker transport to use Shell class

- spec/Dockerfile.puppetdb
- spec/docker-compose.yml
This unpins the puppetdb container in CI. Previously, the 7.x series of
the puppetdb container would immediately close due to an error raised
by a missing certfile when starting puppetdb.
> (GH-2595) Unpin PDB container in CI

- lib/bolt/result.rb
- spec/bolt/result_spec.rb
This commit updates the `to_data` method for the Result class to serialize sensitive task output by calling the `to_s` value explictly on the sensitive output.
> (PE-31142) Serialize sensitive output from task Result

- Puppetfile
This adds the `puppetlabs/powershell_task_helper` module to Bolt's
packaged modules.
!feature
* **Ship with `puppetlabs/powershell_task_helper` module**
([#2639](https://github.com/puppetlabs/bolt/issues/2639))
Bolt now ships with the `puppetlabs/powershell_task_helper` module,
which includes helpers for writing tasks in PowerShell.
> (GH-2639) Ship with powershell_task_helper

- documentation/bolt.ditamap
Future docs builds will require these metatags to be present for
search functionality.
> (Docs) Add prodname and version metadata to map

- .github/workflows/linux.yaml
- lib/bolt/pal.rb
- spec/docker-compose.yml
- spec/fixtures/apply/basic/plans/project_files.pp
- spec/fixtures/inventory/docker.yaml
- spec/integration/apply_spec.rb
- spec/integration/parallel_spec.rb
- spec/lib/bolt_spec/conn.rb
This adds support for using Puppet file syntax
(`puppet://modules/<MODULE>/<FILE>`) in an apply block for files that are
in a Bolt project.
This also removes the `puppet_5_node` Docker container from spec tests,
since Bolt no longer supports Puppet 5.
!bug
* **Support Puppet file syntax for files in a Bolt project**
([#2504](#2504))
Bolt now supports Puppet file syntax
(`puppet:///modules/<MODULE>/<FILE>`) in apply blocks for files in a
Bolt project. Previously, apply blocks would not compile if using this
syntax for files in a Bolt project.
> (GH-2504) Support Puppet file syntax for project files in apply blocks

- lib/bolt/shell/powershell/snippets.rb
This PR modifies the error printed when a target system has an execution policy of `Restricted` or `AllSigned`
When the target has a `Restricted` or `AllSigned` execution policy, it prevents running scripts and prevents pulling info from a script, resulting in an empty `ScriptBlock`. We weren't checking whether it was null or not, so the attempt blows up with a non helpful message. This changes the message to point to the root cause instead of a long stacktrace without any error information.
> Note: This is very hard to test on localhost due to the way execution policies work and how they have to be edited. Best to test using the winrm connection
> (GH-2659 Improve error messages for "bolt script run" on PowerShell

- modules/puppet_connect/plans/test_input_data.pp
- modules/puppet_connect/spec/plans/test_input_data.rb
This PR adds the following to puppet_connect::test_input_data:
* It maintains transport config parity with bolt-server
* It validates that the SSH private-key does not point to a filepath
> (PE-31182)(PE-31192) Improvements to puppet_connect::test_input_data

- rakelib/docs.rake
This fixes some broken links to built-in modules on the "Packaged
modules" docs page.
> (docs) Fix broken built-in module links

- lib/bolt/pal.rb
This fixes a bug where a plan with a Puppet strings `@param` tag that
did not include a description would cause a plan to error.
!bug
* **Handle plan parameter tags without descriptions**
([#2672](https://github.com/puppetlabs/bolt/issues/2672))
Bolt no longer errors if a plan includes a Puppet strings `@param` tag
that does not have a description.
> (GH-2672) Handle plan parameter tags without descriptions

- lib/bolt/outputter/human.rb
- lib/bolt/pal.rb
- spec/bolt/cli_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/integration/private_plan_spec.rb
- spec/integration/project_spec.rb
This adds plan descriptions to `bolt plan show` and `Get-BoltPlan`
output.
!feature
* **Show plan descriptions in plan list**
Plan descriptions now appear in `bolt plan show` and `Get-BoltPlan`
output.
> (maint) Add plan descriptions to 'bolt plan show' output

- documentation/writing_yaml_plans.md
- lib/bolt/pal/yaml_plan.rb
- lib/bolt/pal/yaml_plan/evaluator.rb
- lib/bolt/pal/yaml_plan/step.rb
- lib/bolt/pal/yaml_plan/step/command.rb
- lib/bolt/pal/yaml_plan/step/download.rb
- lib/bolt/pal/yaml_plan/step/eval.rb
- lib/bolt/pal/yaml_plan/step/message.rb
- lib/bolt/pal/yaml_plan/step/plan.rb
- lib/bolt/pal/yaml_plan/step/resources.rb
- lib/bolt/pal/yaml_plan/step/script.rb
- lib/bolt/pal/yaml_plan/step/task.rb
- lib/bolt/pal/yaml_plan/step/upload.rb
- schemas/bolt-yaml-plan.schema.json
- spec/bolt/pal/yaml_plan/evaluator_spec.rb
This adds keys to most YAML plan steps that correspond to plan function
metaparameters. For example, the script step now accepts an `env_vars`
key that corresponds to the `_env_vars` metaparameter, and allows users
to set environment variables on a target when executing the script.
This also fixes a bug where targets listed under the `targets` key in a
plan step were not being passed to the plan. Targets specified in this
manner are now passed to the plan correctly.
Lastly, this includes a refactoring of the `Bolt::PAL::YamlPlan::Step`
classes and the `Bolt::PAL::YamlPlan::Evaluator` class. The step classes
now include methods for formatting options and arguments for plan
function calls as well as an `#evaluate` method that handles evaluating
the step body and calling the step's plan …
> (GH-2629) Add top-level metaparameter keys to YAML plan steps

- lib/bolt_spec/plans/mock_executor.rb
- spec/bolt_spec/plan_spec.rb
- spec/fixtures/bolt_spec/plans/plans/yaml.yaml
This enables testing YAML plans with BoltSpec by adding a
`report_yaml_plan` method to the mock executor.
!bug
* **Test YAML plans with BoltSpec**
YAML plans can now be tested with BoltSpec.
> (maint) Test YAML plans with BoltSpec

- bolt-modules/boltlib/lib/puppet/functions/run_script.rb
- bolt-modules/boltlib/lib/puppet/functions/upload_file.rb
- bolt-modules/file/lib/puppet/functions/file/read.rb
- documentation/analytics.md
- lib/bolt/executor.rb
- lib/bolt_spec/plans/mock_executor.rb
- spec/bolt/executor_spec.rb
Collect analytics on whether absolute paths are uses as the source file for run_script, upload_file, or file::read.
!no-relase-note
> (PE-31273) Collect analytics on source files for plan actions

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
This adds support for using Puppet paths (`<MODULE NAME>/<FILE NAME>`)
in `bolt script run` and `Invoke-BoltScript`. The default behavior is to
still locate the script file using an absolute/relative path, but Bolt
will now fall back to checking if the path is a Puppet path if that
fails.
!feature
* **Support Puppet paths when running scripts from the CLI**
([#2652](https://github.com/puppetlabs/bolt/issues/2652))
You can now use Puppet paths (`<MODULE NAME>/<FILE NAME>`) to specify
the path to a script when running `bolt script run` or
`Invoke-BoltScript`.
> (GH-2652) Support Puppet paths in 'bolt script run'

- documentation/experimental_features.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/config/options.rb
- lib/bolt/config/transport/options.rb
- lib/bolt/logger.rb
- lib/bolt/shell.rb
- lib/bolt/shell/bash.rb
- lib/bolt/shell/powershell.rb
- pwsh_module/command.tests.ps1
- schemas/bolt-defaults.schema.json
- schemas/bolt-inventory.schema.json
- schemas/bolt-project.schema.json
- spec/fixtures/modules/sample/tasks/multiline.json
- spec/fixtures/modules/sample/tasks/multiline.ps1
- spec/fixtures/modules/sample/tasks/multiline.sh
- spec/integration/logging_spec.rb
This adds a new configuration option `stream` that will enable
streaming output back to the console while Bolt is executing actions on
remote targets.
Streaming works by registering a new Ruby logger named 'stream' that is
not additive (so does not send log messages to the parent logger, which
prevents messages from being logged to files or to other Bolt logging
streams). It configures the stream logger to only print to the console
without much formatting. The stream logger is only created if `stream`
is configured. Bolt then prints output to the stream logger as it's
read, in addition to sending messages to the Result object to be
returned and printed when the action is finished.
Streaming messages are prepended with the target's safe name and the 
stream (stdout or stderr) the message …
>  (GH-102) Prototype streaming remote output

- spec/integration/logging_spec.rb
- spec/lib/bolt_spec/project.rb
The Windows testing password includes characters that aren't allowed in
target uris that are looked up in the inventory file. When we use the
full target uri (including password) from the `BoltSpec::Conn` module
along with a project created by `BoltSpec::Project#with_project` which
laid down an empty inventoryfile, Bolt would try to lookup the uri in
the empty inventory and fail.
This makes two changes to address this:
- First, it modifies the failing test to use `--password` instead of
including the password in the URI.
- Second, it modifies `with_project` to only create an inventoryfile if
any inventory data is passed to the function. This will prevent Bolt
from trying to lookup targets in the inventory unnecessarily.
> (maint) Don't include password for Windows target

- documentation/templates/bolt_transports_reference.md.erb
> (Docs) remove bolt.yaml example in transports ref

- rakelib/tests.rake
- spec/integration/transport/lxd_spec.rb
This fixes a bug in the linux spec tests that was preventing any tests
from running in GitHub Actions. The issue specifically came about from
using the `:lxd` tag to mark LXD tests. Updating the tag to
`:lxd_transport` fixes the issue.
> (bug) Fix 'Linux fast' workflow to run tests

- documentation/bolt_inventory_reference.md
This fixes some incorrect links to the transports reference that are in
the inventory reference.
> (docs) Fix broken transports reference links

- lib/bolt/shell/bash.rb
- lib/bolt/shell/bash/tmpdir.rb
- spec/shared_examples/transport.rb
This updates the SSH transport to respect `run-as` configuration when
downloading files. Specifically, when using `run-as`, Bolt executes the
following steps:
- Create a temporary directory as the run-as user
- Copy the source file to the temporary directory as the run-as user
- Chown the temporary directory and its contents to the connecting user
- Download the copy of the source file as the connecting user
- Delete the temporary directory and contents
This is a workaround to a limitation in the net-ssh library, which only
allows for downloading files as the connecting user. Because Bolt users
might not be able to connect as the root user, the source file needs to
be made available to the connecting user.
Because the temporary directory / file copy are just implementations of
this …
> (GH-2679) Support run-as configuration when downloading files

- lib/bolt/shell/bash.rb
- spec/integration/apply_spec.rb
This fixes a bug with running tasks using the `stdin` input method when
using a `tty`. When the `tty` config option is set, Bolt creates a
wrapper script that executes the task and passes the task's parameters
over stdin. However, Bolt would still invoke this wrapper script on the
target and attempt to pass the parameters over stdin to the wrapper
script, even though the wrapper script already included the task
parameters. This resulted in the parameters being passed to the wrapper
script to print to stdout and be incorrectly returned as part of the
task's output.
!bug
* **Do not send task parameters over stdin when using a tty**
([#2680](https://github.com/puppetlabs/bolt/issues/2680))
Tasks with a `stdin` input method that are run on targets with `tty:
true` configuration no longer …
> (GH-2680) Do not send task parameters over stdin when using a tty

- bolt-modules/boltlib/lib/puppet/functions/run_command.rb
- bolt-modules/boltlib/lib/puppet/functions/run_script.rb
- bolt-modules/boltlib/spec/functions/run_command_spec.rb
- bolt-modules/boltlib/spec/functions/run_script_spec.rb
- lib/bolt/pal/yaml_plan/step/command.rb
- lib/bolt/pal/yaml_plan/step/script.rb
This updates the `run_command` and `run_script` plan functions to ensure
the `_env_vars` option is a hash. It also transforms any hash values in
the `env_vars` hash to JSON before calling the executor function,
ensuring that the environment variable is not a Ruby-style hash.
!bug
* **Ensure `env_vars` is a hash in commands and scripts**
([#2689](#2689))
Bolt now ensures that the `env_vars` option passed to commands and
scripts in plans is a hash and will raise a helpful error message
otherwise.
* **Convert `env_vars` hash values to JSON**
([#2689](#2689))
Bolt now converts hash values for an environment variable passed to a
command or script to JSON. Previously, a hash value would be passed
with Ruby-style syntax.
> (GH-2689) Ensure env_vars is a hash, convert values to JSON

- lib/bolt/shell/bash.rb
The use of a wrapper script for passing input to tasks over stdin avoids issues emulating a tty. The wrapper script takes care of setting the interpreter and pipeing in stdin. This commit keeps the logic to conditionally use the wrapper script grouped in a single conditional.
> (GH-2680) Keep wrapper script for tty logic grouped

- lib/bolt/pal.rb
- lib/bolt/pal/yaml_plan/transpiler.rb
- spec/integration/transpiler_spec.rb
This adds support for calling `bolt plan convert` and `Convert-BoltPlan`
with the name of a plan instead of just the path to a plan.
!feature
* **Convert YAML plans by name**
The `bolt plan convert` and `Convert-BoltPlan` commands now accept the
name of a YAML plan to convert instead of just a path to a YAML plan.
> Run 'plan convert' with plan name

- lib/bolt/outputter/human.rb
- spec/bolt/outputter/human_spec.rb
Previously, Bolt assumed that task parameters included the `type` key
when checking to see if the `type` was optional to format it for
printing in `bolt task show` output. If the task included parameters
that didn't specify a type, Bolt would stacktrace. This now only adds
the `optional` parameter formatting if the parameter has a type defined
and that type includes 'Optional', otherwise it formats the type as
required. This prevents Bolt from stacktracing.
!bug
* **Don't stacktrace when showing tasks that include untyped parameters** ([#2719](https://github.com/puppetlabs/bolt/issues/2719))
Bolt will now correctly show task details for tasks that include
parameters that do not specify a type, instead of stacktracing.
> (GH-2719) Correctly show task info if task parameters don't have a type

- Vagrantfile
- lib/bolt/config/transport/lxd.rb
- lib/bolt/config/transport/options.rb
- lib/bolt/transport/lxd/connection.rb
- rakelib/tests.rake
- schemas/bolt-defaults.schema.json
- schemas/bolt-inventory.schema.json
- spec/integration/transport/lxd_spec.rb
This adds a new 'remote' configuration option for the LXD transport that
allows users to connect to LXD remote hosts. This option accepts a
string, and prepends the remote to the expected container name. This
requires that the remote is already configured with LXC.
!feature
* **LXD transport supports remote hosts** ([#2669](https://github.com/puppetlabs/bolt/issues/2669))
The LXD transport includes a new option 'remote' to configure
connecting to remote LXD servers.
> (GH-2669) Add 'remote' configuration for LXD transport

- documentation/bolt_types_reference.md
- lib/bolt/node/output.rb
- lib/bolt/outputter/human.rb
- lib/bolt/result.rb
- lib/bolt/shell/bash.rb
- lib/bolt/shell/powershell.rb
- lib/bolt/transport/orch.rb
- lib/bolt_spec/plans/action_stubs/command_stub.rb
- lib/bolt_spec/plans/action_stubs/script_stub.rb
- spec/bolt/executor_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/bolt/result_spec.rb
- spec/bolt_spec/plan_spec.rb
- spec/integration/local_spec.rb
- spec/integration/plan_spec.rb
- spec/integration/transport/ssh_spec.rb
- spec/integration/transport/winrm_spec.rb
- spec/integration/yaml_plan_spec.rb
- spec/shared_examples/transport.rb
This updates the `bolt command|script run` commands to display
merged output from stdout and stderr on the CLI. When Bolt logs the
output from these two streams, it also adds each line to a
`merged_output` value in the order the lines are received. This
`merged_output` value is passed to the result for the command or script,
and can be accessed from both plans and the JSON output format. Lastly,
the human outputter has been updated to display the merged output by
default, resulting in output resembling what a user would see if they
ran the command or script directly on the target.
!feature
* **Display merged stdout and stderr output for commands and scripts**
([#2653](#2653))
The `bolt command|script run` commands and `Invoke-BoltCommand|Script`
cmdlets now display merged output from …
> (GH-2653) Merge stdout and stderr for commands and scripts

- documentation/modules.md
The Modules overview document listed the wrong precedence of paths on
the modulepath, stating that `<project>/.modules/` would override
`<project>/modules`. This corrects the order to state that any modules
in `<project>/modules` will be used if they have the same name as
`<project>/.modules` - basically that user-created modules will override
installed modules.
> (docs) Correct modulepath precedence documentation

- lib/bolt/outputter/human.rb
- spec/bolt/outputter/human_spec.rb
This fixes a bug that caused Bolt to error when showing info for a task
that supports running in noop mode.
!bug
* **Do not error when showing 'noop' task info**
Bolt no longer errors when printing task information for a task that
supports running in no-operation mode.
> (bug) Don't error when showing noop task info

- bolt-modules/prompt/lib/puppet/functions/prompt.rb
- bolt-modules/prompt/spec/functions/prompt_spec.rb
- lib/bolt/executor.rb
- spec/bolt/executor_spec.rb
This adds a new `default` option for the `prompt` plan function. If a
user does not provide input when prompted, and the `default` option is
set, the function will return the `default` value. The prompt message
itself will display the default value, unless the `sensitive` value is
also set.
!feature
* **Add default value for `prompt` plan function**
([#2704](https://github.com/puppetlabs/bolt/issues/2704))
The `prompt` plan function has a new `default` option which can be
used to return a default value when a user does not provide input.
> (GH-2704) Add default value for 'prompt' plan function

- lib/bolt/cli.rb
- lib/bolt/util.rb
This adds a nice welcome message when users first run the Bolt command.
The message is printed to stdout, and is only printed if the following
is true:
- The stdout stream is a tty
- The user runs `bolt`, `bolt help` or `bolt --help`. This should not
print for any other Bolt commands, such as `bolt --version` or `bolt
command --help`.
- The user has not run Bolt before. This is determined by the presence
of a file `~/.puppetlabs/etc/bolt/.first_runs_free`.
!feature
* **Add welcome message when users first run Bolt**
Bolt now prints a friendly welcome message when users first run Bolt
if they run `bolt`, `bolt --help`, or `bolt help`.
> (hack) Add welcome message when users first run Bolt

- spec/Dockerfile.puppetserver
This updates the path to the crl on the puppetserver container, which
has been updated in a recent release of puppetserver.
> (maint) Update path to crl on puppetserver container

- bolt-modules/prompt/lib/puppet/functions/prompt/menu.rb
- bolt-modules/prompt/spec/functions/prompt/menu_spec.rb
This adds a new `prompt::menu` plan function. It accepts a prompt and
list of options to choose from, and prompts the user to choose one of
the options. The function loops until a valid option is selected, or
returns an optional default value.
!feature
* **`prompt::menu` plan function**
The new `prompt::menu` plan function can be used to prompt the user to
select an option from a menu of options.
---
Blocked by #2713
> (hack) Add 'prompt::menu' plan function

- lib/bolt/transport/orch.rb
- spec/integration/transport/orch_spec.rb
Previously, we assumed that if a task returned with an `_error` key that
it would be a hash and include the `details` key, and that that
`details` key would also have a hash value. Any of these assumptions
might be wrong. This amends the Orchestrator transport to handle
`_error` values that:
* Are not a hash, by placing the provided value under the `message` key
* Is a hash that doesn't have the `details` key by setting the details
key to an empty hash
* Is a hash with a `details` key that is not itself a hash by not trying
to merge our own keys into it.
!bug
* **Handle malformed `_error` values in task results in Orchestrator**
Bolt now handles `_error` from task results in the Orchestrator
transport when the value of the key is not a hash, does not include the
`details` key, or the …
> (bug) Handle malformed `_error` values in task result in Orchestrator

- Puppetfile
This upgrades a few of Bolt's bundled modules to the latest versions.
!feature
* **Upgrade bundled modules**
The following bundled modules have been updated to their latest
versions:
- [puppet_agent 4.5.0](https://forge.puppet.com/puppetlabs/puppet_agent/4.5.0)
- [puppet_conf 1.1.0](https://forge.puppet.com/puppetlabs/puppet_conf/1.1.0)
- [reboot 4.0.2](https://forge.puppet.com/puppetlabs/reboot/4.0.2)
> (maint) Upgrade bundled modules

- documentation/testing_plans.md
- lib/bolt/executor.rb
- lib/bolt_spec/plans/mock_executor.rb
- spec/bolt_spec/plans/mock_executor_spec.rb
(GH-2692) Support 'parallelize' in BoltSpec
This adds support for testing plans that use the `parallelize()` plan
function in BoltSpec. The block passed to the function is evaluated
using each object sequentially instead of in parallel.
!feature
* **Test plans that use `parallelize()` plan function in BoltSpec**
([#2692](#2692))
Plans that use the `parallelize()` plan function can now be tested
with BoltSpec.
---
(GH-2692) Support 'run_task_with' in BoltSpec
This adds support for testing plans that use the `run_task_with()` plan
function to BoltSpec. When BoltSpec runs a plan with this function, it
will execute a separate task run for each target. Users making
assertions about tasks run with `run_task_with()` should make an
assertion about each individual target that the task runs …
> (GH-2692) Support 'run_task_with' and 'parallelize' in BoltSpec

- lib/bolt/inventory/options.rb
Setting `plugin_hooks` as a top level key in `inventory.yaml` is valid (I want to apply the same plugin hook config to every target). Previously a warning that `plugin_hooks` is an "unknown option" when set at the top level of an inventory file was raised. This commit stops that warning by allow listing the setting.
!bug
* **Do not warn on top level `plugin_hooks` config**
Bolt no longer warns that `plugin_hooks` are an unknown option when configured in inventory file.
> (bug) Do not warn valid top level inventory config

- documentation/developer_updates.md
- lib/bolt/inventory/target.rb
- spec/bolt/inventory/target_spec.rb
This updates Bolt to log a deprecation warning when it detects a target
that has facts with dotted names. This warning is logged whether a
target is loaded with a dotted fact name (either in the inventory or
with `Target.new`) or when adding facts to a target (with
`$target.add_facts`).
!deprecation
* **Deprecate dotted fact names**
([#2737](https://github.com/puppetlabs/bolt/issues/2737))
Dotted fact names (e.g. `foo.bar`) are now deprecated. Bolt issues a
deprecation warning if it detects a target is loaded with these facts
or has them added during a plan run.
--- 
---
> (GH-2737) Deprecate dotted fact names

- bolt-modules/boltlib/lib/puppet/datatypes/containerresult.rb
- bolt-modules/boltlib/lib/puppet/functions/run_container.rb
- bolt-modules/boltlib/spec/functions/run_container_spec.rb
- bolt-modules/boltlib/types/planresult.pp
- documentation/bolt_types_reference.md
- documentation/experimental_features.md
- lib/bolt/container_result.rb
- lib/bolt/error.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/logger.rb
- lib/bolt/result.rb
- lib/bolt/transport/docker/connection.rb
- lib/bolt/util.rb
- spec/fixtures/modules/container/plans/apply.pp
- spec/fixtures/modules/container/plans/init.pp
- spec/fixtures/modules/container/plans/volume.pp
- spec/integration/container_spec.rb
This POC introduces the `run_container()` plan function. The function
accepts the name of an image (optionally with a registry prepended) to
run, and a hash of options to apply when running the container. For this
POC, Docker is the only supported container engine. The function returns
a new `ContainerResult` object that contains a `value`, `status`, and
`object`. This function is supported on both *nix and Windows systems.
Currently, supported options are:
* `cmd` - A command to run in the container
* `env_vars` - A hash of environment variables to set in the container
* `ports` - A hash of ports to publish from the container to the host
* `rm` - A boolean, whether to remove the container when it exits
* `volumes` - A hash of directories on the host and their corresponding
directories in …
> (POC) run_container plan function

- developer-docs/bolt-api-servers.md
- lib/bolt/inventory/options.rb
- schemas/bolt-inventory.schema.json
When running `bolt project migrate` we don't remove the `version` key if
the value is `2`, but we still raise a warning that the `version` key
isn't recognized. This amends the inventoryfile schema to include the
`version` key so that users don't see a warning.
!bug
* **Allow 'version' key in inventory files**
Bolt now recognizes the `version` configuration in an inventoryfile
and doesn't raise a warning that the key is unknown.
> (bug) Allow 'version' key in inventory files

- documentation/testing_plans.md
This fixes a broken link to the `run_task_with` function in the 'Testing
plans' doc.
> (docs) Fix broken link in 'Testing plans'

- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/config/options.rb
- lib/bolt/executor.rb
- lib/bolt_spec/plans/mock_executor.rb
- schemas/bolt-project.schema.json
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
This introduces a new project-level configuration option `future` which
contains a hash that can enable various features that may introduce
breaking changes in Bolt. The first suboption of `future` is
`file_paths`, which will enable loading scripts from the `scripts/`
subdirectory of a module once #2731 is complete. This doesn't include a
release note, preferring a larger release note once the whole feature is
implemented.
> (GH-2730) Add future.file_paths config option

- lib/bolt/cli.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- spec/bolt/outputter/human_spec.rb
This updates the output for `bolt inventory show` and
`Get-BoltInventory` to better match the other `show` commands. Targets,
the inventory source, and the target count are now listed under
colorized headings.
This also updates the `--detail` view so that targets are listed in
alphabetical order and use each target's name as a heading for easy
reading. The target's configuration and data is also now displayed in
YAML in the human outputter, to better match the format of the inventory
file. The `--detail` view also now includes the same inventory source
and target count that are in the undetailed view.
!feature
* **Improved output for `inventory show`**
The `bolt inventory show` and `Get-BoltInventory` command now display
`human` output in the same format as other `show` commands.
> (hack) Improve 'inventory show' output

- lib/bolt/cli.rb
This fixes a bug that arises from running the `bolt module add|install`
command when a project does not have a `bolt-project.yaml` file.
Previously, Bolt would call the undefined method
`Bolt::Project.config_file`, result in a stacktrace. Since this method
was removed in Bolt 3.0, the condition that called this method has been
removed.
!bug
* **Do not stack trace when missing project configuration file**
([#2756](https://github.com/puppetlabs/bolt/issues/2756))
Bolt no longer stack traces when installing modules if the project
does not have a `bolt-project.yaml` configuration file.
> (GH-2756) Do not stack trace when missing project config file

- .github/workflows/podman.yaml
- documentation/experimental_features.md
- lib/bolt/config/options.rb
- lib/bolt/config/transport/podman.rb
- lib/bolt/executor.rb
- lib/bolt/transport/docker/connection.rb
- lib/bolt/transport/podman.rb
- lib/bolt/transport/podman/connection.rb
- lib/bolt/util.rb
- rakelib/tests.rake
- schemas/bolt-defaults.schema.json
- schemas/bolt-inventory.schema.json
- spec/bolt/config/transport/podman_spec.rb
- spec/integration/transport/podman_spec.rb
- spec/integration/validator_spec.rb
- spec/lib/bolt_spec/conn.rb
- spec/shared_examples/transport.rb
This adds a new Podman transport to connect to local running Podman
containers. This is mostly useful for testing scenarios and debugging.
The Podman transport accepts many of the same configuration options as
the Docker transport. You can see the full list of supported
configuration options [on the transport reference
page](bolt_transports_reference.md). The Podman transport doesn't
support the `service-url` configuration options as the
transport doesn't support remote connections.
!feature
* **Add Podman transport** ([#2456](https://github.com/puppetlabs/bolt/issues/2456))
The Podman transport connects to local running Podman containers,
useful for testing scenarios or debugging.
> (GH-2456) Add Podman transport

- lib/bolt/outputter/human.rb
- spec/bolt/outputter/human_spec.rb
This updates the output for `bolt plan|task show <name>` to better align
with the formatting in other `show` commands. Information is now listed
under colorized headings and parameter information is colorized and
spaced out to improve readability. This also wraps the usage string and
descriptions so each line is a maximum of 80 characters long, which
makes it easier to read long descriptions.
!feature
* **Improved plan and task information output**
The `bolt plan|task show <name>` and `Get-Bolt(Plan|Task) -Name
<name>` commands now display `human` output in a similar format to
other `show` commands.
> (hack) Improve plan and task info output

- lib/bolt/plugin.rb
- lib/bolt_server/transport_app.rb
This slightly refactors the way that plugins are loaded so that the
`add_module_plugin` method can be called explicitly even if plugin
loading is disabled. Specifically, the `add_ruby_plugin` and
`add_module_plugin` methods now longer verify that the plugin exists or
that plugin loading is enabled. Those steps are now handled exclusively by
`by_name` and `get_hook`, which are the entry points into the plugin
system.
The resulting behavior is the same as before:
1. If a plugin doesn't exist, `by_name` won't raise an error and
`get_hook` will. This allows config to be set for a non-existent
plugin as that will only call `by_name`, which will do nothing. If
the plugin is later *used*, `get_hook` will raise an error.
2. If a plugin does exist but loading is disabled, `by_name` will raise an …
> (PE-31347) Load cloud inventory plugins in bolt-server

- bolt-modules/boltlib/spec/spec_helper.rb
- bolt-modules/ctrl/spec/spec_helper.rb
- bolt-modules/dir/spec/spec_helper.rb
- bolt-modules/file/spec/spec_helper.rb
- bolt-modules/out/spec/spec_helper.rb
- bolt-modules/prompt/spec/spec_helper.rb
- bolt-modules/system/spec/spec_helper.rb
- bolt_spec_spec/spec/functions/with_datatype_spec.rb
- bolt_spec_spec/spec/spec_helper.rb
- modules/aggregate/spec/spec_helper.rb
- modules/canary/spec/spec_helper.rb
- modules/puppet_connect/spec/spec_helper.rb
- modules/puppetdb_fact/spec/spec_helper.rb
The `puppetlabs_spec_helper` ruby library we use as part of testing
embedded Bolt modules was raising a deprecation warning that the default
mocking framework was `mocha` but that to silence the warning the tests
themselves should specify which framework was being used. While I'd
honestly love to switch to `rspec` it's a lot of work to do so for
relatively little gain. For now setting the configuration to `mocha` to
silence the warning is easiest.
> (maint) Address puppetlabs_spec_helper deprecation warning

- documentation/analytics.md
- lib/bolt/analytics.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/config/options.rb
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
- spec/bolt/analytics_spec.rb
- spec/bolt/config_spec.rb
This adds a new configuration option called `analytics` that disables
data collection in Bolt when set to `false`. The option is supported in
both `bolt-defaults.yaml` and `bolt-project.yaml`. If this option is set
to `false`, it cannot be overriden in another configuration file. For
example, setting `analytics: true` in `bolt-project.yaml` will not
enable data collection if `analytics: false` is set in
`bolt-defaults.yaml`.
!feature
* **Disable analytics in system, user, and project config files**
([#2759](https://github.com/puppetlabs/bolt/issues/2759))
The new `analytics` configuration option can be used to disable data
collection in Bolt and is supported in both `bolt-defaults.yaml` and
`bolt-project.yaml`. Disabling data collection cannot be overridden by
enabling it in another …
> (GH-2759) Add 'analytics' config option to disable analytics

- lib/bolt/shell/bash.rb
- spec/integration/local_spec.rb
- spec/integration/logging_spec.rb
In the Bash shell class we collect messages from stdout and stderr in a
few places: when using `run-as` after checking for a prompt, during the
read-loop as the command is executing, and then reading anything that's
unread after the thread exits. When we added streaming and merged_output
features we did this for the main read-loop, but not for the initial
sudo-prompt check or the cleanup loop that executes once the thread has
finished. This resulted in some scripts and commands not having their
results printed since we now print merged_output, which was missing
messages from the final stream reading.
Now, any messages read during the initial sudo-prompt check or once the
thread has finished will be read and logged to the stream output and
saved to `merged_output` so that it can be …
> (bugfix) Ensure all messages are streamed and saved to merged_output

- lib/bolt/pal/yaml_plan/step.rb
- spec/bolt/pal/yaml_plan/step_spec.rb
This fixes a bug that was causing YAML plan plan and task steps that
specified a metaparameter under the `parameters` key to error. The
correct behavior for Bolt is to only error when the metaparameter is
present as both a top-level key _and_ under the `parameters` key. For
example, specifying the `catch_errors` key and the
`parameters._catch_errors` key.
!bug
* **Do not error when using metaparameters in YAML plans**
([#2777](https://github.com/puppetlabs/bolt/issues/2777))
Bolt no longer errors for YAML plans that include a plan or task step
that includes an additional option (e.g. `_catch_errors`) under the
`parameters` key.
> (GH-2777) Do not error when using metaparameters in YAML plans

- guides/targets.txt
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- spec/bolt/cli_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/bolt/outputter/json_spec.rb
(GH-2747) Default to showing all targets with 'inventory show'
This updates the `bolt inventory show` and `Get-BoltInventory` commands
to display the 'all' group if a targetting option is not provided to the
command. Additionally, the human outputter now displays additional
information to the user, indicating that they can view specific targets
using a targetting option or view target config and data with
`--detail`, assuming the options are not provided by the user.
!feature
* **Default to showing all targets with `bolt inventory show`**
([#2747](#2747))
The `bolt inventory show` and `Get-BoltInventory` commands now default
ot showing all targets in the inventory if a targetting option
(`--targets`, `--query`, `--rerun`) are not provided.
---
(GH-2747) Show required options in help text …
> (GH-2747) Default to showing all targets with 'inventory show'

- lib/bolt/plan_creator.rb
- spec/bolt/plan_creator_spec.rb
This updates the error message when `bolt plan new` is run and receives
an invalid plan name to clarify that plan names include the project or
module that the plan is loaded from, so that users understand that plan
names must always include the module namespace in other contexts of Bolt
(for example `plan run` or `plan show`).
> (GH-2757) Update error message when 'plan new' receives incomplete name

- lib/bolt/cli.rb
- lib/bolt/inventory.rb
- lib/bolt/inventory/inventory.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- spec/bolt/cli_spec.rb
- spec/bolt/inventory_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/bolt/outputter/json_spec.rb
- spec/integration/inventory_spec.rb
This updates the output for the `bolt group show` / `Get-BoltGroup`
commands to better align with other `show` commands. The command now
lists information under colorized headers and also lists the source of
the inventory file if one was loaded.
!feature
* **Improved group information output**
The `bolt group show` and `Get-BoltGroup` commands now display `human`
output in a similar format to other `show` commands. The `json` output
now includes the path to the inventory file that the groups are loaded
from.
> (hack) Improve 'group show' output

- bolt-modules/boltlib/lib/puppet/functions/puppetdb_command.rb
- bolt-modules/boltlib/spec/functions/puppetdb_command_spec.rb
- lib/bolt/puppetdb/client.rb
- spec/integration/puppetdb_spec.rb
This adds a new `puppetdb_command` plan function which can be used to
invoke commands in PuppetDB. The function accepts three parameters: the
command, the command version, and the payload. Bolt uses these values to
build a POST request to the command v1 endpoint for PuppetDB. If the
request is successful, the command returns the UUID for the command
invocation, which can be used to reference the command in logs.
Currently, this function only supports and tests the `replace_facts`
command, though other commands might still work.
!feature
* **`puppetdb_command` plan function**
([#2771](https://github.com/puppetlabs/bolt/issues/2771))
The `puppetdb_command` plan function can be used to invoke commands in
PuppetDB. Currently, only the `replace_facts` command is officially
tested and …
> (GH-2771) Add puppetdb_command plan function

- documentation/experimental_features.md
- documentation/running_bolt_commands.md
- lib/bolt/bolt_option_parser.rb
- spec/integration/puppetdb_spec.rb
This adds documentation and updates Bolt's help text to suggest using
`--no-verbose` with `--stream` to prevent Bolt from printing output from
a target twice.
> (GH-2772) Document using --no-verbose with --stream

- lib/bolt/transport/ssh/connection.rb
This replaces the use of the deprecated `Win32API` gem in SSH
connections on Windows with the use of `fiddle` instead.
---
Testing this PR requires running Bolt on a Windows machine and connecting to a target with the SSH transport.
**On main branch**
- Confirm that connecting to a target using the SSH transport results in the following warning:
```
C:/Users/Administrator/bolt/lib/bolt/transport/ssh/connection.rb:118: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
```
**On feature branch**
- Connect to a target using the SSH transport while Pageant is not running. Check the debug logs to confirm that `use_agent = false` is passed to net-ssh.
- Install PuTTY and then start the Pageant process (you should see an icon of a computer with a hat …
> (GH-2740) Use fiddle instead of Win32API

- lib/bolt/module_installer/specs/git_spec.rb
- spec/bolt/module_installer/specs/git_spec_spec.rb
- spec/integration/module_installer_spec.rb
When specifying modules to install, when a user provides a git module if
the module cannot be retrieved we raise an error. Previously the error
simply stated that the provided repo was invalid, without specifying
that private repositories cannot have their dependencies resolved and
must follow a documented workflow. This updates the error message to
state that the repo is either not a Git repo or is private, and link to
documentation describing how to install modules that include a private
Git repo without installing dependencies.
> (GH-2785) Improve error message when provided git repo isn't available

- lib/bolt/transport/docker/connection.rb
- spec/integration/transport/docker_spec.rb
Currently, Docker connections only succeed when the 12 character
"short ID" of a container is used. When a full container ID is
provided, connections fail despite the container being present
and running. This is because the Docker transport searches for the
container ID in the output of `docker ps` and `docker ps` only returns
short ID values unless the `--no-trunc` flag is used.
This commit updates the connection logic to pass the `--no-trunc` flag
and match container IDs using `start_with?` instead of an equality
check.
Fixes puppetlabs/bolt#2791.
> Allow Docker to connect with long IDs

- lib/bolt/outputter/human.rb
Fixed the 'Additional Information' section of the help text for the Get-BoltTask cmdlet having an incorrect parameter for the task name
Fixes #2795
> Fixed Get-BoltTask 'Additional Information' param

- documentation/bolt_installing_modules.md
- documentation/hiera.md
Adding "private git repositories" might help users find this doc a
little easier.
Also fixes a broken link
> (Docs) Add references to private git repos

- guides/guide.txt
- guides/links.txt
- guides/targets.txt
- guides/transports.txt
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- rakelib/docs.rake
- rakelib/pwsh.rake
- spec/bolt/cli_spec.rb
This adds relevant links and recommendations to run 'bolt guide' to
several Bolt help text outputs in an effort to help Bolt users find
relevant documentation more quickly, and on the CLI if they can.
> (GH-2721) Add links and prompts to run 'guide' to Bolt help text

- Puppetfile
This updates the following bundled Puppet modules:
- `puppetlabs-stdlib` from 7.0.0 to 7.0.1:
- This just [fixes typo in validate_ipv6_address function](https://github.com/puppetlabs/puppetlabs-stdlib/blob/main/CHANGELOG.md#v701-2021-04-03)
- `puppetlabs-selinux_core` from 1.0.4 to 1.1.0:
- [This change results in a substantial performance increase when checking current resource state, on the order of 50% or more.](https://github.com/puppetlabs/puppetlabs-selinux_core/blob/main/CHANGELOG.md#110-2021-03-31)
- `puppetlabs-puppet_agent` from 4.5.0 to 4.6.1:
- Remove puppet5 collection from the puppet_agent install task
- Fix SLES 11 PE upgrades and improve GPG key check
- Add Fedora 32 support
- Add exclude parameter to facts_diff task
- New task to remove local filebucket
!removal
* …
> (maint) Update bundled Puppet modules

- documentation/hiera.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- lib/bolt/pal.rb
- lib/bolt/result.rb
- pwsh_module/command.tests.ps1
- rakelib/pwsh.rake
- spec/bolt/cli_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/fixtures/hiera/bolt-project.yaml
- spec/fixtures/hiera/data/nodes/puppet_7_node.yaml
- spec/fixtures/hiera/data/os/Ubuntu.yaml
- spec/fixtures/hiera/data/var.yaml
- spec/fixtures/hiera/hiera_interpolations.yaml
- spec/integration/lookup_spec.rb
This adds a new `lookup` command to Bolt that looks up values with
Hiera. The command first runs `apply_prep` on each target to install the
puppet-agent package and collect facts, then sets up Hiera and looks for
the specified key in the hierarchy. The command requires a targeting
option, and the Hiera lookup is performed in the context of each target
passed to the command, allowing for interpolations using facts.
!feature
* **`lookup` command to look up values with Hiera**
([#2499](https://github.com/puppetlabs/bolt/issues/2499))
The new `bolt lookup` and `Invoke-BoltLookup` commands can be used to
look up values with Hiera.
> (GH-2499) Add 'lookup' command

- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- bolt-modules/boltlib/spec/functions/apply_prep_spec.rb
- spec/fixtures/apply/prep/plans/run_as.pp
- spec/integration/apply_spec.rb
Previously, Bolt would not pass the `_run_as` option through to the
executor when the option was supplied to `apply_prep()`. The `run_as`
configuration would get successfully picked up through other methods,
like passing on the CLI or inventory, or included in the
`puppet_library` plugin configuration. This merges any supported options
passed to `apply_prep` with options passed to the `puppet_library`
plugin hook, giving the plan function configuration precedence. For now
the only supported metaparameter is `_run_as` since that is the only
option supported by the `puppet_library` plugin.
!bug
* **Support _run_as passed to apply_prep()**
Bolt now respects the `_run_as` metaparameter when passed to the
`apply_prep()` plan function. This is the only supported metaparameter,
and takes highest …
> (bug-fix) Support passing '_run_as' to 'apply_prep' plan function

- documentation/troubleshooting.md
- lib/bolt/config/transport/options.rb
- schemas/bolt-defaults.schema.json
- schemas/bolt-inventory.schema.json
This adds a note to the Transport configuration reference page and the
Troubleshooting page that providing an encrypted private SSH key with
`key-data` will not work, and includes instructions on the
Troubleshooting page with how to decrypt the key.
> (GH-2794) Document encrypted keys with 'key-data' issue

- lib/bolt/logger.rb
```
lib/bolt/logger.rb:206: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```
This line was invoking a method by passing a hash and expecting it to be
implicitly interpreted as the the **kwargs argument. This behavior is
deprecated and the hash needs to be explicitly passed as **kwargs.
> (maint) Fix keyword parameters warning in logger

- spec/Dockerfile.puppetdb
This pins the puppetdb container used in spec tests to 7.2.0, as 7.3.1
introduced changes that are causing connection errors.
> (maint) Pin puppetdb container to 7.2.0

- bolt-modules/file/lib/puppet/functions/file/exists.rb
- bolt-modules/file/lib/puppet/functions/file/read.rb
- bolt-modules/file/lib/puppet/functions/file/readable.rb
This fixes a bug where the `file::exists`, `file::read`, and
`file::readable` plan functions would error outside of an apply block if
the `future` configuration was not set.
!bug
* **Do not error in `file::*` plan functions when `future` is not
configured**
The `file::exists`, `file::read`, and `file::readable` plan functions
no longer error when invoked outside of an apply block when `future`
is not configured.
> (bug) Do not error in `file::*` functions when future not configured

- lib/bolt/config/options.rb
- lib/bolt/module_installer/specs.rb
- schemas/bolt-project.schema.json
This updates the link to the documentation for module specs in the
project configuration file. Previously, if a project included an invalid
spec, the raised error message would direct the user to the 'Modules
overview' page. Now, the message directs the user to the docs that
explicitly define valid specs.
> (GH-2820) Update link to module spec documentation

- lib/bolt/bolt_option_parser.rb
When provided a filter that includes characters that aren't allowed in
task or plan names, Bolt raises an error stating that the provided
filter includes characters that cannot be used in task or plan names.
This updates the message to include a list of valid characters in the
message so that users can better understand why the error was raised.
> (maint) Update illegal characters message to list legal characters

- documentation/bolt_installing.md
- documentation/templates/bolt_cmdlet_reference.md.erb
- rakelib/pwsh.rake
This documents installing the PuppetBolt PowerShell module through the
PowerShell Gallery, as the module no longer ships with Bolt.
!feature
* **Ship PuppetBolt PowerShell module to PowerShell Gallery**
([#2550](https://github.com/puppetlabs/bolt/issues/2550))
The PuppetBolt PowerShell module is now shipped to the [PowerShell
Gallery](https://www.powershellgallery.com/packages/PuppetBolt) and is
no longer included in Windows packages. For more information about
installing the PuppetBolt PowerShell module, see the
[documentation](bolt_installing.md#puppetbolt-powershell-module).
> (GH-2550) Document installing PuppetBolt PowerShell module

- lib/bolt/transport/docker/connection.rb
We use `service-url` in `inventory.yaml` to specify an alternate Docker server address. For example:
```
config:
transport: docker
docker:
host: containername
service-url: unix:///var/run/docker2.sock
```
This transport configuration has worked in the past with versions of Bolt 2. When we recently upgraded to Bolt 3, we found that the same configuration fails with a connection error. The error incorrectly refers to the default Docker socket, `/var/run/docker.sock`, instead of the Docker server specified by the inventory.
```
Started on containername...
Failed on containername:
The command failed with exit code 1
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Failed on 1 target: containername
Ran on 1 target in 0.3 sec
```
The `command …
> Set `DOCKER_HOST` in the args to `popen3()` instead of using `--env`

- lib/bolt/applicator.rb
- spec/integration/apply_spec.rb
- spec/lib/bolt_spec/integration.rb
- spec/lib/bolt_spec/project.rb
This updates the applicator to use the name of a module as the name of
the directory that plugin files are saved in when building the plugin
tarball. Previously, the applicator would use name of the module
directory as name of the directory that plugin files were saved to. This
caused issues when referencing a file in a project that had a configured
name that is different than the project directory's name.
For example, in a project named `foo` that uses a `Boltdir`, a file
might be located at `foo/Boltdir/files/somefile.txt`. When building the
plugin tarball, the applicator would set the path of this file to
`Boltdir/files/somefile.txt` instead of the correct path
`foo/files/somefile.txt`. This would cause any plan that referenced that
file using the correct syntax …
> (GH-2832) Use module name for plugin tar directory

- .github/workflows/schemas.yaml
- lib/bolt/config/transport/docker.rb
- lib/bolt/config/transport/lxd.rb
- lib/bolt/config/transport/podman.rb
- lib/bolt/transport/docker/connection.rb
- lib/bolt/transport/lxd/connection.rb
- lib/bolt/transport/podman/connection.rb
- schemas/bolt-defaults.schema.json
- schemas/bolt-inventory.schema.json
- spec/bolt/cli_spec.rb
- spec/integration/transport/docker_spec.rb
- spec/integration/transport/lxd_spec.rb
- spec/integration/transport/podman_spec.rb
This adds support for using `run-as` and associated configuration
options to the Docker, Podman, and LXD transports when running on *nix
systems. Originally, 'run-as' was not supported for the Docker transport
because it could be running on either Windows or *nix, and run-as is not
supported when running on Windows systems. At the time it seemed
confusing for the option to only be supported sometimes, but now that
this is the case for the SSH transport when using the PowerShell
`login-shell` there's more of a precedent for users understanding when
it is and isn't supported. This was intended to be
addressed after the great [shell-transport split of 2020](https://github.com/puppetlabs/bolt/pull/1702),
and just fell through the cracks.
In addition to adding support for `run-as` to Docker …
> (GH-2806) Support run_as for container transports using Bash

- documentation/inventory_files.md
- guides/inventory.txt
This adds documentation describing how inventory is loaded and how it
might lead to different target configuration than expected. It also
includes examples for switching between default transports.
> (GH-2816) Document how inventory is loaded

- lib/bolt/applicator.rb
This fixes a bug in `Bolt::Applicator.build_plugin_tarball` that was
causing Bolt to stacktrace when running an apply block on a Windows
controller. When Bolt builds the tar ball, it joins the module's name
with the path to the module file relative to the module directory (i.e.
`my_module` + `files/some_file.txt`). To get the relative path to the
module file, Bolt calls the Ruby function `Pathname.relative_path_from`.
Previously, the string representation of the file's full path was passed
to this function, which then errored as it called `Pathname.cleanpath`
internally, which is not valid for string objects. Bolt now passes a
`Pathname` object to this function, fixing the stacktrace issue.
> (bug) Use Pathname object when building plugin tar ball path

- documentation/writing_tasks.md
I'm not sure why this is causing an issue in my new build, but I'm
getting a weird java error unless I turn the single quotes around
'someone' to `someone`. It's super weird and I'm going to do some more
testing, but this seems to make the build happy.
> (Docs) Small docs fix

- modules/puppet_connect/plans/test_input_data.pp
This way, users don't have to go back to the Puppet Connect test
workflow docs to remember how to correctly trigger the
puppet_connect::test_input_data plan.
> (PE-31290) Include triggering command in test_input_data description

- lib/bolt_spec/run.rb
- spec/bolt_spec/run_spec.rb
- spec/fixtures/modules/sample/plans/download_file.pp
Ran into a case where using BoltSpec::Run.run_plan with a plan
containing a download_file() call would fail here:
https://github.com/puppetlabs/bolt/blob/3.9.0/bolt-modules/boltlib/lib/puppet/functions/download_file.rb#L99
because Puppet.lookup(:bolt_project) would otherwise be null at this
point.
Providing the config.project to the Bolt::PAL instance created by
BoltSpec::Run::Runner#pal fixes this.
> (bug) Provide project for BoltSpec::Run::Runner#pal

- lib/bolt_spec/plans/mock_executor.rb
THis commit updates the mock executor to match the fiber executor when persisting current plan scope.
> (maint) Standardize persisting scope for current plan

- lib/bolt_server/request_error.rb
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
When asking for information about plans/tasks in bolt-server `environment` is required. Previously an unstructured string response which does not match other serialized error objects was returned. This commit updates that error to conform to the expected structure.
> (PE-31709) Structured errors for missing environment

- bolt-modules/boltlib/lib/puppet/functions/run_task.rb
- bolt-modules/boltlib/lib/puppet/functions/run_task_with.rb
- documentation/analytics.md
- lib/bolt/executor.rb
- lib/bolt_spec/plans/mock_executor.rb
- spec/bolt/cli_spec.rb
This adds a new analytics event that reports whether or not a task is
run in no-operation mode.
!feature
* **Report whether tasks are run in no-operation mode**
([#2840](https://github.com/puppetlabs/bolt/issues/2840))
Bolt now reports whether or not a task is run in no-operation mode
when it collects analytics.
> (GH-2840) Report whether tasks are run in noop mode

- lib/bolt/fiber_executor.rb
- lib/bolt_spec/plans/mock_executor.rb
- spec/fixtures/parallel/background/plans/variables.pp
- spec/integration/parallel_spec.rb
When creating a new Future block, Bolt must copy any variables that
should be in scope for the block into a new scope for the block, so that
if variables redefined inside the block they don't affect other blocks
running in parallel. Gathering variables in scope uses the
`Puppet::Parser::Scope#to_hash` method, which accepts 2 positional
parameters:
- The first parameter tells the function whether to recursively get
variables from parent (aka enclosing) scopes. This defaults to true
and we want it to be true.
- The second parameter tells the function whether to include variables
set to 'undef', which defaults to false and which we want to be true.
Previously we had not enabled including undef variables in the new
scope, which resulted in defined variables not being passed to the new
block …
> (GH-2866) Include undef variables in parallelize blocks

- lib/bolt/config/transport/docker.rb
- lib/bolt/config/transport/podman.rb
- spec/bolt/cli_spec.rb
- spec/integration/transport/podman_spec.rb
This fixes a bug introduced by #2806 that causes Bolt to error on a
Windows controller whenever the `--run-as` command-line option is used.
Previously, the `docker` and `podman` transport config classes included
validation that would raise an error whenever the `run-as` option was
set for the transport and the controller was running Windows. Because
Bolt automatically sets the `run-as` configuration for all transports
that support it when using the `--run-as` command-line option, this
resulted in any command using that option to raise this error, even if
there weren't any targets using that transport.
This removes the relevant validation in the transport config classes.
This will not result in any errors when running on targets using these
transports, as Bolt automatically sets the …
> (bug) Do not error when using `--run-as` on Windows controller

- developer-docs/bolt-server/api.md
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
- spec/fixtures/bolt_server/projects/bolt_server_test_project/modules/plugin_module/lib/puppet/functions/some_function.rb
- spec/fixtures/bolt_server/projects/bolt_server_test_project/modules/pluginfacts_module/facts.d/external_fact.sh
This returns the base64 encoded tar archive of plugin code that is needed to
calculate custom facts.
> (PT-317) Add project_facts_plugin_tarball endpoint to bolt-server

- .github/workflows/publish-powershell-module.yaml
- pwsh_module/pwsh_bolt.psm1.erb
This adds a warning to the PuppetBolt module that the module will no
longer ship with Bolt packages in a future Bolt release. It also
provides information for installing the module through PowerShell
Gallery. The warning is only displayed the first time the module is
used, after which a 'first run' file is created in the module to
indicate that the message should not be printed.
This also adds an environment variable to the module publishing workflow
to not add this warning to the module that is published to PowerShell
Gallery.
!deprecation
* **PuppetBolt PowerShell module will not ship with Bolt packages in a
future release**
([#2550](https://github.com/puppetlabs/bolt/issues/2550))
The PuppetBolt PowerShell module will no longer ship with Bolt
packages on Windows in a future release. …
> (GH-2550) Add deprecation warning to PuppetBolt module import

- guides/debugging.txt
This adds a new guide shown as part of `bolt guide` output that includes
tips on debugging common Bolt issues, including looking in
`bolt-debug.log` and `bolt * show` commands that are useful for
identifying common issues.
!feature
* **New Bolt debugging guide**
Bolt has a new guide with common debugging tips that can be accessed
by running `bolt guide debugging`.
> (hack) Add debugging guide

- lib/bolt_spec/plans/mock_executor.rb
This removes the `timeout` argument from
`BoltSpec::Plans::MockExecutor#wait`'s method signature so it matches
the same method signature on `Bolt::Executor`, which sets `timeout` as a
keyword argument.
!bug
* **Test plans that use `parallelize()` plan function in BoltSpec**
BoltSpec no longer fails when testing plans that include the
`parallelize()` plan function. Previously, testing plans that used
this function would cause the plan to fail with an argument mismatch
error.
> (bug) Fix `BoltSpec::Plans::MockExecutor#wait` method signature

- documentation/running_bolt_commands.md
- pwsh_module/command.tests.ps1
- rakelib/pwsh.rake
This fixes a bug in the PuppetBolt PowerShell module that was preventing
multiple arguments from being passed to the `-Arguments` parameter. This
updates the parameter's `ValueFromRemainingArguments` parameter to
`true`, so any arguments not bound to another parameter are passed to
`-Arguments`. This supports the following cmdlet invocations:
- `Invoke-BoltScript -Script script.sh -Arguments foo,bar -Targets all`
- `Invoke-BoltScript -Script script.sh foo bar -Targets all`
!bug
* **Pass remaining arguments to PowerShell `-Arguments` parameter**
([#2788](https://github.com/puppetlabs/bolt/issues/2788))
The PuppetBolt PowerShell module now correctly supports passing
multiple arguments to the `-Arguments` parameter. Previously, any
unbound arguments were not passed to this parameter, causing …
> (GH-2788) Pass multiple arguments to PowerShell `-Arguments` parameter

- documentation/getting_started_with_bolt.md
This fixes a typo in the Getting Started Guide.
> (docs) Fix Typo Getting Started Guide

- lib/bolt/module_installer/installer.rb
- spec/bolt/cli_spec.rb
Starting in r10k 3.9.1, the `R10K::Action::Puppetfile::Install` class
requires a third parameter. Previously, this third parameter was
optional and Bolt did not pass it, which caused tests to start failing
once it was required.
> (maint) Pass required param to r10k Puppetfile installer

- lib/bolt/bolt_option_parser.rb
This can be merged under Puppet's Trivial patch exemption policy.
!bug
* Fixes typo in Bolt script command helpdoc (`scrips` -> `scripts`)
> Fixes typo in script help doc

- documentation/bolt_installing.md
This adds documentation for installing Bolt on macOS 11.
!feature
* **macOS 11 packages**
([#2855](https://github.com/puppetlabs/bolt/issues/2855))
Bolt now ships packages for macOS 11 (Big Sur).
> (GH-2855) Document installing Bolt for macOS 11

- lib/bolt/outputter/human.rb
- spec/bolt/outputter/human_spec.rb
This resolves a bug where previously, Bolt raised a stack trace when merged_output is nil due to the command or script having raised an error.
!bug
* Bolt no longer raises stack trace with plan error (#2863)
> (GH-2863) Stacktrace when plan throws error

- spec/bolt/outputter/human_spec.rb
This escapes the "[--noop]" string when matching output in a test for
`bolt task show`. Previously, the string was unescaped and resulted in
Ruby printing a warning.
> (maint) Escape "[--noop]" in outputter test

- Puppetfile
This bumps the `puppet_agent` module to 4.8.0.
!feature
* **Support macOS 11 in `puppet_agent::install task**
The `puppet_agent::install` task now supports installing the
puppet-agent package on macOS 11.
> (maint) Bump puppet_agent module to 4.8.0

- lib/bolt/outputter/human.rb
- spec/bolt/outputter/human_spec.rb
This updates the human output for the `bolt guide` command to use a
similar format to the `show` commands.
> (GH-2886) Update `bolt guide` human output

- lib/bolt/applicator.rb
- spec/fixtures/apply/basic/manifests/exported_resources.pp
- spec/fixtures/apply/basic/plans/exported_resources.pp
- spec/integration/apply_spec.rb
This adds an ID to 'exported resources' warnings that come from Puppet
when applying a manifest that creates an exported resource or collects
exported resources. This allows these warnings to be disabled by listing
the ID under the `disable-warnings` config option.
!feature
* **Disable 'exported resources' warnings from Puppet**
([#2889](https://github.com/puppetlabs/bolt/issues/2889))
Warnings logged by Puppet when declaring or collecting exported
resources in a manifest can now be disabled. To disable these warnings
add the `exported_resources` ID under the `disable-warnings`
configuration option.
> (GH-2873) Disable 'exported resources' warning from Puppet

- lib/bolt_server/schemas/connect-data.json
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
At one time, this endpoint used a GET request and therefore expected
versioned_project as a query param. It was later changed to a POST
request with puppet_connect_data included in the request body, but the
versioned_project query param remained. For consistency, we now expect
both pieces of data to be supplied in the request body.
> (PE-32176) Use versioned_project from body for /project_inventory_targets

- acceptance/lib/acceptance/bolt_command_helper.rb
- acceptance/setup/common/pre-suite/032_configure_windows_profile.rb
Starting with Bolt 3.0, we no longer include the `bolt` function in the
PuppetBolt PowerShell module and instead shipped with a batch file for
Windows packages that would run the Bolt executable. When this change
was made acceptance tests were broken as the `PATH` did not include the
path to Bolt's `bin/` directory and the test would error with a "bolt is
not a recognized command" message.
During the beaker setup process (specifically step 032), beaker
updates the `PATH` to include Bolt's `bin/` directory. Previously, the
script responsible for this used the `Join-Path` cmdlet with multiple
positional arguments, which is not supported in PowerShell < 6.0,
resulting in the `PATH` not getting updated. Updating this line to not
error correctly sets the `PATH` for the step that sets it, but …
> (maint) Fix broken Windows acceptance tests

- documentation/bolt_installing.md
This adds documentation for installing Bolt on Fedora 34.
!feature
* **Fedora 34 packages**
([#2903](https://github.com/puppetlabs/bolt/issues/2903))
Bolt now ships packages for Fedora 34.
---
> (GH-2903) Document installing Bolt for Fedora 34

- bolt-modules/out/lib/puppet/functions/out/verbose.rb
- bolt-modules/out/spec/functions/out/verbose_spec.rb
- documentation/boltspec_reference.md
- documentation/logs.md
- documentation/testing_plans.md
- lib/bolt/cli.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- lib/bolt_spec/bolt_context.rb
- lib/bolt_spec/plans/mock_executor.rb
- lib/bolt_spec/plans/publish_stub.rb
- spec/bolt_spec/plan_spec.rb
- spec/fixtures/bolt_spec/plans/plans/out_verbose.pp
- spec/fixtures/modules/output/plans/verbose.pp
- spec/integration/plan_spec.rb
Add `out::verbose` to Bolt, which allows for similar functionality as `out::message`, but only prints when run with `--verbose` flag. We also update relevant documentation and testing. This also adds `allow_out_verbose` and `expect_out_verbose` to BoltSpec.
!feature
* **Add `out::verbose` plan function** ([#2879](#2879))
Bolt now has `out::verbose` plan function, which allows for printing output when run in verbose mode.
> (GH-2879) Add out::verbose Puppet plan function

- lib/bolt_server/schemas/partials/target-ssh.json
- lib/bolt_server/schemas/partials/target-winrm.json
- lib/bolt_server/transport_app.rb
This adds the plugin_hooks key to the SSH and WinRM target schemas,
allowing it to be passed to the API. This will let the key be used
internally within orchestrator without worrying about whether it gets
passed to bolt-server.
This key, along with the existing special 'hostname' and
'private-key-content' keys, will automatically be ignored by Bolt's
transport config handling. However, for clarity we now explicitly filter
the options we pass to the config to include only those that are
accepted by the transport. While not strictly necessary, this makes it
more obvious why those keys don't cause a problem and it provides an
extra layer of certainty in case the underlying implementation shifts in
the future.
> (PE-32485) Allow plugin_hooks to be passed to bolt-server actions

- developer-docs/bolt-server/api.md
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
- spec/fixtures/bolt_server/projects/bolt_server_test_project/modules/plugin_module/types/some_alias.pp
This endpoint returns a tarball of _all_ plugin code for a project. It
might be worth reconciling project_facts_plugin_tarball and
project_plugin_tarball into a single endpoint in the future, but this is
good enough for now.
> (PE-32490) Add project_plugin_tarball endpoint

- documentation/writing_yaml_plans.md
- lib/bolt/pal/yaml_plan/step.rb
- lib/bolt/pal/yaml_plan/step/verbose.rb
- schemas/bolt-yaml-plan.schema.json
- spec/bolt/pal/yaml_plan/evaluator_spec.rb
- spec/bolt/pal/yaml_plan/step_spec.rb
- spec/fixtures/modules/yaml/plans/verbose.yaml
- spec/integration/plan_spec.rb
- spec/integration/yaml_plan_spec.rb
- spec/lib/bolt_spec/integration.rb
This adds a YAML plan verbose step that prints a message when run in verbose mode.
!feature
* **YAML plan verbose step**
([#2926](https://github.com/puppetlabs/bolt/issues/2926))
YAML plans now support a verbose step that prints a message when run in verbose mode.
> (GH-2926) Add YAML plan verbose step

- bolt-modules/boltlib/lib/puppet/functions/background.rb
- bolt-modules/boltlib/lib/puppet/functions/parallelize.rb
- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
- bolt-modules/boltlib/lib/puppet/functions/wait.rb
- bolt-modules/boltlib/spec/functions/background_spec.rb
- bolt-modules/boltlib/spec/functions/parallelize_spec.rb
- bolt-modules/boltlib/spec/functions/wait_spec.rb
- documentation/experimental_features.md
- lib/bolt/executor.rb
- lib/bolt/fiber_executor.rb
- lib/bolt/pal.rb
- lib/bolt/plan_future.rb
- lib/bolt_spec/plans/mock_executor.rb
- spec/bolt/cli_spec.rb
- spec/bolt/fiber_executor_spec.rb
- spec/bolt/plan_future_spec.rb
- spec/fixtures/parallel/wait/plans/no_future/basic.pp
- spec/fixtures/parallel/wait/plans/no_future/infinite_loop.pp
- spec/fixtures/parallel/wait/plans/no_future/inner_bg.pp
- spec/fixtures/parallel/wait/plans/no_future/multiple_calls.pp
- spec/fixtures/parallel/wait/plans/no_future/subplan.pp
- spec/integration/parallel_spec.rb
- spec/integration/private_plan_spec.rb
This amends the `wait()` plan function to wait on all the Futures that
were spawned from the same plan as the `wait()` call if the function is
not provided a list of futures. The function still accepts a `timeout`
or `options` parameter if it is not passed any futures. To support this,
Bolt's `PlanFuture` object now has a `plan_id` attribute, which
determines which **invocation** of a plan the Future was created from
(since the same plan can be invoked multiple times in parallel). When
`wait()` is called without Futures, it selects the Futures from the
FiberExecutor with a matching `plan_id` to itself, and waits on those.
This also removes a flaky test around whether the cache file is updated
when plans in modules are modified. The test doesn't seem to be failing
legitimately based on …
> (GH-2877) `wait()` with no arguments waits on all Futures from the plan

- bolt-modules/out/lib/puppet/functions/out/message.rb
- bolt-modules/out/lib/puppet/functions/out/verbose.rb
- bolt-modules/out/spec/functions/out/message_spec.rb
- bolt-modules/out/spec/functions/out/verbose_spec.rb
- documentation/writing_plans.md
- lib/bolt/outputter/logger.rb
- spec/fixtures/modules/output/plans/verbose.pp
- spec/integration/plan_spec.rb
This updates the `out::message` plan function to log messages at the
`info` level and the `out::verbose` plan function to log messages at the
`debug` level. Both functions continue to print to the console as
before.
!feature
* **Log messages from `out::message` and `out::verbose`**
([#2900](https://github.com/puppetlabs/bolt/issues/2900))
The `out::message` plan function now logs messages at the `info` level
and the `out::verbose` plan function now logs messages at the `debug`
level. Both functions continue to print messages to the console.
> (GH-2900) Log messages from `out::message` and `out::verbose`

- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- lib/bolt/pal.rb
- pwsh_module/command.tests.ps1
- rakelib/pwsh.rake
- spec/bolt/cli_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/bolt/pal_spec.rb
- spec/fixtures/modules/sample/metadata.json
- spec/integration/pal_spec.rb
This adds a new `bolt module show <module>` command that shows detailed
information for a module. It lists the module's name, version, summary,
available plans and tasks, operating system support, and dependencies.
!feature
* **Show detailed module information**
Bolt now supports showing detailed information about a module using
the `bolt module show <module>` command and `Get-BoltModule -Name
<module>` PowerShell cmdlet.
> (hack) Add `bolt module show <module>` command

- lib/bolt/analytics.rb
- spec/bolt/analytics_spec.rb
This fixes a bug that was causing Bolt to warn about analytics
collection when analytics is disabled in a config file and the
`analytics.yaml` file does not exist.
!bug
* **Do not warn about analytics when analytics is disabled**
Bolt no longer displays a warning about analytics collection when
analytics is disabled and the `analytics.yaml` file does not exist.
> (bug) Do not warn about analytics when analytics is disabled

- lib/bolt/outputter/human.rb
- spec/integration/parallel_spec.rb
Bolt will format a PlanResult as JSON when we don't have a handler for
the class of the result. Despite having functions for printing
`Bolt::Result`, `Bolt::ApplyResult`, and `Bolt::Error` types, the plan
result printer in the human outputter would not use these functions and
would format the types as JSON, which often makes them difficult to
read. Bolt will now correctly format the result types if returned from a
plan.
!feature
* **Format PlanResults if they are Bolt datatypes** (hack)
Bolt will now print a more human readable message for plan results
that are Bolt datatypes when using the human output format, rather than
printing JSON.
> (hack) Format PlanResult if it's a Bolt datatype

- documentation/troubleshooting.md
- lib/bolt/config/transport/options.rb
- lib/bolt/config/transport/ssh.rb
- lib/bolt/transport/ssh/exec_connection.rb
- schemas/bolt-defaults.schema.json
- schemas/bolt-inventory.schema.json
- spec/bolt/config/transport/ssh_spec.rb
- spec/bolt/inventory/inventory_spec.rb
This adds a new `batch-mode` configuration option for the `native-ssh`
transport. When set to `false`, `BatchMode` is disabled, which allows
SSH to fall back to querying for a password when key authentication
fails. This config option can be set in conjunction with the
`ssh-command` option to allow users to provide a password
non-interactively to SSH when using `native-ssh`.
!feature
* **Add `batch-mode` configuration option for `native-ssh` transport**
([#2875](https://github.com/puppetlabs/bolt/issues/2875))
The `native-ssh` transport has a new `batch-mode` configuration option
that can be used to enable or disable `BatchMode`. For more
information, see [the
documentation](https://puppet.com/docs/bolt/latest/troubleshooting.html#providing-a-password-non-interactively-using-native-ssh).
> (GH-2875) Add `batch-mode` config option for `native-ssh`

- documentation/bolt_installing.md
The release engineering team is removing vanagon support for Fedora 30,
Fedora 31, and MacOS 10.14, in addition to removing support for the Puppet
Agent. This means that Bolt can no longer build packages for these
platforms, so is removing them.
!removal
* **Remove support for Fedora 30, Fedora 31, and MacOS 10.14**
> (maint) Remove unsupported platforms

- documentation/boltspec_reference.md
- documentation/testing_plans.md
Here we update `boltspec_reference` and `testing_plans` to include documentation for `allow_any_plan` and `allow_any_task`
> (Docs) Add documentation for `allow_any_plan` and `allow_any_task`

- documentation/troubleshooting.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
`--clear-cache` now clears plan/task metadata cache.
!feature
* **`--clear-cache` clears plan/task metadata cache.**
([#2915](https://github.com/puppetlabs/bolt/issues/2915))
`--clear-cache` flag now clears plan/task metadata cache.
> (GH-2915) `--clear-cache` clears plan/task metadata cache

- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- bolt-modules/boltlib/spec/functions/apply_prep_spec.rb
- lib/bolt/cli.rb
- lib/bolt/plugin/task.rb
- spec/bolt/rerun_spec.rb
- spec/integration/apply_spec.rb
- spec/integration/plugin/task_spec.rb
This adds support for using the `_catch_errors` metaparameter in the
`apply_prep` plan function. When set, the function will return a result
set that includes results for all targets that successfully installed
targets and retrieved custom facts, and any errors for targets that were
not able to do both.
This also updates the `bolt apply` and `Invoke-BoltApply` commands to
set `_catch_errors` when running the `apply_prep` function. This allows
the command to complete the apply on as many targets as possible instead
of erroring if even one target fails the `apply_prep` step.
!feature
* **Support `_catch_errors` in `apply_prep`**
([#2925](https://github.com/puppetlabs/bolt/issues/2925))
The `apply_prep` function now accepts the `_catch_errors` parameter.
Additionally, the `bolt apply` and …
> (GH-2925) Support `_catch_errors` in `apply_prep`

- bolt.gemspec
When we updated the `guides/` to be YAML instead of text, we missed
updating the list of files to include in the Bolt gem to include the new
file extension for guides, so 3.14.1 shipped without any guides. This
updates the gemspec to include yaml files in `guides/` in the Bolt gem.
!bug
* **Ship with Bolt guides**
Bolt 3.14.1 neglected to updated the `bolt.gemspec` to include new
guide files. This updates the gemspec to include the new guide files.
> (bug-fix) Package bolt gem with `guides` directory

- acceptance/Rakefile
- acceptance/tests/task_local.rb
- lib/bolt/transport/local/connection.rb
- spec/bolt/transport/local_spec.rb
- spec/fixtures/modules/env_var/tasks/ruby_env.json
- spec/fixtures/modules/env_var/tasks/ruby_env.ps1
- spec/fixtures/modules/env_var/tasks/ruby_env.sh
- spec/integration/local_spec.rb
When running over the `local` transport with `bundled-ruby` set to
false, Bolt will attempt to restore the original Ruby environment
variables, specifically:
* GEM_PATH
* GEM_HOME
* RUBYLIB
* RUBYLIB_PREFIX
* RUBYOPT
* RUBYPATH
* RUBYSHELL
The Bolt binary wrapper explicitly unsets these variables to provide a
clean environment for the Bolt process to run in, which affects running
Bolt from a system package, and Bundler can also modify these
environment variables, saving their original values to
`BUNDLER_ORIG_<env_var>`. Changes to the Ruby environment that Bolt runs
in are incidentally picked up by Ruby tasks and plans running over the
local transport, which opens a new subprocess to execute. The binary
wrapper now stores those environment variables in `BOLT_ORIG_<env_var>`
environment …
> (GH-2922) Attempt to restore Ruby environment on local

- documentation/applying_manifest_blocks.md
- documentation/json_output_reference.md
- documentation/writing_yaml_plans.md
some links were still using a specific version, rather than the
`/latest/` meta-version.
In most cases that did redirect to `/7/` but let's just make sure this
always works.
> (docs) update /puppet/ links to point to latest

- documentation/writing_tasks.md
the divide-by-zero example uses `divisor` as bare word that's never
asigned. We fix the resulting:
```
div-by-zero.rb:14:in `rescue in <main>': undefined local variable or method `divisor' for main:Object (NameError)
```
and provide a sensible error should this case ever occur.
> (docs) Fix ruby error in an example

- acceptance/Rakefile
The environment variable for setting the beaker hosts file was changed
from `BEAKER_HOSTS` to `BEAKER_HOSTS_FILE` in #2956, which caused Bolt's
acceptance tests to begin failing. Tests began failing because the
vanagon integration job in Jenkins generates the hosts file and sets the
path to the file in `BEAKER_HOSTS`. This results in Bolt's acceptance
tests generating a new hosts file, since `BEAKER_HOSTS_FILE` is unset.
Generating the hosts file fails since the rake task runs
`beaker-hostgenerator` instead of the correct `bundle exec
beaker-hostgenerator`.
This resets the environment variable to `BEAKER_HOSTS` as expected by
the Jenkins job and beaker itself, and updates the shell command
executed by the acceptance test rake task.
> (maint) Fix broken acceptance tests

- lib/bolt/fiber_executor.rb
- lib/bolt/plan_future.rb
- spec/bolt/fiber_executor_spec.rb
- spec/fixtures/parallel/parallel/functions/custom_function.pp
- spec/fixtures/parallel/parallel/plans/custom_function.pp
- spec/integration/parallel_spec.rb
This updates `PlanFuture` instances to keep track of their own scope
object. When a `PlanFuture` is resumed by the `FiberExecutor`, the
`global_scope` in Puppet is temporarily overridden with the `PlanFuture`
scope. This prevents ephemerals from being popped off in the wrong order
due to race conditions that arise from invoking custom Puppet language
functions that invoke Bolt executor functions.
!bug
* **Do not remove variables from scope when using `parallelize()`**
([#2889](https://github.com/puppetlabs/bolt/issues/2889))
Bolt no longer removes variables from a plan's scope when invoking
a custom Puppet language function that invokes a `run_*` function from
a `parallelize()` block. Previously, a race condition would result in
the current plan's variables to be removed from the plan's …
> (GH-2889) Temporarily override scope when resuming future

- lib/bolt_server/file_cache.rb
- lib/bolt_server/schemas/action-apply.json
- lib/bolt_server/schemas/action-apply_prep.json
- lib/bolt_server/transport_app.rb
- spec/Dockerfile.puppetserver
- spec/bolt_server/app_integration_spec.rb
- spec/bolt_server/file_cache_spec.rb
- spec/docker-compose.yml
- spec/fixtures/bolt_server/projects/bolt_server_test_project/modules/apply_helpers/tasks/apply_catalog.json
- spec/fixtures/bolt_server/projects/bolt_server_test_project/modules/apply_helpers/tasks/apply_catalog.rb
- spec/fixtures/bolt_server/projects/bolt_server_test_project/modules/apply_helpers/tasks/custom_facts.json
- spec/fixtures/bolt_server/projects/bolt_server_test_project/modules/apply_helpers/tasks/custom_facts.rb
- spec/fixtures/bolt_server/projects/bolt_server_test_project/modules/fake_puppet_agent/tasks/install.rb
- spec/lib/bolt_spec/bolt_server.rb
- spec/lib/bolt_spec/file_cache.rb
This commit adds two new actions to bolt-server. The apply_prep action runs a configurable task to install an agent and the `apply_helpers::custom_facts` task. The apply action runs the `apply_helpers::apply_catalog` task. These actions support apply/apply_prep from project plans run via orchestrator. Given a plugin tarbal is calculated for every invocation, this commit adds caching for plugin tarbals. The caching is "easy" here because a versioned project is unique and will not change over time.
> (PE-32492, PE32496) Support for apply/apply_prep for plans sourced from projects

- documentation/writing_yaml_plans.md
and correctly link to the section that explains how `apply_prep` works.
> (docs) emphasize that `resources` requires `apply_prep`

- documentation/experimental_features.md
This updates an example for the `background` function in the
"Experimental features" doc to use the `map` function instead of `each`.
> (docs) Use `map` in `background` example

- documentation/troubleshooting.md
This adds a section to the 'Troubleshooting' page that documents
limitations around running tasks with sensitive output using the `pcp`
transport.
Closes #2892
> (GH-2892) Document sensitive task output limitations

- lib/bolt/module_installer/puppetfile.rb
- spec/bolt/module_installer/puppetfile_spec.rb
- spec/bolt/module_installer_spec.rb
When a project's `Puppetfile` has a forge module without a version specified, Bolt now offers a more helpful error when attempting to do a `module install/add` of the same module.
!bug
* **Fix stacktrace for conflicting module add and Puppetfile**
[(#2966)](https://github.com/puppetlabs/bolt/issues/2966)
When a project's `Puppetfile` has a forge module without a version specified,
Bolt now offers a more helpful error when attempting to do a `module install/add` of 
the same module.
> (GH-2966) Fix stacktrace for conflicting `module add` and `Puppetfile`

- spec/fixtures/parallel/wait/plans/no_future/basic.pp
- spec/integration/shareable_task_spec.rb
This fixes a shareable task integration test that was caused by the release of
Puppet 7.10.0, which includes changes to an error message that the test
matches against.
This also fixes parallel integration tests on winrm that were failing
due to connection timeout errors. The connection timeout seemed to be
caused by running multiple `sleep` commands on the winrm target.
> (maint) Fix broken integration tests

- lib/bolt/application.rb
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/plan_creator.rb
- spec/bolt/application_spec.rb
- spec/bolt/bolt_option_parser_spec.rb
- spec/bolt/plan_creator_spec.rb
- spec/integration/container_spec.rb
This adds a new flag `--script` to the `bolt plan new` command that
accepts a detailed (new-style) Puppet file reference to a script. The 
flag can only be used if `future.file_paths` is configured, so that
detailed file references are loaded. Bolt will then validate the file
exists, and create a new plan that simply runs the script and returns
the result.
Many users migrate to using Bolt from running scripts, and find it
difficult to begin writing Bolt content that can orchestrate their
scripts. This makes it easy to create the boilerplate for running a
script, with future improvements to accept parameters for the script and 
integrate those into the generated plan.
!feature
* **Pass `--script` to `bolt plan new` to wrap a script in a plan** (hack)
The `bolt plan new` command now accepts …
> (hack) Add --script to plan new

- acceptance/tests/task_local.rb
This removes a broken acceptance test that checks that Ruby environment
variables are restored when the `bundled-ruby` is disabled.
This test currently fails for two reasons:
- The `gem` executable is not available on all *nix VMs when running
tests on Jenkins. This causes the task to fail when attempting to set
`GEM_PATH` with `gem env GEM_PATH`. This issue can be solved by
setting `GEM_PATH` to a dummy value when running the command on the
SUT.
- The `bundled-ruby` config is not disabled. This causes the test to run
using Bolt's bundled Ruby, which is not what is being tested. This
issue can be solved by setting `bundled-ruby: false` in the SUT's
inventory file. However, doing so breaks other `local` transport tasks
that rely on Bolt's bundled Ruby.
Since this feature has been reliably …
> (maint) Remove broken bundled-ruby acceptance test

- lib/bolt/application.rb
This fixes a bug introduced in the CLI refactor. Previously, if a user
did not provide any env vars to a command or script, Bolt would not set
the `env_vars` option for the command. When the CLI was refactored and
the `Bolt::Application` class was introduced, this option was set to
have a default value of an empty hash `{}`. This resulted in the
`Bolt::Shell::Bash` class wrapping all commands in `sh -c`, which caused
commands to fail on some targets (such as those using `native-ssh` to
connect to Windows targets that did not recognize the `sh` command).
!bug
* **Do not wrap commands in `sh -c` when not using environment variables
or privilege escalation**
Bolt no longer wraps commands in `sh -c` when environment variables
are not specified and not using privilege escalation. Previously, …
> (bug) Do not set `env_vars` to an empty hash when none are provided

- lib/bolt/cli.rb
Previously, Bolt would exit with code 1 for any CLI parsing errors and
code 2 for any other errors raised while executing Bolt, which is
[backwards from industry
standards](https://tldp.org/LDP/abs/html/exitcodes.html). This modifies
Bolt to exit with 1 whenever it is not successful. It'd be great to
eventually exit with 2 whenever we raise `Bolt::CLIError`, but Ruby
doesn't seem to have a way to set the exit code when raising errors and
any larger changes seem like more work than they're worth.
!bug
* **Return exit code 1 instead of 2 when Bolt errors** ([#2998](https://github.com/puppetlabs/bolt/issues/2998))
Bolt will now exit with code 1 instead of 2 whenever a Bolt operation
fails.
> (GH-2998) Exit with code 1 when Bolt errors

- documentation/analytics.md
- lib/bolt/config/options.rb
- lib/bolt/executor.rb
- lib/bolt/shell/bash.rb
- lib/bolt/shell/powershell.rb
- schemas/bolt-project.schema.json
- spec/fixtures/modules/sample/scripts/script.py
- spec/fixtures/modules/sample/scripts/script.rb
- spec/integration/ssh_spec.rb
- spec/integration/winrm_spec.rb
- spec/unit/executor_spec.rb
This adds support for running scripts using the `interpreters` transport
configuration. This feature is gated by the `script_interpreter` future
flag.
!feature
* **Support `interpreters` configuration when running scripts**
([#2698](https://github.com/puppetlabs/bolt/issues/2698))
Bolt now supports the `interpreters` transport configuration when
running scripts. To enable this feature, set the
`future.script_interpreter` configuration to `true`.
> (GH-2698) Support `interpreters` configuration when running scripts

- scripts/server_client.rb
The bolt_server client setup script still calls the removed
`Plugin.setup`, which was removed. Since this uses the default Config
object, changing to `new` shouldn't pose any risk or result in any
changes.
> (bug-fix) Use Plugin.new instead of Plugin.setup

- documentation/experimental_features.md
- lib/bolt/pal.rb
This fixes a small bug where the main plan ID was being set incorrectly.
Previously, the main plan ID was set to 1, while the fiber executor
expected the main plan ID to be 0. The main plan ID is now correctly set
to 0 as expected by the fiber executor.
This also adds documentation for running plans in verbose mode to view
error results from a parallel block.
!bug
* **Correctly set main plan ID**
([#2977](https://github.com/puppetlabs/bolt/issues/2977))
Bolt now sets the main plan's ID to the correct value. Previously, the
main plan ID was set incorrectly, causing Bolt to issue warnings
during plan runs when it should not have.
> (GH-2977) Set main plan ID correctly

- libexec/bolt_catalog
Especially when we haven't handled an exception well, and didn't expect
it, we should include a backtrace. It's really, really hard to debug
without this info.
> Include a backtrace on unexpected exceptions

- lib/bolt_spec/bolt_context.rb
- lib/bolt_spec/plans/mock_executor.rb
- spec/bolt_spec/plan_spec.rb
- spec/fixtures/bolt_spec/plans/plans/script.pp
- spec/fixtures/bolt_spec/plans/plans/upload.pp
Updates BoltSpec `allow/expect_upload` and `allow/expect_script` functions to accept an absolute path. The path referred to must still exist, but that's relatively easy to mock with temporary files.
----
!bug
* **Update BoltSpec functions to allow absolute paths** ([puppetlabs#2905](puppetlabs#2905))
BoltSpec's `allow_upload`, `expect_upload`, `allow_script`, and `expect_script` functions now support passing absolute paths that rather than a module reference. The referenced path must refer to a real file or upload and script functions will still error.
> (GH-2905) Update BoltSpec functions to allow absolute paths

- lib/bolt/project_manager.rb
- spec/unit/project_manager_spec.rb
This lays down a `.gitignore` file with the following content as part of
`bolt project init` if the file does not already exist:
* .modules/
* .resource_types/
* bolt-debug.log
* .plan_cache.json
* .plugin_cache.json
* .task_cache.json
* .rerun.json
!feature
* **Create .gitignore with local Bolt files** ([#2985](https://github.com/puppetlabs/bolt))
The `bolt project init` subcommand now lays down a `.gitignore` file
to ignore local files that Bolt creates while executing.
> (GH-2985) Create .gitignore during bolt project init

- Puppetfile
!feature
* **Update bundled modules to latest versions**
The following bundled modules have been updated to their latest
versions:
- [package 2.1.0](https://forge.puppet.com/puppetlabs/package/2.1.0/changelog)
- [puppet_agent 4.9.0](https://forge.puppet.com/puppetlabs/puppet_agent/4.9.0/changelog)
- [puppet_conf 1.2.0](https://forge.puppet.com/puppetlabs/puppet_conf/1.2.0/changelog)
- [reboot 4.1.0](https://forge.puppet.com/puppetlabs/reboot/4.1.0/changelog)
- [service 2.1.0](https://forge.puppet.com/puppetlabs/service/2.1.0/changelog)
- [stdlib 8.0.0](https://forge.puppet.com/puppetlabs/stdlib/8.0.0/changelog)
The `stdlib 8.0.0` module includes breaking changes to the
`ensure_packages` function. If you need to use an older version of
the module, you can [install the …
> (maint) Bump bundled modules to latest versions

- bolt.gemspec
- exe/bolt
This enables Bootsnap's compile cache for Bolt when running on Windows, which caches the compiled Ruby bytecode and YAML Messagepack format results for faster loading. When using Bootsnap we disable the load path cache, since Bolt modifies the load path from the user's environment which results in the cache being recomputed and rewritten every Bolt run, which negates any performance improvements from compilation caching.
> (GH-2291) Enable Bootsnap

- bolt.gemspec
- documentation/bolt_installing_modules.md
- lib/bolt/application.rb
- lib/bolt/config/options.rb
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
This adds a new `module-install.forge.authorization_token` setting which
can be used to configure r10k to use a token for authorizing requests to
the Forge when installing modules.
!feature
* **Support Forge authorization token when installing modules**
Bolt now supports using a token to authorizing requests to the Forge
when installing modules using the
`module-install.forge.authorization_token` setting.
> (PE-32839) Support r10k authorization_token setting

- bolt-modules/boltlib/lib/puppet/functions/run_script.rb
- bolt-modules/boltlib/lib/puppet/functions/upload_file.rb
- bolt-modules/boltlib/spec/functions/run_script_spec.rb
- bolt-modules/boltlib/spec/functions/upload_file_spec.rb
- bolt-modules/file/lib/puppet/functions/file/exists.rb
- bolt-modules/file/lib/puppet/functions/file/read.rb
- bolt-modules/file/lib/puppet/functions/file/readable.rb
- bolt-modules/file/spec/functions/file/exists_spec.rb
- bolt-modules/file/spec/functions/file/read_spec.rb
- bolt-modules/file/spec/functions/file/readable_spec.rb
- documentation/running_bolt_commands.md
- documentation/templates/bolt_defaults_reference.md.erb
- documentation/templates/bolt_project_reference.md.erb
- lib/bolt/application.rb
- lib/bolt/catalog.rb
- lib/bolt/config/options.rb
- lib/bolt/util.rb
- rakelib/docs.rake
- spec/integration/script_loading_spec.rb
- spec/integration/ssh_spec.rb
- spec/integration/winrm_spec.rb
- spec/unit/application_spec.rb
This deprecates the `future.file_paths` config option and enables
loading scripts from the `scripts` directory of a project or module by
default.
!deprecation
* **Deprecate `future.file_paths` configuration option**
The `future.file_paths` configuration option has been deprecated.
!feature
* **Look for scripts in a `scripts` directory**
Bolt now looks for scripts in a project's or module's `scripts`
directory when provided a Puppet file path with the form
`<module>/scripts/<file>`. Previously, this behavior was opt-in only
by setting the `future.file_paths` configuration option.
> (PE-32844) Deprecate `future.file_paths` config option

- documentation/bolt.ditamap
- documentation/bolt_running_scripts.md
- documentation/creating_a_script_plan.md
- documentation/writing_tasks.md
This adds two new documentation pages: Running scripts, and Creating a
script plan. Running scripts details running scripts using Bolt on the
command line and passing arguments to scripts. Creating a script plan
describes how to turn a script into a plan that runs that script, how to
pass arguments to the plan and through to the script, and when to use a
Task instead of a script plan.
This documentation assumes that loading from the `scripts/` directory
works by default, so this shouldn't be published until we remove the
feature flag to enable loading scripts there.
> (PE-32819) Document wrapping scripts in a plan

- documentation/writing_tasks.md
This adds the `scripts` mount as a valid location for task dependency
files.
> (PE-32932) Document scripts mount for task dependency files

- lib/bolt/util.rb
- spec/unit/util_spec.rb
Update: this PR informs users attempting to use Yaml anchor/alias features that Bolt does not support them.
-------------------
Original description:
Ruby's YAML::safe_load method is used to load yaml files. By default,
::safe_load will error on yaml files that contain references and
aliases.
This commit passes `aliases: true` to ::safe_load so that users can use
yaml files which contain aliases.
This is specifically useful when hand-writing complex inventory files
using plugins, to avoid huge amounts of copy-pasta of plugin boilerplate
content in similar targets/groups.
> Communicate clearly that aliases are not supported in yaml files

- lib/bolt/application.rb
This was just a small thing I noticed, when using the default Bolt
project the project doesn't have a name, and so there's no way for `bolt
policy new` to succeed, but the error doesn't say as much. This raises
an error instructing the user to create a project with a name before
creating policies.
> (bug-fix) Error if the project doesn't have a name

- documentation/experimental_features.md
Added documentation on policies and a guide on what has been added to Bolt vis-à-vis policies.
> (PT-789) Add documentation for config policies and `policy` subcommands

- CODEOWNERS
This updates the codeowners file to notify the skeletor team, as the
bolt team is now defunct.
> (maint) Update codeowners to skeletor team

- lib/bolt/module.rb
This adds a warning when `bolt-plugin.json` is found in a module when
Bolt is looking for module plugins. The warning is raised regardless of
whether `bolt_plugin.json` is present, and instructs the user to rename
the file if they want Bolt to load it. We're preferring to warn rather
than just load `bolt-plugin.json` or rename it ourselves because then we
have to determine behavior when `bolt_plugin.json` is present, and would
have to have a precedence if both were loaded, and it just seems less
confusing to have have one be supported and raise an error when we find
common typos.
Also not entirely sure this needs a release note...
!feature
* **Warn when `bolt-plugin.json` is found** ([BOLT-1572](https://tickets.puppetlabs.com/browse/BOLT-1572))
Bolt will now warn if, while loading …
> (BOLT-1572) Warn when bolt-plugin.json is present

- lib/bolt_server/transport_app.rb
This commit updates the configuration of puppet in bolt-server's environment
loading code to allow for reading of versioned environments. The
:versioned_environment_dirs setting in puppet configures it to read from
versioned environments when it finds them, so this change enables that
behavior during environment operations in bolt-server.
Note that enabling the setting does not affect any code loading operations if
environments are _not_ versioned, so to make things easier the setting is
always true.
> (PE-33643) Update bolt-server to read from versioned envs

- bolt-modules/boltlib/spec/functions/run_container_spec.rb
- spec/bolt_server/transport_app_spec.rb
- spec/fixtures/modules/error/plans/winrm_disconnect.pp
- spec/integration/inventory_spec.rb
- spec/integration/logging_spec.rb
- spec/integration/transport/winrm_spec.rb
- spec/integration/winrm_spec.rb
- spec/lib/bolt_spec/conn.rb
For any integration test that runs against a live winrm connection, increase the timeout as the new GH runner is slower to connect.
> (maint) Increase winrm connection timeouts for windows-latest

- lib/bolt/plugin/puppetdb.rb
- spec/unit/plugin/puppetdb_spec.rb
This commit fixes a bug where the puppetdb plugin could not index in to arrays when resolving target_mappings.
!bug
* **Support resolving facts from nested arrays with puppetdb plugin**
([puppetlabs#3065](puppetlabs#3065))
Previously indexing into arrays when resolving values from puppetdb
facts using the target_mapping for the puppetdb plugin did not work.
This is now possible by specifying the index of the array, for example:
`facts.my_fact_array.0.nested_value`.
> (GH-3065) Support looking up pdb facts in arrays puppetdb plugin

- documentation/supported_plugins.md
- lib/bolt/plugin/env_var.rb
- spec/unit/plugin/env_var_spec.rb
I want to use json encoded data fron ENV with the env_var plugin. This adds and option to the plugin to parse values looked up from environment as JSON.
!feature
* **Option to parse data as JSON looked up with `env_var` plugin**
The env_var plugin now accepts a `parse-as-json` option to allow
the plugin to use data encoded as JSON stored in environment
variables.
> (maint) Add option to parse env_var values as json

- documentation/experimental_features.md
- lib/bolt/transport/ssh/exec_connection.rb
- spec/unit/transport/ssh/exec_connection_spec.rb
Updates `native-ssh` so there's always a way to configure it to omit all SSH options (since you can also include them in `ssh-command` and `copy-command`) and puts the command to execute after a `--` to separate out positional arguments.
!bug
* **Make native-ssh more portable**([https://github.com/puppetlabs/bolt/issues/3069](https://github.com/puppetlabs/bolt/issues/3069))
Updates `native-ssh` so setting `batch-mode: false` omits `-o
BatchMode=` and adds a double-dash separater `--` before commands to
execute.
> (GH-3069) Make native-ssh more portable

- lib/bolt/config/options.rb
- lib/bolt/project.rb
- schemas/bolt-defaults.schema.json
- schemas/bolt-project.schema.json
This adds a new `rerunfile` configuration option that allows users to
configure the path to Bolt's rerun file.
!feature
* **Configure path to the rerun file**
([#3049](https://github.com/puppetlabs/bolt/issues/3049))
You can now configure the path to Bolt's rerun file at the project,
user, and system-wide levels with the new `rerunfile` config option.
Supersedes #3052
Closes #3049
> (GH-3049) Configure path to rerun file

- lib/bolt/config/options.rb
- schemas/bolt-defaults.schema.json
This disables the `rerunfile` config option in the user and system
config files, as config for project files should only be configurable in
the project config file.
> (maint) Disable rerunfile config in user and system config

- documentation/bolt_installing.md
!feature
* **RedHat 9 packages**
([#3079](https://github.com/puppetlabs/bolt/pull/3079))
Bolt now ships packages for RedHat 9.
---
Note: The RedHat 9 puppet-tools repository will not be available until shortly before release.
> (PE-33256) Package bolt for RedHat 9

- documentation/bolt_installing.md
!feature
* **SLES 15 packages**
([#3080](https://github.com/puppetlabs/bolt/pull/3080))
Bolt now ships packages for SLES 15.
> (maint) Package bolt for SLES 15

- Gemfile
This bumps the minimum version for the `packaging` gem to 0.105.0, as
Bolt packages are now available for el-9 and this is the earliest
version of the packaging gem that can build packages for that platform.
---
Support for el-9 added to the packaging gem [here](https://github.com/puppetlabs/packaging/commit/225fef5456f15b797ba839c2be4685d658d4f5b4)
> (maint) Bump minimum version for packaging gem to 0.105

- Dockerfile.bolt-server
This updates the bolt-server Alpine base image from 3.12 to 3.14. That's
the latest version with Ruby 2.7. Alpine 3.15 ships 3.0.
> Dockerfile: Use newer alpine base image

- Puppetfile
Ship latest puppet_agent module.
!feature
* **Ship the latest puppet_agent module**
([#3076](#3076))
Bolt now ships with puppet_agent the 4.10.0 module which supports AlmaLinux installation..
> (GH-3076) Update puppet_agent module

- documentation/bolt_installing.md
!feature
* **macOS 12 packages**
([#3088](https://github.com/puppetlabs/bolt/pull/3088))
Bolt now ships packages for macOS 12.
!removal
* **Remove support for macOS 10.15**
([#3088](https://github.com/puppetlabs/bolt/pull/3088))
> (maint) Package Bolt for macOS 12

- Puppetfile
Reverts puppetlabs/bolt#3087 due to https://tickets.puppetlabs.com/browse/BOLT-1586
> Revert "(GH-3076) Update puppet_agent module"

- acceptance/README.md
- acceptance/Rakefile
- acceptance/tests/command_local.rb
- acceptance/tests/file_local.rb
This commit adds two new rake tasks for running bolt acceptance tests against resources provisioned from abs with floaty. Currently it only supports installing bolt from a git source (as this is the most common and useful method for testing changes). Further improvements could include building out better support for dynamically selecting node sets and respecting the different install methods (gem, package, etc).
> (maint) Build workflow for provisioning/testing SUTs from ABS

- documentation/testing_plans.md
Since the setup uses pdk it would reduce complexity to use bundle via pdk for running and testing plans.
> SOLARCH-278 updating bundle instructions to pdk

- Dockerfile.bolt-server
the old --path option throws a warning.
> Dockerfile: dont use legacy bundler syntax

- Puppetfile
This updates Bolt's bundled modules to their latest versions.
!feature
* **Update bundled modules to latest versions**
The following bundled modules have been updated to their latest versions:
- [package 2.2.0](https://forge.puppet.com/puppetlabs/package/2.2.0/changelog)
- [puppet_conf 1.3.0](https://forge.puppet.com/puppetlabs/puppet_conf/1.3.0/changelog)
- [scheduled_task 3.1.0](https://forge.puppet.com/puppetlabs/scheduled_task/3.1.0/changelog)
- [service 2.2.0](https://forge.puppet.com/puppetlabs/service/2.2.0/changelog)
- [stdlib 8.2.0](https://forge.puppet.com/puppetlabs/stdlib/8.2.0/changelog)
> (maint) Update bundled modules

- Puppetfile
- acceptance/Rakefile
This updates the acceptance test Rakefile to not add the `ssh` role to
the Bolt controller. Previously, the `ssh` role was added to the Bolt
controller, which caused some tests run on the controller to connect
over SSH. This caused problems when installing the puppet-agent package
on the controller during acceptance tests, as the
`puppet_agent::install` task added logic to not install the puppet-agent
package when a gem install of the agent is detected in
`puppet_agent >= 4.10.0`. Removing the `ssh` role results in Bolt using
the puppet gem instead of the puppet-agent package.
---
Run the following command from the `acceptance/` directory to see the failing tests:
```shell
bundle exec rake test:preserve
```
Then run the following command to see the tests passing with this change:
```shell …
```
> (BOLT-1586) Remove ssh role from bolt controller in acceptance tests

- spec/bolt_server/app_integration_spec.rb
- spec/bolt_server/file_cache_spec.rb
- spec/integration/inventory_spec.rb
- spec/integration/logging_spec.rb
- spec/integration/puppetdb/client_spec.rb
- spec/integration/puppetdb/puppetdb_spec.rb
- spec/integration/transport/winrm_spec.rb
- spec/integration/winrm_spec.rb
- spec/lib/bolt_spec/conn.rb
This increases the timeouts for spec tests to 120. This should help
prevent tests from failing when PuppetDB/PuppetServer are slow to start
or connections to the WinRM runner are slow.
> (maint) Increase timeouts for spec tests

- lib/bolt/plugin/puppetdb.rb
This fixes a bug where the `puppetdb` was correctly querying certnames
from a named PuppetDB instance, but was not collecting fact values from
the named PuppetDB instance. The `puppetdb` plugin now correctly
connects to the named instance when querying certnames and collecting
fact values.
!bug
* **Collect fact values from a named PuppetDB instance using `puppetdb`
plugin**
([#3106](https://github.com/puppetlabs/bolt/issues/3106))
The `puppetdb` plugin now correctly connects to a named PuppetDB
instance when collecting fact values. Previously, the plugin only
connected to the named PuppetDB instance when querying certnames.
> (GH-3106) Retrieve fact values using named PDB instance

- lib/bolt/application.rb
- lib/bolt/inventory/inventory.rb
- spec/unit/application_spec.rb
- spec/unit/inventory/inventory_spec.rb
!feature
* **Support extended globs for target matching**
Bolt now supports extended globs for target matching in CLI
`--targets` option.
> Support extended globs for target matching

- documentation/running_bolt_commands.md
This adds documentation that details using extended glob matching from
the CLI.
> (docs) Add docs for extended glob matching

- Dockerfile.bolt-server
- config/docker.conf
Previously we were setting bundler config options at the user level in
the build container, which meant they didn't get copied over to the
runtime container. That caused gems not to be found at runtime. We now
set them in the local .bundle/config file so they get copied over to the
final build.
> (maint) Properly configure bundler in bolt-server build

- documentation/bolt_installing.md
This removes Ubuntu 16.04 and Fedora 32 as supported platforms for Bolt.
!removal
* **Remove support for Fedora 32, Ubuntu 16.04**
> (maint) Remove EOL platforms

- lib/bolt/transport/winrm/connection.rb
- spec/integration/parallel_spec.rb
- spec/integration/transport/winrm_spec.rb
This updates the `winrm` transport to execute each command from Bolt in
a separate shell instance. Previously, the `winrm` transport opened a
single shell instance and ran all commands through it. This prevented
tasks and scripts that load DLLs from executing Bolt's cleanup command,
as DLLs cannot be unloaded when the shell instance that loaded them is
still running. Now, any task or script executed over `winrm` is executed
in a separate shell instance from the cleanup command, allowing DLLs to
be unloaded and removed from the temp directory when they are no longer
needed.
!bug
* **Execute commands over `winrm` in separate shell instances**
Bolt now opens a new shell instance each time it runs a command over
`winrm`. Previously, Bolt used a single shell instance to run all
commands, …
> (BOLT-1527) Execute commands over winrm in separate shell instances

- bolt.gemspec
This pins the max version of net-ssh to < 7.0. net-ssh >= 7.0
requires Ruby >= 2.6, which we cannot ship since Bolt needs to be
compatible with Ruby >= 2.5.
> (maint) Pin net-ssh to < 7.0

- lib/bolt/application.rb
- lib/bolt/transport/orch/connection.rb
- spec/integration/parallel_spec.rb
- spec/spec_helper.rb
- spec/unit/application_spec.rb
Previously, we sent all supplied parameter values to the plan_start
command, which meant Orchestrator stored and returned sensitive values.
We now use the plan metadata to remove sensitive values and send them in
a separate `sensitive` array. This allows the names to be stored and
returned without the values, so we can indicate *which* parameters were
used without exposing sensitive data.
When run against versions of PE that don't support the `sensitive`
array, it will just look like those params were never supplied.
> Stop submitting sensitive param values to plan_start command

- lib/bolt/config/transport/lxd.rb
This allows setting a custom Ruby path, which may come in handy when
using Puppet and Ruby packages provided by the distro itself (e.g. Arch
Linux) instead of the official Puppetlabs packages.
This change, together with setting `features: ['puppet-agent']`, allows
`bolt apply` to run against LXD containers with non-default Puppet and
Ruby paths.
!feature
* **Support interpreters in LXD transport configuration** ([#3013](https://github.com/puppetlabs/bolt/issues/3013))
Bolt now also supports setting the interpreters configuration option on LXD
transports.
> Add interpreters config option to LXD transport

- rakelib/tests.rake
This removes the `--fail-fast` flag when running RSpec unit tests.
Previously, the unit test suite would fail as soon as a single test case
failed, which prevented us from seeing all tests that would have failed
in a run. Removing this flag will now let RSpec run all tests and show
all failures in the test suite, allowing for faster development.
> (maint) Do not fail fast for unit tests

- lib/bolt/inventory/group.rb
- lib/bolt/inventory/target.rb
- spec/unit/inventory/group_spec.rb
- spec/unit/inventory/target_spec.rb
This updates the regex used to validate group and alias names to be more
permissive with the characters that can be included in the name.
Previously, group and alias names were restricted to letters, digits,
underscores, and hyphens. This updates the regex to allow any character
other than whitespace or commas (as these are used as delimiters for
target and group names when retrieving targets from inventory).
!feature
* **Allow larger set of characters in group and alias names**
([#3122](https://github.com/puppetlabs/bolt/issues/3122))
Group and alias names can now include any character other than
whitespace characters and commas.
---
This updates target validation to raise an error if a target name
includes a whitespace character or comma. These characters are used as
delimiters for …
> (GH-3122) Update character restrictions on target, group, and alias names

- bolt-modules/boltlib/lib/puppet/datatypes/applyresult.rb
- lib/bolt/applicator.rb
- lib/bolt/apply_result.rb
- lib/bolt/result.rb
- spec/unit/apply_result_spec.rb
This adds a `catalog` attribute to the `ApplyResult` object, which
includes the catalog used during an apply. The catalog is masked using
the `Sensitive` data type to prevent any sensitive information from
being printed to the console or logs.
!feature
* **Include catalog in `ApplyResult` objects**
([#2618](https://github.com/puppetlabs/bolt/issues/2618))
The `ApplyResult` object now includes a `catalog` attribute that
includes the catalog used during an apply. The catalog is masked using
the `Sensitive` data type to prevent sensitive information in the
catalog from being printed to the catalog or Bolt logs.
> (GH-2618) Add `catalog` to `ApplyResult` objects

- .github/workflows/apply.yaml
- .github/workflows/bolt_server.yaml
- .github/workflows/bolt_spec.yaml
- .github/workflows/docker_transport.yaml
- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/linux.yaml
- .github/workflows/local_transport.yaml
- .github/workflows/modules.yaml
- .github/workflows/orch_transport.yaml
- .github/workflows/pwsh.yaml
- .github/workflows/release-notes.yaml
- .github/workflows/schemas.yaml
- .github/workflows/ssh_transport.yaml
- .github/workflows/unit.yaml
- .github/workflows/windows.yaml
- .github/workflows/winrm_transport.yaml
This does two things:
1. Removes `push` as a trigger for workflows in CI.
Because puppetlabs repositories no longer allow for pushing to the
main branch, and because workflows are already triggered for all pull
requests, there is no longer a need to run workflows for pushes to
main.
2. Update paths that trigger workflows in CI.
Paths that trigger workflows have been updated. This limits the tests
that will run when certain files are modified in a pull request. For
example, spec tests will no longer run when files in the
`acceptance/` directory are modified.
> (maint) Update workflow triggers

- bolt.gemspec
- documentation/bolt_installing_modules.md
- lib/bolt/module_installer.rb
- lib/bolt/module_installer/resolver.rb
- lib/bolt/module_installer/specs.rb
- lib/bolt/module_installer/specs/git_spec.rb
- lib/bolt/module_installer/specs/id/base.rb
- lib/bolt/module_installer/specs/id/gitclone.rb
- lib/bolt/module_installer/specs/id/github.rb
- lib/bolt/module_installer/specs/id/gitlab.rb
- spec/integration/module_installer/module_installer_spec.rb
- spec/unit/module_installer/specs/git_spec_spec.rb
- spec/unit/module_installer/specs/id/gitclone_spec.rb
- spec/unit/module_installer/specs/id/github_spec.rb
- spec/unit/module_installer/specs/id/gitlab_spec.rb
This updates Bolt to support installing git-based modules from any
source. Now, Bolt will attempt to download metadata directly from GitHub
or GitLab for public repositories and fall back to cloning the git
repo's metadata if that fails.
This also updates the spec resolver to no longer calculate a SHA based
on the ref provided in project configuration. Previously, Bolt would
calculate a SHA and write it to the Puppetfile to pin the module to a
specific commit when modules are installed. However, doing this is
difficult and time-consuming with the move to supporting any git-based
module.
!feature
* **Support installing any git-based module**
([#3109](https://github.com/puppetlabs/bolt/issues/3109))
Bolt now supports installing any git-based module. Previously, Bolt
only supported …
> (BOLT-1589) Support installing any git-based module

- .github/workflows/winrm_transport.yaml
This fixes the trigger for the WinRM transport workflow to `paths`
instead of `paths-ignore`. Previously, the workflow only ran when files
that do not affect the transport were modified, which is backwards.
> (maint) Update trigger for WinRM transport workflow

- .github/workflows/stale.yaml
This adds a cron workflow that will label issues and PRs without activity
for 60 days as stale. If an issue or PR that is labelled stale continues
to have no activity for 7 days, it will be automatically closed.
> (maint) Add workflow to mark and close stale issues and PRs

- .github/workflows/stale.yaml
This updates the "Stale" workflow so it can be triggered manually and
also increases the number of operations allowed per run.
> (maint) Trigger stale workflow manually, increase operations per run

- lib/bolt/outputter/human.rb
This fixes the usage string in `bolt task show` output so parameters
that define a default value are shown as optional.
> (maint) Fix usage string in `bolt task show` output

- lib/bolt/inventory/inventory.rb
- spec/unit/inventory/inventory_spec.rb
This updates the inventory to support globbing group names in addition
to target names and aliases.
!feature
* **Support globbing group names**
([#2818](https://github.com/puppetlabs/bolt/issues/2818))
Bolt now supports selecting group names with glob patterns when
selecting targets.
> (GH-2818) Support globbing group names

- lib/bolt/plugin/puppetdb.rb
- lib/bolt/puppetdb/client.rb
PuppetDB has degenerate performance when parsing a query that contains a 
long array. When querying facts for a list of certnames, we generate a 
query that enumerates all the certnames to consider. This triggers the 
degenerate performance when querying for a large number (on the order of 
tens of thousands) of nodes. We now follow a common pattern of breaking 
this single array into many nested arrays, capping the length of any 
individual array at 100 elements.
We also now use an `in` query instead of an `or` query, which doesn't have
a performance impact but is cleaner to generate.
This also fixes a bug where we would always query PuppetDB for facts even if we
were only referencing "certname", which is not a fact, in the target_mapping
section.
> Work around PuppetDB bug involving large array queries

- acceptance/setup/common/pre-suite/010_install_ruby.rb
The public_suffix gem beyond version `4.0.7` does not support our RubyGems.
This commit pre-installs that gem version on windows.
> (maint) Pin public_suffix in Windows component acceptance test

- acceptance/tests/plan_ssh.rb
Some new platforms (namely fedora 36) will resolve `$HOSTNAME` as a fqdn. Instead of relying on this environment variable use the `hostname -s` command to compute the hostname. This will work on all of the unix systems we test ssh against in our acceptance test matrix.
> (maint) Make hostname_nix task more specific

- bolt.gemspec
[puppet-strings 3.0.0] was released on 2022-10-21.  It bumps some
minimal requirements which seems to be in-line with those of Bolt so
allow this version too.
[puppet-strings 3.0.0]:https://github.com/puppetlabs/puppet-strings/blob/main/CHANGELOG.md#v300---2022-10-21
> Allow latest version of puppet-strings

- acceptance/setup/common/pre-suite/010_install_ruby.rb
Following up on 806852ae, two of our internal acceptance test platforms, osx12 and windows19 have older Rubies and Rubygems (2.6, 2.5) that are neither compatible with puppet-strings 3, nor capable of recognizing that they need to downshift to 2.x. So this commit updates the presuite to force installation of puppet-strings 2.9.0 ahead of installing the test bolt gem on those platforms.
> (maint) Update acceptance config of OSX/Win for puppet-strings 2.9

- documentation/templates/bolt_types_reference.md.erb
The docs indicated there was a type called `PlanResults` but I couldn't find any such reference so it appears to be a typo of `PlanResult`.
> (maint) Fix docs reference to PlanResult data type

- bolt.gemspec
The 1.2.x series of concurrent ruby is incompatable with existing puppet 7.x. This commit restricts concurrent ruby while we figure out how to take up 1.2.
> (PUP-11722) Restrict concurrent ruby to 1.1.x

- documentation/bolt_running_plans.md
In the docs on running plans, there's a section called 'Plan location' that starts talking abaout where plans are then seems to pivot to talking about tasks. This feels like a typo so this commit changes two instances of the word 'task' to 'plan'.
> (docs) Change word 'task' to 'plan' in 'Plan location' section

- bolt.gemspec
We were previously pinning to an old version. The bug we were pinning the dependency for has been fixed and we now need the updated code. This commit bumps the development dependency to the 5.x series of pupetlabs-spec-helper.
> (maint) unpin spec helper

- documentation/experimental_features.md
- lib/bolt/config/options.rb
- lib/bolt/config/transport/jail.rb
- lib/bolt/executor.rb
- lib/bolt/shell/bash.rb
- lib/bolt/transport/jail.rb
- lib/bolt/transport/jail/connection.rb
- schemas/bolt-defaults.schema.json
- schemas/bolt-inventory.schema.json
- spec/fixtures/modules/results/tasks/init.sh
- spec/fixtures/modules/sample/tasks/stdin.sh
- spec/integration/jail_spec.rb
- spec/lib/bolt_spec/conn.rb
- spec/spec_helper.rb
- spec/unit/shell/bash_spec.rb
FreeBSD has support for jails since FreeBSD 4.0 (released in 2000).
Add a new 'jail' transport to Bolt to allow management of jails on FreeBSD.
Also add integration tests for jail transport.  This require a jail named `bolt` where python3.9 is installed.
While here, use `/bin/sh` when only a basic shell is required and avoid depending on `bash` or "bashisms" (code that is not portable and only works in bash) for the code used for FreeBSD jails.
> Add transport for FreeBSD jails

- Gemfile
- bolt.gemspec
As we prep for building bolt to work with puppet 8 we need to relax the net-scp version dependency while we come up with a way to support running against both the puppet 7 and 8 runtimes.
> (PE-35088) Relax net-scp gem dependency versions

- acceptance/setup/common/pre-suite/010_install_ruby.rb
Previously the wrong platform (fedora) was modified for pinning these gems. The bolt controllers in CI tody are ubuntu, windows and osx. This moves the misplaced fedora config to the correct ubuntu code branch.
> (maint) Pin back puppet and sematic puppet on ubuntu bolt controllers

- bolt.gemspec
Prior to this change, the latest major version of puppet-strings was not being pulled in to bolt.
This change relaxes the requirement to allow versions less than v5.
> (MAINT) Bump puppet-strings dependency

- bolt.gemspec
In preperation for new ruby versions in PE relax the CFPropertyList requirement so later versions can install
> (PE-36345) Relax CFPropertyList version

- acceptance/setup/common/pre-suite/010_install_ruby.rb
A couple things have changed about ruby and chocolatey, requiring new
changes to ensure the windows installation can succeed.
The newest versions of chocolately no longer require the `--lo` flag in
the choco list command, because that command now only lists local
packages instead of doing any remote searching.
Remove use of the flag so acceptance setup can complete
Update the ruby installation to use latest ruby, version 2.5 was unable
to build with new changes to the ruby devkit.
Add new steps to install msys2 and run ridk to install the ruby devkit,
which is required to build gems with C extensions
> (maint) Update acceptance to fix windows ruby install

- lib/bolt/applicator.rb
Previously compiled catalogs would be logged per target at INFO level. This clogs up logs and can expose Sensitive data in catalogs. This commit moves logging of compiled catalogs to the TRACE log level only.
!bug
* **Only log compiled catalogs at trace level** ([#3217](#3217))
Previously compiled catalogs would be logged per target at INFO level. This clogs up logs and can expose Sensitive data in catalogs. This commit moves logging of compiled catalogs to the TRACE log level only.
> (GH-3217) Only log compiled catalogs at trace level

- Gemfile
Upgrading to bundler 2.3.4 or above fixes the 
```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
```
error. In order to apply this change with a locally built bolt:
1. delete Gemfile.lock
2. delete `modules/**/*`
3. upgrade bundler `gem install bundler -v '2.3.4'`
4. confirm that `bundle -v` returns the correct version
5. if 4 is confirmed, then 
5a. `bundle install`
5b. `bundle exec r10k puppetfile install Puppetfile`
> FIXES #3229 Require bundler 2.3.4+ to fix deprecation warning

- Gemfile
We recently added a required bundler version to the ruby version in the Gemspec. Rubocop doesn't like the syntax we used.
> (maint) Fix rubocop failure from recent PR

- lib/bolt/transport/local/connection.rb
Previously we would attempt to use any prior environment variables captured when bolt was invoked by simply looking for those existing. This works when those exist but in the case they did not exist the environment variables were set to empty strings. This makes it impossible to load ruby code (for example to do an apply on local transport). This commit updates the local transport to only set those environment variables if they are explicitly set to something other than an empty string.
!bug
* **Only set ruby env vars for local transport when non empty strings** ([#3236](#3236))
Previously when using bundled-ruby=false for the local transport and not expliclty setting ruby environment variables internal apply tasks did not work due to ruby code not being able to be loaded. Now the local …
> (GH-3236) Only set ruby env vars on local transport when they exist

- Gemfile
Bolt's gemspec allows ruby 2.5 and up. This is the source of truth for ruby compatability. This commit removes the versions in the Gemfile. The restriction was added to try to get rid of a warning message when using a bundler version that is too old. This is something bundler users can manage themselves if the warning is annoying them.
!bug
* **Stop restricting ruby version in Gemfile**
The source of truth for minimum ruby version is in the gemspec. Stop duplicating that and risking conflicts in the Gemfile.
> (maint) stop restricting bundler and ruby in Gemfile

- acceptance/setup/common/pre-suite/010_install_ruby.rb
Component platforms use older OS that we use system ruby to run bolt. Some of these cannot accurately resolve dependencies that consider ruby version. The highline gem released a new major (3) version that drops support for older ruby versions. This commit pins it back in component acceptance tests.
> (main) Update component acceptance tests to pin highline

- acceptance/setup/common/pre-suite/010_install_ruby.rb
Again the issue where rubygems wont consider min ruby version. latest nori gem drops old ruby support, this commit pins to last nori version supported on bolt controllers for component acceptance.
> (maint) Pin nori in component acceptance

- acceptance/setup/common/pre-suite/010_install_ruby.rb
cfpropertylist 3.0.7 adds a new nfk dependency which native extensions cannot be built on older ruby envs on component bolt runners. Pin back to 3.0.6.
> (maint) Pin cfpropertylist on for component acceptance

- acceptance/setup/common/pre-suite/010_install_ruby.rb
The winrm gem carries a dep on nori. We must install nori to the pin to avoid ruby incompatability when resolving winrm deps.
> (maint) Install nori before winrm

- acceptance/Gemfile
Versions prior to 2.1 resulted in errors like the following:
No repository installation step for amazon yet...
We can't use beaker-puppet 3, because that depends on beaker 5.
> Update beaker-puppet 2.1

- .github/actions/docker_setup/action.yaml
- .github/actions/sudo_setup/action.yaml
- .github/workflows/docs.yaml
- documentation/analytics.md
- documentation/bolt_installing.md
- lib/bolt/config.rb
- lib/bolt/shell/powershell/snippets.rb
- spec/unit/config_spec.rb
Collecting analytics is now turned off by default.
!removal
* **Stop collecting bolt analytics** ([#3293](#3293))
Bolt no longer collects analytics by default.
> (maint) Turn off analytics submissions

- lib/bolt/puppetdb/config.rb
- spec/unit/puppetdb/config_spec.rb
Previously regardless of using certs any puppetdb token (either read from default location OR configured in settings) would be sent in x-authentication header for puppetdb requests. In the case a cert is configured, do not include this as the puppetdb endpoint will 401 in the case a valid cert but revoked token is presented.
> (GH-3296) Prefer cert auth to token auth for puppetdb client

- bolt-modules/file/lib/puppet/functions/file/delete.rb
- bolt-modules/file/spec/functions/file/delete_spec.rb
Closes #3286
!feature
* **Add `file::delete()` function** Delete a file on localhost using ruby's `File.delete`. This will only delete files on the machine you run Bolt on.
> (GH-3286) Add `file::delete()` function

- lib/bolt/inventory/target.rb
- lib/bolt/util.rb
When making multiple add_facts calls to add facts to an already present and large set of target facts performance declines as more are added due to the initialization and copying of the large hashes each time.
This change merges the added facts in place to the existing facts, which slightly improves performance.
> Improve add_facts performance

- .github/actions/docker_setup/action.yaml
- .github/actions/sudo_setup/action.yaml
Docker now ships a `docker compose` CLI, no need to install `docker-compose` on test runners.
!no-release-notes
> (maint) Stop installing docker-compose

- bolt-modules/ctrl/lib/puppet/functions/ctrl/do_until.rb
The docs mischaracterized the return value of ctrl::do_until as `nil`. That function returns the value of the given code block's last iteration
> (maint) Fix ctrl::do_until docs

- lib/bolt/config/transport/lxd.rb
- lib/bolt/config/transport/options.rb
- lib/bolt/transport/lxd/connection.rb
- schemas/bolt-defaults.schema.json
- schemas/bolt-inventory.schema.json
!feature
* **add shell-command and tty support to the LXD transport** ([#3262](https://github.com/puppetlabs/bolt/pull/3262))
Previously the LXD transport would always execute commands on the target with `sh -c`. The shell-command and tty options are added to provide a more consistent experience between the docker, podman and lxd transports.
> add shell-command and tty support to the LXD transport

- bolt.gemspec
This updates all version constraints for development dependencies in gemspec to allow their latest major versions.
Followup for https://github.com/puppetlabs/bolt/pull/3249
> dev dependencies: allow latest versions

- lib/bolt/inventory/target.rb
- lib/bolt/target.rb
- lib/bolt/transport/local.rb
- spec/unit/transport/local_spec.rb
Previously defaults were not applied until an action was actually requested on a target. This made inventory resolution confusing and non-determanistic behavior with apply_prep. This commit moves application of defaults for a target to the init method for creating a target object.
!bug
* **Apply bundled-ruby defaults at target creation** ([#3309](3309))
Ensure defaults associated with `bundled-ruby` transport config are applied at target initialization.
> (GH-3309) Ensure bundled-ruby defaults are applied at target init

- lib/bolt/applicator.rb
- libexec/apply_catalog.rb
When using the local transport defaulting to `bundled-ruby: true` it is assumed an agent is on the target. Generally when a `puppet-agent` feature is applied to a target this is assumed to be the case. This provides the core types and providers when an catalog is applied. We explicitly do not want to pluginsync all the core types and providers when we do not have to. This commit updates the apply_catalog task to take advantage of the fact that bolt packages have the core types in them. This works by sending as a task parameter the install location of bundled module content in bolt packages. After unpacking the plugins sent to the apply_catalog task, if the task finds any modules shipped with bolt, it will add those to the `LOAD_PATH`. This allows us to continue to avoid excessive …
> (GH-3310) Ensure plugin code for core types is available on local transport

- spec/integration/plan_spec.rb
Previously the `target` argument was not being properly resolved in the argument array resulting in the literal string `#{target}` being used instead of the resolved value.
> (maint) Fix bug in plan_spec integration test

- acceptance/setup/common/pre-suite/010_install_ruby.rb
Add to gems pinned due to older system ruby being used.
> (maint) Pin back fast_gettext for older platforms

- lib/bolt/inventory/inventory.rb
Update the target string name resolution behavior with two significant improvements:
- Do not perform wildcard lookups unless a wildcard character is present in the string, instead only performing exact-name matches.
- When performing a wildcard lookup, use fnmatch for improved speed and functionality.
> Improve inventory target name resolution

- lib/bolt/module_installer/specs/git_spec.rb
- spec/unit/module_installer/specs/git_spec_spec.rb
Fix regression. Issue description: #3237
> allow ssh transport protocol for a git module spec

- lib/bolt/shell/bash.rb
Currently Bolt::Shell::Bash will leaves open file descriptors at the conclusion of execute(). The file descriptions do fall out of scope at the conclusion of the execute() method and the Ruby GC eventually closes them. However, on a very busy Bolt invocation with lots of short-lived Tasks or a number of Tasks running in parallel (e.g. via background()) the number of open FDs before garbage collection can get moderately high, hitting problems on systems with low file descriptor limits.
In some simple testing in my environment this reduced the number of consistently open FDs from around 90-110 to somewhere in the 50s for a given test scenario.
> Ensure bash shell executions close file descriptors

- acceptance/setup/common/pre-suite/010_install_ruby.rb
The component platforms in internal jenkins CI uses system ruby on older VMs that require old rubies. This commit pins winrm to the last version compatible with the system rubies on test hosts.
> (maint) Pin back winrm gem for component acceptance

- acceptance/setup/common/pre-suite/010_install_ruby.rb
Pin pack public_suffix gem in old ruby envs for component acceptance to maintain compatability with older rubies.
> (maint) Pin public_suffix for component acceptance

- acceptance/setup/common/pre-suite/010_install_ruby.rb
See https://github.com/puppetlabs/puppet-strings/pull/401/files for similar approach.
> (maint) Fix component CI by pinning back yard

- acceptance/setup/common/pre-suite/010_install_ruby.rb
- lib/bolt/pal.rb
Monkey patching libraries is a bad idea. Latest version of yard changed
some internal details, which broke bolt.
A workaround was proposed in #3349 but the root cause was not addressed.
Detect if the version of YARD we are using provide the
`YARD::Logger::Severity` class (part of the new interal API) and if so
use its constants to set the log level, otherwise fallback to the
previous way of setting the log level using a Symbol.
While here, revert the workaround that was committed in #3349 and #3350.
> Fix with latest version of yard

- .github/workflows/apply.yaml
- .github/workflows/bolt_server.yaml
- .github/workflows/bolt_spec.yaml
- .github/workflows/docker_transport.yaml
- .github/workflows/linux.yaml
- .github/workflows/local_transport.yaml
- .github/workflows/modules.yaml
- .github/workflows/orch_transport.yaml
- .github/workflows/ssh_transport.yaml
- .github/workflows/unit.yaml
- .github/workflows/windows.yaml
- .github/workflows/winrm_transport.yaml
- Gemfile
- documentation/hiera.md
- spec/integration/apply_spec.rb
- spec/integration/lookup_spec.rb
Since PE-35920 is resolved I have removed the puppet version pin in the gemfile
> Remove puppet version pin from gemfile

- .github/workflows/apply.yaml
- .github/workflows/bolt_server.yaml
- .github/workflows/bolt_spec.yaml
- .github/workflows/docker_transport.yaml
- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/linux.yaml
- .github/workflows/local_transport.yaml
- .github/workflows/mend.yml
- .github/workflows/modules.yaml
- .github/workflows/orch_transport.yaml
- .github/workflows/release-notes.yaml
- .github/workflows/schemas.yaml
- .github/workflows/ssh_transport.yaml
- .github/workflows/unit.yaml
- spec/integration/cli/cli_spec.rb
- spec/unit/outputter/human_spec.rb
Updated github actions workflows to use ubuntu-22.04 instead of ubuntu-latest, ubuntu-22.04 being the latest stable version of ubuntu for Bolt
> Update actions workflows to use ubuntu-22.04

- acceptance/Gemfile
- acceptance/Rakefile
- acceptance/setup/common/pre-suite/010_install_ruby.rb
These changes updates the acceptance test pre-suite to unpin any ruby2 gems and to make sure ruby3 is installed on the machines tests are being run on
I have also added changes to the acceptance gemfile to allow for newer beaker versions
> Allow git acceptance tests to work for Ruby3

- .github/workflows/apply.yaml
- .github/workflows/bolt_server.yaml
- .github/workflows/bolt_spec.yaml
- .github/workflows/docker_transport.yaml
- .github/workflows/linux.yaml
- .github/workflows/local_transport.yaml
- .github/workflows/orch_transport.yaml
- .github/workflows/ssh_transport.yaml
- .github/workflows/unit.yaml
- .github/workflows/windows.yaml
- .github/workflows/winrm_transport.yaml
- .rubocop.yml
- Gemfile
- spec/integration/cli/cli_spec.rb
- spec/integration/inventory_spec.rb
- spec/integration/jail_spec.rb
- spec/integration/puppetdb/client_spec.rb
- spec/integration/remote_spec.rb
- spec/lib/bolt_spec/puppetdb.rb
- spec/unit/logger_spec.rb
This fixes BlockAlignment issue when running rubocop, incompatible version needs updated to 1.72.2
> 38 errors occurred:
An error occurred while Layout/BlockAlignment cop was inspecting /Users/dana.doherty/Documents/devx/bolt/acceptance/files/example_apply/lib/facter/myfact.rb:3:0.
An error occurred while Layout/BlockAlignment cop was inspecting /Users/dana.doherty/Documents/devx/bolt/acceptance/files/example_apply/lib/puppet/type/warn.rb:3:0.
An error occurred while Layout/BlockAlignment cop was inspecting /Users/dana.doherty/Documents/devx/bolt/acceptance/setup/common/pre-suite/010_install_ruby.rb:3:0.
An error occurred while Layout/BlockAlignment cop was inspecting /Users/dana.doherty/Documents/devx/bolt/acceptance/setup/git/pre-suite/010_install_git.rb:3:0.
An error occurred while …
> Update rubocop version, this fixes BlockAlignment Error
