- lib/bolt/node/ssh.rb
- lib/bolt/node/winrm.rb
- spec/bolt/node/ssh_spec.rb
- spec/bolt/node/winrm_spec.rb
- spec/lib/bolt_spec/errors.rb
Depends on PR https://github.com/puppetlabs/bolt/pull/82
> (BOLT-141) Improve connection error handling

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
> (BOLT-197) Validate plan and task names

- .travis.yml
- CONTRIBUTING.md
- Rakefile
- appveyor.yml
- spec/bolt/node/ssh_spec.rb
- spec/bolt/node/winrm_spec.rb
> (maint) Enable TravisCI SSH testing

- spec/bolt/node/winrm_spec.rb
- The current WinRM specs use the Write-Output cmdlet. The
Write-Output cmdlet is designed for writing objects to the
PowerShell pipeline, *not* for writing stdout to a host.
PowerShell has a few different methods of writing more directly to
stdout, the most popular of which is Write-Host. Write-Host is
typically frowned upon by the PowerShell community, but because it
is not appropriate for use where pipelines may be involved:
http://www.jsnover.com/blog/2013/12/07/write-host-considered-harmful/
When the goal is to emit text to be consumed by other tooling that
doesn't integrate with the PowerShell pipeline, Write-Host becomes
an important tool, and likely the case the tests are interested in
(independent ordered text-based writes to stdout).
Such counterpoints are provided at: …
> (maint) Change winrm specs to write to stdout

- lib/bolt/node/winrm.rb
- spec/bolt/node/winrm_spec.rb
- No longer executes a fresh powershell.exe per command invocation
- Fixes argument passing problems around quotes (at least for
PowerShell scripts)
- Changes what state carries over from script run to script run, so
that the following is now available in subequent calls to
_run_script against the same WinRM node:
* Environment variables
* script scoped variables
* global scoped variables
> (BOLT-72) Execute PowerShell scripts in session

- ux/bolt-CLI-spec.md
Updated human format for tasks, commands, scripts and files
> Updated human format

- spec/bolt/node/winrm_spec.rb
> (maint) fix specs on PowerShell versions < 5

- Rakefile
- new rake tasks for integration testing
- new rake task to update submodules
- fixes default port used in winrm spec
> (MAINT) add rake tasks for integration testing

- lib/bolt/config.rb
- lib/bolt/node.rb
- lib/bolt/node/orch.rb
- spec/bolt/cli_spec.rb
- spec/bolt/node/orch_spec.rb
This is #196 re-opened. I messed up branch names, and cannot seem to fix deleting a branch
> (BOLT-258) Configure pcp transport

- lib/bolt/cli.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- spec/bolt/cli_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/bolt/outputter/json_spec.rb
- spec/fixtures/modules/sample/tasks/params.json
This depends on merging #198 first.
Built gem with these changes is installed to hf3a1dxx7lajzf0.delivery.puppetlabs.net, if you'd like to ssh in and verify it works (at least until EOD today, 12/19/2017).
> (BOLT-157) show docs for tasks

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
I found this bug when I was working to pull in new puppet code yesterday
> (maint) fix schema of Error object in plan results

- .gitmodules
feature_puppet-tasks no longer exists.
> (maint) Use puppet#master for submodule

- lib/bolt/error.rb
- modules/boltlib/spec/functions/run_plan_spec.rb
- modules/boltlib/spec/functions/run_task_spec.rb
- spec/bolt/cli_spec.rb
Improves quotation consistency, and incorporates input from docs review.
> (BOLT-198) Tweak wording

- README.md
light editing (punctuation, typos),  improving readability.
> (docs) minor edits, improving readability.

- CONTRIBUTING.md
- README.md
- Rakefile
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/executor.rb
- lib/bolt/inventory.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/local/shell.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
- spec/bolt/transport/local_spec.rb
- spec/bolt/transport/ssh_spec.rb
- spec/integration/inventory_spec.rb
Add a local transport that should work on systems that support shell scripts. Work on Windows support will come later.
> (BOLT-338) Add local transport for shell systems

- README.md
- lib/bolt/config.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/inventory_spec.rb
Simplifies setup for those using Bolt with Orchestrator.
> (BOLT-356) Change local-validation default to false

- lib/bolt/config.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
Delegate option validation for transports to those transports. This
should be an interily internal refactor.
> (maint) Delegate validation to transports

- .rubocop.yml
- lib/bolt/cli.rb
- lib/bolt/outputter/human.rb
- lib/bolt/pal.rb
- lib/bolt/util.rb
- spec/bolt/cli_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/bolt/pal_spec.rb
- spec/fixtures/modules/parsing/plans/init.pp
- spec/fixtures/modules/parsing/tasks/init.json
- spec/fixtures/modules/parsing/tasks/init.pp
- spec/integration/fail_plan_spec.rb
- spec/integration/parsing_spec.rb
- spec/lib/bolt_spec/integration.rb
- spec/lib/bolt_spec/pal.rb
Does this look like the correct place for this logic?
How should we handle remote orchestrator tasks?
> (BOLT-260) Parse task parameters

- bolt.gemspec
- modules/facts/tasks/bash.sh
- modules/facts/tasks/powershell.ps1
- spec/integration/fail_plan_spec.rb
- spec/integration/modules/facts_spec.rb
Adds tasks to the gem, adds fallback to kernel for bash facts (which adds support for macOS), and adds integration tests for Windows and Linux.
> (BOLT-359) Fixes for the facts module

- bolt-modules/boltlib/lib/puppet/functions/puppetdb_query.rb
- bolt-modules/boltlib/spec/functions/puppetdb_query.rb
- lib/bolt/puppetdb/client.rb
- pre-docs/bolt_configure_puppetdb.md
- pre-docs/writing_plans.md
There are acceptance tests in the orch repo https://github.com/puppetlabs/orchestrator/pull/803
> (BOLT-462) Add pdb_query function to bolt

- Dockerfile
Travis build failing, need to specify 16.04 and install locales.
> (MAINT) update Dockerfile to tag 16.04

- lib/bolt/transport/orch/connection.rb
- spec/bolt/transport/orch_spec.rb
When orchestrator is used, set User-Agent header to specify bolt.
> (BOLT-519) User-Agent header: Orchestrator client

- lib/bolt/transport/ssh.rb
- spec/bolt/inventory_spec.rb
> (BOLT-555) Allow 'tty' option in inventory and/or config

- lib/bolt/analytics.rb
- lib/bolt/cli.rb
- pre-docs/bolt_analytics.md
Report the selected output format - human or json - to analytics.
> (BOLT-579) Report output format to analytics

- pre-docs/bolt_installing.md
This file is an example of DITA-to-markdown output created in the XML editor.
> (test) DITA source files output to markdown

- Gemfile
- spec/bolt/target_spec.rb
- spec/bolt/transport/local_spec.rb
- spec/bolt/transport/ssh_spec.rb
- spec/bolt/transport/winrm_spec.rb
- spec/bolt_ext/server_spec.rb
Adds unit tests for bolt-server and to cover changes to bolt required for the server.
> (BOLT-652) Add unit tests for bolt-server

- lib/bolt/applicator.rb
- lib/bolt/error.rb
- lib/bolt/outputter/human.rb
- spec/bolt/applicator_spec.rb
- spec/integration/apply_spec.rb
Ideas for how to display apply failure output.
> (BOLT-709) Error 'apply' when report identifies failure, and provide human-readable summary

- lib/bolt/inventory/group.rb
- spec/bolt/inventory/group_spec.rb
Previously, we didn't properly validate whether certain nested data
structures were the shape we expected. Specifically, we didn't check
whether the nodes or groups entries were arrays, or whether the
vars/facts/features/config sections were the correct type. This led to
confusing ruby error messages when we tried to treat them as though they
were correct. We now explicitly check these types and raise useful
errors accordingly.
> (BOLT-629) Validate inventory file content more carefully

- acceptance/files/example_apply/metadata.json
- lib/bolt/catalog.rb
- lib/bolt/catalog/loaders.rb
- lib/bolt/pal.rb
- spec/fixtures/apply/basic/metadata.json
> (BOLT-745) Include boltlib in system loader

- .gitmodules
Pulls in https://github.com/puppetlabs/puppet/commit/11dd9886c1d1b09ce86aca672dcf2efbf5229e65
> (BOLT-775) Update Puppet for fix to support resource overrides

- libexec/apply_catalog.rb
Some providers keep handle open to files in their module after running.
On Windows this prevents deleting the temporary modulepath we create
when applying a catalog. Allow this to fail and return a message over
stderr (which will be logged at debug level).
> (BOLT-772) Allow failure when removing Bolt Apply temp directory

- pre-docs/writing_plans.md
> (maint) Fix typos in the docs

- developer-docs/bolt_server.md
This commit adds a new `developer-docs` directory. The bolt server work is documented in bolt_server.md. As new features and updates to bolt server occur the relevant updates can be described in developer docs as part of the corresponding pull request.
> (BOLT-743) Document Bolt-Server API

- developer-docs/bolt_server.md
Update the documentation for configuring bolt-server. Update examples based on change to API task object.
> (maint) Update bolt-server docs

- developer-docs/bolt_server.md
Add concurrency and whitelist config options to developer docs
> (maint) Add new config options to docs

- Puppetfile
Brings in minor bug fixes and Puppet 6 support for recently released
modules.
> (BOLT-888) Update versions for recently released modules

- libexec/apply_catalog.rb
Without this, we get errors like
```
The task failed with exit code 1:
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:54:in `rescue in rescue in init_storage': Cannot remove /tmp/d20181003-855-156fn3k/state/state.yaml: No such file or directory @ unlink_internal - /tmp/d20181003-855-156fn3k/state/state.yaml (Puppet::Error)
from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:50:in `rescue in init_storage'
from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:45:in `init_storage'
from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:205:in `run'
from /tmp/c33af27e-1acd-495c-a495-304fd058ded3/apply_catalog.rb:81:in `block in <main>'
from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'
from …
```
> (BOLT-883) Override settings more directly

- pre-docs/bolt_known_issues.md
Remove known issues that are resolved, or no longer considered issues
(simply the way Bolt works).
> (BOLT-884) Remove resolved known issues

- Puppetfile
Pulls in a bug fix that only affected the provider.
> (maint) Bump augeas_core module

- Puppetfile
- Rakefile
- appveyor.yml
- docker-compose.yml
- spec/fixtures/apply/basic/plans/notify.pp
- spec/fixtures/apply/basic/tasks/ruby_task.rb
- spec/integration/apply_spec.rb
Test that apply works with puppet 5 and 6. Also test that running a ruby task with puppet's ruby works.
> (BOLT-834) Test compatibility with puppet5 and puppet6

- lib/bolt/cli.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/ssh/connection.rb
- spec/bolt/cli_spec.rb
- spec/bolt/transport/local_spec.rb
- spec/bolt/transport/orch_spec.rb
- spec/bolt/transport/ssh_spec.rb
- spec/bolt/transport/winrm_spec.rb
Implements uploading directories - i.e. files in a directory recursively - with SSH and WinRM.
> (BOLT-191) Support uploading directories

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
> (maint) Only load r10k when needed

- .gitignore
- Puppetfile
- pre-docs/writing_tasks.md
Include python_task_helper 0.1.2, and update docs to use it as an example of writing a python task.
> (BOLT-906) Include python_task_helper

- lib/bolt_server/transport_app.rb
Update the bolt-server winrm endpoint to be consistent with the ssh
endpoint for handling the task and target parameters.
> (BOLT-916) Update bolt-server winrm endpoint to support files

- lib/bolt/task.rb
- lib/bolt/task/puppet_server.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
- lib/bolt_server/config.rb
- lib/bolt_server/file_cache.rb
- lib/bolt_server/schemas/task.json
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
- spec/fixtures/server_configs/global-bolt-server.conf
- spec/fixtures/server_configs/required-bolt-server.conf
- spec/lib/bolt_spec/file_cache.rb
Remove support for sending a "file" with the task in boltserver now that
we support downloading and caching files.
> (BOLT-916) Remove ability accept file content from boltserver

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
- spec/integration/apply_spec.rb
Add `--noop` support for `bolt apply`.
> (BOLT-858) Add support for noop

- developer-docs/bolt-server.md
- developer-docs/examples/ssh-echo.json
- developer-docs/examples/winrm-complex-params.json
**What this changes** Include more detailed documentation on testing with local containers for bolt-server, including how to get the IP of the server making the request so that it is appropriately routed to the local targets.
**Why** I made some dumb mistakes while setting up testing, and want to save others the trouble.
> (maint) Update developer docs

- .travis.yml
- scripts/deploy.sh
Update docker login to be more secure, and correctly encrypt DOCKER_TOKEN.
> (maint) Refresh DOCKER_TOKEN to fix docker push to registry

- .travis.yml
Test generation of markdown docs for Bolt's core Puppet functions.
> (maint) Run rake docs task in Travis CI

- pre-docs/writing_plans.md
I'm not sure how to phrase this.
> (DOCS) Add link to pql tutorial.

- Puppetfile
- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- bolt-modules/boltlib/spec/functions/apply_prep_spec.rb
- spec/bolt/cli_spec.rb
Pull in changes in the package and service modules to use implementations and hide platform specific tasks.
> (BOLT-1049) Update package and service module refs

- pre-docs/bolt_configuration_options.md
- pre-docs/bolt_configure_orchestrator.md
@melamos Someone just noticed this
> (docs) add transport to global config options

- pre-docs/writing_tasks.md
> (BOLT-989) Add documentation for wrapping scripts with a task

- CONTRIBUTING.md
Update installation instructions and refresh information about testing.
> (BOLT-1096) Update CONTRIBUTING.md

- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- bolt.gemspec
- lib/bolt/applicator.rb
- libexec/apply_catalog.rb
- libexec/custom_facts.rb
- libexec/query_resources.rb
- pre-docs/applying_manifest_blocks.md
- spec/fixtures/apply/device_test/lib/puppet/provider/fake_device/fake_device.rb
- spec/fixtures/apply/device_test/lib/puppet/transport/fake.rb
- spec/fixtures/apply/device_test/lib/puppet/transport/schema/fake.rb
- spec/fixtures/apply/device_test/lib/puppet/type/fake_device.rb
- spec/fixtures/apply/device_test/plans/facts.pp
- spec/fixtures/apply/device_test/plans/resources.pp
- spec/fixtures/apply/device_test/plans/set_a_val.pp
- spec/fixtures/modules/facts_test/plans/emit.pp
- spec/fixtures/modules/facts_test/plans/init.pp
- spec/integration/apply_spec.rb
- spec/integration/device_spec.rb
- spec/integration/inventory_spec.rb
- spec/lib/bolt_spec/conn.rb
- spec/lib/bolt_spec/puppet_agent.rb
This updates the custom_facts and device_catalog tasks so that they
support running with device modules.
> (BOLT-645) Support using device modules in apply statements

- spec/fixtures/modules/env_var/lib/puppet/functions/env_var/get_var.rb
- spec/fixtures/modules/env_var/plans/get_var.pp
- spec/fixtures/modules/env_var/tasks/get_var.sh
- spec/integration/local_spec.rb
> (BOLT-1132) Add tests for environment variables passing with the local

- developer-docs/bolt_spec-run.md
- developer-docs/examples/bolt_spec_example/tasks/init.json
- developer-docs/examples/bolt_spec_example/tasks/init.rb
This commit adds documentation about BoltSpec::Run.
> (BOLT-1202) Document BoltSpec::Run

- Puppetfile
- acceptance/setup/common/pre-suite/071_install_modules.rb
The bash/powershell implementations for the package/service tasks have been updated to resolve some painful bugs and to make the output more consistent between the implementations. This commit adds the updated modules to the bolt.
> (BOLT-1104, BOLT-1103) Update package and service tasks

- pre-docs/inventory_file_generating.md
This feature will probably be deprecated with v2 inventory work so I
don't think it's work adding a lot of documentation.
> (BOLT-1196) Update inaccuracies in bolt-inventory-pdb docs

- Puppetfile
- acceptance/setup/common/pre-suite/071_install_modules.rb
Pull in bug fixes from the 0.5.1 release.
> (MODULES-8750) Update facts module to 0.5.1

- .rubocop.yml
- pre-docs/bolt_installing_modules.md
- pre-docs/bolt_running_plans.md
- pre-docs/bolt_running_tasks.md
- pre-docs/inspecting_tasks_and_plans.md
Allow users to more easily discover that bolt ships with useful content.
> (BOLT-1225) Make bundled content more discoverable in bolt docs

- lib/plan_executor/app.rb
This commit updates the ruby app.rb code to fix code meant to limit concurrent
calls to the bolt PAL to a single thread.
The code has been updated to work with the newer version of the
concurrent-ruby gem, which has consolidated to a single Promisises class for
everything. Additionally, the call to "pal.get_plan_info" has also been
wrapped in a concurrency promise so that it will also be forced to use the
SingleThreadExecutor.
> (ORCH-2302) Update plan executor to be thread safe

- pre-docs/writing_tasks_and_plans.md
This commit updates the plan description. The existing one implies you need a task to have a plan. Feel free to adjust!
> (Docs) Clarify plan description

- bolt-modules/file/lib/puppet/functions/file/exists.rb
- bolt-modules/file/lib/puppet/functions/file/readable.rb
- bolt-modules/file/spec/functions/file/exists_spec.rb
- bolt-modules/file/spec/functions/file/readable_spec.rb
Added these so that a plan can check if a file exists before uploading it.  As the upload will not catch an error if the file doesn't exist.
> (BOLT-1338) Added file::readable and file::exists functions

- pre-docs/plan_functions.md
This commit updates the markdown generated from puppet strings for the BOLT-901 work.
> (BOLT-901) Update plan function documentation for run_task

- .travis.yml
In addition to checking that there a no errors in the generation of docs from puppet strings, also ensure that the PR includes all of the neccesary changes.
> (maint) Ensure docs rake task keeps plan_functions.md up to date

- bolt-modules/boltlib/lib/puppet/functions/add_facts.rb
- bolt-modules/boltlib/lib/puppet/functions/add_to_group.rb
- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- bolt-modules/boltlib/lib/puppet/functions/facts.rb
- bolt-modules/boltlib/lib/puppet/functions/fail_plan.rb
- bolt-modules/boltlib/lib/puppet/functions/get_resources.rb
- bolt-modules/boltlib/lib/puppet/functions/get_targets.rb
- bolt-modules/boltlib/lib/puppet/functions/puppetdb_fact.rb
- bolt-modules/boltlib/lib/puppet/functions/puppetdb_query.rb
- bolt-modules/boltlib/lib/puppet/functions/run_command.rb
- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
- bolt-modules/boltlib/lib/puppet/functions/run_script.rb
- bolt-modules/boltlib/lib/puppet/functions/run_task.rb
- bolt-modules/boltlib/lib/puppet/functions/set_feature.rb
- bolt-modules/boltlib/lib/puppet/functions/set_var.rb
- bolt-modules/boltlib/lib/puppet/functions/upload_file.rb
- bolt-modules/boltlib/lib/puppet/functions/vars.rb
- bolt-modules/boltlib/lib/puppet/functions/wait_until_available.rb
- bolt-modules/boltlib/lib/puppet/functions/without_default_logging.rb
- bolt-modules/ctrl/lib/puppet/functions/ctrl/do_until.rb
- bolt-modules/ctrl/lib/puppet/functions/ctrl/sleep.rb
- bolt-modules/file/lib/puppet/functions/file/exists.rb
- bolt-modules/file/lib/puppet/functions/file/read.rb
- bolt-modules/file/lib/puppet/functions/file/readable.rb
- bolt-modules/file/lib/puppet/functions/file/write.rb
- bolt-modules/out/lib/puppet/functions/out/message.rb
- bolt-modules/system/lib/puppet/functions/system/env.rb
Previously, we didn't collect usage data for "core" functions outside
boltlib. But we do now!
> (BOLT-1359) Report function calls outside boltlib

- docs/_lab/01-installing-bolt/index.md
- docs/_lab/02-acquiring-nodes/index.md
- docs/_lab/03-running-commands/index.md
- docs/_lab/04-running-scripts/index.md
- docs/_lab/05-writing-tasks/index.md
- docs/_lab/06-downloading-and-running-existing-tasks/index.md
- docs/_lab/07-writing-plans/index.md
- docs/_lab/08-writing-advanced-tasks/index.md
- docs/_lab/09-writing-advanced-plans/index.md
- docs/_lab/10-deploying-an-application/index.md
- docs/_lab/11-apply-manifest-code/index.md
- docs/index.md
Changes the terminology for Plans and Tasks, updates broken links, and fixes some formatting errors and typos.
> (docs) General housekeeping and formatting fixes

- Gemfile
- Puppetfile
- acceptance/setup/common/pre-suite/071_install_modules.rb
- acceptance/tests/apply_plan_ssh.rb
- acceptance/tests/bolt_apply.rb
- bolt.gemspec
This commit includes new releases of the package and service modules.
> (BOLT-1360) Update package and service modules

- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/inventory/group2.rb
- lib/bolt/inventory/inventory2.rb
- lib/bolt/plugin.rb
- lib/bolt/plugin/pkcs7.rb
- lib/bolt/plugin/prompt.rb
- lib/bolt/secret.rb
- lib/bolt/secret/base.rb
- pre-docs/inventory_version2.md
- spec/bolt/plugin/pkcs7_spec.rb
- spec/bolt/plugin/prompt_spec.rb
- spec/integration/plugin/pkcs7_spec.rb
This adds support for hiera-eyaml compatible encryption in the inventory
file as well as a `bolt secret` command that allows users to interact
with encyrpted values.
> (BOLT-1270) Add pkcs7 encryption plugin

- lib/bolt/plugin/pkcs7.rb
- lib/bolt_server/base_config.rb
- spec/bolt/task_spec.rb
This commit fixes word array and array alignment offenses detected by the latest version of rubocop.
> (maint) Fix offenses detected by rubocop update

- spec/docker-compose.yml
This reverts commit d2fddeafdab1762171aa5d92dec1b7fc16f3832b, reversing
changes made to 44a379c064060483dbfd189dd3f2b0e18201daeb.
> Revert "Merge pull request #1052 from donoghuc/pin-postgres"

- pre-docs/writing_plans.md
> (maint) Fix broken link in the docs

- .travis.yml
- spec/Dockerfile.omiserver
- spec/bolt/transport/winrm_spec.rb
- spec/docker-compose.yml
- spec/fixtures/omiserver/docker-entrypoint.sh
- These are mostly oriented around some nuanced issues with the docker-compose testing / how output appears in automated CI runs like TravisCI
> (maint) Minor Docker testing improvements

- lib/bolt/analytics.rb
- lib/bolt/cli.rb
- lib/bolt/executor.rb
- lib/bolt/inventory.rb
- lib/bolt/inventory/group2.rb
- lib/bolt/inventory/inventory2.rb
- lib/bolt/plugin.rb
- lib/bolt/secret.rb
- pre-docs/bolt_installing.md
- spec/bolt/analytics_spec.rb
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
- spec/bolt/inventory/group2_spec.rb
- spec/bolt/inventory/inventory2_spec.rb
- spec/bolt/inventory_spec.rb
- spec/fixtures/modules/analytics/plans/init.pp
- spec/integration/analytics_spec.rb
Should have integration tests for analytics?
> (BOLT-1410) Report plugin usage analytics for bundled plugins

- CODEOWNERS
Chris Cowell is our docs reviewer now!
> (maint) Make Chris Cowell our docs person

- pre-docs/writing_yaml_plans.md
This commit adds some examples of the sharp edges and quirks around converting plans between Yaml and Puppet.
> (BOLT-1286) Document Yaml plan limitations

- docs/_lab/07-writing-plans/index.md
- docs/_lab/08-writing-advanced-tasks/index.md
- docs/_lab/09-writing-advanced-plans/index.md
- docs/_lab/10-deploying-an-application/index.md
- docs/_lab/11-apply-manifest-code/index.md
This incorporates most of the suggestions from
https://github.com/puppetlabs/tasks-hands-on-lab/pull/58, which was filed
against the old tasks-hands-on-lab repo. Credit and thanks to @RandellP!
> Incorporate edits from tasks-hands-on-lab repo

- docs/_lab/04-running-scripts/index.md
> (BOLT-1505) Update bashcheck download link in hands-on lab

- CODEOWNERS
Sets @puppetlabs/skeletor as owners for bolt_server
> (maint) Update CODEOWNERS for bolt_server

- docs/_lab/01-installing-bolt/index.md
The installation doc is not just installation, but also has an overview of what a project directory looks like.  I already had bolt installed, so I skipped this and ran into problems after I set up the nodes.  This makes the title a little more cumbersome, but describes the other two thirds of the document for people who skim.
> Include 'Creating a project' in the title

- Puppetfile
- acceptance/setup/common/pre-suite/071_install_modules.rb
Pull in updates to service task, most notably new `force` option to powershell implementation https://github.com/puppetlabs/puppetlabs-service/compare/1.0.0...v1.1.0
> (packaging) Ship latest version of service module

- lib/bolt_server/file_cache.rb
- spec/bolt_server/file_cache_spec.rb
Specifically this change will allow FileCache to use a file mutex when it is accessed by ACE.
> (FM-8497) Allow FileCache to receive a mutex

- developer-docs/bolt-api-servers.md
- lib/bolt_server/schemas/action-run_script.json
- spec/lib/bolt_spec/bolt_server.rb
This matches what's in Bolt and in pxp-agent's script module.
> (ORCH-2339) Fix run_script to take arguments array

- CHANGELOG.md
- Puppetfile
- lib/bolt/analytics.rb
- lib/bolt/cli.rb
- lib/bolt/plugin.rb
- spec/bolt/cli_spec.rb
This commit pulls in the azure_inventory module. In addition other bundled modules are updated to the latest version.
> (packaging) Ship azure_inventory plugin and update bundled modules

- documentation/bolt.ditamap
Fixing the ditamap so the sidenav on the site renders child pages correctly.
> (Docs) Ditamap fix

- CHANGELOG.md
- lib/bolt/util.rb
- spec/bolt/util_spec.rb
> (GH-1296) Added YAML parsing error details to the bolt logging

- CHANGELOG.md
- bolt-modules/ctrl/lib/puppet/functions/ctrl/do_until.rb
- bolt-modules/ctrl/spec/functions/ctrl/do_until_spec.rb
This adds tests to #844 
Closes #1270
> (GH-1270) Support limit for `do_until`

- CHANGELOG.md
All entries under the 1.35.0 section were edited and are now ready for review.
> Final Changelog updates v 1.35.0

- CHANGELOG.md
All entries under the 1.36.0 section have been  edited and are now ready for review.
> 1.36.0 Changelog edits

- lib/bolt_spec/plans.rb
- lib/bolt_spec/plans/action_stubs/task_stub.rb
- lib/bolt_spec/plans/mock_executor.rb
- lib/bolt_spec/run.rb
- spec/integration/apply_spec.rb
I think these are useful improvements but they don't really fit GH-1191
> (maint) Support testing with v2 inventory in more places

- lib/bolt/inventory/group2.rb
- lib/bolt/inventory/target.rb
- lib/bolt/target.rb
- spec/bolt/inventory/group2_spec.rb
Deleted some commentes and added back some tests that appear to have been deleted unintentionally.
> (GH-1147) Suggestions based on PR review for GH-1147

- CHANGELOG.md
Updated with edits to cover the latest editions to the Changelog and a small revision to last week's bug fix.
> Finalized Changelog edits for 1.36.0 (2.0)

- CHANGELOG.md
- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- documentation/bolt_configuration_options.md
- lib/bolt/plugin.rb
- lib/bolt/plugin/module.rb
- lib/bolt/plugin/task.rb
- spec/bolt/plugin/puppet_library_spec.rb
- spec/fixtures/plugin_modules/inv_plans/plans/puppet_library.pp
> (GH-1191) Support _run_as metaparameter for puppet_library plugins

- CHANGELOG.md
PR contains final Changelog edits for the release of BOlt 1.38.0.
> Final 1.38.0 Changelog edits

- CHANGELOG.md
> Changelog edits for release 1.39.0.

- Gemfile
- bolt.gemspec
This is now needed for `bolt plan show`.
> (GH-1409) Add puppet-strings dependency

- CHANGELOG.md
> Changelog edits: 1.40.0

- CHANGELOG.md
- documentation/bolt.md
max-width isn't an img attribute, but width is.
> (maint) Shrink Bolt logo on docs homepage

- CHANGELOG.md
> Final edits Changelog for 1.42.0

- documentation/bolt_examples.md
This commit adds an example that deploys a package with Bolt and Chocolatey.
> (Docs) Add Bolt example

- CHANGELOG.md
- documentation/bolt_project_directories.md
- lib/bolt/boltdir.rb
- spec/bolt/boltdir_spec.rb
> Revert "(GH-1500) Support .yml for bolt config and inventory"

- documentation/bolt.ditamap
- documentation/inventory_file_v2.md
- documentation/migrating_inventory_files.md
- documentation/using_plugins.md
> (GH-1464) Update Version 2 inventory file and plugins docs

- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
This commit updates the plan metadata endpoint in bolt-server so that the
/plans API does the following:
GET /plans returns _only_ the list of plan names, no associated metadata
GET /plans/:module_name/:plan_name returns the metadata for only one plan
GET /plans_metadata does what the original /plans API did: fetches all plans
and all associated metadata with each plan
These changes to the API are required because fetching all plans and all
metadata was less performant than we originally experienced, so the additions
of the less complex APIs (/plans and /plans/:module/:plan) allows downstream
consumers to only get the exact data they need in a more performant way
> (PE-27909) Split out plan metadata endpoints

- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
This commit excludes the path to a module on disk when requesting plan metadata from bolt server. We do not want use this data for anything and do not want to expose these paths as they should not ever be modified by a human operator. This commit also fixes the `init` bug fixed for the /plans/:module/:plan endpoint (https://github.com/puppetlabs/bolt/commit/5fb7505c2154f6f46e466345e93879b86581a4f6#diff-5455f0d1ba7ece350e45ec171e8fe914) in the /plans endpoint.
> (maint) Exclude path to module for bolt_server plan metadata

- documentation/writing_tasks_and_plans.md
Trivial fix - some rendering issues with this one on the website
> (docs) Fixing some weird formatting issues

- .github/workflows/deploy.yaml
This updates the deploy workflow to correctly run the deploy script.
> (maint) Run script in deploy workflow

- .github/workflows/deploy.yaml
This updates the deploy workflow to properly checkout the repo before
running the deploy script.
> (maint) Checkout repo in deploy workflow

- CHANGELOG.md
- lib/bolt/plugin.rb
- lib/bolt/plugin/env_var.rb
- spec/bolt/plugin/env_var_spec.rb
This adds an `env_var` builtin plugin that looks up data from an
environment variable.
> (GH-1564) Add env_var builtin plugin

- lib/bolt_server/pe/pal.rb
This commit ports over the work done in orchestrator to support reading modulepath from bolt.yaml present in an environment root (https://github.com/puppetlabs/orchestrator/pull/1266/files). Without it a bolt.yaml without `modulepath` set would cause pe-bolt-server to error when hitting the /plans/* endpoints.
> (PE-28244) Ignore bolt.yaml in environment root when no modulepath is specified

- .rubocop.yml
- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- bolt.gemspec
- lib/bolt/applicator.rb
- lib/bolt/executor.rb
- lib/bolt/inventory/group.rb
- lib/bolt/module.rb
- lib/bolt/pal.rb
- lib/bolt/pal/yaml_plan/step/resources.rb
- lib/bolt/transport/local/shell.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/winrm/connection.rb
- lib/bolt/util.rb
- lib/bolt_server/transport_app.rb
- spec/bolt/pal/yaml_plan/evaluator_spec.rb
- spec/bolt_server/file_cache_spec.rb
Ruby 2.3 has been EOL since March 2019 and Ruby 2.4 will be EOL in March 2020.
> (maint) Bump required ruby version to 2.5

- lib/bolt/transport/ssh.rb
> reintroduce gss-api auth which was removed by 59d3f66

- documentation/bolt.md
> (docs) Fixing invalid html

- lib/bolt/config.rb
- lib/bolt/inventory/group.rb
- lib/bolt/inventory/target.rb
This makes a couple more changes to improve the performance of loading the inventory.
**Don't copy entire config to merge transport data**
Previously, we made a deep copy of and validated the entire Bolt::Config 
object for every Target. That's quite expensive and creates a huge amount
of GC overhead, especially given that we're cloning complex active objects
like loggers and hitting the filesystem to expand paths while validating.
The only reason we did this copying was because the logic that knew how to
merge two transport configs together happened to live on the Bolt::Config
object and happened to make in-place modifications to the config.
That method is now abstracted to a class method on Bolt::Config so it can
be used by the Target object without copying the entire config. We now …
> Inventory performance improvements

- documentation/bolt_installing.md
- Changed Puppet install note to address new users.
- Fixed notes
- Parallelism - install/installing
> (Docs) Fixes to installing doc

- Puppetfile
> (maint) Bump bundled modules to latest versions

- Puppetfile
> (GH-1668) Bump aws-inventory to 0.5.0

- documentation/inventory_file_v2.md
Adding links to config reference from inventory file doc.
> (Docs) Add links to config from inventory docs

- documentation/bolt.md
Adding Ben Ford's blog post on automating scripts with Bolt
> (Docs) Adding blog post on Bolt plans

- Puppetfile
> (maint) Bump terraform to 0.5.0

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/docs-change.md
- .github/ISSUE_TEMPLATE/feature-request.md
This adds issue templates that override the puppetlabs
organization-level issue templates.
> (maint) Add issue templates

- .rubocop.yml
- spec/bolt/config_spec.rb
- spec/bolt/pal/yaml_plan/evaluator_spec.rb
This enables a handful of Rubocop cops that are set to become default.
> (maint) Add new default cops

- documentation/bolt.ditamap
- documentation/bolt_project_directories.md
- documentation/bolt_running_plans.md
- documentation/bolt_running_tasks.md
- documentation/directory_structure.md
- documentation/experimental_features.md
Adding an "Experimental features" section for features that are large
enough to need documentation, but aren't neccessarily ready to be added
to the docs proper.
> (WIP) GH-1803

- documentation/applying_manifest_blocks.md
- documentation/bolt_installing.md
- documentation/bolt_installing_modules.md
- documentation/bolt_options.md
- documentation/bolt_project_directories.md
- documentation/bolt_running_plans.md
- documentation/bolt_running_tasks.md
- documentation/experimental_features.md
- documentation/inspecting_plans.md
- documentation/inventory_file_v2.md
- documentation/module_structure.md
- documentation/running_bolt_commands.md
- documentation/writing_tasks.md
Making our "Related information" and "Tips" sections a little more consistent. I like the little book unicode for Related information - I think it helps that section stand out a little more.
> (Docs) Style consistency edits

- README.md
> (maint) Update hands-on lab link in repository README

- documentation/experimental_features.md
> (maint) Fix ResourceInstance attributes table in experimental docs

- lib/bolt/config.rb
The Jruby environment used in Orchestrator does not have the `Etc::SC_OPEN_MAX` constant defined. Given the default is evaluated even if the config is overridden this commit updates the logic to decide whether to attempt to read the system config. This change also caches the result for the `default_concurrency` method so that the system config is not fetched multiple times.
> (maint) Jruby compatibility with default Bolt::Config

- documentation/getting_started_with_bolt.md
These changes should fix issues for Windows users
> (docs)Updates to fix the guide on Windows

- documentation/getting_started_with_bolt.md
- Added a link to the repo
- Made some small edits
> (GH-1915) Bolt getting started repo

- .gitignore
- documentation/templates/bolt_transports_reference.md.erb
- documentation/templates/privilege_escalation.md.erb
- Adding some generated docs to .gitignore.
- Fixing a couple links that were causing build errors.
> (Docs) build maintenance

- documentation/writing_tasks.md
This adds a 'Debugging tasks' section to the 'Writing tasks' doc that
describes different approaches to debugging tasks. It covers using
Bolt's debugging logs, debugging libraries in common scripting
languages, using the debugging methods in the task helper libraries,
running tasks as scripts, and redirecting `stderr`.
Closes #1918 
> (GH-1918) Add 'Debugging tasks' section to 'Writing tasks'

- documentation/bolt.ditamap
- documentation/bolt_configure_orchestrator.md
Also moves Apply doc into Puppet section of docs
> (Docs) Change link to shim doc

- documentation/bolt_installing_modules.md
- documentation/module_structure.md
> (Docs) Overriding a packaged module

- pwsh_module/pwsh_bolt.psm1.erb
- rakelib/pwsh.rake
- (GH-2090) Fix powershell version parameter
- (GH-2090) Improve PowerShell parameter template
- (GH-2090) More PowerShell parameter validation
> (GH-2090) More PowerShell parameter validation

- lib/bolt/pal.rb
This was always warning about the project shadowing a module with the
same name, because we load the project as a module and it thus
"conflicted" with itself. We now explicitly check that the path to the
module is different than the path to the project.
We also bypass the check entirely if we're not loading the project as a
module. This is just a short-circuit that doesn't change the correctness
of the method, since no module would ever have matched the name `nil` to
issue this warning in that case.
> (GH-2108) Don't report project as conflicting with itself

- lib/bolt/applicator.rb
When compiling catalogs, we use a single scope object to capture the
current plan scope at the time of the compilation, and then merge in
target-specific information for each compile. However, the compile
method was *modifying* the single scope object to add its
target-specific info. This caused a race condition whereby the scope
could be modified by another thread and the wrong target inserted and
used for compilation.
This appears to be relatively uncommon at low levels of concurrency,
because the critical section only lasts until the scope has been
serialized to JSON to be passed to the compilation process. Once that's
happened, any external modifications won't affect the current compile.
Due to the GIL, it's impossible for multiple threads to be running that
code at the same time, so …
> (GH-2156) Don't leak scope between targets

- .rubocop.yml
- lib/bolt/applicator.rb
- lib/bolt/cli.rb
- lib/bolt/transport/base.rb
- lib/bolt/util.rb
- lib/bolt_server/file_cache.rb
- lib/bolt_spec/bolt_context.rb
- spec/bolt/logger_spec.rb
This enables several cops that were made defaults in Rubocop 0.91.
> (maint) Add new cops for Rubocop 0.91

- documentation/applying_manifest_blocks.md
Previously, Bolt would use the same Hiera hierarchy for lookups both
inside apply blocks and outside apply blocks, and simply removed facts
and vars from the PAL ScriptCompiler to prevent users from using
interpolations in their hierarchies for lookups outside apply blocks.
This meant that hierarchies that used interpolations would error even if
the user wasn't looking up data that included an interpolation. To
mitigate this, we added a separate hierarchy under the key
`plan_hierarchy` in puppetlabs/puppet#8232.
This documents using the plan_hierarchy Hiera config key, including a
short example.
Closes #1835
!feature
* **Define Hiera data to be looked up outside apply blocks under plan_hierarchy key** ([#1835](https://github.com/puppetlabs/bolt/issues/1835))
Previously, Bolt used the same …
> (GH-1835) Document plan_hierarchy usage

- documentation/writing_plans.md
> (Docs) Clarify init plans in subdirectories

- lib/bolt/logger.rb
When initializing the Logging library, we previously only checked
whether it had already been initialized and skipped doing it if it had.
However, when using Bolt as a library, it's possible that other code
(for instance, the winrm gem) might set up Logging before Bolt has a
chance to, probably initializing it with the _default_ set of log
levels. That causes Bolt to fail when trying to use the `trace` level,
since no method will exist for it on the Logger objects.
We now explicitly check not whether Logging has been initialzied at all,
but whether the levels we need exist. This does allow Logging to be
initialized with _additional_ levels beyond what Bolt needs, but ensures
that Bolt's levels exist at a minimum.
This also slightly refactors how we set up some instance variables on
the …
> (GH-2188) More reliably initialize log levels

- documentation/writing_plugins.md
This updates the 'Writing plugins' docs page to better describe the
process of writing a plugin.
> (GH-2076) Update 'Writing plugins' docs page

- lib/bolt/pal.rb
This updates `Bolt::PAL.with_puppet_settings` to safely delete the
tmpdir used to configure Puppet. Previously, the tmpdir was created with
a block, which would result in the tmpdir being automatically deleted
once the block completed. However, if the tmpdir was deleted before this
happened, Bolt would error and show a stacktrace. Now, Bolt manually
deletes the tmpdir if it exists instead of relying on the `mktmpdir`
method to do it automatically.
!bug
* **Safely delete tmpdir used to configure Puppet for PAL**
([#2245](https://github.com/puppetlabs/bolt/issues/2245))
Bolt now safely deletes the tmpdir used to configure Puppet when using
PAL. Previously, if the tmpdir was deleted during a Bolt run before
Bolt deleted the directory itself, an error with a stacktrace would be
raised.
> (GH-2245) Safely delete tmpdir used when configuring Puppet for PAL

- documentation/automating_windows_targets.md
- documentation/tig_stack.md
The section on deploying a choco package on a Windows target was a
little overcomplicated. The PS cmdlets need to be checked as I couldn't
test them.
> (Docs) Update choco package doc

- lib/bolt/transport/ssh/exec_connection.rb
Fixes #2289 by disabling loading the ssh config.
> Fixes #2289

- lib/bolt_server/schemas/partials/task.json
The previous PR forgot to do this.
> (maint) Change 'project' => 'versioned_project' in required URL params

- documentation/developer_updates.md
This adds a developer update for Bolt 3.0 that lists expected changes
and removals in Bolt 3.0, with a brief explanation on why the change is
being made.
> (GH-2375) Bolt 3.0 developer update

- developer-docs/bolt-api-servers.md
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
This commit changes the project_ref parameter to versioned_project
to match the parameter in puppetserver.
> (PE-30693) change project_ref to versioned_project

- documentation/experimental_features.md
> (bug) Add link to plugin cache release

- lib/bolt/puppetdb/client.rb
It can be difficult to debug where slowdowns in PuppetDB requests are
happening because we only log failures and don't notify users when we're
beginning and finishing HTTP requests. Adding logging allows us to
pinpoint if the query itself is slow, or if something in Bolt is
performing slowly.
> (maint) Log PuppetDB requests

- documentation/troubleshooting.md
Moved the bit on tempdirs into its own section so it's easier
for people to scan and find the info they're looking for
> (Docs) Improve troubleshooting doc

- documentation/applying_manifest_blocks.md
- documentation/running_bolt_network.md
> (Docs)Fixing build error

- lib/bolt/plugin.rb
- lib/bolt/plugin/puppet_connect_data.rb
- spec/bolt/plugin/puppet_connect_data_spec.rb
> (PE-30766) Add the puppet_connect_data plugin to Bolt

- lib/bolt_server/config.rb
- lib/bolt_server/transport_app.rb
> (PE-30856) Add and use the builtin-content-dir setting

- documentation/bolt_configure_orchestrator.md
- documentation/bolt_installing.md
Fixes broken link and updates Homebrew install instructions.
Closes #2539, #2534
> (Docs) Fixes #2539 and #2534

- pwsh_module/command.tests.ps1
- pwsh_module/pwsh_bolt_internal.ps1
Needs to be merged along with https://github.com/puppetlabs/bolt-vanagon/pull/149
Acceptance Criteria:
1. Install the Artifact from https://github.com/puppetlabs/bolt-vanagon/pull/149
2. Replace the beginning of `C:\Program Files\WindowsPowerShell\Modules\PuppetBolt\PuppetBolt.psm1` with the contents of this PR.
3. Test using any PowerShell bolt command like `Invoke-BoltCommand`
> (GH-2551) Move to bolt.bat

- documentation/writing_plans.md
This introduces a new section about using Hiera interpolations with the
`plan_hierarchy` key. It clarifies that plans are not run in
environment- or node-specific contexts, and so only have access to
variables in scope. It also provides an example of using static
variable lookups in a plan.
> (GH-2467) Clarify using interpolations in plan_hierarchy

- documentation/bolt_installing.md
- documentation/configuring_bolt.md
- documentation/templates/privilege_escalation.md.erb
> (Docs) Minor changes for 3.0

- bolt.gemspec
> Revert "(GH-2547) Use Puppet 7"

- documentation/bolt.md
- documentation/bolt_installing.md
- documentation/configuring_bolt.md
- documentation/upgrading_to_bolt_3.md
- Update 3.0 page with instructions for installing 2.44
- A couple of small edits 
> (Docs) Some more 3.0 changes

- documentation/bolt.ditamap
- documentation/hiera.md
- documentation/writing_plans.md
This adds a dedicated documentation page for using Bolt with Hiera.
> (GH-2492) Add dedicated Hiera docs

- lib/bolt_server/transport_app.rb
This way, other pal-dependent bolt-server operations are not blocked on
project file metadata fetching, which can take a while for large
directories.
> (PE-30449) Only acquire pal_mutex for pal-dependent code

- documentation/bolt_installing.md
> (Docs) Update DMG instructions

- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
- spec/fixtures/bolt_server/projects/bolt_server_test_project/bolt-project.yaml
- spec/fixtures/bolt_server/projects/bolt_server_test_project/plans/allowlist_glob.pp
- spec/fixtures/bolt_server/projects/bolt_server_test_project/tasks/allowlist_glob.sh
> (PE-31222) Support globs in project allowlists

- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
The puppet_library plugin hook defaults to the task plugin with the task
set to the puppet_agent::install task.
> (PE-31357) Update bolt-server to return the target's plugin hooks

- CHANGELOG.md
------
Thanks for your contribution! Note that all community contributors will be required to sign our Contributor License Agreement, unless you fall under the [Trivial Patch Exemption Policy](https://puppet.com/community/trivial-patch-exemption-policy). If you believe it applies to your pull request, please comment explaining why you do not need to sign the CLA. Directions for signing will be attached to your pull request shortly.
Please note that all contributions may be publicly recognized in release notes.
> (maint) Update changelog to 3.4.0

- modules/puppet_connect/plans/test_input_data.pp
- modules/puppet_connect/spec/plans/test_input_data_spec.rb
The puppet_library plugin hook can be configured to run an arbitrary task (following the task plugin spec) for connect. Currently only the task plugin (ie not module plugin) is supported. For the validation plan, bolt uses the default puppet_agent module based plugin where connect will specify this same default using the task based plugin notation. The plan validates that either the default is being used or that a task based plugin is being used. The other current limitation is that for connect every target must have the same plugin configured. The validation plan validates this.
Finally, the test file for this module has been renamed so the tests contained in it will actually be run in the rake task triggered by github actions.
> (PE-31344) Validate puppet_library plugin hook for connect

- Puppetfile
!feature
* **Update bundled modules**
The following bundled modules have been updated to their latest
versions:
- [aws_inventory 0.7.0](https://forge.puppet.com/puppetlabs/aws_inventory/0.7.0/changelog)
- [gcloud_inventory 0.3.0](https://forge.puppet.com/puppetlabs/gcloud_inventory/0.3.0/changelog)
> (maint) Update bundled modules to latest versions

- documentation/developer_updates.md
This includes a developer update detailing the motivation for changing
the syntax for loading scripts and files, and the phased approach we're
taking to rolling changes out.
!feature
* **Developer Update: Script loading changes**
There's a new Developer Update in town, [read it
here](https://puppet.com/docs/bolt/latest/developer_updates.html).
> (GH-2738) Developer update about script loading changes

- lib/bolt/transport/ssh/connection.rb
Previously we were manually using Window's
[FindWindowW](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-findwindoww)
function via Fiddle to see if pageant is running and determine if we
need to pass `use-agent: false` to Net::SSH on Windows. Initially this
check ran just fine in CI, but recently started exiting 1 when called.
Our theory is that the types we had for the parameters or return were
incorrect, but since the system was exiting it was impossible to catch
the error and see it, and since this couldn't be reproduced locally and 
was only happening in Github Actions finding system logs was also not 
possible.
This updates our own pageant check to simply use the 
Net::SSH::Authentication::Pageant::Win module which defines pretty much
the same function …
> (maint) Use Net::SSH pageant module to check pageant

- documentation/bolt_installing.md
- documentation/templates/bolt_cmdlet_reference.md.erb
- rakelib/pwsh.rake
> Revert "(GH-2550) Document installing PuppetBolt PowerShell module"

- documentation/inventory_files.md
This adds examples of using shared inventory across multiple projects to
the inventory docs page.
> (GH-2474) Add shared inventory examples

- documentation/troubleshooting.md
This adds documentation to the Troubleshooting page that describes using
`/bin/sh -c` to run a command using the Docker transport when
interpolating environment variables into the command.
> (GH-2802) Document using '/bin/sh -c' for the Docker transport

- .github/workflows/docs.yaml
This is a small test that generates the Bolt docs and then runs
the DITA OT in strict mode to check for any issues.
Strict mode fails early if it encounters an error.
> (Docs) Adds docs test

- bolt-modules/boltlib/spec/functions/apply_prep_spec.rb
- bolt-modules/boltlib/spec/functions/get_resources_spec.rb
- bolt-modules/boltlib/spec/functions/run_container_spec.rb
- lib/bolt/error.rb
- modules/canary/plans/init.pp
- spec/integration/apply_spec.rb
- spec/integration/catch_errors_spec.rb
- spec/integration/parallel_spec.rb
- spec/integration/plugin/module_spec.rb
- spec/integration/plugin/task_spec.rb
This removes plan aborted language from errors and warnings.
> (GH-2847) Remove plan aborted language

- lib/bolt/pal.rb
This fixes a bug where Bolt would stacktrace when listing plans or tasks
and the plugin or task cache included a file that no longer exists.
Specifically, this error is raised by the `File.mtime` method receiving
a non-existent filepath.
The conditions that cause this bug are:
- Moving a module to a different location in the modulepath.
- Deleting a module that shadows another module of the same name on the
modulepath.
If the user then runs `plan|task show`, Bolt will error.
!bug
* **Do not stacktrace with non-existent files in plan or task cache**
Bolt no longer errors with a stacktrace when listing plans or tasks
when the plan or task cache include paths to files that no longer
exist.
> (bug) Fix stacktrace when cache includes missing file

- lib/bolt_server/transport_app.rb
This ensures that they don't appear in the logs.
> (PE-32470) Wrap sensitive parameters before calling Executor#run_task

- documentation/hiera.md
> (Docs) Fix broken link

- bolt.gemspec
> (maint) Bump ffi

- developer-docs/releasing-bolt.md
> (maint) Update 'Releasing Bolt' documentation

- documentation/using_plugins.md
> (docs) Add note about when to use plugin_hooks

- lib/bolt/transport/orch/connection.rb
- spec/integration/transport/orch_spec.rb
When running a plan over the PCP transport, Bolt issues a
`command/plan_start` API request and gets a Plan ID to use throughout
the Bolt run. The plan ID is then associated with every subsequent
`run_task` request, so that the task is associated with the plan it's
running as part of. If the Orchestrator is restarted as part of the
plan, it (correctly) marks the plan as 'failed' and returns a
`plan-already-finished` error for subsequent task runs using the same
ID. This makes sense, but Bolt can continue to run the tasks with a new
ID given that restarting the Orchestrator is a somewhat common case.
When Bolt gets a `plan-already-finished` error from the Orchestrator it
will start a new plan to generate a new Plan ID, and will rerun the task
and continue executing.
!feature
* **Continue …
> (GH-2964) Restart a task over PCP if it fails with 'plan-already-finished'

- documentation/templates/bolt_project_reference.md.erb
- documentation/templates/bolt_transports_reference.md.erb
- documentation/using_plugins.md
> (maint)(docs) Fix some build gremlins

- bolt.gemspec
- exe/bolt
> Revert "(GH-2291) Enable Bootsnap"

- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
> (PE-32930) Load task dependency files from the scripts directory

- documentation/bolt_installing.md
!feature
* **Debian 11 packages**
Bolt now ships packages for Debian 11.
> (PE-32840) Build Bolt for Debian 11

- lib/bolt/application.rb
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/config/options.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- lib/bolt/pal.rb
- lib/bolt/project.rb
- pwsh_module/command.tests.ps1
- rakelib/pwsh.rake
- schemas/bolt-project.schema.json
- spec/integration/policy_spec.rb
- spec/unit/cli_spec.rb
This adds the new `policy apply|new|show` subcommands and the `policies` config option.
> (PT-738) Add `policy` subcommands and `policies` config option

- documentation/writing_tasks.md
> (docs) Remove duplicate phrase

- documentation/getting_started_with_bolt.md
Some style changes and clarifications for the getting started guide.
> (docs) Bolt GS style updates

- documentation/writing_yaml_plans.md
This updates the doc based on feedback from
https://stackoverflow.com/questions/71325299/can-you-use-facts-in-a-yaml-based-bolt-plan
> (Docs) Update the YAML plans doc

- CODEOWNERS
> (maint) Update invalid codeowners file

- documentation/testing_plans.md
Add some basic documentation explaining how to stub/mock calls to
the puppetdb_* functions when unit testing Plans that use them.
> Document testing plans with PuppetDB functions

- documentation/bolt_installing.md
Revert "(maint) Package Bolt for macOS 12" due to https://tickets.puppetlabs.com/browse/BOLT-1586
> Revert "(maint) Package Bolt for macOS 12"

- documentation/bolt_installing.md
> (maint) Add documentation for installing macOS 12 packages

- CHANGELOG.md
> (maint) Update changelog to 3.23.0

- lib/bolt_server/file_cache.rb
The `timeout_interval` option for `Concurrent::TimerTask` had a critical bug that was unable to be fixed
upstream. The latest conccurnet-ruby release no longer supports the timeout https://github.com/ruby-concurrency/concurrent-ruby/pull/926/files
This commit updates the `expire` function to handle timing out. Timeouts could occur when the file cache mutex can not be aquired. Ensuring that the purge_timeout is respected helps avoid the possiblilty of deadlocks due to too many piled up purges.
> (maint) Do not rely on Concurrent::TimerTask timeout_interval argument

- CHANGELOG.md
> (maint) Update changelog to 3.23.1

- CHANGELOG.md
> (maint) Update changelog to 3.24.0

- Puppetfile
!feature
* **Update bundled modules to latest version**
The following bundled modules have been updated to their latest versions:
- [puppet_agent 4.12.1](https://forge.puppet.com/modules/puppetlabs/puppet_agent/4.12.1/changelog)
- [stdlib 8.4.0](https://forge.puppet.com/modules/puppetlabs/stdlib/8.4.0/changelog)
> (maint) Bump bundled modules

- CHANGELOG.md
> (maint) Update changelog for 3.25.0

- CHANGELOG.md
> (maint) Update changelog for 3.26.1

- documentation/projects.md
> (DOCUMENT-1364) Show powershell cmdlet for project init

- documentation/writing_plans.md
> Correct code typo

- lib/bolt_server/schemas/action-run_task.json
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
- spec/fixtures/modules/sample/tasks/sleep.json
- spec/fixtures/modules/sample/tasks/sleep.ps1
- spec/fixtures/modules/sample/tasks/sleep.sh
TODO: Discuss on PR comments and decide what direction we want to go with timing out tasks run over ssh/winrm in PE
> (PE-35138) Timeouts for task execution in bolt server

- .github/workflows/mend.yml
Change the Mend product category from RE to Puppet Enterprise
> (maint) Fix Mend Product category

- Puppetfile
- spec/integration/apply_spec.rb
Update to latest modules for next bolt release.
!feature
* **Update puppet modules shipped with bolt packages**
Modules shipped with bolt packages have been updated to latest.
> (maint) Update packaged modules

- CHANGELOG.md
> (maint) Prep 3.29.0 release

- acceptance/setup/common/pre-suite/010_install_ruby.rb
Noticed https://github.com/puppetlabs/bolt/pull/3349/files#r1769020246 after a CI run.
> (maint) Fix copy paste bug doing yard pin

- Puppetfile
Updating puppetlabs-puppet_agent to 4.21.0
> Update puppet-agent module to 4.21.0
