puppetlabs/bolt

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
Include the incorrect subcommand or action in the raised exception so it's clear
what part of the CLI is incorrect.
> (BOLT-142) Include incorrect subcommand and action in message

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
Allow hosts to be specified on stdin `--nodes -`, or from a file,
`--nodes @file.txt`. In both cases, the nodes should be specified
one node URI per line. Leading and trailing spaces will be
stripped. Bolt still accepts comma-separated list of nodes.
> (BOLT-29) Allow hosts to be specified in file or stdin

- bolt.gemspec
The old approach of `git ls-files` relied on commands which don't
typically exist on Windows, so `bundle install` would fail.
Also we were shipping unnecessary files, like the docs pdf, example
tasks, etc. According to the rubygems specification, `files` should only
contain require-able files[1].
Reduce the set of files that are packaged in the gem to only what is
needed.
[1] http://guides.rubygems.org/specification-reference/#files
> (BOLT-149) Simplify what files are packaged in the gem

- lib/bolt/cli.rb
- lib/bolt/executor.rb
- lib/bolt/node.rb
- lib/bolt/node/errors.rb
- lib/bolt/node/ssh.rb
- lib/bolt/result.rb
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
- spec/bolt/node/ssh_spec.rb
- spec/spec_helper.rb
This commit modifies bolt to use the `secure` verifier by default. The
connection will be allowed if the remote host has an entry in our known_hosts
file and the key presented by the host matches our local copy.
Add a command line option (either -k or --insecure) to fallback to the old
lenient behavior. The other net-ssh verifiers `null` and `strict` are not
supported.
> (BOLT-152) Default to secure ssh authentication

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
If verbose was specified on the command line after debug it would override the
log level.
> (maint) Fix ordering sensitivity with debug and verbose

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
In the event we execute a list that happens to have a node twice the command will be executed twice, simply running a uniq on the array to ensure it is a unique set.
> Add a uniq function to nodes array to ensure we deduplicate list

- lib/bolt/node/ssh.rb
- spec/bolt/node/ssh_spec.rb
Rescue all Net::SSH::Exceptions, as net-ssh rescues ETIMEDOUT and rethrows as Net::SSH::ConnectionTimeout.
The order of rescue block is changed since AuthenticationFailed and HostKeyError derive from the Net::SSH::Exception super class.
```
$ bundle exec bolt command run 'hostname -f' --nodes 8.8.8.8
8.8.8.8:
Failed to connect to 8.8.8.8: Net::SSH::ConnectionTimeout
Ran on 1 node in 75.44 seconds
```
> (BOLT-141) Rescue Net::SSH:Exception

- lib/bolt/cli.rb
The <task> parameter was missing from "puppet task" related help.
Make "Puppet task" and "Puppet task plan" usage consistent.
> (BOLT-182) Add task name to help

- bolt.gemspec
- lib/bolt/node_uri.rb
- spec/bolt/node_uri_spec.rb
Ruby's URI class does not correctly parse special characters in the `userinfo`
section of a URI. Use Addressable instead. Note it requires ruby 2.0 and
up, which is compatible with Bolt.
> (BOLT-124) Use Addressable to parse URIs

- lib/bolt/node/ssh.rb
- lib/bolt/node/winrm.rb
- spec/bolt/node/winrm_spec.rb
The winrm library wraps httpclient which can raise subclasses of
HTTPClient::TimeoutError during a connect, instead of Errno::ETIMEDOUT or WinRM
specific errors. As a result, we weren't handling connect/receive/send timeouts
or BadResponseErrors at the SOAP layer[1].
Always rescue StandardError from which RuntimeError, SocketError,
SystemCallError, and Net::SSH::Exception derive from.
[1] https://github.com/nahi/httpclient/blob/82929c4baae14c2319c3f9aba49488c6f6def875/lib/httpclient.rb#L249-L281
> (BOLT-141) Always rescue StandardError during ssh and winrm connect

- Gemfile
- bolt.gemspec
- exe/bolt
Rubocop dropped support for Ruby 2.0 analysis, see commit
https://github.com/bbatsov/rubocop/commit/2f6f3f297cd957def22419d8d70a1afd9410e497.
Pin to rubocop 0.50.0, while fixing rubocop errors that occur with
0.51.0.
> (maint) Pin to rubocop 0.50.0

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
> (BOLT-28) Make --password optional and prompt the user if value is missing

- lib/bolt.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/executor.rb
- lib/bolt/node.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/executor_spec.rb
- spec/bolt/node/ssh_spec.rb
- spec/bolt/node_spec.rb
- spec/spec_helper.rb
Apply CLI options when running a plan, such as `--user`, `--password`, `--tty`, etc.
> (BOLT-183) Apply CLI options when running plans

- bolt.gemspec
Puppet requires addressable < 2.5.0, because that version includes a
dependency that doesn't support ruby 1.9. In order to use puppet and
bolt gems together, e.g. when running `puppet script`, we need to relax
bolt's addressable gem dependency.
> (maint) Relax addressable gem constraint

- lib/bolt/cli.rb
- lib/bolt/node/winrm.rb
- spec/bolt/node/winrm_spec.rb
Update help so that it's clear to omit the `--password` value to be
prompted for the password.
Also winrm printed an ugly stack trace if the password is omitted,
because the WinRM connection was created in our initialize method
instead of connect. Move it to the latter so that we gracefully handle
exceptions.
> (BOLT-28) Improve help for password prompting

- bolt.gemspec
The net-ssh library renamed the `paranoid` key to `verify_host_key` in
commit net-ssh#c4fbcdc882[1]. Using the latter key fails if net-ssh < 4.2,
so bump our minimum net-ssh runtime dependency.
[1] https://github.com/net-ssh/net-ssh/commit/c3fbcdc882f6763fa718f6adbd9d1d60eaf04b62
> (BOLT-192) Require at least net-ssh 4.2, but less than 5.0

- bolt.gemspec
Require addressable < 2.5.0 to avoid a dependency on public_suffix whose
version 3.0 requires ruby 2.1 or greater.
We can revert back to addressable ~> 2.4 when we drop ruby 2.0 support.
> (BOLT-193) Avoid dependency on public_suffix for ruby 2.0

- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/node.rb
- lib/bolt/node_uri.rb
- spec/bolt/cli_spec.rb
- spec/bolt/node_spec.rb
- spec/bolt/node_uri_spec.rb
Adds a `--transport` command line option for specifying the default transport to use if one is not specified. The default transport is ssh. This is handy for Windows as you don't need to repeat winrm in each node URI:
```
$ bolt command run whoami --nodes={hghi7uvplkq8kki,qksuptpp9h5gunc}.delivery.puppetlabs.net --transport winrm -u Administrator -p
Please enter your password:
qksuptpp9h5gunc.delivery.puppetlabs.net:
qksuptpp9h5gunc\administrator
hghi7uvplkq8kki.delivery.puppetlabs.net:
hghi7uvplkq8kki\administrator
Ran on 2 nodes in 0.65 seconds
```
> (BOLT-53) Global transport

- lib/bolt/node/orch.rb
- lib/bolt/node/ssh.rb
- lib/bolt/node/winrm.rb
- spec/bolt/node/orch_spec.rb
- spec/bolt/node/ssh_spec.rb
- spec/bolt/node/winrm_spec.rb
- tasks/init.rb
Bolt now accepts arguments to scripts. If an argument contains spaces it must be
quoted, e.g. bolt script run script.sh 'arg with spaces'
```
$ bx bolt script run spec/fixtures/scripts/success.sh 'one two' three -n o4np54hfrljr5wo.delivery.puppetlabs.net -k
o4np54hfrljr5wo.delivery.puppetlabs.net:
arg: one two
arg: three
standard out
standard error
Ran on 1 node in 0.79 seconds
```
```
$ bx bolt script run spec/fixtures/scripts/success.ps1 "one two" three -n winrm://mllw3jr0io5r4zo.delivery.puppetlabs.net -k -u Administrator -p
....
mllw3jr0io5r4zo.delivery.puppetlabs.net:
arg: one two
arg: three
standard output
Ran on 1 node in 2.09 seconds
```
> (BOLT-52) Allow arguments to be passed to scripts

- spec/bolt/node/orch_spec.rb
Update unit test to verify script args can be passed through
orchestrator without shell interpolation.
> (BOLT-52) Verify orch handles script args correctly

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
If the local script to upload and execute doesn't exist, then generate
an error, instead of calling into net-sftp with a nil argument. We
already verify the argument to `bolt upload`, so that did not need to
change.
> (BOLT-189) Error if local script doesn't exist

- CONTRIBUTING.md
- Rakefile
- appveyor.yml
- spec/bolt/node/ssh_spec.rb
- spec/bolt/node/winrm_spec.rb
Turns on WinRM tests in AppVeyor, so that connection behavior is tested on PRs.
This results in some additional runtime, but appears to be < 10% in a few PRs I've spot checked.
> (maint) Enable AppVeyor WinRM testing

- lib/bolt/node/winrm.rb
- spec/bolt/node/winrm_spec.rb
- spec/fixtures/modules/sample/tasks/winstdin.ps1
Commit 4ce307fef1 changed the execute_process method to expect an array
instead of a string. But when I rebased 30049627fa on top, the code path
for puppet apply passed in a string.
Pass an array of args for the puppet apply case. Ensure files are quoted for
powershell, ruby and puppet, and for bolt script run. Set the working directory
to the parent directory of the resolved executable, so that puppet.bat can load
environment.bat in the same directory. It's also more consistent with how
scripts are likely to be written. Also Add tests for how arguments are
generated.
> (BOLT-158) execute_process expects an array of args

- lib/bolt/node/winrm.rb
- spec/bolt/node/winrm_spec.rb
- Previously, the stdout stream was read / parsed synchronously prior
to draining the stderr stream, which could lead to a deadlock if
too much output was produced on stderr
- The correct way to drain stdout / stderr is by responding to events
and sending them directly to the host. Add a few ScriptBlocks to
handle OutputDataReceived and ErrorDataReceived from the process.
- Note for output to not appear correctly on stderr, the code had
to stop using the Write-Error cmdlet and had to move to using
$Host.UI.WriteErrorLine
This has the side effect of not appending the extra newlines
that were introduced as part of
9fff248
> (BOLT-200) Prevent WinRM stream reading deadlock

- lib/bolt/node/winrm.rb
- spec/bolt/node/winrm_spec.rb
(BOLT-206) Correctly handle winrm exit status
- Given the winrm command first looks to the $? automatic variable,
failure status of running PowerShell code could be misinterpreted.
$? is the status of the last operation in the context of PowerShell
and doesn't reflect the status of calling the Invoke-Interperter
function. So with the success of the function executing, the winrm
gem is considering the operation a success.
PowerShell does not allow for setting $? manually (a good thing),
so there are a few options for handling a scenario in which the
PowerShell helper code ran correctly, but the invoked executable
(powershell.exe, ruby.exe, puppet.bat, etc) return a non-zero
exit status:
* Generate a failing command that doesn't pollute the PowerShell
$Error collection (which requires some …
> (BOLT-206) Correctly handle winrm exit status

- lib/bolt/node/winrm.rb
- spec/bolt/node/winrm_spec.rb
Requires #110 be merged first ... 
- Previously, the winrm executor may have produced an error like:
```
Exception calling "Start" with "1" argument(s): "The system cannot find the file specified"
At line:11 char:17
+ $LASTEXITCODE = Invoke-Interpreter @invokeArgs
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Interpreter
```
This is unhelpful to an end user, who typically would prefer to
know tha their system could not find `ruby.exe` or `puppet.bat`
This changes the error message to the more acceptable:
```
Could not find executable 'puppet.bat' in C:\ProgramData\Boxstarter;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wb …
```
> (BOLT-202) Improve winrm missing executable error

- lib/bolt/cli.rb
- lib/bolt/executor.rb
- lib/bolt/notifier.rb
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
- spec/bolt/notifier_spec.rb
All of the run_* methods now take an optional block. If one is provided, then
the node and its result will be yielded to the block as the operation finishes.
Only one result will be yielded at a time, so callers do not need to worry about
concurrency issues. For example, colorize modifies the global stdout stream
color and doesn't need to worry about concurrency issues.
> (BOLT-151) Yield node results as they finish

- lib/bolt/node/winrm.rb
- spec/bolt/node/winrm_spec.rb
- Change the WinRM _run_script helper to behave similarly to
_run_task. Look up whitelisted file extensions to determine what
may be executed on the remote host - currently this includes .rb,
.ps1 and .pp
- Add some basic mocked tests demonstrating scripts may be invoked
in this fashion
- Update wording on some tests so its clear when PowerShell is being
invoked.
> (BOLT-208) Execute WinRM scripts by whitelist

- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/outputter.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- lib/bolt/result.rb
- spec/bolt/cli_spec.rb
- spec/bolt/node_spec.rb
- spec/bolt/outputter/json_spec.rb
- spec/bolt/result_spec.rb
This commit adds support for the --format flag and the json format
option. When specified the format is used for results of the action
printed to stdout. It does not effect logging to stderr.
Once the functions are moved into bolt it will be easier to clean up the relationship between results in bolt and execution results in puppet.
> (BOLT-45) Support JSON format

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
Prompts for the privelege escalation password if `sudo-password` is
passed on the CLI with no value.
> (BOLT-226) Fix sudo-password so password is actually optional (#163)

- bolt.gemspec
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
Use call_function instead of deprecated run_plan to invoke a plan.
Ensures boltlib is packaged as part of the gem, and that we include it
in modulepath when executing a plan.
> (BOLT-185) Drop use of PAL run_plan

- lib/bolt/outputter/human.rb
Plan results may be any object and cannot always be pretty printed.
> (maint) Don't pretty-print plan results

- bolt.gemspec
- lib/bolt/executor.rb
- lib/bolt/node/ssh.rb
This commit changes the ssh transport to use scp instead of sftp for
file uploads. This allows users to upload files, scripts and tasks
regardelss of whether sshd on the target is configured to support sftp
or the user has sftp permissions.
> (BOLT-225) use scp instead of sftp to copy files

- lib/bolt/cli.rb
This commit runs plans with empty facts instead of running facter from
bolt. This cuts 2s off of most plan runs and will allow us to discover
which facts if any are useful to expose to plans.
> (maint) Use empty facts when running plans

- appveyor.yml
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/node.rb
- lib/bolt/node/orch.rb
- lib/bolt/node/ssh.rb
- lib/bolt/node/winrm.rb
- spec/bolt/cli_spec.rb
- spec/bolt/node/ssh_spec.rb
- spec/bolt/node_spec.rb
- spec/fixtures/configs/invalid.yml
- spec/integration/ssh_spec.rb
- spec/integration/winrm_spec.rb
- spec/lib/bolt_spec/conn.rb
- spec/lib/bolt_spec/integration.rb
This commit adds the ability to load config options from a file. This
required a small refactor to seperate config-like options from
command-options. Config like options are all flags and are passed around
with config but may not be read from the config file. The Command
options are those that are not prefaced with flags and are only exposed
to the execute function of the CLI not passed around with the config.
There is a further distinction between global config options and those
that are transport specific. Transport specific options are specified
for each transport in the config file but only map to a single flag for
all transports as command line flags. Most of these flags only work with
the ssh transport now.
> (BOLT-241) Load config from file

- lib/bolt/node.rb
This was copy-pasted from the `run_command` function and resulted in script invocations failing in verbose or debug mode.
> (maint) Fix reference to undefined variable

- lib/bolt/node/winrm.rb
- spec/bolt/node/winrm_spec.rb
This PR adds support for the `powershell` input method to the `Bolt::WinRM` class.
The implementation injects a base64 encoded JSON blob containing the task parameter values to the PowerShell session which is then expanded in that session into powershell's `Hashtable` data structure which is then in turn used for splatting in the invocation of the task code.
> (BOLT-156) Add powershell input method

- lib/bolt/node_uri.rb
Previously, we were requiring 'addressable', which is a helper available
in addressable 2.4.0 that will require both 'addressable/uri' and
'addressable/tempalte'. Because we don't have a dependency on
addressable >= 2.4.0, it's possible that the require will fail for some
users.
The fixes for this are either to change the dependency on addressable or
require 'addressable/uri'. The recommended way to use the library is to
require only 'addressable/uri' if 'addressable/template' isn't needed,
which is our use case. Therefore, we keep our previous addressable
dependency and update the require.
Fixes #178.
> (maint) Properly require addressable

- README.md
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/node.rb
- lib/bolt/node/ssh.rb
- lib/bolt/node/winrm.rb
- spec/bolt/cli_spec.rb
- spec/bolt/node/ssh_spec.rb
- spec/bolt/node/winrm_spec.rb
Supercedes #81 
Needs a few more tests:
Needs some extra info on why WinRM is now configured as such.
> (BOLT-163) Configurable connection timeout

- lib/bolt/cli.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- spec/bolt/cli_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/bolt/outputter/json_spec.rb
Apply special formatting when an ExecutionResult is the final output from running a plan.
Example output would be something like
```
[
{
"node": "node1",
"status": "finished",
"result": {
"_output": "foo\n"
}
},
{
"node": "node2",
"status": "failed",
"result": {
"_error": "bar\n"
}
}
]
```
> (BOLT-165) Format ExecutionResult returned from a plan

- bolt.gemspec
- puppetlabs_spec_helper 2.6.0 release introduced a new bug that
requires that a .fixtures.yml exists with a fixtures: section in
it. A temporary pin to 2.5.1 was made until the issue could be
fixed, which it has now with a 2.6.1 gem release
> (maint) Remove PSH 2.5.1 pin

- lib/bolt/node/orch.rb
- spec/bolt/node/orch_spec.rb
Make sure the error reported when a task target node is skipped indicates the fact.
> (BOLT-262) Report skipped nodes as such

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
Adds the `bolt plan show` command to list available plans.
> (BOLT-32) List available Puppet task plans

- lib/bolt/config.rb
- lib/bolt/node.rb
- lib/bolt/node/orch.rb
- lib/bolt/node/winrm.rb
- spec/bolt/cli_spec.rb
- spec/bolt/node/winrm_spec.rb
Switch PCP and WinRM transport config options from `ca-cert` to `cacert`
to be shorter and consistent with CURL and other Puppet tools.
> (BOLT-270) Update ca-cert to cacert

- lib/bolt/cli.rb
- lib/bolt/execution_result.rb
- lib/bolt/node.rb
- lib/bolt/target.rb
- modules/boltlib/lib/puppet/datatypes/executionresult.rb
- modules/boltlib/lib/puppet/datatypes/target.rb
- modules/boltlib/lib/puppet/functions/file_upload.rb
- modules/boltlib/lib/puppet/functions/run_command.rb
- modules/boltlib/lib/puppet/functions/run_script.rb
- modules/boltlib/lib/puppet/functions/run_task.rb
- modules/boltlib/spec/functions/file_upload_spec.rb
- modules/boltlib/spec/functions/run_command_spec.rb
- modules/boltlib/spec/functions/run_script_spec.rb
- modules/boltlib/spec/functions/run_task_spec.rb
This commit adds the `ExecutionResult` and `Target` data types to `Bolt`
and makes them available to Puppet using the new
`Puppet::DataTypes#create_type` introduced by PUP-8195.
Note! The data types were previously present in Puppet core and this
commit must be synchronized with an upgrade to use a puppet version
where PUP-8265 (covering the removal) has been merged.
> (BOLT-267) Add ExecutionResult and Target data types to Bolt

- lib/bolt/config.rb
- spec/bolt/config_spec.rb
- spec/lib/bolt_spec/integration.rb
Changes the default config file to `bolt.yaml`; continues to fall back
to `bolt.yml` if `bolt.yaml` not found. Issues a warning if both
`bolt.yml` and `bolt.yaml` exist.
> (BOLT-259) Update config file to default to `bolt.yaml`

- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/node.rb
- spec/bolt/cli_spec.rb
- spec/integration/ssh_spec.rb
Only note: if I do pass `--sudo`, it still asks for a password. It doesn't seem to actually do anything, but the prompt is misleading and annoying. It seems to be coming from https://github.com/puppetlabs/bolt/blob/master/lib/bolt/cli.rb#L197
```
$ bb task run exec command=whoami -n fgyhjd78bkyzjtv.delivery.puppetlabs.net -u lucy -p puppetlabs --sudo --tty
Please enter your privilege escalation password: 
Started on fgyhjd78bkyzjtv.delivery.puppetlabs.net...
Finished on fgyhjd78bkyzjtv.delivery.puppetlabs.net:
lucy
{
}
Ran on 1 node in 2.32 seconds
```
> (BOLT-264) add run-as to ssh config

- lib/bolt/cli.rb
- lib/bolt/config.rb
- spec/bolt/cli_spec.rb
I realized for the warning message around having `--sudo-password` without `--run-as` I left out the case where run-as is configured in a file. This fixes that issue, and gets rid of warnings in the spec tests.
> (BOLT-264) Don't show warning when run-as is configured in file

- spec/bolt/cli_spec.rb
- spec/fixtures/modules/sample/plans/init.pp
Tests the fix for PUP-8271 when included in Bolt.
> (maint) Add test that we can list plans with an init plan

- spec/bolt/cli_spec.rb
- spec/fixtures/modules/sample/tasks/params.json
Pulls in fix for PUP-8270 to only display the original type
specification rather than the expanded one that includes defaults.
> (BOLT-284) Fix extra type specification in `task show`

- modules/boltlib/lib/puppet/functions/run_task.rb
- modules/boltlib/spec/fixtures/modules/test/tasks/params.json
- modules/boltlib/spec/functions/run_task_spec.rb
This commit adds add check that the user defined argument hash passed to
the `run_task` function is an instance of the `Data` data type.
> (BOLT-283) Assert that run_task arguments are Data compatible

- lib/bolt/execution_result.rb
We're going to be refactoring this soon anyway at which point were
should design the to_s output better. We can't rely on Pops anyway if we
want to use this directly in bolt and this at least prevents infinite
recursion.
> (BOLT-294) Create local to_s method for ExecutionResults

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
- spec/fixtures/modules/results/plans/test_methods.pp
- spec/fixtures/modules/results/tasks/init.sh
- spec/integration/execution_result.rb
This ensures the datatypes we expose to plans are loaded before plans
are run. Otherwise there is a chance one will be returned by run_* but
it's methods will not be available.
> (BOLT-293) Load Datatypes before running plans.

- lib/bolt/cli.rb
- modules/boltlib/lib/puppet/functions/file_upload.rb
- modules/boltlib/lib/puppet/functions/run_command.rb
- modules/boltlib/lib/puppet/functions/run_script.rb
- modules/boltlib/lib/puppet/functions/run_task.rb
This commit adds `return_type ExecutionResult` to the `run_xxx` and
`file_upload` functions to ensure that the `ExecutionResult` data type
is loaded before an attempt is made to access it in Puppet.
This removes the need for pre-loading the data type.
> (BOLT-293) Add return_type to run_xxx and file_upload functions

- exe/bolt
- lib/bolt/cli.rb
- lib/bolt/outputter/human.rb
- spec/bolt/cli_spec.rb
- spec/bolt/outputter/human_spec.rb
Overhauls error handling when calling Puppet functions to catch exceptions before they're passed to the PAL compiler and rethrow them outside the PAL API. This allows us to work with undecorated exceptions and provide simpler error messages. It also prevents Puppet from logging when we would rather display the message directly.
For errors running Bolt subcommands:
- When using human-format output, print errors to stdout and color them
red rather than printing to stderr.
- When using json-format output, errors will no longer be reprinted on
stderr.
Errors parsing Bolt configuration will continue to be output on stderr.
> (BOLT-285) Overhaul error handling around Puppet code evaluation

- README.md
- lib/bolt/config.rb
- lib/bolt/node.rb
- lib/bolt/node/winrm.rb
- spec/bolt/cli_spec.rb
- spec/bolt/node/winrm_spec.rb
Support running arbitrary scripts on Windows as long as an extension
handler is registered and its extension added to PATHEXT.
Preserves support for running scripts without an extension as powershell
scripts, but will only do it if they have no extension (rather than when
they have an extension that doesn't match one of the built-in defaults:
.rb, .ps1, .pp).
> (BOLT-295) Support running arbitrary scripts on Windows

- acceptance/tests/plan_winrm.rb
- acceptance/tests/task_winrm.rb
Updates acceptance tests to create powershell scripts with a .ps1
extension, rather than relying on previous undocumented behavior of Bolt
appending .ps1 to scripts without an extension.
> (BOLT-295) Update acceptance tests to use .ps1 explicitly

- bolt.gemspec
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/executor.rb
- lib/bolt/formatter.rb
- lib/bolt/logger.rb
- lib/bolt/node.rb
- lib/bolt/node/ssh.rb
- lib/bolt/node/winrm.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/executor_spec.rb
- spec/spec_helper.rb
This commit swaps out the built-in Ruby Logger class for the Logging
gem, modeled after log4j.
This allows us much better control over which components log at which
levels, as well as allowing multiple log destinations (ie. both STDERR
and a file). It also includes built-in support for problems like
colorization that we would otherwise need to roll on our own.
> (BOLT-268) Switch from built-in Logger to Logging gem

- exe/bolt
- lib/bolt/cli.rb
- lib/bolt/error.rb
- lib/bolt/execution_result.rb
- lib/bolt/outputter/human.rb
- modules/boltlib/lib/puppet/functions/file_upload.rb
- modules/boltlib/lib/puppet/functions/run_command.rb
- modules/boltlib/lib/puppet/functions/run_script.rb
- modules/boltlib/lib/puppet/functions/run_task.rb
- modules/boltlib/spec/functions/file_upload_spec.rb
- modules/boltlib/spec/functions/run_command_spec.rb
- modules/boltlib/spec/functions/run_script_spec.rb
- modules/boltlib/spec/functions/run_task_spec.rb
- spec/fixtures/modules/results/plans/test_methods.pp
- spec/fixtures/modules/sample/plans/single_task.pp
Previously the run_* functions would return ExecutionResults containing
failures by default leaving it up to the plan author to check `ok`
before continting. Now run_* functions will check the ExecutionResult
and raise a RunFailure exception unless they are successful. The
'_abort' option can be passed to allow failing results to be returned
> (BOLT-222) run_* functions will raise an exception when they fail

- exe/bolt
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
Previously, as long as an operation was started successfully, bolt would
always exit 0, regardless of whether it actually completed successfully.
This meant that it was impossible to tell whether a task or command had
actually run on the nodes in question, only whether the task exists
or whether the command was properly interpreted by bolt.
For tasks, scripts, comamnds and file uploads, we now exit 2 if any node
fails. The behavior for plans is unchanged, as we still don't have a
solid definition of a plan "result". It can now be assumed that if bolt
exits 0, the operation completed successfully on every node.
> (BOLT-209) Return exitcode 2 when some nodes fail an operation

- lib/bolt/cli.rb
- lib/bolt/node/winrm.rb
Bolt defaults to using SSL for WinRM unless explicitly instructed
otherwise, but the default configuration for Windows hosts is to not accept
SSL connections for WinRM. Because of that, a common failure scenario is to
try to run bolt against a node and have it fail to connect because the SSL
port isn't open. Since we want to maintain a secure default, this commit
adds logic to detect that case and mention what the problem might be,
pointing users to try --insecure.
Another potential error case is trying to use SSL to connect to the non-SSL
port, which result in an extremely arcane OpenSSL error:
SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A:
unknown protocol
We now also detect this scenario and mention the likely cause.
Also corrected the description of the default …
> (BOLT-277) Provide pointers for common WinRM connection error cases

- README.md
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
Exception causes were added in Ruby 2.1. We want to continue using them.
Provide a fallback to inferior error handling for Ruby 2.0.
> (BOLT-311) Provide Ruby 2.0 fallback for exception causes

- acceptance/Rakefile
This reverts commit b6ed2a3. Ended up being unused by CI.
> Revert "(BOLT-252) change raketask to work with LAYOUT ENV"

- lib/bolt/executor.rb
- lib/bolt/node.rb
- lib/bolt/node/orch.rb
- lib/bolt/node/ssh.rb
- lib/bolt/node/winrm.rb
- lib/bolt/result.rb
- spec/bolt/node/orch_spec.rb
- spec/bolt/node/ssh_spec.rb
- spec/bolt/node/winrm_spec.rb
- spec/bolt/node_spec.rb
Removes the dumb wrappers around run_* from node. Moves logic around upload to a new UploadResult type.
Note that the deleted Node tests were mostly redundant with the Result tests.
> (maint) Refactor logic out of Node class

- acceptance/README.md
- acceptance/Rakefile
Since CI doesn't actually use the CI namespace I removed it from the Rakefile.
> (MAINT) remove ci namespace from acceptance rakefile

- lib/bolt/outputter/human.rb
- spec/bolt/outputter/human_spec.rb
This favors to_json over to_s when displaying the result of a plan. As a
side effect this will cause strings to be quoted which we may want to
reconsider later.
> (BOLT-286) Results and ResultSets should be displayed in json from plans

- lib/bolt/executor.rb
- lib/bolt/node.rb
- lib/bolt/node/orch.rb
- lib/bolt/node/ssh.rb
- lib/bolt/node/winrm.rb
- modules/boltlib/lib/puppet/functions/run_command.rb
- modules/boltlib/lib/puppet/functions/run_plan.rb
- modules/boltlib/lib/puppet/functions/run_script.rb
- modules/boltlib/lib/puppet/functions/run_task.rb
- modules/boltlib/spec/functions/run_command_spec.rb
- modules/boltlib/spec/functions/run_plan_spec.rb
- modules/boltlib/spec/functions/run_script_spec.rb
- modules/boltlib/spec/functions/run_task_spec.rb
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
- spec/bolt/node/orch_spec.rb
- spec/bolt/node/ssh_spec.rb
- spec/bolt/node/winrm_spec.rb
- spec/fixtures/run_as/test/files/id.sh
- spec/fixtures/run_as/test/plans/except.pp
- spec/fixtures/run_as/test/plans/id.pp
- spec/fixtures/run_as/test/plans/incept.pp
- spec/fixtures/run_as/test/tasks/id.sh
- spec/integration/run_as_spec.rb
Adds support for passing `_run_as => 'foo'` to `run_command`, `run_task`, `run_script`, and `run_plan` as part of a plan to tell them to run as a different user. Only applies to the SSH transport.
When specified on `run_plan`, it overrides any config settings for the duration of that plan and applies to all run function calls during that plan.
When specified on other run functions, overrides any config setting and prior plan setting when running that command/script/task on the targets.
> (BOLT-292) Add support for _run_as option to run functions

- lib/bolt/cli.rb
An issue with OpenSSL on Windows results in a very slow call to
`random_bytes` unless done very early in the program. Make sure we
initialize early to avoid this issue if we're doing anything complicated
on Windows (like using Puppet).
> (BOLT-303) Speed up tasks/plans when using winrm from Windows host

- lib/bolt/cli.rb
- lib/bolt/pal.rb
- spec/bolt/pal_spec.rb
- spec/spec_helper.rb
Previously the PAL class was only used for tests and was duplicated in
CLI. This converts CLI to interact with Puppet through the PAL clas
instead.
> (maint) Use Bolt::PAL for interactions with puppet

- .rubocop.yml
- lib/bolt/node/ssh.rb
Prior to this commit, bolt reported an error when Net-SSH
attempted to use an unconfigured ssh-agent.
Net-SSH offers a use_agent option which can be used to skip ssh-agent.
With this commit, bolt checks the environment to see if ssh-agent
is configured and its socket exists.
> (BOLT-81) check for ssh_agent

- Vagrantfile
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
- spec/bolt/node/ssh_spec.rb
- spec/bolt/node/winrm_spec.rb
- spec/integration/ssh_spec.rb
- spec/integration/winrm_spec.rb
- spec/lib/bolt_spec/conn.rb
- spec/signal_helper.rb
- spec/spec_helper.rb
Adds code which installs a SIGINT handler just before any command/script/task/plan is executed and removes it afterwards.
When invoked, the handler logs an appropriate message at the info level and then makes bolt exit promptly possibly leaving behind processes running on nodes.
Note that this does not prevent bolt from printing a stacktrace when it receives SIGINT while not executing any command/script/task/plan.
> (BOLT-194) Gracefully handle Ctrl-C

- lib/bolt/executor.rb
- lib/bolt/node.rb
- lib/bolt/node/ssh.rb
- lib/bolt/node/winrm.rb
- modules/boltlib/lib/puppet/functions/file_upload.rb
- modules/boltlib/spec/functions/file_upload_spec.rb
- spec/bolt/executor_spec.rb
- spec/bolt/node/ssh_spec.rb
Previously, uploaded files would be owned by the user making the SSH
connection. For `file upload`, that was plainly incorrect. For tasks and
scripts, that caused an issue where the uploaded file might or might not be
executable by the user in question, depending on how the tempdir was created
and what the original file permissions were.
We now always chown the file to the run-as user, to ensure that the user can
actually execute the file.
We also now support the `_run_as` argument to the `file_upload()` plan
function, which has the same semantics as passing `--run-as` to `bolt file
upload` on the CLI.
> (BOLT-218) Upload files as the run-as user

- lib/bolt/error.rb
- modules/boltlib/lib/puppet/functions/fail_plan.rb
- modules/boltlib/spec/functions/fail_plan_spec.rb
- spec/fixtures/modules/error/plans/args.pp
- spec/fixtures/modules/error/plans/err.pp
- spec/integration/fail_plan_spec.rb
- spec/lib/bolt_spec/integration.rb
This adds a fail_plan function to the boltlib module. This function
should be used to raise an error if a plan fails.
> (BOLT-123) Add fail_plan function to boltlib

- lib/bolt/result.rb
Previously attempting to print a Result data type would not display
anything other than the type name. Now it prints the contents as a hash.
Output now is
> Notice: Scope(<module>/foo/plans/init.pp, 11): Everything's fine, we're all fine here in {"node":"vagrant:vagrant@localhost:20022","status":"failure","result":{"_output":"","_error":{"kind":"puppetlabs.tasks/task-error","issue_code":"TASK_ERROR","msg":"The task failed with exit code 1:\n","details":{"exit_code":1}}}}
This is consistent with ResultSet's formatting of an array of Results.
> (maint) Add printable format for Result

- bolt.gemspec
FFI releases since 1.9.18 seem to be messed up. On Centos 7 they now try
to build libffi and require autoconf. Pin to 1.9.18 until that mess
settles.
> (maint) Pin FFI to 1.9.18

- lib/bolt/error.rb
- lib/bolt/outputter/human.rb
- lib/bolt/pal.rb
- modules/boltlib/lib/puppet/functions/run_plan.rb
- spec/fixtures/modules/error/plans/catch_plan.pp
- spec/fixtures/modules/error/plans/catch_plan_run.pp
- spec/fixtures/modules/error/plans/run_fail.pp
- spec/fixtures/modules/error/tasks/fail.sh
- spec/integration/fail_plan_spec.rb
- spec/lib/bolt_spec/integration.rb
In order to add module unit tests I'll have to spread the "handles errors" ruby 2.0 logic there. I think it's better to just wait until we drop ruby 2.0 support to test at that level.
> (BOLT-307) Add _catch_error option to run_plan

- lib/bolt/cli.rb
- lib/bolt/inventory.rb
- lib/bolt/inventory/group.rb
- lib/bolt/target.rb
- modules/boltlib/lib/puppet/functions/fail_plan.rb
- modules/boltlib/lib/puppet/functions/get_targets.rb
- modules/boltlib/lib/puppet/functions/run_command.rb
- modules/boltlib/lib/puppet/functions/run_script.rb
- modules/boltlib/lib/puppet/functions/run_task.rb
- modules/boltlib/spec/functions/file_upload_spec.rb
- modules/boltlib/spec/functions/get_targets_spec.rb
- modules/boltlib/spec/functions/run_command_spec.rb
- modules/boltlib/spec/functions/run_script_spec.rb
- modules/boltlib/spec/functions/run_task_spec.rb
- spec/bolt/cli_spec.rb
- spec/bolt/inventory/group_spec.rb
- spec/bolt/inventory_spec.rb
- spec/bolt/node/orch_spec.rb
- spec/bolt/node/ssh_spec.rb
- spec/bolt/node/winrm_spec.rb
- spec/bolt/node_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/bolt/target_spec.rb
- spec/integration/inventory_spec.rb
Adds support for targeting nodes by group. A group name can be used in-place of a target URI on the CLI
```
bolt command run 'hostname' --nodes ssh://host1,group_name
```
or in commands that accept a list of targets
```
run_command('hostname', ['ssh://host1', 'group_name'])
```
Note that the top-level group in inventory is named `all` unless otherwise specified.
Bolt plan run functions will now also split comma-separated list of target URIs, allowing the following to work via a CLI argument similar to `--nodes`
```
plan targets(String $targets) { run_command('hostname', $targets) }
```
A new function has been added to help resolve target input to a list of Targets, `get_targets`. It backs the Bolt plan run functions, so it will split on comma/space and translate groups to targets in that …
> (BOLT-318) Add support for targeting nodes by group

- lib/bolt/pal.rb
- spec/fixtures/modules/error/plans/nested.pp
- spec/integration/fail_plan_spec.rb
This is a temporary hack until we have a better way to generate a JSON
object for Error objects returned from plans. Since our output is based
on to_json now we need Error to support to_json to handle nested
objects.
> (PUP-8441) Monkey Patch to_json onto Puppet::DataTypes::Error

- README.md
- lib/bolt/cli.rb
- lib/bolt/inventory.rb
- spec/bolt/cli_spec.rb
- spec/bolt/inventory_spec.rb
- spec/fixtures/inventory/invalid.yml
Supports using wildcard `(*)` when passing nodes to `get_targets` to match multiple nodes if present in inventory.
Also fix some things.
> (BOLT-330) Allow wildcard matching node names in inventory

- lib/bolt/pal.rb
- spec/bolt/cli_spec.rb
Adds a note on viewing available tasks and plans when one cannot be
found.
> (BOLT-198) Add 'bolt task show', 'bolt plan show' to error messages

- lib/bolt/executor.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/transport/winrm.rb
- lib/bolt/transport/winrm/connection.rb
- spec/bolt/executor_spec.rb
- spec/bolt/transport/orch_spec.rb
This pull request adds new methods batch_task, batch_script, batch_command and
batch_upload to transports. These methods are used to indicate to a transport
that it should perform an operation on multiple nodes as part of a single
batch. This is specifically useful for the orch transport, which can run many
nodes as part of a single orchestrator job. Previously, it would create one
orchestrator job for each node.
This PR adds a batches() method to the transport, which is called by
the executor to determine how to batch runs. This allows all the
concurrency constructs to be moved entirely into the executor, so that
transports don't have to care about concurrency at all, other than the
requirement that they be thread-safe.
The executor now has a batch_execute() method that takes a list of …
> (BOLT-316) Batch tasks, etc when using the orch transport

- lib/bolt/executor.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
- modules/boltlib/lib/puppet/functions/run_task.rb
- modules/boltlib/spec/functions/run_command_spec.rb
- modules/boltlib/spec/functions/run_task_spec.rb
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
- spec/bolt/transport/orch_spec.rb
- spec/bolt/transport/ssh_spec.rb
- spec/bolt/transport/winrm_spec.rb
- spec/lib/bolt_spec/task.rb
Passes the Puppet Task type to transports rather than executable path
and input method. This allows transports to introspect tasks more
directly.
The Puppet Task type is an object that corresponds to the description at
https://github.com/puppetlabs/puppet/blob/5.4.0/lib/puppet/pops/pcore.rb#L43-L84.
> (BOLT-328) Pass Puppet Task type to transports

- lib/bolt/pal.rb
- modules/boltlib/lib/puppet/functions/file_upload.rb
- modules/boltlib/lib/puppet/functions/get_targets.rb
- modules/boltlib/lib/puppet/functions/run_command.rb
- modules/boltlib/lib/puppet/functions/run_script.rb
- modules/boltlib/lib/puppet/functions/run_task.rb
- modules/boltlib/types/targetspec.pp
(BOLT-342) Add TargetSpec type alias to replace TargetOrTargets
This moves the TargetOrTargets type alias out of the boltlib functions
and directly into the types/ directory of boltlib, as the new
Boltlib::TargetSpec alias. We also create a top-level TargetSpec alias
that refers to Boltlib::TargetSpec, so that users who wish to specify
that type in their plans can do it without having to namespace it under
Boltlib, which is purely an implementation detail.
The TargetSpec type accepts a String, a Target, or any set of Arrays of
those two types.
Specifically, TargetSpec represents the set of types that can be passed
to get_targets() and result in an Array[Target]. For the most part,
this type should be transparent to users, since it can be passed through
to other plans and to run_task, etc. …
> (BOLT-342) Add TargetSpec type alias to replace TargetOrTargets

- bolt.gemspec
- lib/bolt/cli.rb
Fixes gem packaging to include `bolt-modules`. Also remove an unused variable.
> (BOLT-333) Fix packaging, some rename cleanup

- lib/bolt/transport/base.rb
- spec/integration/fail_plan_spec.rb
- spec/integration/result_set_spec.rb
- spec/integration/run_as_spec.rb
- spec/integration/ssh_spec.rb
- spec/integration/target_spec.rb
- spec/lib/bolt_spec/conn.rb
Work on batching execution introduced a regression where errors would be
caught but not yielded to the event block passed to the executor.
Therefore the CLI would no longer report connection failures.
Restore yielding transport exceptions as error results if a block is
passed.
> (BOLT-344) Restore displaying errors for failed connection on the CLI

- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/transport/winrm.rb
- spec/bolt/transport/ssh_spec.rb
- spec/bolt/transport/winrm_spec.rb
Previously, we weren't always safely interpolating filenames and variables
into SSH commands. We now construct commands as arrays, using Shellquote to
properly escape them.
When interpolating task parameters to set powershell environment variables,
we were naively using just single quotes to escape the values. That doesn't
work if the value itself contains single quotes. We now use a single-quoted
here string to ensure that we get the literal value as intended.
> (BOLT-340) Properly escape strings when constructing commands

- lib/bolt/executor.rb
- spec/bolt/executor_spec.rb
This code tries to ensure that every Promise we construct will get a
value, no matter what happens during execution, in order to avoid a
deadlock. However, the call to create the error result itself had a bug,
causing... a deadlock. We now properly pass the target when creating the
error result, avoiding aforementioned deadlock.
> (maint) Properly construct error result of last resort

- exe/bolt-inventory-pdb
- lib/bolt_ext/puppetdb_inventory.rb
- spec/bolt_ext/puppetdb_inventory_spec.rb
This adds the bolt-inventory-pdb command which can be used to populate a
"template" inventory file with nodes based on PuppetDB queries.
The input to the command is basically an inventory file, except groups
should have a "query" field instead of a "nodes" field. The command will
read the input, execute each of the queries against PuppetDB, and print
a complete inventory with the "nodes" field populated for each group.
This command supports both token and cert auth to PuppetDB, and will
read the puppetdb.conf from the `puppet query` command if it's present.
> (BOLT-331) Add helper to generate an inventory from PuppetDB

- bolt.gemspec
- lib/bolt/transport/orch.rb
- spec/bolt/transport/orch_spec.rb
The orchestrator transport will now batch based on service-url,
token-file in addition to task-environment. Instead of reading config on
initialization is used the config for the first target of each batch to
create a client.
> (BOLT-346) Support different inventory orchestrator config

- lib/bolt/inventory.rb
- lib/bolt/inventory/group.rb
- spec/bolt/inventory/group_spec.rb
- spec/bolt/inventory_spec.rb
Node names in inventory now accept full URIs. To use config from a node
in inventory, you will need to exactly match the name in inventory when
specifying the node on the command-line or in a plan.
> (BOLT-337) Nodes in inventory accept full URI syntax

- lib/bolt/inventory/group.rb
- spec/bolt/inventory/group_spec.rb
This converts @nodes in an inventory group to a Hash so it can be more
quickly searched and prevented descending into a group when searching if
it does not contain the node. In practice this reduces the time of a
get_targets call for 18k targets from ~1min ~1s
> (perf) Improve performance when searching a large inventory.

- bolt.gemspec
This reverts commit 36e45eb7d5f8cc6bf7431281a5eb01fc428b21f9.
https://github.com/ffi/ffi/issues/607 has been resolved.
> Revert "(maint) Pin FFI to 1.9.18"

- lib/bolt_ext/puppetdb_inventory.rb
The error message when no input file is given is confusing, as it refers
to an argument that doesn't exist. Update the message to be accurate.
> (BOLT-357 Fix bolt-inventory-pdb help message

- lib/bolt/outputter/human.rb
- spec/bolt/outputter/human_spec.rb
Provides a summary at the end of a run of which nodes succeeded and
failed that can be copied and re-run via `--nodes`.
> (BOLT-345) Provide summary of successful and failed nodes

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
This change makes it possible to specify the `nodes` parameter of a plan by passing the `--nodes` option(s). (If more than one is passed then the values they specify are concatenated comma delimited.)
It is an error to specify both the `--nodes` option(s) and the `nodes` parameter. It is also an error to specify the `--nodes` option when running a plan which doesn't take the `nodes` parameter. The specified value *is* however passed to the plan as the `nodes` parameter, but that fails as that parameter is not expected by the plan.
While the use of the `--nodes` option in the way enabled by this commit is allowed it is not encouraged and so the option is not printed in the help messages related to `bolt plan` commands produced by `bolt help`. This necessitated creation of a subclass of the …
> (BOLT-336) Treat --nodes as the nodes parameter for run plan

- README.md
The tasks-hands-on-lab is a step-by-step introduction to Bolt. Provide a
prominent link for visitors new to Bolt to help them get started.
Fixes #318.
> (docs) Provide a link to the tasks-hands-on-lab

- lib/bolt/cli.rb
> (maint) Fix typo in 'inventory'

- Vagrantfile
- spec/bolt/transport/ssh_spec.rb
Restores the option of setting up the testing environment using Vagrant only (i.e. without having to use Docker).
The part of the Vagrant setup which duplicates (and potentially conflicts with) the Docker setup is disabled by default. One has to enable it explicitly by setting the `BOLT_TEST_USE_VAGRANT` environment variable to a non-empty value before running vagrant, e.g.:
```bash
BOLT_TEST_USE_VAGRANT=1 vagrant up
BOLT_TEST_USE_VAGRANT=1 vagrant destroy -f
```
> (maint) Restore support for Vagrant testing setup

- lib/bolt/config.rb
- lib/bolt/inventory.rb
- lib/bolt/inventory/group.rb
- lib/bolt/transport/orch.rb
- lib/bolt/util.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/inventory_spec.rb
- spec/bolt/transport/orch_spec.rb
- spec/integration/inventory_spec.rb
Moves task_environment to be specific to the pcp transport, and fixes specifying token-file and service-url in the Bolt config file (it worked correctly in the inventory file).
Fixes the inventory file config section so it uses structure and keys
that are consistent with the config file format. Previously it required
them to match the internal structure of the Bolt::Config object, which
led to a lot of inconsistency between inventory and config file formats.
So
```
config:
transports:
ssh:
host_key_check: false
```
is now
```
config:
ssh:
host-key-check: false
```
> (BOLT-352, BOLT-358) Fix config file and inventory file config bugs

- lib/bolt/executor.rb
- spec/bolt/executor_spec.rb
Previously, running a command across targets with different protocols
would try to reach the target on each protocol. Now correctly group by
protocols and only try to reach a particular target by its specified
protocol.
> (BOLT-363) Fix batching by protocol

- README.md
- bolt-modules/boltlib/lib/puppet/functions/run_task.rb
- bolt-modules/boltlib/spec/functions/run_task_spec.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/inventory_spec.rb
Adds support for the `pcp/local-validation` configuration setting.
When set to `false` then, under the condition that a task is run on targets exclusively using the `pcp` transport, no validation of the specified task parameters against the local task definition is performed (the definition is not even loaded so the task doesn't even need to be installed locally).
The validation still takes place if the task is run on targets which use different transports (which may or may not include the `pcp` transport).
> (BOLT-356) Add pcp/local-validation setting

- lib/bolt/cli.rb
- lib/bolt/inventory.rb
- spec/bolt/cli_spec.rb
- spec/bolt/inventory_spec.rb
This adds the ability for bolt to accept inventory data from an
environment variable instead of a file. This can be useful when running
bolt programatically.
> (BOLT-377) Accept inventory in environment variable

- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/util.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/inventory_spec.rb
- spec/bolt/transport/ssh_spec.rb
This allows private key data to be stored directly in config in addition
to the path to private key files.
> (BOLT-379) Accept key-data in addition to the path of a key file

- acceptance/README.md
- acceptance/Rakefile
- acceptance/config/package/options.rb
- acceptance/setup/package/pre-suite/015_install_puppet_agent_repo.rb
- acceptance/setup/package/pre-suite/020_install.rb
This adds the `test:package` rake task, which runs the bolt acceptance
tests against a dev package.
> (BOLT-348) Add package-based install method to acceptance tests

- CONTRIBUTING.md
- README.md
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/transport/winrm.rb
- lib/bolt/transport/winrm/connection.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/inventory_spec.rb
- spec/integration/inventory_spec.rb
- spec/integration/winrm_spec.rb
Currently Bolt doesn't support ignoring SSL verification for use with self-signed certificats.
To support this i've introduced a new command line switch and config option under the WinRM transport called `ssl-verify` that can be used from the CLI with the `--[no-]ssl-verify` option.
In the interest of security i've continued to use the "secure by default" paradigm and make the default value of `--ssl-verify` be `true`
> (BOLT-389) Initial implementation of WinRM --[no-]ssl-verify

- lib/bolt/inventory.rb
- spec/bolt/inventory_spec.rb
When added to inventory implicitly, it becomes part of the `all` group.
Instead default `transport` to `local` only if the name `localhost`
isn't found in inventory when creating the Target.
> (BOLT-388) Avoid adding 'localhost' to inventory

- README.md
facts.os.family would return (e.g.) 'RedHat', not 'Linux'.  facts.kernel works instead.
> README.md - fixed the sample '--query' command

- Gemfile
- Rakefile
- locales/bolt.pot
- locales/config.yaml
Adds some basic gettext setup to ensure CI jobs for updating the pot
file don't break. This is also necessary preparation for localization.
> (maint) Add gettext:update_pot Rake task

- lib/bolt/pal.rb
- spec/integration/parsing_spec.rb
When resolving types to display as part of `bolt plan show`, ensure
`TargetSpec` is still an alias in the compiler so that types using that
name resolve to an existing type.
> (BOLT-407) Ensure TargetSpec is aliased while resolving types

- lib/bolt/cli.rb
Remove `Eg.` as inconsistent docs practice. Update the documentation and example.
New output
```
-n, --nodes NODES                Node(s) to connect to in URI format or group name (Optional)
--nodes localhost,node_group,ssh://nix.com:2222,winrm://windows.puppet.com
* URI format is [protocol://]host[:port]
* NODES can be a comma-separated list of URI format and/or group names
* NODES can also be '@<file>' to read from a file or '-' to read from stdin
* Windows nodes must specify protocol with winrm:// unless otherwise configured
* protocol is `ssh` by default; may be ssh, winrm, pcp, local
* port defaults to `22` for SSH
* port defaults to `5985` or `5986` for WinRM, based on the --[no-]ssl setting
```
> (BOLT-365) Update nodes usage

- lib/bolt/transport/local.rb
- lib/bolt/transport/local/shell.rb
- spec/bolt/transport/local_spec.rb
Open3.capture3() fails if the value of any provided environment variable
isn't a string, so now we stringifying them. This behavior matches what the
SSH transport does, by just using whatever the Ruby coercion to string
does, without any special handling for structured data.
This also fixes an issue with the local transport raising misleading errors,
effectively assuming that every exception was a tmpdir creation failure.
> (maint) Stringify environment variables with local transport

- lib/bolt/pal.rb
- spec/integration/parsing_spec.rb
When checking whether plan parameter types matched the JSON-parsed
input, we failed to actually retrieve the parameter types so we always
used the parsed result. Fix so we retrieve the parameter types
correctly.
> (BOLT-432) Correctly retrieve types for plan parameters

- lib/bolt_ext/puppetdb_inventory.rb
Fixes `bolt-inventory-pdb` so it works again by requiring all necessary
components after code refactor.
> (BOLT-433) Fix requires for bolt-inventory-pdb

- lib/bolt/error.rb
- lib/bolt/pal.rb
- lib/bolt/util.rb
- spec/integration/fail_plan_spec.rb
- spec/lib/bolt_spec/integration.rb
Currently none of the Datatypes we expect to support can contain
non-data attributes. Therefore to handle the Error Datatype we only have
to walk a single top level data object so we can do that and drop the
monkey patch. We don't restrict plans to returning only expected data
types. Essentially we previously supported PlanReturn as defined below
and we should either make that official or handle pcore transformation
explicitly.
type PlanReturn = Variant[Data, Error, Result, ResultSet, Target,
Array[PlanReturn], Hash[String, PlanReturn]]
> (PUP-8441) Handle serializing Puppet Error Datatype better

- lib/bolt/inventory.rb
- spec/fixtures/modules/facts/plans/emit.pp
- spec/fixtures/modules/facts/plans/init.pp
- spec/fixtures/modules/vars/plans/emit.pp
- spec/integration/inventory_spec.rb
When a node is not in inventory or doesn't have facts/vars set, return
an empty hash rather than nil so that the plan doesn't error.
> (BOLT-435) Return empty hash rather than nil when not in inventory

- Gemfile
- lib/bolt/pal.rb
- modules/aggregate/spec/fixtures/modules/test_task/tasks/init.sh
- modules/aggregate/spec/plans/count_spec.rb
- modules/aggregate/spec/plans/node_spec.rb
- modules/aggregate/spec/spec_helper.rb
- modules/canary/spec/fixtures/modules/test_task/tasks/init.pp
- modules/canary/spec/plans/init_spec.rb
- modules/canary/spec/spec_helper.rb
- spec/lib/bolt_spec/plans.rb
- spec/lib/bolt_spec/plans/mock_executor.rb
This adds a plan test helper with a mock executor capable of stubbing
out task calls. This is a prototype for how plan testing unit testing in
the large puppet ecosystem. Eventually this functionality should be
moved into rspec-puppet but that is probably blocked in bolt
unvendoring puppet
Questions:
- Is this too similar to rspec-mock
- Does the general workflow make sense
> (BOLT-397) Add helpers for testing plans and mocking run_task

- acceptance/README.md
- acceptance/Rakefile
The main change here is to not generate a new hosts file if Jenkins has already done so. We can tell this has happened if BEAKER_HOSTS is set, so in the Rakefile we'll just skip host file generation if that env var is set.
The rest of the PR is changes to the README that were made prior to updating ci-job-configs that I didn't want to get rid of.
> (BOLT-349) Make acceptance Rakefile env vars valid bhg strings

- lib/bolt/transport/winrm.rb
Exceptions running a script will be written to stderr before exiting,
with the result that Bolt logs them to DEBUG.
> (maint) Add better error logging for WinRM

- bolt-modules/boltlib/lib/puppet/functions/puppetdb_fact.rb
- bolt-modules/boltlib/spec/functions/puppetdb_fact.rb
- lib/bolt/cli.rb
- lib/bolt/executor.rb
- lib/bolt/pal.rb
- lib/bolt/util/on_access.rb
- modules/puppetdb_fact/spec/plans/init_spec.rb
- modules/puppetdb_fact/spec/spec_helper.rb
- spec/bolt/util/on_access_spec.rb
- spec/lib/bolt_spec/pal.rb
- spec/lib/bolt_spec/plans.rb
Note that it places expectations on the executor directly. The
`puppetdb_fact` method may move out of the executor directly, so we
don't add an explicit helper to BoltSpec::Plans.
> (maint) Add spec tests for the puppetdb_fact plan

- lib/bolt/cli.rb
A mess of improvements on the Bolt help output.
More organized output
```
Usage: bolt <subcommand> <action> [options]
Available subcommands:
bolt command run <command>       Run a command remotely
bolt file upload <src> <dest>    Upload a local file
bolt script run <script>         Upload a local script and run it remotely
bolt task show                   Show list of available tasks
bolt task show <task>            Show documentation for task
bolt task run <task> [params]    Run a Puppet task
bolt plan show                   Show list of available plans
bolt plan show <plan>            Show details for plan
bolt plan run <plan> [params]    Run a Puppet task plan
Run `bolt <subcommand> --help` to view specific examples.
where [options] are:
-n, --nodes NODES                Identifies the …
```
> (maint) CLI help improvements

- lib/bolt/cli.rb
The tmpdir is a property of the transport/target, not part of the local
run context. Move it to the Transports section of help output.
> (maint) Move tmpdir to Transports section

- bolt-modules/boltlib/lib/puppet/functions/file_upload.rb
- bolt-modules/boltlib/lib/puppet/functions/run_command.rb
- bolt-modules/boltlib/lib/puppet/functions/run_script.rb
- bolt-modules/boltlib/lib/puppet/functions/run_task.rb
- bolt-modules/boltlib/spec/functions/file_upload_spec.rb
- bolt-modules/boltlib/spec/functions/run_command_spec.rb
- bolt-modules/boltlib/spec/functions/run_script_spec.rb
- bolt-modules/boltlib/spec/functions/run_task_spec.rb
- lib/bolt/cli.rb
- lib/bolt/executor.rb
- lib/bolt/pal.rb
- lib/bolt/transport/orch.rb
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
- spec/bolt/transport/orch_spec.rb
- spec/integration/inventory_spec.rb
The `run_task()`, `run_script()`, `run_command()`, and `file_upload()`
functions can now take a positional "description" argument after the target. If
supplied, the description will be logged at notice level when running that
step, and will also be set as the job description in orchestrator.
There is also now a `--description` argument which can be used to specify the
description for a one-off job from the CLI. That description will similarly be
logged and sent to orchestrator.
> (BOLT-410) Allow descriptions for run_* functions and CLI

- acceptance/setup/common/pre-suite/010_install_ruby.rb
- acceptance/setup/gem/pre-suite/020_install.rb
- acceptance/setup/git/pre-suite/020_install.rb
- acceptance/tests/plan_ssh.rb
- acceptance/tests/plan_winrm.rb
This also includes improvements to speed up gem installation during tests.
Previously, we were installing build tools and building native extensions for
gem dependencies. Now we install the OS packages for those dependencies
instead. We also now install with --no-ri and --no-rdoc, which cuts the install
time by half.
> (maint) Speed up gem installation during tests

- lib/bolt/cli.rb
The new description flag was accidentally grouped with authentication
options while merging multiple changes. Move it up to primary options as
something we encourage people to use.
> (maint) Move description to primary options

- spec/fixtures/modules/sample/plans/single_task.pp
- spec/integration/logging_spec.rb
Add a test that description, when passed as an argument to a run action,
is included in logging.
> (BOLT-410) Add test that description is used in logging

- modules/facts/tasks/powershell.ps1
This commit improves the OS version detection if/else block by
converting it to a switch statement. This reduces line count and is
easier to read, which also brings it into following PowerShell coding
style guidelines.
> (maint) Improve facter powershell task syntax

- CONTRIBUTING.md
- Gemfile
- Puppetfile
This allows users to manage packages, services, and puppet.conf settings in
an out-of-the-box bolt install.
This adds a Puppetfile to manage the set of modules we bundle with bolt. It
also adds a development dependency on r10k to apply the Puppetfile.
> (BOLT-334) Bundle the package, service, puppet_conf modules

- lib/bolt/inventory/group.rb
- spec/bolt/inventory/group_spec.rb
- spec/bolt/inventory_spec.rb
Previously, the code needed to support nested inventory groups was
present, but with an explicit check to disable it. This commit removes
that check and fixes a bug where variables were merged in reverse order
compared to other values.
Groups can now be defined within other groups. Variables/config prefer the
first "branch" (top-level group) that the node matches, and use the most
deeply nested (most specific) group within that branch. In other words,
we use depth-first lookup, and merge across branches.
A group is not allowed to be defined as a child of multiple parent
groups. This triggers the same error as redefining a group did
previously.
> (BOLT-439) Support inventory groups defined within other groups

- pre-docs/bolt_installing.md
Highlight packages as the primary install method, with installing from
gem available as a last option.
> (BOLT-426) Add pre-docs for installing

- lib/bolt/pal.rb
- lib/bolt/pal/logging.rb
- spec/bolt/cli_spec.rb
- spec/spec_helper.rb
This adds a stub 'logging' logdestination type to Puppet that passes log
messages through to the Logging logger used by bolt. This causes
Puppet's logs to be logged alongside bolt logs, with the same format.
This also means that Puppet logs properly get logged to files in
addition to the console.
This also fixes a bug where we weren't actually logging in Puppet,
because `with_puppet_settings` was resetting the log destinations to
empty. We now reconfigure logging every time we re-initialize settings,
so that we always log.
We now use the 'debug' log level for Puppet, causing it to "log"
*everything* (which really means pass it through to the Logging logger),
allowing the Logging logger to decide which messages to actually log.
> (BOLT-455) Use bolt logger from puppet

- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/executor.rb
- lib/bolt/logger.rb
- pre-docs/bolt_configuration_options.md
- pre-docs/bolt_options.md
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
- spec/bolt/logger_spec.rb
- spec/integration/logging_spec.rb
- spec/lib/bolt_spec/integration.rb
Previously, we used a fairly overbearing log format for the console,
including the complete ISO-8601 date time with microsecond-precision, the
name of the class doing the logging, and the log level. We now print only
the message itself, excluding the timestamp, logger name and the log level.
We now use colors to indicate the log level on the console, with red
representing errors, yellow for warnings, green for notices and the rest
uncolored.
Because the context can sometimes be useful, we continue to include it in
the log format we use for log files. We also exclude colors for log files.
To make up for the lack of timestamps, we now include a duration in the
"finished" message for every step.
We also now only list the nodes targeted by an action if there are 5 or
fewer; otherwise we just …
> (BOLT-453) Improve logging to the console

- Puppetfile
Brings in agentless tasks for Windows and Linux.
> (BOLT-482) Bump puppetlabs-service to 0.3.1

- acceptance/Rakefile
This commit updates the rototiller tasks for testing bolt to use 'bundle exec
beaker' instead of just 'beaker' when executing beaker runs
For some reason the tasks fail in jenkins runs with 'beaker not found' when we
do not include the 'bundle exec'. We attempted to investigate but never
reached a conclusion so for now we will use this to allow jenkins to work
> (BOLT-348) Update test tasks to use cmd = 'bundle exec beaker'

- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
- bolt.gemspec
- lib/bolt/cli.rb
- lib/bolt/error.rb
- lib/bolt/executor.rb
- lib/bolt/pal.rb
- lib/bolt/plan_result.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/orch/connection.rb
- modules/aggregate/spec/plans/count_spec.rb
- modules/aggregate/spec/plans/node_spec.rb
- modules/canary/spec/plans/init_spec.rb
- modules/facts/spec/plans/info_spec.rb
- modules/facts/spec/plans/init_spec.rb
- modules/facts/spec/plans/retrieve_spec.rb
- modules/puppetdb_fact/spec/plans/init_spec.rb
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
- spec/bolt/transport/orch_spec.rb
- spec/lib/bolt_spec/plans.rb
When a plan is run the orchestrator transport will send the plan_start
command the first time a task runs on a node through that orchestrator.
Every task will be run with the plan_task command instead of the task
command and before exiting bolt will send a plan_finish command with the
result to each orchestrator that was used during the plan.
> (BOLT-372) Send information to orchestrator when running a plan

- acceptance/setup/package/pre-suite/020_install.rb
The last change to how wo setup packages broke install on Ubuntu. Switch
to using a beaker-puppet helper that works correctly for all platforms,
and was recently fixed (beaker-puppet 0.13.3) to correctly install
generic MSIs on Windows rather than assume a puppet-agent MSI.
> (maint) Fix CI on Ubuntu

- acceptance/Rakefile
Use default test platforms that work with `test:git` and `test:gem`.
CentOS 7's Ruby is too old to be the default controller.
> (maint) Update test defaults to work for test:git

- lib/bolt/transport/ssh/connection.rb
- pre-docs/writing_tasks.md
- spec/bolt/transport/ssh_spec.rb
This may result in tasks that do not specify input method and accept
stdin not causing a permission error when run with sudo if the user
does not have the appropriate permissions. That is preferable to running
with no environment variables set.
1. Users who don't specify input method are more likely to use
environment variables
2. Running with unset environment variables may be dangerous if the task
author was relying on parameter validation.
> (BOLT-505) pass -E to sudo when using environment variable params

- modules/facts/tasks/bash.sh
- modules/facts/tasks/powershell.ps1
- modules/facts/tasks/ruby.rb
The facter_task module does this, and is a frequent request whenever we
do something that doesn't include Puppet facts.
> (BOLT-460) Include Puppet facts in facts module

- bolt-modules/boltlib/lib/puppet/functions/without_default_logging.rb
- spec/fixtures/modules/logging/plans/without_default.pp
The functionality was implemented as `without_plan_logging`, but
original plan was to use `without_default_logging`. Update names to
`without_default_logging`.
> (BOLT-451) Fix naming for `without_default_logging`

- .travis.yml
- bolt-modules/boltlib/lib/puppet/functions/without_default_logging.rb
- spec/integration/logging_spec.rb
Steps in the script section of .travis.yml are not executed as scripts themselves so calling exit in them halts the entire "script" section and masks any other failures.
> make travis fail

- lib/bolt/config.rb
Previously, setting `transport` in the config file did nothing. Now it
can be used to set the default transport, which is useful in
environments which primarily use winrm or pcp.
> (BOLT-484) Allow transport to be set in the config file

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
When executing a plan, allow targets to be built from PDB query.
> (BOLT-486) Plans accept targets via puppetdb

- spec/integration/modules/facts_spec.rb
Temporary fix so tests will pass. Bug BOLT-518 should address this.
> (MAINT) Travis test failure Ubuntu image update

- lib/bolt/puppetdb/client.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/util/on_access.rb
- spec/lib/bolt_spec/integration.rb
- passing splat keyword args as single hash
- Style/MethodMissing was split into two separate cops
- save navigation on map
> (MAINT) Corrections based on Rubocop 0.56.0

- bolt-modules/boltlib/lib/puppet/functions/puppetdb_fact.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/error.rb
- lib/bolt/inventory.rb
- lib/bolt/logger.rb
- lib/bolt/pal.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
- lib/bolt/util.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/inventory_spec.rb
CLIError was being used as a generic error in many parts of bolt. This
limits the use of CLIError to the CLI class. In most cases error that
were CLIErrors become Bolt::ValidationError or generic Bolt::Errors.
CLIError is still probably overused in the CLI class.
> (BOLT-508) Stop using CLIError outside of Bolt::CLI

- lib/bolt/executor.rb
- spec/bolt/executor_spec.rb
Initializing CachedThreadPool with max_threads does not cap concurrency as expected. Use ThreadPoolExecutor instead.
> (BOLT-520) Enforce concurrency limit

- modules/facts/tasks/bash.sh
- spec/integration/modules/facts_spec.rb
Rastasheep/ubuntu-sshd no long comes with lsb_release. Use /etc/os-release to parse ubuntu facts.
> (BOLT-518) Fact task incorrect OS Family

- lib/bolt/outputter/human.rb
- spec/bolt/outputter/human_spec.rb
A prior change introduced PlanResult, an object that wraps all plan
output. That broke the message when no results are returned; fix it.
> (BOLT-532) Restore message when plan returns no results

- acceptance/config/gem/options.rb
- acceptance/config/git/options.rb
- acceptance/config/package/options.rb
- acceptance/setup/common/pre-suite/050_build_bolt_inventory.rb
- acceptance/tests/command_ssh.rb
- acceptance/tests/command_winrm.rb
- acceptance/tests/cross_platform_task.rb
- acceptance/tests/file_ssh.rb
- acceptance/tests/file_winrm.rb
- acceptance/tests/plan_ssh.rb
- acceptance/tests/plan_winrm.rb
- acceptance/tests/script_ssh.rb
- acceptance/tests/script_winrm.rb
- acceptance/tests/task_ssh.rb
- acceptance/tests/task_winrm.rb
- bolt-modules/boltlib/lib/puppet/functions/run_task.rb
- bolt-modules/boltlib/lib/puppet/functions/set_feature.rb
- bolt-modules/boltlib/spec/functions/run_task_spec.rb
- lib/bolt/inventory.rb
- lib/bolt/target.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
- pre-docs/writing_tasks.md
- spec/bolt/cli_spec.rb
- spec/bolt/target_spec.rb
- spec/lib/bolt_spec/task.rb
- spec/pal/features_spec.rb
This change adds logic to the existing transports to dynamically select the
appropriate task implementation based on the available features of a
target. Target now has a select_impl() method which, given a task and an
optional list of "additional" features, will return the path to the first
suitable executable. The "additional" features are passed by the transport
and account for any features which are directly implied to be present
based on the transport (ie. 'shell' for ssh and 'powershell' for winrm).
This allows a single task to have multiple implementations for different
platforms and for Bolt to choose the appropriate one for each target at
runtime.
A new set_feature() function in puppet language can be used to add and
remove features on a target.
> (BOLT-135) Support multiple task implementations

- bolt.gemspec
Without this, gem builds will fail when using tasks and plans because
Puppet won't find its dependency.
> (BOLT-135) Add semantic_puppet dependency to gemspec

- acceptance/setup/common/pre-suite/050_build_bolt_inventory.rb
Previously, we were hard-coding /root as the root home directory for all
platforms. On Windows and Mac, that home directory is different, so we
now check the platform we're on and determine the directory dynamically.
> (maint) Properly detect root homedir on windows/mac

- pre-docs/bolt_configuration_options.md
With BOLT-366, more transport-specific config options were exposed in
the global config. Update docs to reflect the new options.
Resolves #448.
> (maint) Update docs with new config options

- acceptance/setup/common/pre-suite/050_build_bolt_inventory.rb
The previous hard-coded Windows path was incorrect, because cygwin has
its own home directory (set by $HOME) which is what bolt uses for the
inventory.
Now with extra `I Tested It`!
> (maint) Use $HOME to determine home directory on all platforms

- modules/facts/plans/retrieve.pp
- modules/facts/spec/plans/info_spec.rb
- modules/facts/spec/plans/init_spec.rb
- modules/facts/spec/plans/retrieve_spec.rb
- modules/facts/tasks/init.json
- spec/bolt/cli_spec.rb
Adds `facts` metadata-only task that dispatches to specific
implementations based on features in transports. Use it to simplify
`facts` plans.
> (BOLT-399) Add `facts` metadata task

- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- pre-docs/bolt_configuration_options.md
- spec/bolt/config_spec.rb
- spec/bolt/transport/ssh_spec.rb
This adds a new config option run-as-command to the ssh transport. This
command can be used to override the sudo support either to use a
different command than sudo or to specify which sudo options to use. It
will not use the sudo-password option.
> (BOLT-521) Allow users to specify the run-as-command for ssh

- bolt-modules/boltlib/spec/functions/run_task_spec.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
- spec/bolt/cli_spec.rb
- spec/bolt/transport/winrm_spec.rb
- spec/fixtures/modules/sample/tasks/ps_noop.ps1
- spec/integration/winrm_spec.rb
- spec/lib/bolt_spec/task.rb
When powershell task is run over winrm, parameters are passed by default as powershell named arguments.
> (BOLT-536) Default input method for PowerShell

- lib/bolt/transport/ssh/connection.rb
- spec/bolt/transport/ssh_spec.rb
The `chown <user>:` syntax to inherit group from user is not portable.
Use `id -g <user>` to get the user's group and explicitly use it when
changing ownership to make it more portable.
Note that this will still fail on some platforms with very old versions
of `id` that don't support `-g`, such as the default `id` on Solaris 10.
> (BOLT-545) Explicitly set group based on id -g for chown

- lib/bolt/transport/ssh/connection.rb
AIX, and possibly other such systems, doesn't have `mktemp` available by
default. That was causing remote tempdir creation to fail. Since we
already have a functioning alternative using UUIDs, we now use that in
all cases. If the user supplied an explicit tmpdir, that remains the
parent, and we default to /tmp otherwise.
> (BOLT-546) Avoid mktemp to work on AIX

- lib/bolt/pal.rb
- lib/bolt/puppetdb/config.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/util.rb
- lib/bolt_ext/puppetdb_inventory.rb
- pre-docs/bolt_configure_puppetdb.md
- pre-docs/inventory_file_generating.md
- spec/bolt/puppetdb/config_spec.rb
- spec/signal_helper.rb
Try to load puppetdb config first from user supplied configfile, second from ~/.puppetlabs/client-tools, finally from /etc/puppetlabs/client-tools. This simplifies Bolt-PE integration out of the box.
> (BOLT-544) add secondary default for puppetdb.conf

- Gemfile
- acceptance/setup/common/pre-suite/050_build_bolt_inventory.rb
- lib/bolt/analytics.rb
- lib/bolt/cli.rb
- pre-docs/bolt_analytics.md
- pre-docs/bolt_installing.md
- spec/bolt/analytics_spec.rb
- spec/spec_helper.rb
Every time the user runs a command (`bolt task run`, `bolt plan show`),
we now submit a "screenview" event to Google Analytics, where the
"screen" is the command that was run. The information included is:
a) bolt version
b) user locale
c) the "screen" run
d) a unique, random user id
IP addresses are anonymized, and we do *not* include the name of the
task or plan run.
The unique ID is stored in ~/.puppetlabs/bolt/analytics.yaml. That
file also accepts the setting `disabled: true` which will disable the
collection of analytics.
To avoid polluting the data with development and test runs, we also use
a BOLT_DISABLE_ANALYTICS environment variable, which is automatically
set when running via bundler and while running the tests.
Analytics submission is performed in the background and errors are …
> (BOLT-488) Submit data to Google Analytics for each command invocation

- Dockerfile
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/transport/winrm/connection.rb
- spec/bolt/transport/ssh_spec.rb
When run-as is requested without a password but the password is required we should fail. However when attempting that against targets where the user's login shell is bash, a 2nd sudo attempt would hang. Fix the issue causing us to attempt a 2nd sudo in the first place, and close the connection after when no password is available to prevent future issues.
> (BOLT-534) Fix sudo hanging when user shell is bash

- bolt-modules/boltlib/spec/spec_helper.rb
- lib/bolt/analytics.rb
- lib/bolt/pal.rb
- modules/aggregate/spec/spec_helper.rb
- modules/canary/spec/spec_helper.rb
- modules/facts/spec/spec_helper.rb
- modules/puppetdb_fact/spec/spec_helper.rb
- pre-docs/bolt_analytics.md
- spec/bolt/analytics_spec.rb
- spec/spec_helper.rb
- vendored/require_vendored.rb
This adds a new custom dimension for operating system. We use Facter to
compute the value, and we do so asynchronously after creating the
analytics client. The overhead to load facter and compute OS is ~100ms,
which should be negligible for all but the speediest Bolt invocations.
> (BOLT-489) Report user OS and version to google analytics

- .rubocop.yml
- bolt-modules/boltlib/lib/puppet/datatypes/target.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/ssh.rb
- spec/lib/bolt_spec/conn.rb
Disable ones where style doesn't fit existing practice. Fix unnecessary
ternary operators.
> (maint) Address new rubocop cops

- lib/bolt/cli.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/orch/connection.rb
- spec/bolt/cli_spec.rb
- spec/bolt/transport/orch_spec.rb
If a plan includes any targets that use the PCP transport, send
finish_plan to the configured transport variants after all plan
execution has finished with results and status.
Error responses to finish plan are logged at debug level.
> (BOLT-547) Finish plan when execution ends

- lib/bolt/analytics.rb
- lib/bolt/cli.rb
- lib/bolt/executor.rb
- pre-docs/bolt_analytics.md
- spec/bolt/analytics_spec.rb
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
We now send one event per-transport when a transport is first
initialized. This allows us to understand how commonly each transport is
being used and whether they're being used together.
> (BOLT-490) Collect events for each transport used

- lib/bolt/analytics.rb
- lib/bolt/cli.rb
- lib/bolt/inventory.rb
- spec/bolt/analytics_spec.rb
We now include the number of nodes and number of groups (as custom
dimensions 2 and 3) in the screen_view hit submitted whenever a bolt
command is run.
This also adds a mapping of custom dimension name to id, to make it
easier to correctly match fields and values.
> (BOLT-562) Send inventory size with screen_view

- .gitignore
- Gemfile
- Rakefile
`rake docs` generates docs for Bolt, it's core functions, and packaged
modules.
`rake json` generates a JSON file containing docs for Bolt's core
functions.
> (BOLT-559) Add `rake docs` and `rake json` to generate Bolt docs

- lib/bolt/analytics.rb
- lib/bolt/cli.rb
- pre-docs/bolt_analytics.md
We now include the number of targeted nodes with the screen_view hit
that we submit each time a bolt command is run. This counts the
*resolved* targets, after groups and PuppetDB queries have been taken
into consideration. This does not account for the number of nodes run as
part of a plan, unless those nodes were passed using --nodes or --query.
> (BOLT-491) Collect number of targeted nodes for each bolt command

- pre-docs/writing_plans.md
Since we now document Bolt functions by generating docs from the code we want
to remove static function documentation and point users to the reference docs
instead.
> (BOLT-561) De-duplicate pre-docs with strings docs

- lib/bolt/transport/orch.rb
- lib/bolt/transport/orch/connection.rb
- spec/bolt/transport/orch_spec.rb
Orhcestrator will reject requests with metaparams in the params.
Metaparams should be stripped from a task before sending a request to
orchestrator. Some like noop will have to be added back in elsewhere in
the request.
> (BOLT-597) Don't send metaparams as params to orchestrator

- lib/bolt/outputter/human.rb
- spec/bolt/outputter/human_spec.rb
Previously `task show <task>` would include `--nodes, -n <node-name>` in
the USAGE string. It's redundant and slightly confusing to include both
`--nodes` and `-n` as option. Use just one to simplify the usage
suggestion.
> (maint) Simplify the usage string for task info

- pre-docs/inventory_file.md
The feature implemented is `vars`. Docs incorrectly referred to `vals`;
correct to be consistent with the implementation.
> (maint) Correct docs from `vals` to `vars`

- Rakefile
- bolt-modules/boltlib/lib/puppet/functions/add_facts.rb
- bolt-modules/boltlib/lib/puppet/functions/fail_plan.rb
- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
- bolt-modules/boltlib/lib/puppet/functions/set_feature.rb
- bolt-modules/boltlib/lib/puppet/functions/vars.rb
- bolt-modules/boltlib/lib/puppet/functions/without_default_logging.rb
- pre-docs/reference.md.erb
Drop the separate JSON and Markdown docs generation, and standardize on customized markdown output for the function reference. REFERENCE.md is generated with `rake docs`.
> (BOLT-591) Standardize on markdown output for function reference

- lib/bolt/inventory.rb
- pre-docs/bolt_options.md
- spec/integration/inventory_spec.rb
When bolt is invoked from a windows OS with the target of localhost, do not set the default transport to 'local'
> (BOLT-583) Do not default to localhost on windows

- pre-docs/reference.md.erb
Drop TOC, it doesn't map well to the docs page format. Also use headers
for signatures rather than line separators that also don't work well
with the docs page format.
> (BOLT-591) Update REFERENCE.md layout

- exe/bolt_catalog
- lib/bolt/catalog.rb
This adds a POC new command to generate catalogs and JSON AST from
manifests. The code is kept separate from most of bolt since it's a
different process and we should expect it to be completely rewritten.
> (BOLT-567) Add command to generate catalogs

- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/outputter.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- spec/bolt/cli_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/bolt/outputter/json_spec.rb
- spec/lib/bolt_spec/integration.rb
Adds a `--trace` option that prints error backtraces.
> (maint) Add `--trace` option

- lib/bolt/transport/winrm.rb
- spec/bolt/transport/winrm_spec.rb
- spec/fixtures/complex_params/input.json
- spec/fixtures/complex_params/output
- spec/fixtures/modules/sample/tasks/complex_params.ps1
- spec/fixtures/modules/sample/tasks/winparams.json
- spec/fixtures/modules/sample/tasks/winparams.ps1
- spec/fixtures/modules/task_param/tasks/win.json
- spec/fixtures/modules/task_param/tasks/win.ps1
- spec/integration/task_param.rb
- spec/integration/winrm_spec.rb
When using powershell input method, only pass expected parameters to the
function. When it receives unexpected parameters the function call will
fail, and we don't want that to happen due to metaparameters that aren't
used.
This restriction requires that functions explicitly mention all
parameters they wish to use, rather than using a collector array for any
remaining parameters.
> (BOLT-630) Only pass expected params for powershell input to function

- acceptance/README.md
- acceptance/Rakefile
- acceptance/lib/acceptance/bolt_setup_helper.rb
- acceptance/setup/common/pre-suite/030_set_password.rb
- acceptance/setup/common/pre-suite/050_build_bolt_inventory.rb
- acceptance/setup/gem/pre-suite/020_install.rb
- acceptance/setup/git/pre-suite/020_install.rb
- bolt.gemspec
Rototiller expects defaults to be declared in the Rakefile, while beaker
subcommands don't use the Rakefile. The end of the acceptance README
provides instructions for running with beaker subcommands that didn't
work unless you explicitly set all the optional environment variables
you needed. Refactor so that both paths share defaults.
> (maint) Fix acceptance helpers so Rototiller and beaker subcommands work

- acceptance/config/gem/options.rb
- acceptance/config/git/options.rb
- acceptance/config/package/options.rb
- acceptance/files/example_apply.pp
- acceptance/setup/common/pre-suite/070_install_puppet.rb
- acceptance/setup/common/pre-suite/071_install_facts.rb
- acceptance/tests/apply_ssh.rb
- acceptance/tests/apply_winrm.rb
- appveyor.yml
- lib/bolt/applicator.rb
- lib/bolt/catalog.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
- spec/bolt/transport/ssh_spec.rb
- spec/bolt/transport/winrm_spec.rb
- spec/fixtures/apply/apply_catalog.ps1
- spec/fixtures/apply/apply_catalog.sh
- spec/fixtures/apply/basic/plans/init.pp
- spec/integration/apply_spec.rb
Add integration tests for applying a manifest block. Include tests that `_noop` works.
Also fix an issue where non-string types were not serialized as JSON when using the `environment` input method.
> (BOLT-634, BOLT-647, BOLT-677) Add tests, fix non-string types with environment input

- ext/debian/pe-bolt-server.default
- ext/debian/pe-bolt-server.init
- ext/systemd/pe-bolt-server.logrotate
- ext/systemd/pe-bolt-server.service
- lib/bolt/puppetdb/config.rb
- lib/bolt/transport/orch.rb
This adds the necessary infra to deploy the pe-bolt-server as a service, including service init files, defaults, and the unit file. We also need to check if the `$HOME` environment variable exists and set paths more explicitly if it doesn't, since when the service starts that env var won't be avialable.
To test this:
* Copy exe/bolt-server to /opt/puppetlabs/puppet/bin
* Copy ext/systemd/pe-bolt-server.service file to /lib/systemd/system/ 
* Create symlink to /etc/systemd/system/multi-user.target.wants/
* Copy ext/systemd/pe-bolt-server.logrotate to /etc/logrotate.d/pe-bolt-server
* Copy ext/debian/pe-bolt-server.default file to /etc/default/pe-bolt-server
* Copy ext/debian/pe-bolt-server.init file to /etc/init.d/pe-bolt-server
* `systemctl daemon-reload`
* `service pe-bolt-server start` …
> (BOLT-650) Add bolt as a service

- acceptance/lib/acceptance/bolt_command_helper.rb
- acceptance/setup/common/pre-suite/071_install_facts.rb
- acceptance/tests/apply_ssh.rb
- acceptance/tests/apply_winrm.rb
- lib/bolt/applicator.rb
Windows CLI uses a different modulepath, and needs a non-Cygwin
directory to install the facts module.
Skip the apply winrm test if the controller node is a winrm target and
has its own Ruby installed, as Bolt will fail to run apply in Puppet
Agent's Ruby. That will be fixed separately.
> (BOLT-634) Fix modulepath on Windows

- lib/bolt/applicator.rb
- lib/bolt/catalog.rb
- libexec/bolt_catalog
- spec/fixtures/apply/basic/plans/plan_vars.pp
- spec/fixtures/apply/basic/plans/target_vars.pp
- spec/fixtures/apply/basic/plans/trusted.pp
- spec/integration/apply_spec.rb
Include plan variables and trusted data when compiling a manifest block.
> (BOLT-672, BOLT-673) Add plan variables and trusted data

- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
- bolt-modules/boltlib/lib/puppet/functions/run_task.rb
- bolt-modules/boltlib/spec/functions/run_plan_spec.rb
- bolt-modules/boltlib/spec/functions/run_task_spec.rb
- lib/bolt/analytics.rb
- lib/bolt/cli.rb
- lib/bolt/executor.rb
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
- spec/lib/bolt_spec/plans/mock_executor.rb
Include the name of the task/plan being run if that name refers to a piece of built-in content. The task/plan name should not be included if it isn't a piece of bundled content, as the name may be sensitive.
> (BOLT-578) Report bundled content to GA

- bolt-modules/boltlib/lib/puppet/functions/puppetdb_fact.rb
- bolt-modules/boltlib/lib/puppet/functions/puppetdb_query.rb
- lib/bolt/applicator.rb
- lib/bolt/catalog.rb
- lib/bolt/pal.rb
- libexec/bolt_catalog
- spec/bolt/applicator_spec.rb
- spec/fixtures/apply/basic/manifests/init.pp
- spec/fixtures/apply/basic/plans/class.pp
- spec/fixtures/apply/basic/plans/disabled.pp
- spec/fixtures/apply/basic/plans/pdb_fact.pp
- spec/fixtures/apply/basic/plans/pdb_query.pp
- spec/integration/apply_spec.rb
Sets modulepath to Bolt's modulepath. Enables Bolt's puppetdb functions
when compiling a manifest block. Other functions continue to be
disabled.
> (BOLT-633) Set modulepath, enable puppetdb functions during apply

- .travis.yml
Somehow we were previously running docker-compose without the setup
Travis CI docs outline. Yesterday it stopped working. Add sudo:required
and services:docker to fix.
> (maint) Fix Travis CI config

- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
- bolt-modules/boltlib/types/planresult.pp
- spec/fixtures/apply/basic/plans/init.pp
- spec/integration/apply_spec.rb
Previously if only an `apply` was used, nothing would refer to ResultSet
and the type would not be loaded. Ensure the type is always loaded so we
can use it as the result of an `apply`.
> (BOLT-684) Ensure we can operate on a ResultSet returned by apply

- lib/bolt/applicator.rb
- lib/bolt/catalog.rb
- lib/bolt/config.rb
- lib/bolt/pal.rb
- libexec/bolt_catalog
- spec/bolt/applicator_spec.rb
- spec/bolt/config_spec.rb
- spec/fixtures/apply/basic/plans/hiera_lookup.pp
- spec/fixtures/apply/data/common.yaml
- spec/fixtures/apply/hiera.yaml
- spec/fixtures/apply/hiera_datadir.yaml
- spec/fixtures/apply/hiera_datadir/common.yaml
- spec/fixtures/apply/hiera_invalid.yaml
- spec/integration/apply_spec.rb
When compiling catalogs for apply bolt should configure and use hiera. This data should by default come from the boltdir not the global or user specific puppet path.
> (BOLT-631) Support Hiera config for plan apply

- lib/bolt/applicator.rb
- lib/bolt/bolt_option_parser.rb
- lib/bolt/config.rb
- lib/bolt/error.rb
- lib/bolt/executor.rb
- lib/bolt/pal.rb
- spec/bolt/applicator_spec.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/fixtures/apply/apply_catalog.ps1
- spec/integration/apply_spec.rb
Refactors the executor to expose `queue_execute` and `await_results` as async components. `apply` uses them to parallelize compiling and executing manifest blocks across multiple targets, using separate thread pools for compilation (a local CPU-intensive operation) and execution. Compilation thread pool is limited by a new `compile-concurrency` config option.
> (BOLT-635) Parallelize multi-target apply

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
Only generate a list of bundled plan/task content when running a plan or task. Building list of bundled content is expensive and not required when not running a plan or task.
> (BOLT-705) Bundled content for plan/task only

- lib/bolt/applicator.rb
- lib/bolt/catalog.rb
- lib/bolt/catalog/compiler.rb
- lib/bolt/catalog/logging.rb
- lib/bolt/error.rb
- lib/bolt/inventory.rb
- lib/bolt/pal/logging.rb
- lib/bolt/util/puppet_log_level.rb
- spec/bolt/applicator_spec.rb
- spec/fixtures/apply/basic/plans/error.pp
- spec/integration/apply_spec.rb
Adds a logger to handle messages from compiling manifest blocks for
targets that gathers all log messages created during the compilation and
redirects them to Bolt's logging facilities.
> (BOLT-636) Add logger for manifest block compilation

- spec/bolt/applicator_spec.rb
A change to the Executor's default arguments and testing of log messages
were both merged independently, introducing a test failure that wasn't
caught by PR testing. Fix the test.
> (maint) Fix test failure resulting from multiple merges

- lib/bolt/applicator.rb
- spec/bolt/applicator_spec.rb
- spec/integration/apply_error_spec.rb
- spec/integration/apply_spec.rb
Process errors returned by apply. If a known pattern identifying that
Puppet is not installed, replace it with a helpful error message.
> (BOLT-682) Provide helpful error messages if we detect Puppet missing

- exe/bolt-inventory-pdb
- lib/bolt_ext/puppetdb_inventory.rb
- spec/bolt/transport/local_spec.rb
- spec/bolt/transport/ssh_spec.rb
- spec/bolt/transport/winrm_spec.rb
- spec/bolt_ext/puppetdb_inventory_spec.rb
bolt-inventory-pdb now writes errors to stderr. Also adds unit tests for task implementations over transports that support them and bolt-inventory-pdb.
> (maint) bolt-inventory-pdb errors to stderr, and add unit tests

- acceptance/files/example_apply.pp
- acceptance/tests/apply_nonroot.rb
- acceptance/tests/apply_winrm.rb
- lib/bolt/applicator.rb
- spec/bolt/applicator_spec.rb
- spec/bolt/transport/ssh_spec.rb
- spec/fixtures/apply/basic/plans/catch_error.pp
- spec/fixtures/run_as/test/plans/run_as_user.pp
- spec/integration/apply_error_spec.rb
- spec/integration/apply_spec.rb
- spec/integration/run_as_spec.rb
Add support for `_catch_errors` and `_run_as` to `apply`. Previously
`_catch_errors=true` was the default behavior, now it will default to
false and allow it to be changed to true.
> (BOLT-648, BOLT-649) Support _catch_errors, _run_as

- acceptance/tests/apply_nonroot.rb
- lib/bolt/transport/ssh/connection.rb
When running a task with tty and using sudo to execute as a non-root
user, if stdin isn't consumed (like in the `facts` task) but is sent
over SSH it appears to be echoed back. Disable echo mode when using tty
to ensure it's not echoed.
Note that when using `--tty`, Puppet prints errors on stdout instead of
stderr.
> (BOLT-691) Fix running task with tty echoing input

- Gemfile
- bolt.gemspec
Ensure r10k is listed as a gem dependency rather than listed in the
Gemfile as Bolt now uses it directly.
> (BOLT-523) Add r10k to gem dependencies

- acceptance/tests/apply_nonroot.rb
- lib/bolt/transport/ssh/connection.rb
This reverts commit e73a6fc680d78ee027fb45e6f867df4330908908. The
attempt to fix echoing back stdin did not work consistently across
platforms; in particular CentOS 6, SLES 12, and Ubuntu 14.04 still had
problems.
> Revert "(BOLT-691) Fix running task with tty echoing input"

- acceptance/tests/apply_nonroot.rb
macOS 10.11 images don't have /etc/sudoers.d, only disable requiretty on
Linux in acceptance tests.
> (maint) Only disable requiretty on Linux systems in tests

- acceptance/files/example_apply/files/motd
- acceptance/files/example_apply/lib/puppet/type/warn.rb
- acceptance/files/example_apply/plans/init.pp
- acceptance/tests/apply_nonroot.rb
- acceptance/tests/apply_ssh.rb
- acceptance/tests/apply_winrm.rb
- lib/bolt/applicator.rb
- libexec/apply_catalog.rb
- spec/bolt/applicator_spec.rb
When using the apply() keyword, we now copy the contents of the `lib`
and `files` directories of every module to the agent. This allows native
types and providers to be used, as well as for puppet:// file sources to
resolve correctly.
This is accomplished by packing those files into a gzipped tarball,
which is then passed as a parameter to the apply_catalog internal
task. That tarball is then written to disk on the agent, unpacked, and
set as the modulepath for the catalog application.
> (BOLT-640) Build and sync plugin tarball to agents

- acceptance/tests/apply_ssh.rb
- acceptance/tests/apply_winrm.rb
In a previous commit filepath was updated to generate a unique name each
test run. However in the SSH tests it was created based on the Bolt
controller's concept of tmp, which may not be simply portable. Generate
a unique directory name in a known location that should be safe for SSH
targets. Do the same with WinRM for consistency.
> (BOLT-640) Fix filepath setup to be usable on many platforms

- bolt-modules/boltlib/lib/puppet/functions/facts.rb
- bolt-modules/boltlib/lib/puppet/functions/get_targets.rb
- bolt-modules/boltlib/lib/puppet/functions/vars.rb
- bolt-modules/boltlib/spec/functions/get_targets_spec.rb
- lib/bolt/applicator.rb
- lib/bolt/catalog.rb
- lib/bolt/config.rb
- lib/bolt/inventory.rb
- lib/bolt/util.rb
- libexec/bolt_catalog
- spec/bolt/applicator_spec.rb
- spec/fixtures/apply/basic/plans/inventory_lookup.pp
- spec/fixtures/apply/basic/plans/xfail_set_feature.pp
- spec/fixtures/apply/basic/plans/xfail_set_var.pp
- spec/fixtures/apply/inventory.yaml
- spec/integration/apply_spec.rb
Serialize information about targets in inventory. Pass this data
to bolt_catalog and load into puppet so that get_targets etc can
be used in an apply block.
> (BOLT-642) Support inventory function in apply

- lib/bolt/result_set.rb
The convention for Enumerable is to return the original object when
calling `each`. ResultSet wasn't doing that, and was instead implicitly
returning the results array.
> (maint) Return self from ResultSet#each

- acceptance/lib/acceptance/bolt_command_helper.rb
- acceptance/setup/common/pre-suite/050_build_bolt_inventory.rb
- acceptance/setup/common/pre-suite/071_install_modules.rb
- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- bolt-modules/boltlib/spec/functions/apply_prep_spec.rb
- spec/bolt/applicator_spec.rb
Previously we used two different HOME locations when running Bolt on
Windows. This was to provide path to modules that we could put on the
command-line that both Cygwin and Bolt would understand. However with
the move to using Bolt to install from a Puppetfile to Boltdir, we need
to use a single location for Boltdir. Update test helpers to use the
Windows paths to the default Boltdir.
Also, always ensure the default_boltdir exists before we try to copy to
it.
> (BOLT-641) Use consistent HOME dir when testing Bolt

- libexec/apply_catalog.rb
- libexec/custom_facts.rb
According to Ruby's docs at
https://ruby-doc.org/stdlib-2.4.0/libdoc/etc/rdoc/Etc.html#method-c-getlogin
we should avoid `getlogin` for security-related purposes and try
`getpwuid` if it fails. `getlogin` returns `nil` in containers under
Docker for Mac. Use `getwpuid.name` instead to get the current user name
when deciding what user should own the files that we untar.
> (BOLT-735) Avoid Etc.getlogin

- libexec/apply_catalog.rb
- libexec/custom_facts.rb
Windows returns nil for `getpwuid`. So try `getlogin`, and fall back to
`getpwuid` for containers where `getlogin` doesn't work.
> (BOLT-735) Cross-platform fix

- .rubocop.yml
- exe/bolt-server
Ensure we start the rack server. This is safer than exec because with
exec we need to make sure we get the rackup application that points to
the correct Ruby.
> (BOLT-653) Ensure rack server starts without rackup on PATH

- Puppetfile
- spec/bolt/cli_spec.rb
Addition of windows support for installing Puppet Agent on windows targets introduces a new powershell implementation for install_agent task. This commit updates the git reference to puppet_agent repo and updates cli spec accordingly.
> (BOLT-615) Update puppet_agent git ref

- lib/bolt/catalog.rb
- lib/bolt/error.rb
- lib/bolt/inventory.rb
- lib/bolt/node/errors.rb
- lib/bolt/pal.rb
- lib/bolt/result_set.rb
- lib/bolt_spec/run.rb
- spec/bolt/inventory_spec.rb
- spec/bolt_spec/run_spec.rb
- spec/integration/modules/facts_spec.rb
- spec/lib/bolt_spec/conn.rb
This adds a new set of BoltSpec spec helpers that can be used to run
tasks, commands, and plans from tests without handling cli flags or
running in a separate process.
> (BOLT-717) Add BoltSpec::Run public helper

- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- bolt-modules/boltlib/spec/functions/apply_prep_spec.rb
When apply_prep gets a failure attempting to run `puppet_agent::version`
or `puppet_agent::install`, it will no longer mask that error with an
error querying the task name. It now successfully gets the task name and
includes it with the original error.
> (BOLT-753) Fix apply_prep when handling failed task runs

- config.ru
- ext/config/bolt-server.conf
- lib/bolt_ext/server-config.rb
- spec/bolt_ext/server_config_spec.rb
- spec/fixtures/configs/global-bolt-server.conf
- spec/fixtures/configs/required-bolt-server.conf
This adds 3 keys to the bolt-server configuration:
* `ssl-cert`: the path to the ssl cert for bolt-server to use
* `ssl-key`: the path to the ssl key for bolt-server to use
* `ssl-ca-cert`: the path to the ssl ca certificat for bolt-server to use
It validates that each of these keys is present and a readable file, then configures Puma to bind to the specified port over SSL using these credentials.
> (BOLT-654) Add SSL configuration for bolt-server

- acceptance/tests/apply_ssh.rb
- acceptance/tests/script_winrm.rb
beaker-puppet's install helpers also setup puppet to be found when
running the command. We're not using that so we can test apply. However
that means any use of puppet needs to use the full path, which is easy
to do because we're only using it on non-Windows tests.
Also remove test that's adequately covered by winrm transport tests and
relied on Puppet's ruby.
> (BOLT-768) Fix acceptance tests without Beaker puppet install

- acceptance/lib/acceptance/bolt_command_helper.rb
Without this macOS runs with LANG=C resulting in Ruby/Bolt expecting
US-ASCII encoded external input. That caused a particular problem with
`…` returned by `pkgutil` when installing puppet-agent on macOS targets.
> (maint) Ensure Bolt runs with UTF-8 under macOS

- acceptance/tests/apply_ssh.rb
Until SLES is supported by the puppet_agent::install task (MODULES-7655)
we skip apply tests if SLES is a target.
> (maint) Skip testing on SLES

- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
- lib/bolt/executor.rb
- lib/bolt_spec/plans/mock_executor.rb
- spec/bolt/cli_spec.rb
- spec/integration/logging_spec.rb
Current plans do not have a `Starting: plan xxx` and `Finished: plan xxx in SS.ss sec`.
This PR adds those logging messages into plan executions.
A timestamp is returned from the `log_start_plan()` function so that nested plans produce accurate time measurements.
> (BOLT-767) Add logging messages for plans

- ext/redhat/pe-bolt-server.init
Following logic assumes `exec` is the name of a binary, not a command to
run. Move arguments to where we start the process.
> (PE-24721) Fix exec for RedHat 6 init script

- libexec/apply_catalog.rb
Puppet 4.10.9 and older did not include a second argument for
`push_application_context`. In all versions since then, the 2nd argument
has been optional, defaulting to the value we're passing in. So drop
passing the 2nd argument to support older Puppet 4 versions.
> (BOLT-776) Apply with older Puppet 4

- config.ru
- exe/bolt-server
- ext/redhat/pe-bolt-server.init
- ext/systemd/pe-bolt-server.service
Pass daemonize option to the correct handler. Also ensure pidfile is configured. Update services to match.
Put pidfile and logs in subdirectories so pe-bolt-server can be made owner of them.
> (PE-24721) Correctly daemonize

- lib/bolt_ext/server.rb
- spec/bolt_ext/server_spec.rb
The bolt-server expected API and the documented API have gotten out of sync.
This updates the bolt server to expect the structure in the documented api, specifically moving the 'options' keys out a level and removing 'options' as a key.
> (BOLT-788) Update bolt server to accept documented API

- lib/bolt_ext/server.rb
This adds a valid default for parameters if it's not provided
> (BOLT-788) Make parameters key optional

- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/transport/winrm.rb
- lib/bolt/transport/winrm/connection.rb
I believe there's a race condition that can be triggered in the Logging
library when creating many loggers and setting `level=` concurrently.
Filed as https://github.com/TwP/logging/issues/200.
This fix avoids the race by setting up the shared transport logger once
and passing it to connection instances.
> (BOLT-685) Avoid setting `level=` on log level repeatedly

- lib/bolt/executor.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt_ext/server.rb
- spec/bolt/executor_spec.rb
- spec/bolt/transport/ssh_spec.rb
Ensure we don't read from the users system SSH config or the global Bolt config when running bolt via the API
> (BOLT-722) Don't load ssh config if using bolt via api

- Puppetfile
- acceptance/setup/common/pre-suite/071_install_modules.rb
- acceptance/tests/apply_ssh.rb
- spec/bolt/cli_spec.rb
Update the puppet_agent shipped with Bolt to include support for
installing on SLES so apply_prep works.
> (BOLT-797) Support apply_prep on SLES

- lib/bolt/transport/ssh/connection.rb
- spec/bolt/transport/ssh_spec.rb
This commit changes the netssh verifier from `lenient` to `null` when `host-key-check` is false. The lenient verifier will raise an exception (HostKeyMismatch) when a target is present in `~/.ssh/known_hosts`, but the key given does not match any known for that target. The `null` verifier does no host-key checking at all.
> (BOLT-805) No host key verify w/ host-key-check=false

- developer-docs/bolt_server.md
- ext/config/bolt-server.conf
- lib/bolt_ext/server-config.rb
- spec/bolt_ext/server_config_spec.rb
This sets the bolt-server port higher since it's an internal tool
> (BOLT-786) Change bolt-server port to 62658

- pre-docs/bolt_configuration_options.md
`verbose` is not an option, but `info` and `error` are.
> (docs) Fix log levels available in config

- developer-docs/bolt_server.md
This commit documents 2 changes to the bolt-server API:
* The addition of a `/winrm/run_task` endpoint, which is very similar to the `/ssh/run_task` endpoint but whose target object has different options
* The addition of a `file` JSON object in place of `file_contents` in the task object.
The latter change is because we need to know the filetype to run tasks on windows hosts. Long term we want to get this data directly from puppetserver, but aren't sure we can make this change in the time frame we have. For now we still need the file_content, in addition to the filetype, and will accept other keys provided by the [puppetserver task api](https://github.com/puppetlabs/puppetserver/blob/master/documentation/puppet-api/v3/task_detail.markdown).
> (BOLT-723) Document changes to the bolt-server API

- ext/redhat/pe-bolt-server.init
- ext/systemd/pe-bolt-server.service
Set a umask to prevent bolt-server's logfile being world-readable when
running as a service.
> (BOLT-655) Include umask on pe-bolt-server to lock down logfile

- examples/server-client.rb
- lib/bolt/target.rb
- lib/bolt/task.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
- lib/bolt_ext/server.rb
- spec/bolt_ext/server_spec.rb
This adds a new `/winrm/run_task` endpoint to pe-bolt-server which runs a task on a node over the winrm transport. It currently writes a `.ps1` file to the bolt controller system, and uses that as an executable to run the task over winrm. It also sets the `input_method` to 'powershell' in order for the parameters key to work.
> (BOLT-723) Add winrm run_task endpoint

- developer-docs/bolt_server.md
It's difficult to set reasonable defaults for these keys, and currently they default to `Etc.getlogin` and `nil`. They should be required keys.
> (maint) Make user and password required keys

- developer-docs/bolt_server.md
- lib/bolt/transport/ssh/connection.rb
- lib/bolt_ext/server.rb
- spec/bolt_ext/server_spec.rb
When the Executor is asked not to load config, include the `ssh-agent` in that. The Executor is expected not to use any external SSH input in this mode.
Use `private-key-content` if passed to `/ssh/run_task`. Error if both `private-key-content` and `password` are set.
> (BOLT-722, BOLT-793) Disable ssh-agent, accept private-key-content in bolt-server

- lib/bolt/transport/base.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/local/shell.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
- spec/bolt/transport/local_spec.rb
- spec/bolt/transport/winrm_spec.rb
Previously serializing environment input as JSON was fixed for SSH and
WinRM, but the Local transport was missed. Fix it.
> (BOLT-807) Serialize environment input as JSON in local transport

- lib/bolt/applicator.rb
On newer versions of powershell, such as the one in Nano Server that we
use for local testing, the error reported when trying to run 'apply'
changed from `Could not find executable 'ruby.exe'` to `The term
'ruby.exe' is not recognized as the name of a cmdlet`. This does not
seem to apply to older versions of Powershell such as used in AppVeyor
CI. Correctly match the new error string and report that Puppet is not
installed when trying to use `apply`.
> (BOLT-812) Bolt correctly identifies missing Puppet on newer Powershell

- lib/bolt/bolt_option_parser.rb
- spec/bolt/cli_spec.rb
Let `bolt command run whoami --nodes @~/hosts.csv` find the `hosts.csv`
file in your home directory.
Fixes #600
> (BOLT-813) Expand tilde in nodes file path

- lib/bolt_ext/server.rb
- spec/bolt_ext/server_spec.rb
By default Sinatra returns HTML when it errors. This can't be parsed into JSON, and makes handling errors for api users difficult and hard to trace. This catches those errors and returns json instead
> (BOLT-657) Catch sinatra html errors and return json

- Gemfile
- lib/bolt_ext/server_acl.rb
- lib/bolt_ext/server_config.rb
- puma_config.rb
- spec/bolt_ext/server_acl_spec.rb
- spec/bolt_ext/server_config_spec.rb
- spec/fixtures/configs/bad-whitelist.conf
- spec/fixtures/configs/global-bolt-server.conf
- spec/fixtures/configs/local-bolt-server.conf
Allow configuring a whitelist as an array of certnames. Use rails-auth to enforce the whitelist of services allowed to make requests via bolt-server.
> (BOLT-754) Use rails-auth to enforce a whitelist

- lib/bolt_ext/server_config.rb
- puma_config.rb
- spec/bolt_ext/server_config_spec.rb
- spec/fixtures/configs/global-bolt-server.conf
- spec/fixtures/configs/local-bolt-server.conf
In bolt-server, concurrency is synonymous with how many threads are
available to process run task requests. Allow configuring the max number
of server threads with `concurrency`, which defaults to 100.
> (BOLT-809) Add 'concurrency' option to configure bolt-server threads

- Puppetfile
- spec/bolt/cli_spec.rb
This module was an experimental inclusion to provide basic functionality
to reuse existing Puppet resource types. Since we've now introduced the
apply() keyword as a general, supported solution to this problem, the
apply module is no longer necessary. We're choosing to immediately
remove this rather than add a deprecation based on the fact that we have
no known users of the feature.
> (BOLT-750) Remove apply module and apply::resource task

- bolt-modules/boltlib/lib/puppet/functions/run_task.rb
- bolt-modules/boltlib/spec/functions/run_task_spec.rb
- bolt-modules/boltlib/types/argsspec.pp
- pre-docs/writing_plans.md
- pre-docs/writing_tasks.md
* Plans can no longer pass in `Sensitive` typed arguments
* `run_task()` validates input parameters against the `Data` type once again
* The `Boltlib::ArgsSpec` type has been removed, since `Sensitive` is no longer accepted as an argument type.
* The `Sensitive` type is no longer listed in the `writing_tasks` documentation for acceptable parameter data types
* Task authors can still specify `"sensitive": true` on parameters and they will be wrapped with `Sensitive` under the hood and not logged (except in `--debug` mode).
> (BOLT-794) Adjustments to sensitive handling

- spec/bolt/transport/base_spec.rb
- spec/bolt/transport/local_spec.rb
- spec/bolt/transport/orch_spec.rb
- spec/bolt/transport/ssh_spec.rb
- spec/bolt/transport/winrm_spec.rb
- spec/lib/bolt_spec/sensitive.rb
This removes the dependency on setting up sensitive types in the
base_spec before runnig the other transport specs. It makes the
local bug less dependent on the version of echo installed.
> (maint) remove depenency between transport specs and echo bug

- acceptance/tests/script_ssh.rb
- acceptance/tests/script_winrm.rb
- lib/bolt/transport/base.rb
Transports must be usable even when Puppet is not initialized. Only
check for Sensitive types if they're loaded, and add an argument to
acceptance tests for `script run` to ensure that it's not used when
Puppet isn't loaded.
> (BOLT-794) Remove requirement that Puppet is initialized for transports

- bolt-modules/boltlib/lib/puppet/functions/file_upload.rb
- bolt-modules/boltlib/lib/puppet/functions/run_script.rb
- bolt-modules/boltlib/lib/puppet/functions/upload_file.rb
- bolt-modules/boltlib/spec/functions/upload_file_spec.rb
- lib/bolt/cli.rb
- lib/bolt/executor.rb
- pre-docs/plan_functions.md
- pre-docs/writing_plans.md
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
- spec/fixtures/run_as/test/plans/run_as_user.pp
This function was inconsistent with the other plan functions, including
run_\* and set_\*, which are all \<verb\>\_\<object\> rather than \<object\>\_\<verb\>.
This change standardizes the plan functions so they should be easier to
remember.
This leaves behind a stub file_upload implementation that issues a deprecation
warning and calls upload_file in its place.
> (BOLT-751) Rename file_upload function to upload_file

- Gemfile
- bolt.gemspec
- lib/bolt/transport/winrm.rb
- lib/bolt/transport/winrm/connection.rb
- spec/bolt/transport/winrm_spec.rb
This commit uses a modified winrm-fs library to upload file contents received by the bolt-server API from memory instead of writing to a temporary file. The modifications to winrm-fs will be included in Bolt by extending relevant winrm-fs classes to avoid being blocked on changes getting accepted to winrm-fs. The winrm-fs work is currently being tracked with https://github.com/donoghuc/winrm-fs/tree/BOLT-664.
> (BOLT-664) Upload file from memory over WinRM

- developer-docs/bolt_server.md
This adds the 'run-as' option example to bolt-server's developer docs
> (maint) Add run-as option to developer docs

- .rubocop.yml
- lib/bolt/transport/base.rb
This version enabled by default a new cop we had previously been
ignoring (Layout/EmptyLineAfterGuardClause). This commit disables it
explicitly. It also fixes one indentation issue.
> (maint) Fix rubocop 0.59 issues

- lib/bolt/bolt_option_parser.rb
- lib/bolt/config.rb
- lib/bolt/pal.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/integration/logging_spec.rb
Previously, relative paths in the bolt.yaml file were treated as relative
to pwd, which is almost never what's expected. We now treat them as
relative to Boltdir, allowing a modulepath like site:modules to be used to
represent .../Boltdir/site:.../Boltdir/modules, regardless of where the
Boltdir is located on disk.
When modulepath is specified on the CLI, relative paths are still
interpreted as relative to the pwd, which should be less surprising for new
users than making it implicitly based on a directory (Boltdir) they may not
even know exists.
> (BOLT-719) Allow modulepath relative to Boltdir

- Gemfile
- lib/bolt_ext/schemas/ssh-run_task.json
- lib/bolt_ext/schemas/task.json
- lib/bolt_ext/schemas/winrm-run_task.json
- lib/bolt_ext/server.rb
- spec/bolt_ext/server_spec.rb
- spec/lib/bolt_spec/conn.rb
Validate JSON requests for ssh and winrm run_task endpoints. This commit adds the gem dependency json-schema. This library provides JSON validation against defined schemas as well as detailed error messages about malformed or prohibited JSON requests.
> (BOLT-658) Validate bolt-transport-api requests

- lib/bolt/boltdir.rb
- pre-docs/bolt_configuration_options.md
- pre-docs/bolt_installing_modules.md
Previously, the default modulepath was just `modules`. That made it
difficult to use a Puppetfile with `bolt puppetfile install` while also
using some custom module content, as every custom module needed to be
added to Puppetfile with `local: true` simply in order to be preserved
when updating.
Now, we use `modules:site` as the default modulepath, which provides
users a location to install modules via the Puppetfile (`modules`) as
well as a location for custom content that should not be managed with
the Puppetfile (`site`). `bolt puppetfile install` will always install
to the first element of the modulepath, so we break the typical Puppet
convention and put `modules` *first*.
> (BOLT-766) Add 'site' to default modulepath

- Gemfile
- bolt.gemspec
- lib/bolt_ext/schemas/ssh-run_task.json
- lib/bolt_ext/schemas/task.json
- lib/bolt_ext/schemas/winrm-run_task.json
- lib/bolt_ext/server.rb
- spec/bolt_ext/server_spec.rb
- spec/lib/bolt_spec/conn.rb
Previously the paths for validating JSON schema templates only worked when running from Rspec tests as they were relative to the root directory of Bolt. This commit handles the paths accordingly.
> (maint) Update JSON schema paths

- Puppetfile
- lib/bolt/applicator.rb
- lib/bolt/pal.rb
- spec/bolt/applicator_spec.rb
In Puppet 6, many types and providers have been removed from core into
their own modules. Those modules are included in the puppet-agent package
so the out-of-the-box experience remains the same. In order to preserve
that same experience when using the apply() functionality, we now vendor
the same modules in Bolt.
Because we vendor the externalized "core" Puppet modules, we need to avoid
syncing them to agents. These plugins are included out-of-the-box in
puppet-agent 5 (where they are core) and 6 (as modules). That means it's
unnecessary to copy any of this content to agents. Moreover, because the
vendored modules are only intended to be used by Puppet 6 agents, they can
cause problems when syncing to Puppet 5 agents, where they can supersede
the built-in plugins with potentially …
> (BOLT-840) Include "vendored" Puppet types

- lib/bolt/transport/winrm/connection.rb
Ensure ruby tasks continue to work on Windows when upgrading to Puppet 6.
> (BOLT-844) Add Puppet 6 PATH for Ruby on Windows

- .gitignore
Add new bundled modules to .gitignore to prevent clutter in dev
environments.
> (maint) Add new bundled modules to .gitignore

- spec/bolt/executor_spec.rb
We are seeing transient issues around the default sleep time for checking threads used by executor. When we first observed the transient failures we bumped the wait time from 0.1 to 0.2 seconds. Instead of bumping the wait time again Nick Lewis suggested looping until the threads are done with a max timeout to avoid continuing to hard code wait times that may not be needed in tests.
> (maint) Fix transient failures in executor spec test

- lib/bolt/target.rb
- spec/bolt/target_spec.rb
When a user or password are passed via the URI, Bolt unencodes them to
allow passing complex strings in the URI. It shouldn't do that for
users and passwords passed via CLI flags or inventary, but did, meaning
passwords that include things like `%F3` get mangled and don't work. Fix
so only URI components are unencoded.
> (BOLT-852) Ensure user and password aren't mangled

- lib/bolt/transport/ssh.rb
- spec/bolt/transport/ssh_spec.rb
When using --run-as, we create a wrapper script around the task and
embed the stdin directly into the script inside a heredoc. Previously,
it was possible for escape sequences within that heredoc to corrupt the
stdin, resulting in incorrect task behavior. We now properly set the
heredoc to ignore all escape sequences, ensuring the task receives
the stdin exactly as intended.
Because we always send stdin as a single line of JSON, it's impossible
for it to escape the heredoc by including a line starting with EOF (our
heredoc marker).
> (BOLT-854) Properly escape stdin when using --run-as

- pre-docs/applying_manifest_blocks.md
- pre-docs/bolt_installing.md
**What this changes** This adds a note to the gem install docs and the apply manifest docs about installing bolt's required puppet modules
**Why** `apply_prep` specifically doesn't work without modules installed, and it's difficult to find documentation on why or know that it's related to installing from a gem.
> (maint) Add note to install modules with gem install

- lib/bolt_ext/schemas/task.json
This commit changes the schema for Task in bolt server to allow additional properties in the task metadata field. It explicitly adds a definition for `input_method` as there are only two acceptable values.
> (maint) Do no restrict keys in bolt-server task metadata schema

- libexec/apply_catalog.rb
Previously, when using the apply() function, it was possible for Puppet
"features" to be loaded from the default modulepath, rather than from
the temporary modulepath we set up. This could cause incorrect versions
of features to be loaded or for necessary features to be missed.
This happened because there are two methods that parts of Puppet use to
find the current environment:
* Puppet.lookup(:current_environment)
* Puppet.lookup(:environments).get(name)
We override the production environment with our custom modulepath and
set that as :current_environment in the Puppet context. However, that
doesn't affect the :environments value in the context, which still
contains the default directory environments. Thus, any code that looks
up the environment that way will find the original version of …
> (BOLT-857) Properly override environment in all cases

- bolt-modules/boltlib/lib/puppet/functions/puppetdb_query.rb
- pre-docs/inventory_file_generating.md
- pre-docs/plan_functions.md
**What this changes** This adds links to more information about PQL to relevant parts of the documentation
**Why** Because it's not obvious to new users what PQL is or how it's different from other query languages, and providing direct links to PQL information in 'obvious' places is helpful for finding that info
> (maint) Add links to PQL information

- lib/bolt/applicator.rb
This fixes a couple of issues preventing the apply() functionality from working
in a PE environment.
Previously, we were assuming that running the apply_catalog task would
always return a single result. Since the PCP transport can properly batch
nodes, it's possible for it to return several results at once, which we
need to account for.
Because these tasks are actually mocked in Bolt, their name is irrelevant.
However, in order to run them in PE, a task with the same name needs to
actually be installed. These tasks have been copied into the
puppetlabs-apply_helpers module for installation in PE.  Therefore, we need
to refer to them by the names `apply_helpers::custom_facts` and
`apply_helpers::apply_catalog` in order to work in PE.
This requires the [`puppetlabs-apply_helpers …
> (BOLT-643) Enable apply() over PCP

- spec/integration/ssh_spec.rb
- spec/integration/winrm_spec.rb
Extend integration tests to include running against the same target
multiple times. This test helps prevent clobbering other runs on the
same target.
> (maint) Add tests across multiple targets for ssh, winrm

- lib/bolt/task.rb
- spec/bolt/task_spec.rb
- spec/bolt/transport/local_spec.rb
- spec/bolt/transport/ssh_spec.rb
- spec/bolt/transport/winrm_spec.rb
Update for task spec revision 3: support input_method in individual implementations.
Depends on https://github.com/puppetlabs/bolt/pull/651.
> (BOLT-758) Support different input_methods for implementations

- spec/bolt/cli_spec.rb
- spec/fixtures/modules/sample/tasks/params.json
Add a test showing Bolt no longer errors on unknown metadata keys.
> (BOLT-752) Add test with unknown metadata keys

- lib/bolt/applicator.rb
- lib/bolt/boltdir.rb
- spec/bolt/boltdir_spec.rb
For existing Puppet users, the control repo is a source of Puppet content
including modules and hiera data. It's helpful to be able to use Bolt from
within that context and pick up all of the content that's deployed in the
Puppet environment. However, doing that currently requires creating a
Boltdir with a bolt.yaml that refers to the hiera config and modulepath
using relative paths like ../modules.
We now look for a bolt.yaml in the current directory (if there is no
Boltdir) and treat the local directory as the Boltdir if one is found. This
allows the defaults for hiera config and modulepath to work when running
Bolt from a standard control repo.
This also fixes an issue where hiera.yaml files containing symbols wouldn't be
loaded. Since many existing hiera.yaml configs do contain …
> (BOLT-816) Enable control repos as Boltdirs

- Puppetfile
- spec/bolt/cli_spec.rb
Bump the puppetlabs-facts module to 0.3.1 so failure gathering facts will no longer be hidden.
> (BOLT-865) Bump facts to 0.3.1

- lib/bolt/config.rb
- spec/bolt/config_spec.rb
- spec/lib/bolt_spec/integration.rb
~/.puppetlabs/bolt.yaml(yml) has been deprecated for a few releases and
is removed with this commit.
> (BOLT-749) Remove support for legacy bolt.yaml location

- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- bolt-modules/boltlib/spec/functions/apply_prep_spec.rb
- lib/bolt/applicator.rb
Use the Sensitive type to suppress verbose logging of the base64-encoded
plugins data sent as part of apply_prep (gathering custom facts). Also
updates the catalog application arguments, but they're normal logging is
suppressed so it doesn't have visible impact at verbose.
> (maint) Suppress base64-encoded binary data in apply_prep

- lib/bolt/pal.rb
- spec/integration/parsing_spec.rb
Previously, using `bolt plan show <plan-name>` for a plan with a
parameter of type TargetSpec would display the parameter type as
TargetSpec = Boltlib::TargetSpec = Variant[String[1], Object[{name => 'Target', attributes => {'uri' => String[1], 'options' => {type => Hash[String[1], Data], value => {}}}, functions => {'host' => Callable[[0, 0], String[1]], 'name' => Callable[[0, 0], String[1]], 'password' => Callable[[0, 0], Optional[String[1]]], 'port' => Callable[[0, 0], Optional[Integer]], 'protocol' => Callable[[0, 0], Optional[String[1]]], 'user' => Callable[[0, 0], Optional[String[1]]]}}], Array[Boltlib::TargetSpec]]
Which is unhelpful.
We now explicitly check for alias types and just display the type name,
rather than the full string representation.
> (BOLT-413) Don't expand type alias names in bolt plan show

- lib/bolt/apply_result.rb
- spec/integration/apply_error_spec.rb
This ensures that errors other than puppet-missing are correctly
generated when the apply test fails.
> (BOLT-863) Correctly generate errors when apply_task fails

- pre-docs/bolt_installing_modules.md
This commit adds documentation for the modules packaged with bolt. Brief descriptions of module content and details for how to override bundled modules is provided.
> (BOLT-796) Document bundled module content

- libexec/apply_catalog.rb
- spec/integration/apply_spec.rb
Bolt Apply still picked up settings from `puppet.conf`, which can lead
to confusing failures. Update `apply_catalog` to override required app
settings - similar to how Bolt sets up Puppet - to point to a temp
directory. The result should be that we ignore any config on the system,
write any logs and runtime state to that temporary directory, and read
environments from that location (i.e. the only available environment
will be the built-in `production`).
> (BOLT-883) Redirect all Puppet input and output to temp dir

- libexec/apply_catalog.rb
- spec/fixtures/apply/basic/lib/puppet/functions/pid.rb
- spec/fixtures/apply/basic/plans/defer.pp
- spec/integration/apply_spec.rb
Makes the `Deferred` type work in `apply` statements. This type allows
Puppet functions to be invoked when the catalog is being applied on the
agent rather than during compilation.
> (BOLT-855) Make Deferred work in 'apply'

- pre-docs/bolt_configure_orchestrator.md
Suggest that users make the default bundled module content available in the PE environment to be used with PCP. Link to the installing modules section and provide explanation of why it is important.
> (BOLT-820) Add suggested modules documentation to PCP config

- bolt-modules/boltlib/lib/puppet/datatypes/applyresult.rb
- lib/bolt/apply_result.rb
- lib/bolt/outputter/human.rb
- spec/integration/apply_spec.rb
- spec/integration/plan_spec.rb
Previously the human format for plan results was always JSON which was
hard to read. Now the human output of ResultSets looks like the human
output for task/command/script/file_upload results. Apply results have a
message that summarized resource changes for them.
I'm going to poke at refactoring "with_node_logging" to make it more human readable with apply but I think this bit will make nlews output easier.
> (BOLT-866) Improve human format output for PlanResults

- libexec/custom_facts.rb
- spec/fixtures/apply/prep/plans/init.pp
- spec/integration/apply_spec.rb
Make custom_facts more like apply_catalog facts gathering. Use a
temporary directory for isolation, and ensure agent facts like
clientcert are included.
> (BOLT-898) Include agent facts in apply_prep

- lib/bolt/catalog.rb
- spec/fixtures/apply/basic/manifests/strict.pp
- spec/fixtures/apply/basic/manifests/strict_variables.pp
- spec/fixtures/apply/basic/plans/strict.pp
- spec/fixtures/apply/basic/plans/strict_variables.pp
- spec/integration/apply_compile_spec.rb
We want Bolt to be able to compile most Puppet 4+ manifests, so we need to allow deprecated functions. TODO: this should be configurable.
> (BOLT-900) Allow deprecations in functions used in a manifest block

- developer-docs/bolt-server.md
Bolt server allows a `connect-timeout` parameter for ssh and winrm
targets.  The units of the parameter were not documented.  This
updates the description to include the units and describe what
happens when the timeout is exceeded.
> (maint) improve connect-timeout documentation for bolt-server

- lib/bolt/catalog.rb
- spec/bolt/catalog_spec.rb
The Bolt::Catalog by default logs all messages from Puppet's compile.
This creates a lot of extra output during testing that we ignore.
Suppress everything below warnings during unit tests.
> (maint) Suppress logging during tests

- acceptance/tests/cross_platform_task.rb
- lib/bolt/task.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/transport/winrm.rb
- lib/bolt/transport/winrm/connection.rb
- lib/bolt_ext/server.rb
- pre-docs/writing_tasks.md
- spec/bolt/task_spec.rb
- spec/bolt/transport/local_spec.rb
- spec/bolt/transport/orch_spec.rb
- spec/bolt/transport/ssh_spec.rb
- spec/bolt/transport/winrm_spec.rb
- spec/fixtures/modules/shareable/tasks/init.json
- spec/fixtures/modules/shareable/tasks/invalid_path.json
- spec/fixtures/modules/shareable/tasks/list.ps1
- spec/fixtures/modules/shareable/tasks/list.sh
- spec/fixtures/modules/shareable/tasks/not_a_directory.json
- spec/fixtures/modules/shareable/tasks/not_a_file.json
- spec/fixtures/modules/shareable/tasks/unknown_file.json
- spec/fixtures/modules/shareable/tasks/unknown_module.json
- spec/integration/shareable_task_spec.rb
Add shareable task code in the form of the `files` metadata property. Implemented specifically for the SSH, WinRM, and Local transports; the PCP transport doesn't use it because Bolt only sends the name of the task, and Orchestrator handles the rest.
> (BOLT-755) Add shareable task code

- bolt.gemspec
- lib/bolt/transport/ssh/connection.rb
- spec/bolt/transport/ssh_spec.rb
This enables adding the ed25519 gem in packaging to support those keys.
> (BOLT-380) Bump net-ssh to 5.0+ release

- lib/bolt/pal.rb
- pre-docs/bolt_command_reference.md
- pre-docs/inspecting_tasks_and_plans.md
- pre-docs/writing_tasks.md
- spec/bolt/cli_spec.rb
- spec/fixtures/modules/sample/tasks/private.json
- spec/fixtures/modules/sample/tasks/private.sh
When a task is marked as `private` in metadata, do not list it when listing tasks.
> (BOLT-734) Hide private tasks from task list UI

- bolt.gemspec
- lib/bolt/transport/ssh/connection.rb
We plan to package Bolt with net-ssh 5, primarily for ed25519 support.
However many things that might be used alongside bolt-as-a-gem - such as
Beaker - still pin to net-ssh 4. Make it compatible with both.
> (BOLT-380) Make Bolt compatible with net-ssh 4 and 5

- lib/bolt/executor.rb
- lib/bolt/transport/base.rb
- spec/bolt/executor_spec.rb
Previously a NotImplementedError thrown by the transport would get added to the result, but never printed. Ensure that errors not handled by the transport get logged. Our normal expectation is that the transport handles all errors and adds them to the error result.
> (BOLT-922) Ensure NotImplementedError messages are not lost

- pre-docs/writing_tasks.md
**What this changes** Add documentation around task implementations having distinct names and individual metadata
**Why** So that tasks can be uploaded to the forge, and for a better user experience with puppet enterprise
> (BOLT-614) Add docs around multi-implementation task names

- appveyor.yml
- spec/spec_helper.rb
The Vagrant VM used for testing locally does not support installing packages using an MSI which is necessary for the puppet_agent::install task. The images used on Appveyor support MSI installation. Previously when testing locally (with something like `bundle exec rspec`) the Appveyor specific tests would fail. This commit configures Rspec to filter Appveyor specific tests when the environment variable `APPVEYOR_AGENTS` is not set.
> (maint) Skip Appveyor tests locally

- lib/bolt_spec/run.rb
- spec/bolt_spec/run_spec.rb
This commit adds `run_script` to the BoltSpec::Run module to support running scripts for automated testing.
> (BOLT-915) Add run_script to BoltSpec

- bolt.gemspec
- lib/bolt/task.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
- pre-docs/writing_tasks.md
- spec/bolt/transport/local_spec.rb
- spec/bolt/transport/ssh_spec.rb
- spec/bolt/transport/winrm_spec.rb
- spec/fixtures/modules/shareable/tasks/list.ps1
- spec/fixtures/modules/shareable/tasks/list.sh
- spec/integration/shareable_task_spec.rb
When using an installdir for extra files, put the task executable there under its own module path to simplify writing and testing tasks that use other files as libraries. Updating according to clarification of the tasks specification.
> (BOLT-931) Put task executable in installdir when present

- lib/bolt_server/file_cache.rb
- spec/bolt_server/file_cache_spec.rb
Add a purge process - run on startup and every day after - to remove
tasks from the file cache that haven't been used in over a week.
> (BOLT-928) Add daily purge process to bolt-server's file cache

- lib/bolt_server/file_cache.rb
When a `Bolt::error` is rescued there was a typo in the `is_a?` method where the `?` was ommitted. This was causing acceptance tests failures in ORCH.
> (maint) Fix typo in exception handler

- lib/bolt_server/file_cache.rb
The `:executor` option in the concurrent promise instantiation had a typo that resulted in non-parallel download resulting in non-serial execution of `download_file`.
> (maint) Fix typo in options hash

- Puppetfile
The `puppet_agent::install_shell` task has been updated to use the `bash.sh` implementation for the `facts` task. This commit updates the references to the updated modules.
> (BOLT-915) Update facts and puppet_agent modules

- lib/bolt/target.rb
- spec/bolt/target_spec.rb
- spec/fixtures/apply/basic/plans/inventory_lookup.pp
- spec/fixtures/modules/results/plans/test_printing.pp
- spec/integration/apply_compile_spec.rb
- spec/integration/target_spec.rb
**What this changes** Modify the `to_s` method of `Bolt::Target` to only print the user, host, protocol, and port of the target
**Why** So that sensitive and unnecessary information is not displayed when printing targets
> (BOLT-944) Only print selected options for a target

- .gitignore
- Puppetfile
- pre-docs/writing_tasks.md
**What this changes** Adds the ruby_task_helper module to the Puppetfile, and include a link in the docs
**Why** So that the helper is installed with bolt
> (BOLT-907) Add ruby task helper to docs and Puppetfile

- acceptance/tests/apply_plan_ssh.rb
- acceptance/tests/apply_plan_winrm.rb
- acceptance/tests/bolt_apply.rb
- acceptance/tests/plan_ssh.rb
- acceptance/tests/plan_winrm.rb
The way we were quoting the code to be applied wasn't working properly
on windows. Also, we were incorrectly referencing the JSON error type to
rescue.
> (BOLT-858) Fix apply test on windows

- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
Remove stack traces from bolt-server responses by removing them from the result status hash in bolt server. This should preserve the trace in log messages. If a stack trace is included in the result of a task output (for example a task that throws and exception during it's execution) it will still be included in the response.
> (BOLT-925) Scrub stack trace from bolt server errors

- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
**What this changes** Generate JSON for body of 400 and 500 error responses from bolt_server
**Why** so that PE tools that consume the errors can parse them.
> (BOLT-917) Return JSON from bolt_server for errors

- lib/bolt/transport/orch/connection.rb
The Orchestrator endpoint for finishing a plan requires a value.
Previously a plan without a return value would fail to finish the plan.
Send an empty string so the plan is successfully finished.
> (BOLT-959) Successfully finish a plan without a result

- .dockerignore
- Dockerfile
**What this changes** This updates the pe-bolt-server dockerfile to use the alpine linux base image instead of the ruby base image. It then installs ruby and dependencies, and installs and starts pe-bolt-server just as the previous dockerfile did.
**Why** This is slimmed-down container that only includes what we need for bolt-server, and is more consistent with the image layering we use throughout Puppet.
> (BOLT-965) bolt-server Dockerfile to use alpine

- developer-docs/bolt-server.md
- lib/bolt_server/config.rb
- puma_config.rb
- spec/bolt_server/config_spec.rb
This commit allows select configuration options to be set with environment variables. Environment variable options take precedence over options defined in `bolt-server.conf`.
> (BOLT-966) Configure Bolt-Server from environment variables

- bolt-modules/boltlib/lib/puppet/functions/run_command.rb
- bolt-modules/boltlib/lib/puppet/functions/wait_until_available.rb
- bolt-modules/boltlib/spec/functions/wait_until_available_spec.rb
- lib/bolt/error.rb
- lib/bolt/executor.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/orch/connection.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
- spec/bolt/executor_spec.rb
- spec/bolt/transport/local_spec.rb
- spec/bolt/transport/orch_spec.rb
- spec/bolt/transport/ssh_spec.rb
- spec/bolt/transport/winrm_spec.rb
Add the `wait_until_available` function to wait for all targets to be available for connections. Accepts a description, wait_time in seconds (default 120), and retry_interval in seconds (default 1).
> (BOLT-956) Add wait_until_available function

- pre-docs/bolt_installing.md
**What this changes** Includes the path to the analytics config file in the docs for disabling analytics
**Why** so that Windows users don't have to find the path on their own.
> (maint) Add windows path to analytics disabling docs

- lib/bolt_spec/plans.rb
- lib/bolt_spec/plans/mock_executor.rb
BoltSpec plan testing didn't implement `without_default_logging` or `wait_until_available`. Add them to support running plans that use them. Also add an init helper so that logging is configured ready (so `notice` doesn't error).
> (BOLT-971) Fix functions and initialization with BoltSpec

- lib/bolt/applicator.rb
- lib/bolt/executor.rb
- lib/bolt/pal.rb
- lib/bolt_spec/plans/mock_executor.rb
- spec/bolt/applicator_spec.rb
- spec/bolt/cli_spec.rb
- spec/bolt/pal_spec.rb
For apply actions - via `bolt apply` or the `apply` function in a Plan -
capture events counting the size of the code being run (in number of
statements), and number of resources produced by those manifests.
> (BOLT-644) Add analytics for size of applied manifests

- lib/bolt/transport/ssh.rb
- pre-docs/bolt_installing.md
- pre-docs/bolt_known_issues.md
- pre-docs/index.md
Add a known issue to explain our current lack of support for Kerberos because we had to remove it and can't support the obvious gem.
> (docs) Document support for Kerberos as a known issue (BOLT-980)

- bolt-modules/boltlib/lib/puppet/functions/add_to_group.rb
- lib/bolt/inventory.rb
- lib/bolt/inventory/group.rb
- spec/fixtures/modules/add_group/plans/init.pp
- spec/fixtures/modules/add_group/plans/x_fail_group_name_exists.pp
- spec/fixtures/modules/add_group/plans/x_fail_non_existent_group.pp
- spec/integration/inventory_spec.rb
This commit adds an `add_to_group` method callable from `Target` objects in plans. The method can be called from a `Target` object with the argument of the group to add the `Target` to. When a group does not exist the target will not be added to ANY group. If a `Target` of the same name exists in the requested group it will be overridden by the added `Target`.
> (BOLT-942) Allow target to be added to group during plan execution

- lib/bolt/plan_result.rb
- lib/bolt_spec/plans.rb
- lib/bolt_spec/plans/action_stubs.rb
- lib/bolt_spec/plans/action_stubs/command_stub.rb
- lib/bolt_spec/plans/action_stubs/script_stub.rb
- lib/bolt_spec/plans/action_stubs/task_stub.rb
- lib/bolt_spec/plans/action_stubs/upload_stub.rb
- lib/bolt_spec/plans/mock_executor.rb
- spec/bolt_spec/plan_spec.rb
- spec/fixtures/bolt_spec/plans/plans/apply.pp
- spec/fixtures/bolt_spec/plans/plans/apply_prep.pp
- spec/fixtures/bolt_spec/plans/plans/command.pp
- spec/fixtures/bolt_spec/plans/plans/init.pp
- spec/fixtures/bolt_spec/plans/plans/script.pp
- spec/fixtures/bolt_spec/plans/plans/task.pp
- spec/fixtures/bolt_spec/plans/plans/upload.pp
Adds support for the `_run_as` parameter, `run_command`, `run_script`, and `upload_file` when spec testing plans. Also adds tests for the BoltSpec::Plans module.
> (BOLT-984) Improvements to BoltSpec::Plans

- lib/bolt/analytics.rb
- lib/bolt/applicator.rb
- lib/bolt/executor.rb
- lib/bolt_spec/plans/mock_executor.rb
- spec/bolt/analytics_spec.rb
- spec/bolt/applicator_spec.rb
- spec/bolt/executor_spec.rb
Send a single event for each `apply` that includes metrics for that
apply as custom dimensions: statement count, mean and standard deviation
of resource counts across targets. This provides more flexibility in how
to use the data than sending event values.
> (BOLT-644) Send a single event for apply with metrics

- pre-docs/bolt_installing.md
Our previous instructions for using gems with Bolt required
root/Admnistrator access on the host. That is not required to install
Puppet modules, which meant you might be able to install a module but
not the gems required for it to work. Provide instructions that work as
a non-privileged user.
> (docs) Recommend `gem install --user-install`

- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- bolt-modules/boltlib/spec/functions/apply_prep_spec.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/docker.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
- lib/bolt_spec/plans.rb
- lib/bolt_spec/plans/mock_executor.rb
- pre-docs/bolt_configure_orchestrator.md
When Bolt connects to a target over the Orchestrator transport, we know
that the puppet-agent package is installed. Skip querying version to
check. That removes the requirement that the correct version of the
puppetlabs-puppet_agent module is installed in your PE infrastructure to
run `apply_prep`.
> (BOLT-940) Simplify setup for apply with Orchestrator

- Gemfile
The `0.61.0` Rubocop release has a bug tracked with https://github.com/rubocop-hq/rubocop/issues/6550
Pin to `0.60.0` until resolved.
> (maint) Pin Rubocop to 0.60.0

- lib/bolt/transport/ssh/connection.rb
Bolt was timing out on my first trial command:
`bolt command run uptime --nodes mynode`
Verified in code that problem was that Bolt was going out on port 22474 and that the options[:port] in lib/bolt/transport/ssh/connection.rb was empty (same issue and port trying in Ruby 2.5.3 irb) 'mynode' is sub for one of our servers dns:
`#akaruna /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.4.0 $ bolt command run uptime --nodes mynode
#Started on mynode...
#{:verify_host_key=>#<Net::SSH::Verifiers::Always:0x00007f94db37d530>, :timeout=>10, :verbose=>:debug}
#D, [2018-12-05T23:02:12.219769 #57362] DEBUG -- net.ssh.transport.session[3fca6d9ceed4]: establishing connection to mynode:22474`
Verified that setting the port to 22 if not otherwise specified fixed this issue:
`options = { …
> Set default port to 22 for ssh connection if not otherwise specified

- lib/bolt/transport/ssh/connection.rb
This change prevented bolt from honoring port directives in ssh config
This reverts commit 4a50b1500e0a47745c4328d29d3ea06e36d9b731, reversing
changes made to 50fbfc8f47e3132468f9b40e17e009f5574a25e0.
> Revert "Merge pull request #779 from structuralartistry/fix_ssh_port"

- Gemfile
Version 0.61.0 contained a bug so we pinned to 0.60.0 with https://github.com/puppetlabs/bolt/pull/778 PR. The 0.61.1 tag fixes the issue.
> (maint) Bump Rubocop

- lib/bolt/transport/docker.rb
- spec/bolt/transport/docker_spec.rb
This was missed when `wait_until_available` and the `docker` transport
were merged around the same time.
> (BOLT-1018) Implement wait_until_available for the Docker transport

- developer-docs/bolt-server.md
- lib/bolt_server/file_cache.rb
- spec/bolt_server/file_cache_spec.rb
Previously when purging the temporary directory for downloading task files (weekly or on startup) the `tmppath` directory itself was deleted resulting in errors downloading files. Instead of deleting the temporary directory during a purge delete only the contents of the temporary directory.
> (BOLT-969) Exclude cache tmp directory from purge

- bolt-modules/boltlib/lib/puppet/functions/run_task.rb
- bolt.gemspec
- lib/bolt/config.rb
- lib/bolt/executor.rb
- lib/bolt/inventory.rb
- lib/bolt/node/errors.rb
- lib/bolt/target.rb
- lib/bolt/task.rb
- lib/bolt/task/remote.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/remote.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
- pre-docs/bolt_configuration_options.md
- pre-docs/inventory_file.md
- pre-docs/writing_tasks.md
- spec/bolt/applicator_spec.rb
- spec/bolt/inventory_spec.rb
- spec/bolt/transport/docker_spec.rb
- spec/bolt/transport/local_spec.rb
- spec/bolt/transport/shared_examples.rb
- spec/bolt/transport/ssh_spec.rb
- spec/fixtures/modules/remote/tasks/init.json
- spec/fixtures/modules/remote/tasks/init.sh
- spec/integration/apply_compile_spec.rb
- spec/integration/inventory_spec.rb
- spec/integration/remote_spec.rb
- spec/lib/bolt_spec/transport.rb
This adds a remote transport to support revision 4 of the task spec. The
remote transport will proxy a task to the node defined as run-on its
config.
I still want to add a few more tests and update the predocs
> (BOLT-791) Support remote tasks

- Rakefile
- lib/bolt/inventory.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/powershell.rb
- lib/bolt/transport/winrm.rb
- lib/bolt/transport/winrm/connection.rb
- pre-docs/bolt_options.md
- spec/integration/inventory_spec.rb
- spec/integration/local_spec.rb
Add support for local transport on windows OS.
> (BOLT-608) Add `local` transport for Windows OS

- lib/bolt/transport/remote.rb
- spec/bolt/transport/remote_spec.rb
Remote targets should always point to a non-remote target with run-on.
This prevents multiple levels of lookups in loops in trying to determine
the correct proxy and makes behavior clearer when run-on is a group.
> (BOLT-791) Don't allow remote targets to run on other remote targets.

- spec/integration/apply_spec.rb
This is an issue because BOLT-997 means the the agent task won't work if facts are collected by facter instead of the shell facts task.
> (maint) agent was not correctly uninstalled after tests

- pre-docs/writing_tasks.md
_items was part of a pre rev1 task spec proposal and shouldn't appear in
documentation.
> (docs) remove reference to unimplemented '_items' from example

- appveyor.yml
- lib/bolt/transport/local.rb
- spec/bolt/transport/local_spec.rb
- spec/bolt/transport/shared_examples.rb
- spec/spec_helper.rb
When using the local transport set `provided_features` to `shell` or `powershell` to reflect running on a windows or POSIX system. 
Run the local transport unit tests on windows bolt controllers.
> (BOLT-608) Set provided features for local transport  

- Puppetfile
The {ruby,python}_task_helper modules have been refactored to be structured under the `files` instead of the `lib` directory.
> (maint) Bump task helper modules

- bolt.gemspec
Tasks can now make use of `files` content from other modules. Ensure the
bundled modules include the `files` directory, particularly for
`python_task_helper` and `ruby_task_helper`. Also include `locales` for
translations that might be used in plans.
We explicitly exclude other things to restrict this to plan and task
content. We'd rather manifests and other traditional Puppet content be
explicitly pulled in by users that want them.
> (BOLT-1036) Include 'files' content from bundled modules

- lib/bolt_spec/run.rb
- spec/bolt_spec/run_spec.rb
This commit adds the ability to use `bolt apply` in `BoltSpec`. An `apply_manifest` function has been added to `BoltSpec::Run` module to allow applying manifest code from a file or from a string with the `:execute` option.
> (BOLT-954) Support bolt apply in BoltSpec

- lib/bolt/bolt_option_parser.rb
- pre-docs/bolt_command_reference.md
- spec/bolt/cli_spec.rb
**What this changes** Adds shortened command syntax for description, modulepath, inventoryfile, transport, and verbose.
**Why** So they're faster to type.
> (BOLT-1047) Add short commands

- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- bolt-modules/boltlib/lib/puppet/functions/get_resources.rb
- bolt-modules/boltlib/spec/functions/get_resources_spec.rb
- lib/bolt/applicator.rb
- lib/bolt_spec/plans.rb
- lib/bolt_spec/plans/action_stubs/script_stub.rb
- lib/bolt_spec/plans/action_stubs/task_stub.rb
- libexec/query_resources.rb
- spec/bolt_spec/plan_spec.rb
- spec/fixtures/apply/basic/plans/resources.pp
- spec/fixtures/bolt_spec/plans/plans/apply_prep.pp
- spec/fixtures/bolt_spec/plans/plans/get_resources.pp
- spec/integration/apply_spec.rb
Adds a `get_resources` function that can be run against targets with Puppet Agent installed to query the state of resources on those nodes.
> (BOLT-1035) Add get_resources function

- bolt-modules/boltlib/spec/functions/get_resources_spec.rb
- lib/bolt_spec/plans.rb
- lib/bolt_spec/plans/action_stubs.rb
Remove unused code, and make `allow_*` truly unlimited in BoltSpec::Plans
unless overridden by `be_called_times`.
> (BOLT-1035) Fixes based on further code review

- lib/bolt/config.rb
- pre-docs/bolt_configuration_options.md
- spec/bolt/config_spec.rb
This allows the `modulepath` setting in `bolt.yaml` to be specified as an
array of module directories in addition to the previous behavior of a
PATH-like string. Because the PATH separator varies by platform, this
allows users to write a single `bolt.yaml` that will work on both *nix
and Windows systems.
> (BOLT-817) Support array of directories for modulepath

- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- pre-docs/bolt_configuration_options.md
- spec/bolt/transport/ssh_spec.rb
inventory
```
nodes:
- ma4wbg4k9352e3q.delivery.puppetlabs.net
config:
ssh:
proxyjump: u0tfqlau5siznqy.delivery.puppetlabs.net
host-key-check: false
```
usage
```
clavelin:bolt adreyer$ bundle exec bolt command run hostname -n ma4wbg4k9352e3q.delivery.puppetlabs.net
Started on ma4wbg4k9352e3q.delivery.puppetlabs.net...
Warning: Permanently added 'u0tfqlau5siznqy.delivery.puppetlabs.net,10.16.115.130' (ECDSA) to the list of known hosts.
Finished on ma4wbg4k9352e3q.delivery.puppetlabs.net:
STDOUT:
ma4wbg4k9352e3q
```
> (BOLT-1039) expose proxyjump option from bolt config.

- pre-docs/writing_plans.md
In the documentation for `puppetdb_query` i noticed the syntax highlighting was broken. After further inspection it appears a quote is missing in the example. This PR adds the missing quote.
> Added missing quote to puppetdb_query example

- pre-docs/inventory_file.md
**What this changes** Replaces incorrect `transports` reference with correct transport-specific config option
> (maint) Correct `transports` reference in inventoryfile

- Puppetfile
Fix installing puppet_agent when facter is already installed on some
platforms where facter and the facts scripts differ.
> (BOLT-997) Bump facts and puppet_agent modules for fix

- bolt-modules/ctrl/lib/puppet/functions/ctrl/do_until.rb
- pre-docs/plan_functions.md
Previously the example used to generate function docs was missing parens.
> (docs) Add missing parens to ctrl::do_until function example

- acceptance/setup/gem/pre-suite/020_install.rb
- acceptance/setup/git/pre-suite/020_install.rb
The `--no-ri` and `--no-doc` flags have been deprecated for bundler. (https://github.com/rubygems/rubygems/commit/0d22d6025ce2653ec9fb20a4e0745c79bda677da) user `--no-document` instead.
> (maint) Update bundle command for installing from Gem

- pre-docs/running_bolt_commands.md
@melamos This is really painful when users run into it. I'm not sure how to make it as discoverable as possible.
> (BOLT-1056) Add warning about using shell one-liners

- acceptance/setup/common/pre-suite/010_install_ruby.rb
Only the latest `ffi` version is compatable with ruby 2.6 on windows. Use choco to install pinned version of ruby for acceptance tests.
> (maint) Pin ruby to version 2.5 on windows

- lib/bolt/transport/local/shell.rb
- spec/bolt/transport/shared_examples.rb
Fixes the exit status return value for local transport. 
Based on the documentation for Process::Status https://ruby-doc.org/core-2.5.0/Process/Status.html :+1: 
```
Posix systems record information on processes using a 16-bit integer. The lower bits record the process status (stopped, exited, signaled) and the upper bits possibly contain additional information (for example the program's return code in the case of exited processes). Pre Ruby 1.8, these bits were exposed directly to the Ruby program. Ruby now encapsulates these in a Process::Status object. To maximize compatibility, however, these objects retain a bit-oriented interface. In the descriptions that follow, when we talk about the integer value of stat, we're referring to this 16 bit value.
```
To get the actual exit status we …
> (BOLT-1074) Fix exit status return value for local transport

- lib/bolt/transport/api.rb
- lib/bolt/transport/api/connection.rb
- lib/plan_executor/app.rb
- lib/plan_executor/executor.rb
- spec/bolt/transport/api_spec.rb
- spec/plan_executor/executor_spec.rb
This adds a new executor class for the `plan_executor` service, which bypasses logic around batching and queueing and exclusively uses the orchestrator transport. It also includes a new api transport class based on the orchestrator transport, which doesn't call `start_plan` as that's handled by the orchestrator.
Giving the plan executor service it's own executor greatly simplifies the logic around running jobs through the service.
> (BOLT-1007) Create plan executor class for plan_executor service

- lib/bolt/transport/local.rb
Previously other errors from invoking a task or script would also be
caught and wrapped in FileError. We should only do that for errors we
know are related to creating the tmpdir.
> (maint) Only wrap tmpdir-related errors in FileError

- lib/bolt/puppetdb/config.rb
- spec/bolt/puppetdb/config_spec.rb
Previously bolt would fail to run if it failed to read puppetdb.conf.
Now it will issue an error level log message but continue running.
> (BOLT-756) Don't error when puppetdb.conf can't be loaded.

- acceptance/files/example_apply/plans/puppet_status.pp
- acceptance/setup/common/pre-suite/071_install_modules.rb
- acceptance/tests/apply_plan_ssh.rb
- acceptance/tests/apply_plan_winrm.rb
The most reliable way to query the status of puppet using the service task is the ruby implementation. This commit uses updated service, package, and puppet_agent modules for git based testing and updates the apply tests to use the service::init task by wrapping in a plan that sets the puppet-agent feature on target nodes.
> (BOLT-1049) Update acceptance tests to service::init task

- lib/bolt/puppetdb/config.rb
Previously an error message would occur if no puppetdb.conf was found.
> (BOLT-756) Only try to load puppetdb.conf if exists

- Rakefile
- pre-docs/plan_functions.md
Previously the `docs` rake task would output to `REFERENCE.md` and the output would be added to `pre-docs/plan_functions.md`. This commit changes the `docs` rake task to update the `plan_functions.md` file directly.
> (docs) Track output of rake docs task as plan_functions.md

- bolt.gemspec
- lib/bolt/puppetdb/client.rb
- spec/integration/apply_compile_spec.rb
This commit adds `HTTPClient::ConnectTimeoutError` to the list of handled exceptions for rolling with a puppetdb failover. Previously this would raise a PuppetDBerror and not result in checking for other acceptable puppetdb connections.
> (BOLT-938) Handle connect timeout error for puppetdb client failover

- lib/bolt/inventory/group.rb
- spec/bolt/inventory/group_spec.rb
This allows valid hostnames like prod-master-1 to be used as aliases,
without having to translate the hyphens to underscores. This does not
allow an alias to _begin_ with a hyphen.
> (BOLT-1022) Allows hyphens in aliases and group names

- Puppetfile
- acceptance/setup/common/pre-suite/071_install_modules.rb
The powershell implementation for the puppet_agent::install task now downloads the msi over https instead of http.
> (FM-7656) Update puppet_agent module ref

- Puppetfile
- acceptance/setup/common/pre-suite/071_install_modules.rb
The puppet_agent module has reached a 2.x release that includes task content! This allows us to download from puppet forge by version instead of github reference.
> (maint) Track puppet_agent module by tag instead of commit

- spec/Dockerfile.puppetdb
The puppetdb docker image has had a major update that changes the way we use in for testin bolt. This commit pins to a compatible version while we sort out how to update tests to be compatible with new image.
> (maint) Pin to compatible puppetdb docker image

- acceptance/tests/apply_plan_ssh.rb
- acceptance/tests/bolt_apply.rb
Puppet agent is not yet available for osx 10.14. Previously we skipped agent dependent tests for osx 10.11 for a similar reason. This can be reverted once puppet agent is available on osx 10.14.
> (BOLT-1040) Skip puppet-agent dependent tests for osx-10.14

- pre-docs/writing_plans.md
Plan parameters can be passed as either key=value pairs (where complex
values must be encoded as JSON) or with `--params` followed by a
stringified JSON object. The example mixed those patterns incorrectly.
> (BOLT-1099) Correct inconsistent example of passing plan parameters

- lib/bolt/transport/orch.rb
- spec/bolt/transport/orch_spec.rb
The bolt_shim::script task now expects the script extension to be provided when the target is has a windows OS. See https://github.com/puppetlabs/puppetlabs-bolt_shim/pull/8 for corresponding bolt_shim module PR.
> (BOLT-830) Add script extension metadata for bolt_shim script task

- Puppetfile
- acceptance/setup/common/pre-suite/071_install_modules.rb
We would like to ship bolt with the update described in FM-7732. When the next release goes out has that update we will switch back to downloading from forge release.
> (FM-7732) Track master branch of puppet_agent for update

- pre-docs/bolt_installing.md
- pre-docs/index.md
**What this changes** Adds Fedora 28 and 29 to the install documentation
**Why** We now ship Fedora 28 and 29 packages
> (BOLT-978) Update install docs to include Fedora 28 and 29

- pre-docs/bolt_installing.md
Include path to download link for bolt package built for Mojave.
> (BOLT-1040) Update install docs for bolt on macOS 10.14

- pre-docs/bolt_configure_orchestrator.md
The docs had a reference to an outdated bolt_shim version. This commit updates the reference to the latest version. Mainly to support running powershell tasks over pcp against windows targets.
> (BOLT-830) Update bolt_shim module version in docs

- lib/plan_executor/app.rb
- lib/plan_executor/executor.rb
- lib/plan_executor/orch_client.rb
- spec/plan_executor/app_spec.rb
- spec/plan_executor/executor_spec.rb
- spec/plan_executor/orch_client_spec.rb
Previously, the plan executor service used the public orchestrator API
to run plan tasks and submit plan results. This required it to follow
the same rules as a user running plans; specifically, it needed to
authenticated with an RBAC token and was only allowed to operate on
plans that were started by the same user for whom its RBAC token was
issued.
Now the service uses the internal API with certificate authentication to
connect as the API user and operate on plans with complete authority.
Because the public orchestrator-client library doesn't support features
we *need* like certificate authentication and the internal command API,
and it *does* have some automatic behavior around config loading that
we *don't* want, we now use a JSONClient (from the httpclient library)
directly to talk …
> (BOLT-1107) Use internal orchestrator API for running plan tasks

- lib/bolt/boltdir.rb
Previously site specific modules were expected to be in the default `site` directory. This was just a convention and the name `site` doesn't clearly convey what it is for. This commit adds a new default `site-modules` directory to the modulepath. This makes it more clear to users that this is a directory that modules go in.
> (BOLT-1108) Add site-modules to modulepath

- bolt.gemspec
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- lib/bolt/pal.rb
This commit adds a `bolt module show` command that lists out each module path
in the Bolt environment, followed by the modules available and their versions
in a manner similar to `puppet module list`.
> (BOLT-1118) Add command to show available modules

- lib/plan_executor/orch_client.rb
In order to support powershell tasks on windows targets the bolt_shim module expects the script basename to be included for the `script` task.
> (BOLT-830) Send file basename to bolt_shim script task

- lib/bolt_spec/run.rb
- spec/bolt_spec/run_spec.rb
- spec/integration/apply_spec.rb
Previously, these methods had confusing and inconsistent signatures
using a mix of optional parameters and keyword arguments. In some cases,
the optional parameters were themselves expects to be hashes, which
conflicted with the keyword arguments. That caused confusing behavior
when invoking the functions with only some arguments, as a hash intended
to be a positional argument could be interpreted as an _invalid_ keyword
arguments hash, or vice versa.
These functions now always require their `params` (or equivalent)
argument, leading to slightly more verbose but always clear
invocations. The functions which previously expected an options hash in
addition to their keyword arguments now expect the options hash to
be provided as a keyword argument named `options`.
> (BOLT-1057) Standardize BoltSpec::Run helper method signatures

- pre-docs/bolt_known_issues.md
- A simple fix was put in place for the triple quotes problem, but a
large problem with JSON handling still looms.
BOLT-1130 has been created to describe / address that problem and
the known issues have been updated accordingly.
> (BOLT-159) Replace known issue 159 with BOLT-1130

- Puppetfile
The 0.3.0 release includes a bug fix that symbolizes all parameter keys passed to the TaskHelper::task method by TaskHelper::run.
> (BOLT-1053) Update ruby_task_helper to 0.3.0

- lib/bolt/config.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/docker.rb
- lib/bolt/transport/docker/connection.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/local/shell.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/remote.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/transport/winrm.rb
- lib/bolt/transport/winrm/connection.rb
- pre-docs/bolt_configuration_options.md
- spec/bolt/applicator_spec.rb
- spec/fixtures/modules/sample/tasks/bolt_ruby.json
- spec/fixtures/modules/sample/tasks/bolt_ruby.rb
- spec/fixtures/modules/sample/tasks/interpreter.json
- spec/fixtures/modules/sample/tasks/interpreter.py
- spec/integration/docker_spec.rb
- spec/integration/local_spec.rb
- spec/integration/ssh_spec.rb
- spec/integration/winrm_spec.rb
This commit adds a configuration option to the local transport to configure what interpreter to run a task with. If an interpreter is set for a task with a given extension then that will override the shebang in the task.
> (BOLT-146) Add configuration option to set task interpreter

- CONTRIBUTING.md
- Vagrantfile
- appveyor.yml
- bolt.gemspec
- lib/bolt/config.rb
- lib/bolt/transport/winrm.rb
- lib/bolt/transport/winrm/connection.rb
- pre-docs/bolt_configuration_options.md
- spec/bolt/applicator_spec.rb
- spec/bolt/inventory_spec.rb
- spec/bolt/transport/winrm_spec.rb
Updated version of #856 - adds / addresses a small number of new things
- Fixes `Vagrantfile` to port forward 445 to 2445 of host (else there is no way to test locally)
- Errors when SSL is specified in conjunction with SMB (as encryption is not yet available)
- Removes SMB1 support
- Uses `WindowsError::NTStatus` status objects rather than embedding Win32 error codes
- Improves error handling / messages when SMB port gets a connection refused error
- Adds smb-port configuration option (defaults to port 445)
- Adds tests against SMB transfers
- Adds recursive directory copy over SMB
From original PR courtesy @joshcooper:
WinRM sucks for file transfer because it base64 encodes the payload,
compresses it as a zip file, transfers the contents via Powershell in
SOAP/XML messages, and …
> (BOLT-153) Windows SMB file transfer support

- lib/bolt_spec/plans.rb
In order to load and configure Puppet, Bolt and the logger, users need
to call `BoltSpec::Plans.init` before any tests run. This commit
documents that fact alongside the rest of the BoltSpec inline
documentation.
> (BOLT-1073) Document how to init BoltSpec

- lib/bolt_server/schemas/ssh-run_task.json
- lib/bolt_server/schemas/winrm-run_task.json
The `file-protocol`, `smb-port` options have been added to winrm transport. The `interpreters` option has been added to both winrm and ssh. This commit allows those configuration options in the {winrm,ssh}-run_task schemas.
> (BOLT-146)(BOLT-153) Update bolt-server schemas

- lib/bolt/transport/ssh.rb
- spec/integration/ssh_spec.rb
The initial implementation of the `interpreters` configuration option for BOLT-146 failed to handle the case where a task both expected parameters to be passed over STDIN and be run with privilage escalation configured with the `run-as` option. Specifically the wrapper script that is used to invoke the task and pass the parameters needed to be updated to include the interpreter. This commit adds and update to the wrapper script to respect the interpreter while using the `run-as` feature.
> (BOLT-1155) Update wrapper script used for run-as over ssh

- lib/bolt/transport/base.rb
- spec/bolt/executor_spec.rb
- spec/fixtures/run_as/test/plans/run_as_user.pp
- spec/integration/run_as_spec.rb
Previously when the `run-as` option was set (config, inventory, CLI) any run_* function that specified the `_run_as` option would be overriden. This led to confusing behavior for users. This commit removes overriding `_run_as` with `run-as`.
> (BOLT-1050) Do not override _run_as in plans with config

- pre-docs/writing_tasks.md
It seems that in a revision the example wrapper task got a character truncated from the end. This commit updates with the character added back.
> (maint) Fix typo in wrapping an existing script with task docs

- bolt.gemspec
Pull in new features and bug fixes for r10k by requiring `~> 3.1`
> (BOLT-1106) Bump r10k major version

- pre-docs/writing_plans.md
- pre-docs/writing_tasks.md
This commit documents how parameter that have the value `nil` are passed to tasks that use the `environment` `input-method` as the string value `null`.
> (BOLT-1085) Document how nil values are passed to tasks

- pre-docs/bolt_installing.md
Add a warning in the installation documentation about enabling the puppet 6 repo when installing bolt on puppet master.
> (BOLT-1142) Add warning about enabling puppet 6 foss repo on master

- bolt.gemspec
- spec/bolt/transport/orch_spec.rb
The 0.4.2 version of orchestrator_client adds persistent HTTP connections for linux clients as well as validation and helpful error messages for token-file config.
> (BOLT-1076) Bump orchestrator_client gem

- lib/bolt/pal.rb
- lib/bolt/pal/yaml_plan_evaluator.rb
- spec/bolt/cli_spec.rb
- spec/fixtures/modules/sample/plans/yaml.yaml
This allows `bolt plan show` and `bolt plan show <plan>` to find and
display YAML plans. We create a new YamlPlanEvaluator class and pass it
to Puppet via the context (as yaml_plan_instantiator), which then calls
back into Bolt whenever a YAML plan is loaded. This allows the logic for
listing and finding plans to live in Puppet, but for all of the logic
about how to run them to live in Bolt.
The execution of YAML plans follows a similar model as Puppet plans: we
create a Puppet function which, when invoked, will run the plan. We
use a PlanWrapper class to encapsulate the plan data and make it behave
like a Puppet PlanDefinition object. This commit also includes an empty
definition of the `evaluate_block_with_bindings` method, which allows
our YamlPlanEvaluator to function as though it …
> (BOLT-1151) Load and show YAML plans

- lib/bolt/executor.rb
- lib/bolt/pal/yaml_plan_evaluator.rb
- spec/bolt/pal/yaml_plan_evaluator_spec.rb
- spec/integration/plan_spec.rb
This implements support for running YAML plans containing task and command
steps only. Every other kind of step is unsupported.
Variable interpolation is supported for targets and for parameter values,
with only exact variable matches (like `$foo`) being supported. Any other
value will be treated as a literal.
> (BOLT-1152) Run YAML plans

- lib/bolt/transport/ssh/connection.rb
The 5.2.0 release of net-ssh contains an update to behavior of host-key-check to be more consistent with that of ssh(1). Ssh(1) does not require both hostname and IP when performing host-key-check where net-ssh < 5.1.0 did. This was causing issues for users whereby they could ssh to their nodes with system ssh but not with the bolt ssh transport. The net-ssh maintainer agree to the following plan:
1.) 5.2.0 introduce check_host_ip: false flag, and set check_host_ip to false if CheckHostIP false in net-ssh configs
2.) 6.0 make check_host_ip: false the default and give deprecation warning for check_host_ip: true usage
3.) 7.0 remove check_host_ip
This commit ensures that the check_host_ip flag is set to false.
> (BOLT-495) Set check_host_ip flag to false for net-ssh

- bolt-modules/system/lib/puppet/functions/system/env.rb
Rubocop 0.66.0 now identifies that `ENV[]` will always return frozen
strings and therefore our freeze is redundant.
> (maint) Remove redundant freeze

- lib/bolt/analytics.rb
- lib/bolt/applicator.rb
- lib/bolt/config.rb
- lib/bolt/executor.rb
- lib/bolt/notifier.rb
- lib/bolt/transport/docker/connection.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/transport/winrm/connection.rb
- lib/bolt_server/file_cache.rb
- lib/plan_executor/app.rb
- spec/fixtures/scripts/bolt_cli_loader.rb
- spec/integration/cli_spec.rb
- spec/spec_helper.rb
Refactors code loads so that gem code that isn't needed for commands like `help` will never be loaded
In a Windows 10 VM test environment, this PR will:
* Cut run time from 4.4 seconds to 2.6 seconds (times vary depending on disk IO - in pathological cases the difference can be much more extreme)
* Reduces the amount of code Ruby loads from 845 files down to 395 files
Things to still improve
Moving further exploration / improvements to #906
> (BOLT-1119) Improve Bolt startup time (on Windows)

- lib/bolt/transport/ssh/connection.rb
Acceptance tests were failing because "cannot modify frozen string" using ssh transport from a windows bolt controller. This commit does not freeze the PAGEANT_NAME string.
> (BOLT-1119) Fix error when using ssh transport on windows controller

- lib/bolt/transport/ssh/connection.rb
- To properly load alongside Puppet, the require for Win32API must
use the same case as Puppet.
From the Puppet code:
require 'Win32API' # case matters in this require!
- Without this change, Bolt will stream a number of warnings like:
C:/PROGRA~1/PUPPET~1/Bolt/lib/ruby/2.5.0/win32api.rb:10: warning: already initialized constant Win32API::DLL
C:/PROGRA~1/PUPPET~1/Bolt/lib/ruby/2.5.0/Win32API.rb:10: warning: previous definition of DLL was here
C:/PROGRA~1/PUPPET~1/Bolt/lib/ruby/2.5.0/win32api.rb:11: warning: already initialized constant Win32API::TYPEMAP
C:/PROGRA~1/PUPPET~1/Bolt/lib/ruby/2.5.0/Win32API.rb:11: warning: previous definition of TYPEMAP was here
C:/PROGRA~1/PUPPET~1/Bolt/lib/ruby/2.5.0/win32api.rb:12: warning: already initialized constant Win32API::POINTER_TYPE …
> (BOLT-1119) Ensure Win32API require case correct

- lib/bolt/pal.rb
- lib/bolt/pal/yaml_plan.rb
- lib/bolt/pal/yaml_plan/evaluator.rb
- lib/bolt/pal/yaml_plan/loader.rb
- spec/bolt/pal/yaml_plan/evaluator_spec.rb
- spec/bolt/pal/yaml_plan/loader_spec.rb
- spec/bolt/pal/yaml_plan_spec.rb
Previously, there was no way for one step to rely on the result of another
step. Now we expose the result of each named step as a variable with the
same name as the step. This allows parameters for one step to be computed
by using the result of a previous step. The result for a step _without_ a
name will be discarded.
We also now validate that step names are legal variable names and that there
are no duplicate names between parameters and steps, as Puppet variables can
only be defined once.
This also includes a performance improvement to the YAML plan loader as well as
an improvement to how errors are displayed when listing plans.
> (BOLT-1171) Expose step results as variables

- lib/bolt/pal/yaml_plan.rb
- lib/bolt/pal/yaml_plan/evaluator.rb
- spec/bolt/pal/yaml_plan/evaluator_spec.rb
- spec/fixtures/modules/sample/plans/yaml.yaml
- spec/fixtures/modules/yaml/files/test.sh
- spec/fixtures/modules/yaml/plans/command.yaml
- spec/fixtures/modules/yaml/plans/param_passing.yaml
- spec/fixtures/modules/yaml/plans/script.yaml
- spec/fixtures/modules/yaml/plans/task.yaml
- spec/fixtures/modules/yaml/plans/upload.yaml
- spec/integration/plan_spec.rb
- spec/integration/yaml_plan_spec.rb
Previously, YAML plans always returned `undef`. Now they accept a top-level
`return` key which can be either a value or an expression which will be
evaluated and returned after the plan finishes. Plans which don't specify a
`return` will still return `undef`.
> (BOLT-1187) Accept a `return` expression for YAML plans

- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
Previously, we were running plans in the scope in which they were
called, causing variables in the surrounding scope to be visible to the
plan. We now run plans from the scope in which they're defined, which is
global scope. That causes every plan invocation to have a fresh scope
without any stray variables polluting it.
> (BOLT-1190) Don't leak scope to sub-plans

- pre-docs/bolt.md
- pre-docs/writing_plans.md
- pre-docs/writing_tasks_and_plans.md
- pre-docs/writing_yaml_plans.md
This adds a new page on writing YAML plans and links to it from several
other places in the docs.
> (BOLT-1189) Document how to write YAML plans

- lib/bolt/pal/yaml_plan/evaluator.rb
- spec/bolt/pal/yaml_plan/evaluator_spec.rb
- spec/fixtures/modules/yaml/plans/define_foo.yaml
- spec/fixtures/modules/yaml/plans/delegate.yaml
- spec/fixtures/modules/yaml/plans/plan_isolated_from_subplan.yaml
- spec/fixtures/modules/yaml/plans/plan_with_isolated_subplan.yaml
- spec/fixtures/modules/yaml/plans/undefined_var.yaml
- spec/integration/yaml_plan_spec.rb
This adds a `plan` step which can be used to run another plan.
This also fixes an issue with scope leaking between plan invocations.
Previously, we were running plans in the scope in which they were called,
causing variables in the surrounding scope to be visible to the plan. We now
run plans from the scope in which they're defined, which is global scope. That
causes every plan invocation to have a fresh scope without any stray variables
polluting it.
> (BOLT-1175) Support running plans from YAML plans

- lib/bolt/pal/yaml_plan/loader.rb
**What this changes** This checks the `Psych.parse` signature available in the installed ruby stdlib to see if `legacy_filename` is available. If it is, we can assume passing filename using the keyword parameter. If not, use the old Psych.parse signature and just pass a filename
**Why** So that we can successfully load plans on ruby < 2.6
> (BOLT-1201) Use old Psych.parse signature if needed

- acceptance/Gemfile
- acceptance/setup/package/pre-suite/020_install.rb
It appears that most of the sticky points for staying on beaker 3 have been worked out. Adding the new platform requires a change to beaker that landed in the 4 series. This commit begins the attempt to migrate to beaker 4.
> (maint) Building for el 8 requires patches that landed in beaker 4

- Gemfile
- bolt.gemspec
This is the version that contains YAML plan loading.
> (BOLT-1150) Bump puppet dependency to 6.4.0

- lib/bolt/apply_result.rb
- lib/bolt/result.rb
- lib/bolt/transport/docker.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/winrm.rb
- lib/bolt_spec/plans/action_stubs/command_stub.rb
- lib/bolt_spec/plans/action_stubs/script_stub.rb
- spec/bolt/apply_result_spec.rb
- spec/bolt/cli_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/bolt/result_set_spec.rb
- spec/bolt/result_spec.rb
- spec/bolt/transport/orch_spec.rb
- spec/bolt/transport/shared_examples.rb
- spec/integration/target_spec.rb
This adds type and object keys to the result object that display what
type is was(task/command...) and what the object or first argument to
the action was.
> (BOLT-1125) Add more information about what was run to Results

- lib/bolt_spec/run.rb
- spec/bolt_spec/run_spec.rb
This commit facilitates setting inventory and config for BoltSpec::Run methods using memoized helper methods from RSpec. BoltSpec will attempt to look up a `bolt_inventory` or `bolt_config` method from RSpec and use that if `:config` or `:inventory` is not set in the call to run_*.
> (BOLT-1206) Allow configuration of BoltSpec via Rspec

- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
- lib/bolt/analytics.rb
- lib/bolt/executor.rb
- lib/bolt/pal/yaml_plan/evaluator.rb
- pre-docs/bolt_installing.md
We now submit a "Plan -> yaml" event when running a YAML plan, which
includes the number of steps in the plan and whether the return value of
the plan is a constant value or a Puppet expression.
> (BOLT-1193) Collect data about YAML plan usage

- pre-docs/writing_yaml_plans.md
This commit reworks the docs for YAML plans to flow in the same way that
users will likely adopt features. Previously, it was structured purely
as reference documentation, and assumed a base of Puppet knowledge. This
commit fleshes out some of the information about how to do basic
operations in Puppet like array/hash indexing, function invocation, and
blocks.
This also adds a clear warning that YAML plans are an experimental
feature subject to change.
> (BOLT-1218) Improve YAML plan documentation

- pre-docs/bolt_installing.md
This commit documents installing puppet-bolt on el 8 platforms. Bolt is build and tested on redhat 8, this should also cover centos 8 when that is available.
> (BOLT-1204) Document installing bolt on el 8 platforms

- pre-docs/bolt_configuration_options.md
**What this changes** Corrects "ssl: When true, Bolt will use normal http connections for WinRM. Default is true" to "ssl: When true, Bolt will use https connections for WinRM. Default is true"
> (maint) Docs typo: http -> https

- spec/bolt_server/app_integration_spec.rb
The app_integration.rb spec appeared to have been filtered out because it did not match the pattern `--pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb`.
> (maint) Activate bolt_server integration test

- .rubocop.yml
- .travis.yml
- lib/bolt/config.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/local/shell.rb
- lib/bolt/transport/local_windows.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/transport/sudoable.rb
- lib/bolt/transport/sudoable/connection.rb
- lib/bolt/transport/sudoable/tmpdir.rb
- pre-docs/bolt_configuration_options.md
- spec/bolt/transport/local_spec.rb
- spec/bolt/transport/shared_examples.rb
- spec/bolt/transport/ssh_spec.rb
- spec/integration/inventory_spec.rb
- spec/integration/local_spec.rb
- spec/spec_helper.rb
This adds support for `run-as`, `sudo-password`, and `run-as-command` to the local transport. These can be configured in the config file, by command line options, or in the inventory file, and should behave exactly like the same options for SSH.
I ended up keeping the SSH and local functionality mostly separate in order to take advantage of `popen3` and other system libraries for the local transport. I also pulled most of SSH's `sudo` tests into the shared examples so that local can use them.
>  (BOLT-1052) Add run-as option to local transport 

- .rubocop.yml
- acceptance/files/example_apply/lib/puppet/type/warn.rb
- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
- lib/bolt/analytics.rb
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/executor.rb
- lib/bolt/pal.rb
- lib/bolt/puppetdb/client.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/transport/sudoable.rb
- lib/bolt/transport/winrm.rb
- lib/bolt_server/transport_app.rb
- spec/bolt/applicator_spec.rb
- spec/bolt/cli_spec.rb
- spec/bolt/executor_spec.rb
- spec/bolt/inventory_spec.rb
- spec/bolt/transport/remote_spec.rb
- spec/bolt/transport/shared_examples.rb
- spec/bolt/transport/ssh_spec.rb
- spec/fixtures/apply/basic/lib/puppet/type/warn.rb
- spec/integration/apply_compile_spec.rb
The Executor currently takes both optional args and keyword args. It also takes
a couple of its arguments (`bundled_content` and `load_config`) purely so it
can pass them along to other parts of the system that need them.
This PR reworks the keyword args to be set more directly on the objects that
need them, rather than passing them through the Executor.
We now set `bundled_content` directly on the analytics client, since that's the only place it's needed.
We set `load-config` directly on Target objects via a default on the transport,
and override it explicitly in bolt-server. This carries the setting with the
Target, rather than leaking an implementation detail of the SSH transport into
the Executor. This specifically does _not_ allow `load-config` to be set in the
Bolt config or …
> (maint) Simplify Executor initialize signature

- appveyor.yml
- ci.ps1
- There's a bunch of redundant and hard to read code in appveyor.yml
that is moved verbatim to a separate file ci.ps1, then is refactored
- Break it into reusable functions (that can also be used in local dev):
* Set-CACert - Sets `SSL_CERT_FILE` environment variable to the latest CA bundel from curl.haxx.se
* Install-Puppetfile - Installs the CA bundle, sets env var and installs the Puppetfile
* New-RandomPassword - generates random password
* New-LocalAdmin - creates a new user with name / password and adds them to RDP group
* Install-Certificate - installs a cert in the machine store given its password
* Grant-WinRMHttpsAccess - enables winrm SSL access given a cert thumbprint
* Set-WinRMHostConfiguration - CI helper that wraps up installing the bolt cert and configuring winrm to use …
> (BOLT-1209) Refactor AppVeyor commands to PowerShell script / verify WinRM connection in PowerShell

- CONTRIBUTING.md
- README.md
- pre-docs/bolt.md
- pre-docs/bolt_installing.md
This adds our Slack channel info to the README, the main `bolt` documentation page, and the `installing Bolt` page. Also adds Puppet's twitter to the `bolt` docs page, and updates verbage of the CONTRIBUTING doc for consistency.
> (BOLT-1133) Add slack channel info to documentation

- lib/bolt/inventory.rb
- lib/bolt/inventory/inventory2.rb
- lib/bolt/task.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/local_windows.rb
- spec/bolt/applicator_spec.rb
- spec/bolt/inventory/inventory2_spec.rb
- spec/bolt/inventory_spec.rb
- spec/integration/local_spec.rb
This ensures that 'magic' local config only gets merged with the provided config when the hostname is localhost, regardless of the transport used. The 'magic' config options for localhost are to add the `puppet-agent` feature to the localhost target, and to set the default ruby interpreter to be Bolt's ruby.
> (BOLT-1205, BOLT-1200) Add default local config only for localhost

- .travis.yml
- lib/bolt/transport/local/shell.rb
**What this changes** If the readstream had reached EOF then select will still return the stream as available for reading, per http://man7.org/linux/man-pages/man2/select.2.html. We want to catch an EOF error if the stream can't be read and return an empty string to the node output.
**Why** This breaks when the user is not prompted for a password, for instance if the user doesn't have a password. Instead it should escalate the user and continue executing.
> (BOLT-1242) Don't check for sudo prompt when stderr is EOF

- spec/bolt/puppetdb/client_spec.rb
Previously, these tests were using bad_host{1,2}.dne.com as their
example "bad" hosts. However, those hosts happen to actually resolve to
servers somewhere, which blackhole our connections, causing them to
block for 60 seconds before finally timing out. Since we attempt three
total connections to these hosts, that adds 180 unnecessary seconds to
the test runtime. In general, it's also bad practice for our tests to
attempt to connect to random machines on the internet.
We now use example.com, which is specifically intended for this kind of
use case and simply fails to resolve. This causes the tests to fail fast
and cuts off three minutes from their runtime.
> (maint) Speed up PuppetDB tests which timed out

- lib/bolt/bolt_option_parser.rb
- lib/bolt/boltdir.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/rerun.rb
- lib/bolt/result.rb
- pre-docs/bolt_command_reference.md
- pre-docs/bolt_configuration_options.md
- pre-docs/bolt_options.md
- spec/bolt/cli_spec.rb
- spec/bolt/rerun_spec.rb
- spec/bolt/result_set_spec.rb
- spec/bolt/transport/ssh_spec.rb
- spec/integration/target_spec.rb
Bolt will now write a <boltdir>/.last_result.json file whenever a
command fails. Users can use this file to target nodes from the last
failure with the `--retry` flag.
In order to avoid spreading `nodes` to a new file this also adds a
`target` key to the status hash of Results.
This still needs predocs.
> (BOLT-843) Support retrying on failed nodes.

- lib/bolt/inventory/group2.rb
- lib/bolt/inventory/inventory2.rb
- spec/bolt/inventory/group2_spec.rb
- spec/bolt/inventory/inventory2_spec.rb
- spec/fixtures/modules/add_group/plans/init.pp
- spec/integration/inventory2_spec.rb
Moving forward bolt will standardize on calling targets targets instead
of nodes to avoid confusion about remote targets. This commit causes the
version 2 inventory file to look in `targets` instead of `nodes` for the
members of a group.
> (BOLT-1231) Switch V2 inventory to use 'targets' instead of 'nodes.

- lib/bolt/rerun.rb
Previously if there is no `.rerun.json` and a plan exits with non-ResultSet a warning is logged. This commit updates rerun logic to only attempt to delete the rerun file if it exists.
> (maint) Only attempt delete .rerun.json if it exists

- spec/fixtures/modules/add_group/plans/init.pp
- spec/integration/inventory2_spec.rb
- spec/integration/inventory_spec.rb
Previously the test to verify that `add_to_group` does not overwrite existing targets in inventory was mislabled and did not actually test the functionality. This commit adds more descriptive names. It updates the tests such that when a target exists in inventory and has an associated var, adding a target with the same name from a plan using the `add_to_group` function does not overwrite or try to duplicate the target.
> (maint) Fix inventory add_to_group integration test

- pre-docs/writing_yaml_plans.md
We defined 2 parameters `frontends`, based on the descriptions the second should be `backends`.
> (maint) Fix typo in yaml plan docs

- lib/bolt/pal/yaml_plan.rb
- lib/bolt/pal/yaml_plan/evaluator.rb
- spec/bolt/pal/yaml_plan/evaluator_spec.rb
- spec/bolt/pal/yaml_plan/loader_spec.rb
- spec/bolt/pal/yaml_plan_spec.rb
- spec/fixtures/modules/yaml/plans/bad_puppet.yaml
- spec/fixtures/modules/yaml/plans/upload.yaml
- spec/integration/yaml_plan_spec.rb
When a plan is loaded the following validation occurs.
1. All required keys for all steps are present
2. No unexpected keys are allowed in plan steps or parameters
3. All puppet code is verified to be syntactically correct
> (BOLT-1194) Validate simple plans

- lib/bolt/pal/yaml_plan.rb
The original implementation of the yaml plan validation did not allow the `description` key to be declared for YAML plan parameters. This commit adds that as an allowable key.
> (BOLT-1194) Allow description key in yaml plan params

- lib/bolt/cli.rb
- lib/bolt/inventory.rb
- lib/bolt/inventory/group2.rb
- lib/bolt/inventory/inventory2.rb
- lib/bolt/plugin.rb
- lib/bolt/plugin/puppetdb.rb
- pre-docs/inventory_version2.md
- spec/bolt/cli_spec.rb
- spec/bolt/inventory/inventory2_spec.rb
- spec/bolt/inventory_spec.rb
- spec/integration/apply_compile_spec.rb
- spec/integration/inventory2_spec.rb
- spec/lib/bolt_spec/integration.rb
This adds a primative plugin concept to Bolt. Currenlty this is closely
tailored to the needs of the 'puppetdb' plugin which is a bit magic
since it uses prexisting puppetdb configuration.
The key parts of the plugin framework are `self.setup` which returns a new
plugin library with plugins loaded and `by_name` which allows us to
fetch the puppetdb plugin. We should expect to refactor basically
everything else around how we load plugins as we develop more hooks and
external plugins.
This is currently based on the BOLT-1232 PR since it also needs to add pre-docs
> (BOLT-1109) Support puppetdb lookups in inventory2

- lib/bolt/transport/sudoable.rb
In the case where a user specified with `run-as` tried to upload a file to a destination owned by a user with different privilages an command prompt is raised which causes the command to hang indefinitely. By adding the `-f` flag to the `mv` command an appropriate permission error is raised and the operation does not hang.
> (BOLT-1262) Do not let file upload hang with sudoable

- pre-docs/bolt_configuration_options.md
Add documentation about where OpenSSH config files are read from and what values are respected. Also document dependency on ssh-agent for authentication with password protected private keys.
> (BOLT-1227) Document OpenSSH configuration file options

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
Previously an missing command argument would result in a stack trace. This commit validates that a command is given when invoking `bolt command run` on the CLI is a string with at least one character. Note this validation is modeled after the plan function `run_command` which validates the command argument is of type `String[1]`.
> (BOLT-1243) Error with helpful message when no CLI command given

- pre-docs/bolt_configuration_options.md
This commit adds a list of configuration options that the net-ssh gem will respect (and wont be overridden by bolt).
> (BOLT-1227) Enumerate OpenSSH configuration options available with bolt

- acceptance/config/gem/options.rb
- acceptance/config/git/options.rb
- acceptance/config/package/options.rb
- acceptance/lib/acceptance/bolt_setup_helper.rb
- acceptance/setup/common/pre-suite/031_add_local_nix_user.rb
- acceptance/tests/bolt_apply.rb
- acceptance/tests/command_local.rb
- acceptance/tests/file_local.rb
- acceptance/tests/script_local.rb
- acceptance/tests/task_local.rb
This commit adds acceptance tests for the local transport. These tests are intended to set a baseline for testing local transport on a variety of supported platforms that are not covered by integration tests. This first iteration tests the behaviour of run-as accross different platforms as well as using bolt's puppet to apply manifest code.
> (BOLT-1259) Add acceptance tests for local transport

- lib/bolt/inventory/group.rb
- lib/bolt/inventory/group2.rb
- spec/bolt/inventory/group2_spec.rb
- spec/bolt/inventory/group_spec.rb
Previously if the config set in inventory was either not defined, or was not a hash a stack trace would be raised when trying to access `target['options']&.keys`. This commit adds a validation step to ensure there is either no config set or that if it is set that it is a hash. The net effect is to raise a validation error pointing to the offending key instead of a stack trace.
> (BOLT-1274) Raise validation error when inventory config is invalid

- bolt-modules/boltlib/lib/puppet/datatypes/applyresult.rb
- bolt-modules/boltlib/lib/puppet/datatypes/result.rb
- bolt-modules/boltlib/lib/puppet/datatypes/resultset.rb
- lib/bolt/apply_result.rb
- lib/bolt/result.rb
- lib/bolt/result_set.rb
- lib/bolt/transport/orch.rb
- pre-docs/writing_plans.md
- spec/bolt/apply_result_spec.rb
- spec/bolt/cli_spec.rb
- spec/bolt/result_set_spec.rb
- spec/bolt/transport/shared_examples.rb
- spec/integration/target_spec.rb
This commit renames the type attribute of a result object to action (BOLT-1125). It also exposes it as an action method for a result object in the plan language.
> (BOLT-1223) Rename result type to result action, expose in plan

- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
Previously, we loaded the inventory for all commands, regardless of
whether the command actually needed the inventory. This meant that an
invalid inventory would cause commands like `bolt task show` to fail,
even though they shouldn't care about the inventory whatsoever.
We were loading the inventory in order to figure out the number of nodes
and groups in use to include in the analytics report. We now only
include that information if the command is using targets.
> (BOLT-1268) Only load inventory when necessary

- lib/bolt/pal/yaml_plan/step.rb
Previously, we were looking for a newline character to decide that the
content of an eval was multiple lines and should be wrapped in `with()`.
However, single line strings created using the mutli-line syntax in YAML
(which is necessary to be interpreted as code blocks) end in a newline.
We now check for more precisely what we means, which is that the string
contains multiple lines, not just that it might end with a newline.
> (BOLT-1299) Properly detect multi-line evals

- lib/bolt/plugin.rb
- lib/bolt/plugin/terraform.rb
- pre-docs/inventory_version2.md
- spec/bolt/plugin/terraform_spec.rb
- spec/fixtures/terraform/empty.tfstate
- spec/fixtures/terraform/terraform.tfstate
This adds a plugin that can load terraform state and map resource
properties to target parameters. This allows a terraform project to be
used to dynamically determine the targets to use when running Bolt.
> (BOLT-1265) Add terraform target-lookup plugin

- Puppetfile
- acceptance/setup/common/pre-suite/071_install_modules.rb
The location of public release packages will change on May 14.
As such, the following changes aim to prepare for the changeover
to ensure there are no breakages with downstream dependencies.
> (maint) Update puppet_agent module to 2.1.2

- acceptance/setup/common/pre-suite/010_install_ruby.rb
Install appropriate dependencies for installing bolt as a gem on fedora28
> (maint) Git based acceptance tests on fedora28

- pre-docs/bolt.md
- pre-docs/bolt_running_plans.md
- pre-docs/writing_plans.md
This commit adds links to some real world plan examples in the writing plans section of the docs.
> (BOLT-1185) Add plan examples to bolt docs

- spec/integration/apply_spec.rb
- spec/lib/bolt_spec/puppet_agent.rb
For the second time in two weeks a puppet 5 agent was installed for "latest". The test failure message for using an apply with the `deferred` feature does not make it obvious that an incompatible agent is used. This commit updates the test to use the generalized `BoltSpec::PuppetAgent` install method and ensure a `deferred` compatible agent is installed. It also modifies the install method such that it will default to install the latest collection and optionally install from a specified collection.
> (maint) Ensure testing deferred in apply has compatible agent version

- CONTRIBUTING.md
This adds more detailed steps to our workflow for having contributors open PRs against Bolt. It includes forking, cloning, and branching methods that contributors should follow.
> (maint) Add steps for opening a PR to contributing

- acceptance/setup/common/pre-suite/010_install_ruby.rb
The newest version of the ffi gem (1.11.1) is not installable on macos with native ruby version. In order to support git based testing on macos for 10.13, pin to 1.9.25.
> (maint) Pin ffi to 1.9.25 for macos git-based acceptance tests

- README.md
- pre-docs/bolt.md
- pre-docs/getting_started_with_bolt.md
- pre-docs/running_bolt_commands.md
As part of bolt write the docs, make the https://puppetlabs.github.io/bolt/ more discoverable.
> (docs) Replace reference to task hands on lab to github.io site

- lib/bolt/plugin/puppetdb.rb
- lib/bolt/puppetdb/client.rb
- spec/bolt/plugin/puppetdb_spec.rb
- spec/bolt/puppetdb/client_spec.rb
- spec/integration/inventory2_spec.rb
- spec/lib/bolt_spec/conn.rb
This allows user who are using the PuppetDB inventory plugin to set config
values based on facts gathered from PuppetDB. It works by collecting a list
of facts and a list of certnames that we need those facts for, then makes a
single puppetdb query to the `fact-contents` endpoint for the facts. It then
iterates back through the config to fill in the right values for the right
nodes.
> (BOLT-1264) Set config from PuppetDB facts

- pre-docs/plan_functions.md
This commit adds the plan documentation generated by puppet strings to the pre-docs for the new file plan functions.
> (BOLT-1338) Add documentation for file::{exists,readable}

- bolt-modules/boltlib/lib/puppet/datatypes/resultset.rb
- lib/bolt/result_set.rb
- pre-docs/writing_plans.md
- spec/bolt/result_set_spec.rb
- spec/fixtures/modules/results/plans/test_methods.pp
- spec/fixtures/modules/results/tasks/init.sh
- spec/integration/result_set_spec.rb
- spec/integration/ssh_spec.rb
- spec/integration/target_spec.rb
This should be possible/easy:
$reboot_targets = $patch_results.ok_set.filter_set |$result| {
$result['reboot_flag'] == true
}.targets
This commit makes it work by adding a `.filter_set` method which acts the same as `.filter`, but returns a ResultSet datatype.
The existing `.filter` method was insufficient because it returned a Tuple, not a ResultSet.
> (BOLT-1337) Make ResultSet.filter return ResultSet

- .travis.yml
- Rakefile
- appveyor.yml
- bolt-modules/out/Rakefile
- bolt-modules/out/lib/puppet/functions/out/message.rb
- bolt-modules/out/spec/functions/out/message_spec.rb
- bolt-modules/out/spec/spec_helper.rb
- lib/bolt/outputter/human.rb
- pre-docs/plan_functions.md
- spec/bolt/outputter/human_spec.rb
Previously, plans used the built-in Puppet logging functions
(info/notice/etc) to print output for the user. This doesn't work well
now that the default log level for the console is warn. It also doesn't
match our expected semantics around when logging should be used vs. when
the outputter should be used.
We have a new out::message function that can be used to send output to
the user via the outputter. This function takes a message and directs it
to the console if using the human outputter. Currently, the message is
ignored when using the JSON outputter.
> (BOLT-1325) Add out::message function to print a message

- pre-docs/inventory_file_generating.md
- pre-docs/inventory_version2.md
This allows user who are using the PuppetDB inventory plugin to set config
values based on facts gathered from PuppetDB. This adds documentation including an example on how the feature works.
> (BOLT-1264) Document puppetdb inventory plugin config

- Gemfile
- lib/bolt/task.rb
It appears that the new cri release (2.15.7) introduces a breaking change to r10k which is used to install modules for integration tests. This commit temporarily pins cri to a compatible version.
> (maint) Temporarily pin cri gem so that r10k works for test setup

- pre-docs/applying_manifest_blocks.md
- pre-docs/bolt_configuration_options.md
- pre-docs/bolt_installing_modules.md
- pre-docs/bolt_options.md
- pre-docs/inventory_file.md
This makes all instances (that I could find) of 'bolt project directory' a link to the project directory page, and standardizes capitalization.
> (BOLT-1343) Always link to project directory

- lib/bolt/plugin/terraform.rb
- pre-docs/inventory_version2.md
- spec/bolt/plugin/terraform_spec.rb
- spec/fixtures/terraform/terraform.tfstate
- spec/fixtures/terraform/terraform3.tfstate
Terraform 0.12 introduced version 4 of the statefile format, which is
significantly different from the previous version. In particular, resources are
organized differently, named differently, and their parameters are broken into
nested hashes and arrays instead of alays being a flat hash.
This adds support for the new statefile format by checking the "version" field
and determining how to process the resources. We still accept exactly the same
options in the plugin and the user doesn't need to be aware of which format
their statefile is in.
We do some standardization of the resources into a list, but keep their
parameters in whatever form they came from the statefile. Then at lookup time,
we check for both the dotted form of the key as well as doing the nested
lookup. Only one of those …
> (BOLT-1341) Support Terraform statefile version 4

- lib/bolt/cli.rb
- lib/bolt/config.rb
- pre-docs/bolt_configuration_options.md
- spec/bolt/cli_spec.rb
This exposes the r10k proxy setting in a new section of bolt.yaml called
`puppetfile`. This proxy will be used for Git HTTPS and Puppet Forge
operations.
> (BOLT-1327) Support `proxy` setting for bolt puppetfile install

- lib/bolt/inventory/group2.rb
- lib/bolt/inventory/inventory2.rb
- lib/bolt/plugin.rb
- lib/bolt/plugin/prompt.rb
- pre-docs/inventory_version2.md
- spec/bolt/inventory/group2_spec.rb
- spec/bolt/inventory/inventory2_spec.rb
- spec/bolt/plugin/prompt_spec.rb
- spec/integration/cli_spec.rb
- spec/integration/inventory2_spec.rb
This commit adds a prompt plugin. When data is loaded from inventory, values that the key '_plugin' points to will be used to look up available plugins by name. For the prompt plugin, a new instance of the prompt class is instantiated with the data in the same level of '_plugin' key in the hash. The `inventory_config_lookup` hook returns a concurrent delay which when executed prompts the user for a value.
> (BOLT-1269) Add prompt plugin

- docs/_layouts/default.html
- docs/debugging.md
- lib/bolt/transport/winrm/connection.rb
This adds a new page to the website that includes some basic information on
common error cases and how to diagnose them.
Also fixes a typo in an error message.
> (website) Add a page with debugging tips

- spec/integration/device_spec.rb
These tests are failing due to a bug in puppet-resource_api 1.8.3 which
is included in the latest puppet-agent release. Until that's fixed,
these tests are marked pending. That means they will run and will be
ignored if they fail; if they pass, the test suite will fail, indicating
that we need to remove the pending designation.
> (maint) Skip tests that fail against puppet-resource_api 1.8.3

- docs/_layouts/default.html
We now link to the hands-on lab from the 'Bolt Hands-on Lab' heading, so
there's no need to have an extra "Introduction" entry in the navigation.
This also caused the numbered labs to not align with their index in the
navigation list, which is a minor annoyance.
> (website) Remove redundant "Introduction" link

- Rakefile
- spec/bolt/transport/winrm_spec.rb
- spec/docker-compose.yml
When the OMI docker container was introduced, it was configured to map local port 2598{5,6} to 598{5,6}. This is the same port used the vagrant windows nano image. While this is not a problem in Travis or Appveyor, it prevents local testing using both the windows nano vagrant image and the docker OMI container. This commit removes the port conflict.
> (BOLT-1324) Fix port collision for local test setup

- bolt-modules/boltlib/lib/puppet/functions/upload_file.rb
- lib/bolt/bolt_option_parser.rb
- pre-docs/bolt_command_reference.md
- pre-docs/plan_functions.md
- pre-docs/running_bolt_commands.md
Update the string docs for the upload_file boltlib function to mention
that the function is able to upload directories as well as files.
>  (BOLT-1379) (docs) 'file upload' can handle directories

- lib/bolt/config.rb
- pre-docs/bolt_configuration_options.md
We now accept a `forge` map under the `puppetfile` config section. This
map can contain a `proxy` key overriding the top-level proxy for
Forge-specific operations, and a `baseurl` key specifying an alternate
Forge.
> (BOLT-1376) Accept Forge settings for `bolt puppetfile install`

- modules/canary/plans/init.pp
This adds docstrings for the canary plan to help with strings
development. Currenlty it appears as those strings only handles the
@param statements
> (BOLT-1356) Add docstrings for canary plan

- acceptance/config/gem/options.rb
- acceptance/config/git/options.rb
- acceptance/config/package/options.rb
- acceptance/lib/acceptance/bolt_setup_helper.rb
- acceptance/setup/common/pre-suite/032_configure_windows_profile.rb
- acceptance/tests/script_local.rb
- acceptance/tests/task_local.rb
- lib/bolt/transport/local_windows.rb
- lib/bolt/transport/powershell.rb
Previous to this commit the local_windows transport would call the powershell
profile if the default value for the 'interpreter' variable was ever used. in
this scenario the default interpreter needs to include PS_ARGS defined in the
powershell transport.
This commit adds PS_ARGS to the default of interpreter
> (BOLT-1358) Fix local_windows transport calling profile

- lib/bolt/executor.rb
- spec/bolt/executor_spec.rb
Previously, wait_until_available() would only check connectivity for a
batch at a time, and if any target in the batch was unavailable it would
report the whole batch as unavailable.
This commit modifies the error handling such that if a batch comes back
as having any unavailable targets in it, the results are partitioned so
that individual, target-by-target availability reporting is performed
correctly.
> (BOLT-1382) Fix batch err in wait_until_available

- bolt-modules/boltlib/lib/puppet/functions/catch_errors.rb
- bolt-modules/boltlib/spec/functions/catch_errors_spec.rb
- pre-docs/plan_functions.md
- pre-docs/writing_plans.md
- spec/fixtures/modules/catch_errors/plans/break.pp
- spec/fixtures/modules/catch_errors/plans/init.pp
- spec/fixtures/modules/catch_errors/plans/return.pp
- spec/fixtures/modules/catch_errors/plans/typed.pp
- spec/fixtures/modules/error/tasks/fail.json
- spec/fixtures/modules/error/tasks/fail.ps1
- spec/fixtures/modules/error/tasks/typed.json
- spec/fixtures/modules/error/tasks/typed.ps1
- spec/fixtures/modules/error/tasks/typed.sh
- spec/integration/catch_errors_spec.rb
This adds a new Bolt plan language function `catch_errors`, which accepts an optional Array of error kinds to catch and a block of Bolt plan code to catch errors for. If an error matching the kinds (or all kinds, if none are specified) is raised in the block it is returned from the block, otherwise the result of the block is returned.
> (BOLT-1316) Add catch_errors plan language function

- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
This commit removes the SwitchHider class and filters excluded switches from the OptionParser stack. Previously, switches were extended with the SwitchHider class and their visiblity was toggled depending on whether or not an option was valid for a specified command. This commit removes the SwitchHider class and instead removes a switch entirely from the stack, resulting in the options not being shown in the help text or being considered valid commands.
> (BOLT-1342) Remove excluded options and separators from help text

- spec/integration/device_spec.rb
This commit removes the rspec pending designation as a fix for this test appears to have been released with puppet 6.5
> (maint) Unskip resolved device spec test

- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
- bolt-modules/boltlib/spec/fixtures/modules/test/plans/run_me_nodes.pp
- bolt-modules/boltlib/spec/functions/run_plan_spec.rb
- pre-docs/plan_functions.md
To provide consistency of special treatment for a plan parameter named
$nodes, allow the run_plan() function to be invoked with $nodes as the
second positional argument, so that it can be used the same way
run_task() is. E.g.
run_task('util::hello', $targets,
message => 'hello, beautiful world!',
)
run_plan('reboot', $targets,
message => 'what a great day to reboot!',
)
This matches the way run_task() works when a nodes/targets argument is
defined.
Previously, a plan needed to be invoked as follows, which resulted in
inconsistency in how to run "actions" against "targets", in tasks vs.
plans.
run_task('util::hello', $targets,
message => 'hello, beautiful world!',
)
run_plan('reboot',
nodes   => $targets,
message => 'what a great day to reboot',
)
> (BOLT-1197) Add $nodes run_plan() positional arg 2

- acceptance/tests/apply_plan_ssh.rb
- acceptance/tests/bolt_apply.rb
With the release of puppet agent 6.5.0 for fedora 30 the puppet_agent::install task should have an agent to download which will allow apply acceptance tests to work on fedora 30.
> (BOLT-1302) Enable apply acceptance tests for fedora 30

- Gemfile
- Rakefile
- bolt.gemspec
- ext/build_defaults.yaml
This commit adds the necessary rake tasks, gem dependency and build metadata to build and stage the bolt gem for the release pipeline. This allows the gem to be shipped to public repos with the same job that ships the bolt system packages.
> (BOLT-1317) Add rake tasks for building gem for shipping pipeline

- pre-docs/writing_plans.md
Previously the example provided for passing parameters to tasks from a plan was confusing as it made it appear that a Target object could be passed to a task via standard parameter passing. This commit updates the example to illustrate how parameters are serialized to JSON when passed to tasks and therefore to not expect objects to be passed directly without serialization.
> (BOLT-1361) Improve plans documentation regarding parameter passing

- spec/docker-compose.yml
Changes in 9.6.14 introduce erros in the migration scripts for puppetdb which is blocking CI. Unpin once resolved.
> (maint) Pin postgres docker image to 9.6.13

- lib/bolt/inventory/group2.rb
- lib/bolt/inventory/inventory2.rb
- lib/bolt/plugin/prompt.rb
- lib/bolt/plugin/puppetdb.rb
- lib/bolt/plugin/terraform.rb
- lib/bolt/secret/base.rb
- lib/bolt/util.rb
- pre-docs/inventory_version2.md
- spec/bolt/inventory/group2_spec.rb
- spec/bolt/inventory/inventory2_spec.rb
- spec/bolt/plugin/prompt_spec.rb
- spec/bolt/plugin/puppetdb_spec.rb
- spec/bolt/plugin/terraform_spec.rb
- spec/integration/inventory2_spec.rb
This removes the target-lookups section of inventory v2. In place of it
users should put target-lookup entries directly in the targets list.
> (BOLT-1409) Deprecate target-lookups to standardize plugin behavior

- pre-docs/bolt_installing.md
This commit adds the installation instructions for installing bolt from the puppet 6 collection.
> (BOLT-1302) Document installation for puppet-bolt on fedora 30

- bolt-modules/boltlib/lib/puppet/functions/catch_errors.rb
- pre-docs/plan_functions.md
- pre-docs/writing_plans.md
A newline in the `@return` docstring cut off the string when compiled in CI, and the return type for `catch_errors` was not specified. This also rewords the `Catching Errors` section of the docs for clarity.
> (maint) Fix typos in puppet strings docs for catch_errors

- spec/lib/bolt_spec/bolt_server.rb
Previously the target2request method would set the port for an ssh target as the string '22'. The transport app schema requires this value to be an integer. This commit updates the method to set the default ssh port to the integer value.
> (maint) Specify bolt_server spec helper default port as integer

- lib/bolt_spec/plans/action_stubs/script_stub.rb
- lib/bolt_spec/plans/action_stubs/task_stub.rb
- spec/bolt_spec/plan_spec.rb
This commit returns the original hash of expected parameters for printing when a script or task stubs raise an error. Previously, the original hash of parameters was split into separate 'arguments' and 'options' hashes which were then incorrectly reassembled into a single hash whenever the stubs errored.
> (BOLT-1399) Return original parameter hash when erroring

- Gemfile
This commit pins the yard gem to avoid unwanted behavior in puppet-strings rake task to generate plan function docs. For example with 0.9.20 `out::message` becomes `:'out::message'`.
> (maint) Pin yard gem due to introduction of bug in puppet-strings

- lib/bolt/cli.rb
- lib/bolt/inventory/group2.rb
- lib/bolt/pal.rb
- lib/bolt/plugin.rb
- lib/bolt/plugin/task.rb
- pre-docs/inventory_version2.md
- spec/fixtures/modules/identity/tasks/init.json
- spec/fixtures/modules/identity/tasks/linux.sh
- spec/fixtures/modules/identity/tasks/win.ps1
- spec/integration/plugin/task_spec.rb
- spec/lib/bolt_spec/integration.rb
This adds a task plugin that will run an arbitray task on localhost and
use the result. This currenlty supports the inventory_config and
inventory_target hooks.
Since this plugin is only used to bootstrap inventory at this point it
creates a one off Inventory instance to use. This approach may have to
be reconsidered if the task plugin is extended to post-inventory hooks
in the future. For simplicity it creates it's own PAL and Executor
instances too.
> (BOLT-1408) Add task plugin

- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- spec/bolt/config_spec.rb
This commit adds a warning that displays when a specified modulepath does not exist but a case-insensitive version does. The case-insensitive version of the modulepath is displayed with the warning. Previously, if the modulepath's case was incorrect then Bolt would not be able to locate the modules.
The reason for this change is that some Bolt users may be expecting case-insensitivity when specifying a modulepath, but not know that Bolt is case-sensitive.
> (BOLT-1318) Warn when case-insensitive modulepath exists

- .travis.yml
Hipchat is no longer used for notifications.  This commit removes this from
Travis.
> (maint) Remove Hipchat notifications

- lib/bolt/logger.rb
The logging library used by bolt allows setting a pattern to display messages. Bolt configures a newline to be appended to each message. For some terminals a newline will stop the reset character for colorization. The logging library appends the `clear` character to the log message *after* the newline has been appended. This commit updates the pattern to reset the terminal color before the newline. https://github.com/TwP/logging/blob/ef8b0f47e473b69dbccfea508fb5cf5d5f0ec2a6/lib/logging/color_scheme.rb#L193
> (maint) Explicitly reset message color with logging

- .rubocop.yml
Rubocop unfortunately expects all files on Windows to be CRLF however in most
cross platform projects, like Bolt, the line endings are LF.  This commit
updates Rubocop to expect LF line-endings instead.
> (maint) Allow rubocop to be used on Windows

- lib/bolt/transport/orch.rb
- lib/bolt/transport/orch/connection.rb
- pre-docs/bolt_configuration_options.md
Previously the `job-poll-{interval,timeout}` settings for the ruby orchestrator client were only configurable in `orchestrator.conf`. This commit exposes these settings in bolt configuration. If these are set in bolt config, they will override the settings in orchestrator.conf which is the desired behaviour because *only* the ruby implementation of the orchestrator client should use these settings.
> (BOLT-1425) Expose orchestrator-client_ruby settings in bolt conf

- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- spec/bolt/cli_spec.rb
- spec/integration/inventory_spec.rb
This adds support for an `inventory show` command that lists target names for targets which match the targetting option and are in the inventory.
> (BOLT-1398) Add inventory show command

- lib/bolt_server/transport_app.rb
- spec/bolt_server/app_integration_spec.rb
- spec/bolt_server/transport_app_spec.rb
- spec/lib/bolt_spec/bolt_server.rb
Refactors transport_app_spec tests in a way that should allow for easier
additions of other actions (like run_command, upload_file, run_script)
to the bolt server API alongside run_task.
app_integration_spec tests remain the same, except for a renamed helper
method.
> (BOLT-1403) Make bolt-server specs less task-specific

- lib/bolt/pal/yaml_plan.rb
- lib/bolt/pal/yaml_plan/evaluator.rb
- lib/bolt/pal/yaml_plan/step.rb
- lib/bolt/pal/yaml_plan/step/command.rb
- lib/bolt/pal/yaml_plan/step/eval.rb
- lib/bolt/pal/yaml_plan/step/plan.rb
- lib/bolt/pal/yaml_plan/step/resources.rb
- lib/bolt/pal/yaml_plan/step/script.rb
- lib/bolt/pal/yaml_plan/step/task.rb
- lib/bolt/pal/yaml_plan/step/upload.rb
- lib/bolt/pal/yaml_plan/transpiler.rb
- pre-docs/writing_yaml_plans.md
- spec/bolt/pal/yaml_plan/evaluator_spec.rb
- spec/bolt/pal/yaml_plan/step_spec.rb
- spec/bolt/pal/yaml_plan_spec.rb
- spec/fixtures/modules/yaml/plans/conversion.yaml
- spec/fixtures/modules/yaml/plans/empty_resources.yaml
- spec/fixtures/modules/yaml/plans/resource_failure.yaml
- spec/fixtures/modules/yaml/plans/resources.yaml
- spec/integration/transpiler_spec.rb
- spec/integration/yaml_plan_spec.rb
This step accepts a list of resources and applies them similarly to the
`apply()` statement in Puppet language plans. A resource has a type,
title and parameters. As a shorthand, the type can be set as a key whose
value is the title, so long as the type name doesn't conflict with
another allowed key (type, title or parameters).
The resources step is applied by generating Puppet manifest code for
each resource, wrapping it an `apply()` statement so it is valid in
tasks mode, then parsing it and passing it to the Applicator.
> (BOLT-1222) Add a 'resources' step for YAML plans

- lib/bolt/inventory/group2.rb
- spec/bolt/inventory/group2_spec.rb
When the `inventory_targets` plugin hook doesn't find the specified
plugin, it used the wrong key in the error message to find the name.
> (maint) Plugin lookup error message looks for wrong key

- spec/bolt/transport/shared_examples.rb
Previously the transport shared examples attempted to test various scenarios
however the ruby strings used contain duplicates:
'\'single single\'' is just the same as "'double single'" from a ruby point of
view except the first word has changed.  The same goes for single double,
single "double" single and single \'single\' single.
This commit removes the redundant tests and their expectations.
> (maint) Remove redundant test cases

- bolt.gemspec
- lib/bolt/config.rb
- lib/bolt/plugin.rb
- lib/bolt/plugin/aws.rb
- pre-docs/inventory_version2.md
- spec/bolt/plugin/aws_spec.rb
This adds a plugin that can lookup AWS EC2 instances in a specified region, allowing Bolt to dynamically determine the targets to use when running a command. Instances can also be filtered by tags and other instance properties.
> (BOLT-1328) Add AWS EC2 target-lookup plugin

- spec/integration/inventory2_spec.rb
- spec/integration/inventory_spec.rb
The test name `when running over local` is ambiguous because the test is tagged
with bash.  This commit updates the test name to better reflect what is actually
being tested.
> (maint) Update integration test name

- .rubocop.yml
- bolt-modules/out/lib/puppet/functions/out/message.rb
- docs/debugging.md
- lib/bolt/cli.rb
- lib/bolt/executor.rb
- lib/bolt/outputter/json.rb
- pre-docs/plan_functions.md
- pre-docs/writing_plans.md
- spec/fixtures/modules/output/plans/init.pp
- spec/integration/output_spec.rb
This commit updates the log level documentation in the writing plan docs to include updated information about how to log messages from plan execution. It also adds a section to the common debugging page with some prescriptive recommendations for handling plan logging.
> (BOLT-1445, BOLT-1455) Update log level docs

- Gemfile
- Rakefile
- Unpin yard gem from 0.9.19
Previously, yard was pinned due to changes in how dynamic symbols are handled by yard 0.9.20, causing formatting issues for plan functions such as out::message. The puppet-strings gem was updated to fix this formatting issue.
- Delete data_types field from generated docs
As of puppet-strings 2.3.0, an additional field is generated for the docs, causing the docs rake task to fail. This commit deletes the data_types field.
> (maint) Fixes from puppet-strings 2.3.0 release

- lib/bolt/transport/local_windows.rb
- lib/bolt/transport/sudoable.rb
This commit displays the input for a task as json when using the --debug option. Previously, task input was displayed as a ruby hash.
> (BOLT-1456) Show task input in debug output as json

- lib/bolt/analytics.rb
- lib/bolt/boltdir.rb
- lib/bolt/cli.rb
- spec/bolt/boltdir_spec.rb
Adds a custom dimension to the screen view for Boltdir usage. When the Boltdir is set up, it will log its type as either Boltdir, bolt.yaml, the default directory, missing default directory, or a Boltdir specified as a command line option.
> (BOLT-1315) Collect analytics about Boltdir usage

- Rakefile
- developer-docs/kerberos.md
- lib/bolt/config.rb
- lib/bolt/transport/winrm.rb
- lib/bolt/transport/winrm/connection.rb
- pre-docs/bolt_configuration_options.md
- pre-docs/bolt_known_issues.md
- pre-docs/bolt_options.md
- pre-docs/inventory_file.md
- pre-docs/inventory_version2.md
- spec/bolt/transport/winrm_spec.rb
* #999, except without the not-quite-working-yet Docker container setup!
* supersedes #950 
- This PR is considered experimental due to a number of current
limitations:
* Works only with MIT Kerberos from a Linux node
* Does not work with Heimdal on OSX
- gssapi gem support for Heimdal is not well vetted
- OSX doesn't export Kerberos IOV functions needed for MS DCE RPC
* Does not work from a Windows node as winrm / gssapi gems only
support MIT Kerberos, and Windows has its own APIs
* Has been manually tested in a simple AD environment that has a
CentOS host domain joined to Windows Active Directory
Note that Kerberos is an authentication method, not a transport, so
can be used with or without SSL just like other authentication.
- Automated tests have been scaffolded, to be completed in a …
> (BOLT-126) Add WinRM Kerberos support from Linux

- .travis.yml
- developer-docs/kerberos.md
- spec/Dockerfile.omiserver
- spec/Dockerfile.samba-ad
- spec/bolt/transport/winrm_spec.rb
- spec/docker-compose.yml
- spec/fixtures/omiserver/docker-entrypoint.sh
- spec/fixtures/omiserver/domain-join.sh
- spec/fixtures/omiserver/omi-enable-kerberos-auth.sh
- spec/fixtures/omiserver/realmd.conf.tmpl
- spec/fixtures/omiserver/smb.conf.tmpl
- spec/fixtures/omiserver/sssd.conf.tmpl
- spec/fixtures/omiserver/verify-omi-authentication.sh
- spec/fixtures/omiserver/verify-pwsh-authentication.sh
- spec/fixtures/samba-ad/docker-entrypoint.sh
- spec/fixtures/samba-ad/kerberos-client-config.sh
- spec/fixtures/samba-ad/krb5.conf.tmpl
- spec/fixtures/samba-ad/krb5.osx.conf
- spec/fixtures/samba-ad/samba-ad-config.sh
- spec/fixtures/samba-ad/smb.conf.tmpl
- spec/fixtures/samba-ad/supervisord.conf
* builds on ~~#996~~
* blocked by ~~#1087~~
* follow-on dev PR setup at #1093 
- Ensure that Basic auth with credentials can be used over HTTP(S)
against the OMI server setup
This basically verifies that the NTLM authentication file is properly
setup for use with OMI server and contains bolt:$BOLT_PASSWORD
where $BOLT_PASSWORD is setup during container build
- These checks are performed with both omicli *and* pwsh. The scripts
are separated so that the pwsh tests can be performed from another
container used for development
- The current docker-compose hostname: omiserver is sufficient for the
container to correctly self-identify
- This establishes an Active Directory server in the Docker compose
stack, which is one of the easier ways on Linux to establish a KDC
(Key Distribution Center). …
> (BOLT-1472) Setup Kerberos in Container Tests

- lib/bolt/cli.rb
- spec/integration/parsing_spec.rb
When running a script there could be positional script arguments that contain `=` characters. Previously, regardless of the subcommand the cli parser would try to extract task_options by splitting arguments on the `=` character. This commit updates the parser to only attepmt to built a task_options hash if a task or plan is being run.
> (BOLT-1412) Only process task_options for tasks/plans

- lib/bolt/inventory/inventory2.rb
- spec/fixtures/apply/basic/plans/inventory_2_lookup.pp
- spec/fixtures/apply/inventory_2.yaml
- spec/integration/apply_compile_spec.rb
Until get_targets is supported for inventory v2 in apply blocks empty data should be passed to bolt_catalog. There is still the expectation that config data (namely transport information) is passed along in order for a net new target to be returned when get_targets is used within an apply block with inventory v2. This commit sends along the expected serialized config data while still excluding any existing target information in the inventory.
> (BOLT-1492) Fix error in get_targets with inventory v2 in apply

- bolt-modules/boltlib/lib/puppet/functions/get_targets.rb
- pre-docs/inventory_version2.md
- pre-docs/plan_functions.md
Add note that `get_targets` behaves different within apply blocks when
used with version 2 inventory as opposed to version 1. Include docs on
how to convert a plan using the version 2 inventory to version 1
inventory behavior.
>  (BOLT-1492) Note behavior change for get_targets 

- lib/bolt/config.rb
- lib/bolt/plugin.rb
- lib/bolt/plugin/aws.rb
- pre-docs/inventory_version2.md
- spec/bolt/plugin/aws_spec.rb
This updates the location of AWS plugin configuration in the config
file. Previously, configuration settings were under the 'aws' field.
These settings should instead be under the 'plugins' field, similar to the
Prompt plugin.
**Current Config**
```
aws:
credentials: /path/to/creds
```
**Updated Config**
```
plugins:
aws:
credentials: /path/to/creds
```
> (BOLT-1501) Change AWS plugin config field

- lib/bolt/bolt_option_parser.rb
This changes regular heredocs to squiggly heredocs in the option parser
help text banners. The only improves the readability of the file itself.
> (maint) Use squiggly heredoc in help text banner

- pre-docs/bolt_installing_modules.md
The command `bolt puppetfile install` fails in certain situations where the
cachedir is inaccessible; this change calls out the ENV variables responsible.
The $HOMEDRIVE is set in some Windows enterprise environments (for specifying DFS mounts), and the bolt docs currently do not call this out.
> (docs) Documents gotcha for enterprise win users with HOMEDRIVE set

- Puppetfile
- acceptance/setup/common/pre-suite/071_install_modules.rb
This commit updates the puppet_agent, reboot, and cron_core modules to their latest releases to be shipped with bolt.
> (BOLT-1504) Update bundled modules to latest versions

- CONTRIBUTING.md
- spec/integration/catch_errors_spec.rb
Limit the catch_errors integration tests to ssh targets. Also note in the CONTRIBUTING.md that bundled modules are required for some tests.
> (maint) Ensure that rspec unit tag does not rely on ssh/winrm targets

- developer-docs/kerberos.md
- spec/Dockerfile.linuxdev
- spec/Dockerfile.omiserver
- spec/docker-compose-dev.yml
- spec/fixtures/linuxdev/bolt-kerberos-test.sh
- spec/fixtures/linuxdev/docker-entrypoint.sh
- spec/fixtures/omiserver/build-omi.sh
- spec/fixtures/omiserver/docker-entrypoint.sh
- spec/fixtures/omiserver/sssd.conf.tmpl
Builds on top of #999
Blocks #1101 
This adds a development environment useful for testing / debugging *any* problem between the winrm / gssapi gem and OMI server. 
Note that the final commit currently clones source from https://github.com/Iristyle/omi/tree/debugging-winrm-gem-kerberos which has extra debug / trace statements.
There are at least 2 known problems for interop between the winrm gem and OMI server that this should help diagnosing:
* [BOLT-1476](https://tickets.puppetlabs.com/browse/BOLT-1476) Kerberos auth fails somewhere after OMI server authorizes the connection. Then the next payload OMI returns is encrypted, but cannot be decrypted by the winrm gem. It's unclear if the wrong cipher is being used or if there is another problem?
* There are problems running tasks + higher …
> (BOLT-1475) Kerberos Development Container

- lib/bolt/plugin.rb
- lib/bolt/plugin/vault.rb
- pre-docs/inventory_version2.md
- spec/bolt/plugin/vault_spec.rb
This adds support for looking up secrets from a Vault server to populate
fields in the inventory config. Secrets can be looked up by specifying
the path of a KV engine and the address of the server, and authenticating
through a token or userpass.
> (BOLT-1424) Add Vault plugin

- lib/bolt/analytics.rb
This adds a warning message to users the that Bolt collects analytics
data the first time Bolt is run.
> (GH-1130) Warn users before setting up analytics

- lib/bolt/pal/yaml_plan/evaluator.rb
- lib/bolt/pal/yaml_plan/step/resources.rb
- pre-docs/writing_yaml_plans.md
- spec/bolt/pal/yaml_plan/step_spec.rb
- spec/fixtures/modules/yaml/plans/conversion.yaml
- spec/fixtures/modules/yaml/plans/resource_failure.yaml
- spec/fixtures/modules/yaml/plans/resources.yaml
- spec/integration/transpiler_spec.rb
This commit implements calling apply_prep on the targets defined in a resources step of a yaml plan. Currently apply prep is implicitly called on all the targets listed in the step for each resources step. The transpiler has also been updated to reflect the change.
> (BOLT-1451) Implicitly call apply_prep for yaml resources step

- pre-docs/running_bolt_from_docker_image.md
Add a new pre-docs section that includes documentation for running the puppet/puppet-bolt container.
> (BOLT-1407) Add documentation for running bolt from container

- lib/bolt/config.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt_server/schemas/partials/target-ssh.json
- pre-docs/bolt_configuration_options.md
- spec/bolt/applicator_spec.rb
- spec/bolt/inventory/inventory2_spec.rb
- spec/bolt/inventory_spec.rb
- spec/integration/apply_compile_spec.rb
In certain ssh configurations the socket.close method for net-ssh https://github.com/net-ssh/net-ssh/blob/dd13dd44d68b7fa82d4ca9a3bbe18e30c855f1d2/lib/net/ssh/transport/session.rb#L130 can hang. This commit implements the use of a fallback method defined in the net-ssh session class called `shutdown!` after a configurable timeout period to avoid hanging indefinitely when net-ssh cannot close a socket.
> (BOLT-1423) Ensure ssh session is closed after disconnect-timeout

- docs/_config.yml
- docs/_layouts/default.html
- docs/_layouts/post.html
- docs/_posts/2019-08-07-vault-target-api-apply-prep.md
This finally uses the official built-in "posts" capability of Jekyll to
provide a "developer updates" blog, for posts related to what's going on in
Bolt. These posts are written as markdown files, linked from the sidebar,
and each one has a link to the next and previous post chronologically.
> Add "developer updates" blog section to website

- pre-docs/bolt_command_reference.md
This updates the command reference documentation to show available
options for each subcommand-action. Previously, the documentation had a
list of subcommand-actions and a list of options, making it difficult to
tell which options applied to which subcommand-actions.
This also adds the 'secret' subcommand to the command reference.
> (BOLT-1422) Update command reference docs

- docs/_layouts/default.html
- docs/_sass/modified-cayman.scss
- docs/blog.html
This adds a homepage that lists all developer blog posts in a single
location with short excerpts. It also lists posts in reverse
chronological order in the sidebar so new posts will be visible.
> Add homepage for developer blog on website

- Puppetfile
- acceptance/setup/common/pre-suite/071_install_modules.rb
The facts module now supports detecting os.distro.codename in the shell implementation.
> (maint) Update facts module to 0.6.0

- lib/bolt/transport/local.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/sudoable.rb
Closes #1145 
This removes a warning that's raised when `--sudo-password` is specified
on the command line when `--run-as` is not specified on the command
line. The warning was often raised for valid use cases where
`--sudo-password` was specified and `--run-as` was not, and predicting
whether the warning was needed is more difficult than the warning is
worth.
> (GH-1145) Remove sudo-password with no run-as warning

- docs/_config.yml
- docs/_layouts/default.html
This adds support for an Atom feed for the Bolt Developer Updates blog  using the
jekyll-feed plugin.
> Add Atom feed to website

- lib/bolt/plugin/terraform.rb
- pre-docs/inventory_version2.md
- spec/bolt/plugin/terraform_spec.rb
This adds support for loading a remote Terraform state file using the
Terraform CLI. Previously, state could only be read from local
state files.
Additionally, inventory cofig options are validated to ensure only known
keys are used and that all required keys are present.
> (GH-1131) Add remote state support for Terraform plugin

- lib/bolt/transport/docker.rb
The default timeout of a command using a docker transport is 60 seconds. See this example:
```
$ bolt command run 'sleep 300' --targets a8ad33ff68069d48fdacc80172c8e4e79214f55523aaab143e1a7238e670a73a -i inventory.yaml
Started on a8ad33ff68069d48fdacc80172c8e4e79214f55523aaab143e1a7238e670a73a...
Failed on a8ad33ff68069d48fdacc80172c8e4e79214f55523aaab143e1a7238e670a73a:
read timeout reached
Failed on 1 node: a8ad33ff68069d48fdacc80172c8e4e79214f55523aaab143e1a7238e670a73a
Ran on 1 node in 62.26 seconds
```
This is to short for some longer running commands (Like a puppet apply) The timeout seems ro be default value provided by the docker-api gem. You can override this value .
This PR allows uses a large number (24 hours) to override this default timeout.
With this change, the example …
> (fix) Change read timeout on docker transport to large number

- lib/bolt/transport/docker.rb
An extra space before a comment somehow slipped through. Trivial to fix.
> (maint) Fix rubocop 

- acceptance/tests/task_local.rb
- lib/bolt/transport/local/shell.rb
- lib/bolt/transport/local_windows.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/transport/sudoable.rb
- lib/bolt/transport/sudoable/connection.rb
- pre-docs/bolt_configuration_options.md
- spec/bolt/transport/ssh_spec.rb
Previously when running a task that required parameters to be passed on stdin using the run-as option for the ssh or local transport a wrapper script was used on the target. The data to be sent on stdin to the task executable was written to the wrapper script which was directed to stdin. This allowed reserving stdin to *only* pass the privilage escalation password. Writing input data to disk is undesirable given sensitive parameters could be written to disk as well as permissions issues on the wrapper when executing bolt as root with the run-as option set to a less privileged user for the local transport. This commit updates the local and ssh transports to not use a wrapper script. This is accomplished by generating a random string and echoing it before executing a task executable, when …
> (GH-1159) Do not use wrapper script for tasks that require data on stdin 

- developer-docs/bolt-api-servers.md
- lib/bolt_server/schemas/action-run_command.json
- lib/bolt_server/transport_app.rb
- spec/bolt_server/app_integration_spec.rb
- spec/lib/bolt_spec/bolt_server.rb
In cases where PXP Agent is not installed on a target node
and thus cannot run a command, SSH or WinRM should be used.
This commit adds the `POST /run_command` endpoint which will
delegate either to SSH or to WinRM accordingly.
> (BOLT-1400) Add `run_command` endpoint to bolt server

- bolt.gemspec
- lib/bolt/transport/docker.rb
- lib/bolt/transport/docker/connection.rb
- pre-docs/bolt_configuration_options.md
- spec/bolt/transport/docker_spec.rb
- spec/bolt/transport/shared_examples.rb
- spec/integration/cli_spec.rb
- spec/integration/docker_spec.rb
- spec/lib/bolt_spec/files.rb
LCOL = Linux Containers on Linux
LCOW via HyperV Isolation = [Link](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers#linux-containers-with-hyper-v-isolation)
WCOW = Windows Containers on Windows
This PR is only about being able to use the docker transport, on Windows, with Linux containers. While not explicitly tested with LCOW using Hyper-V isolation (or even LCOW2), this should also support this scenario.
This PR does NOT address Windows containers on Windows (WCOW). That will require a lot of additional work as there are currently hardcoded assumptions in both the code and tests.
~~This is currently not test on Appveyor. Additional work would be needed to see if this is possible.  This PR was focused on making sure that the new …
> (GH-1060) Use Docker CLI instead of docker-api gem

- lib/bolt/transport/docker.rb
- lib/bolt/transport/docker/connection.rb
When moving to the docker cli instead of the gem the tty option was not ported over, this commit adds the -tty flag when a the tty transport option is requested. The wait option was added as a workaround which was specific to the docker-api gem and was added after the original PR was raised, this commit removes it as it does not appear to be an issue with the CLI.
> (GH-1060) Port over unused docker-api option tty, remove unused option wait

- developer-docs/bolt-api-servers.md
The paths to the JSON schemas that describe SSH and WinRM target objects
have changed, and I forgot to update them in these docs as part of
BOLT-1403.
> (ORCH-2337) Update developer docs for SSH/WinRM targets

- lib/bolt/transport/ssh/connection.rb
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
We recently modified the behavior of Bolt's SSH transport when
`host-key-check` is nil. Previously it would not check the host key but
now it tries to add the host key to known_hosts. Since Bolt defaulted to
`host-key-check: true` this didn't change Bolt's behavior, but did
affect `bolt-server` which bypasses the config defaults that Bolt has.
`bolt-server` now defaults to `host-key-check: false` over the SSH
transport.
> (maint) Set host-key-check to false for bolt-server

- lib/bolt/outputter/human.rb
- spec/bolt/outputter/human_spec.rb
Closes #1183
The modulepath listed in `bolt task show` and `bolt plan show` output used a hardcoded ':' as the file path separator, which is incorrect on Windows. It now uses ruby's `File::PATH_SEPARATOR` to display the correct path separator
> (GH-1183) Correct file path separator in task show modulepath

- lib/bolt/outputter/human.rb
- spec/bolt/outputter/human_spec.rb
Previously, we displayed durations as only seconds. That meant that
lengthy operations would be reported as, for instance, 123 seconds. We
now break these times down into hours and minutes where applicable,
written as:
1 hr, 2 min, 3 sec
2 min, 3 sec
3.76 sec
When the duration is under a minute, we include two decimal places for
the seconds display. Otherwise, we strip the sub-second duration and
round to the nearest second.
> (maint) Include hours and minutes in duration display

- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
Previously only `Bolt::Error`s were caught when executing a `puppet_library` task. Other errors (from example parsing metadata files) were surfaced. This commit rescues `StandardError` when executing the `puppet_library` hook so that the error can be turned in to a bolt result.
> (GH-1125) Catch puppet errors in apply prep with puppet_library hook

- pre-docs/bolt_configuration_options.md
- pre-docs/inventory_version2.md
Previously the documentation suggests specifying parameters with `params`, this commit updates it to use the correct `parameters` as well as fixing a reference to `nodes` in an inventory 2 file.
> (docs) Fix puppet_library plugin hook reference

- Puppetfile
The task helpers were not wrapping errors in an `_error` key. That bug has been fixed in both, this commit pulls in the bugfix releases for those modules.
> (packaging) Update {python,ruby}_task_helper modules

- spec/docker-compose.yml
Setting the restart policy to `always` for the samba-ad container results in the container automatically starting when not explicitly stoped. Restarting the samba-ad container *without* the rest of the containers in the docker-compose stack can result in improper configuration. This commit removes the restart policy with the assumption that the docker-compose stack will always be initialized at once.
> (maint) Do not automatically restart samba-ad container

- lib/bolt/applicator.rb
- spec/fixtures/apply/basic/plans/run_as_apply.pp
- spec/fixtures/apply/basic/plans/whoami.pp
- spec/integration/apply_spec.rb
Previously, apply() blocks would ignore the `_run_as` argument passed to
their containing plan.
plan a() {
run_plan(b, _run_as => 'someone')
}
plan b() {
apply(...) { }
}
In this case, the catalog compiled for the `apply()` block in plan b
would be executed as whatever user bolt connected to the user as instead
of the "someone" user specified via `_run_as`. This happened because the
Applicator class failed to replicate the full executor behavior of
running a task.
The Applicator now honors `run_as` if it's set on the executor, passing
it through to the transport's `batch_task` method.
This already worked fine for `run_as` set on a Target in the inventory
or for the `--run-as` flag.
> (GH-1167) Honor run_plan(..., _run_as => ...) from apply()

- Dockerfile
- scripts/server_client.rb
The bolt-server container needs a new package installed with apk so that native extensions can be built for the nio4r gem that is required by puma. Also, the server_client script needs an update to for the BoltSpec::BoltServer module.
> (maint) Install linux-headers for alpine to support nio4r gem

- pre-docs/writing_plans.md
A plan parameter example was referencing `$nodes` when the parameter
was actually named `$webservers`.  This updates the code in the example.
> (maint) fix parameter reference in plan example

- lib/bolt/transport/powershell.rb
- spec/fixtures/complex_params/input.json
- spec/fixtures/complex_params/output
- spec/fixtures/modules/sample/tasks/complex_params.ps1
closes https://github.com/puppetlabs/bolt/issues/1205
Previously, when parsing xml in the `Get-ContentAsJson` implementation a regex used to filter out xml elements with whos `MemberType` `Properties` had a name that was preceeded with `__` or contained the string `type`. Filtering on the string `type` caused task parameters that contain that string to be ignored, preventing users from being able to effectively pass powershell task paramters with the `type` in the name. Unfortunately, with the current implementation powershell parameters with the name `type` will be clobbered by a `Property` called type. However this commit updates the regex to *only* filter out the property that exactly matches `type`. Note that this work allows powershell task parameters with `type` in the name, but not …
> (GH-1205) Allow powershell task parameters with `type` in the name

- developer-docs/bolt-api-servers.md
- lib/bolt_server/file_cache.rb
- lib/bolt_server/schemas/action-upload_file.json
- lib/bolt_server/transport_app.rb
- spec/bolt_server/app_integration_spec.rb
- spec/fixtures/modules/upload_file/files/subdir/sub-file.sh
- spec/fixtures/modules/upload_file/files/test-file.sh
- spec/lib/bolt_spec/bolt_server.rb
In cases where PXP Agent is not installed on a target node
and thus cannot upload a file, SSH or WinRM should be used.
This commit adds the `POST /upload_file` endpoint which will
delegate either to SSH or to WinRM accordingly.
> (ORCH-2340) Add `upload_file` endpoint to bolt-server

- docs/_includes/lesson11/Boltdir/site/profiles/plans/nginx_install.pp
When `curl`ing from the command line, it is easy to have your output
swallowed up by a fancy prompt.  It's probably cleaner anyhow.
> Add a newline to the site_content on lesson 11

- docs/_includes/lesson11/Boltdir/inventory.yaml
The inventoryfile for lesson 11 contains a target with the name `localhost` used to target a docker container with an exposed port on 20024. The special `localhost` target name inherits the localhost defaults (including the `puppet-agent' feature). This causes apply prep to fail when an agent is not installed on the target system. This commit updates the example so that the special "localhost" target name is not used so users do not run in to this problem.
> (maint) Update inventoryfile in HOL to not use special localhost target

- lib/bolt_server/schemas/action-check_node_connections.json
- lib/bolt_server/schemas/transport-ssh.json
- lib/bolt_server/schemas/transport-winrm.json
- lib/bolt_server/transport_app.rb
- spec/bolt_server/app_integration_spec.rb
- spec/bolt_server/transport_app_spec.rb
- spec/lib/bolt_spec/bolt_server.rb
Adds a check_node_connections endpoint for use in the Puppet Enterprise orchestrator's implementation of wait_until_available. Individual commit messages have details.
> (ORCH-2341) Add check_node_connections endpoint to bolt_server

- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
The test setup for the apply_prep spec relies on setting global context that is no-longer available to be set with override. This commit updates the apply_prep method to only look up the overridden values once.
> (maint) Cache the puppet lookup for bolt_{inventory,executor}

- acceptance/setup/common/pre-suite/010_install_ruby.rb
Update component pipeline to use 10.14 instead of 10.13 due to issues with installing ffi with native ruby.
> (maint) Unpin ffi due to updating to macos 10.14 bolt controller

- docs/_lab/10-deploying-an-application/index.md
Fixes 'no info with --verbose' to 'no info without --verbose'
Adds missing '_catch_errors' line
> (maint) Fix verbose logging and catch_errors

- developer-docs/bolt-api-servers.md
- lib/bolt_server/transport_app.rb
- spec/bolt_server/app_integration_spec.rb
- spec/bolt_server/transport_app_spec.rb
Fixes a bug I introduced yesterday in #1221:
Previously, the conversion to JSON of bolt_server responses that use
`targets` instead of `target` was broken - it did not correctly format
the results as a parsable array.
This change fixes that, and instead of returning just the result list,
aggregate endpoints now return their own status hash, with two entries:
- 'status': will be 'success' only if all targets succeeded. If at least
one target failed, this will also be set to 'failure', even though the
request itself was successful and returns 200.
- 'result': contains the array with individual status hashes for each target.
> (ORCH-2341) Fix aggregate results reporting in bolt_server

- CHANGELOG.md
This commit updates the changelog to describe two closed issues. https://github.com/puppetlabs/bolt/issues/1167 , https://github.com/puppetlabs/bolt/issues/1205
> (docs) Update changelog with missing information

- docs/_includes/lesson11/Boltdir/inventory.yaml
- docs/_includes/lesson11/Boltdir/site/profiles/plans/nginx_install.pp
- docs/_lab/11-apply-manifest-code/index.md
The `profiles::nginx_insall` plan for lab 11 assigned class names for `haproxy::balancermember` based on the target name. When the target name is a URI the plan would error because names cannot include `:` or `/`. This commit updates the plan to declare unique class names without having to rely on scrubbing the target name/uri of illegal characters.
> (maint) Update lab 11 to handle URI target names

- CHANGELOG.md
- lib/bolt/transport/winrm.rb
- lib/bolt/transport/winrm/connection.rb
- spec/bolt/config_spec.rb
- spec/bolt/transport/winrm_spec.rb
This commit adds logic to the winrm transport to not try to read the `cacert` file when not using `ssl`. This avoids confusing errors when the `cacert` is not readable but `ssl` is not being used.
> (GH-1164) Only try to read cacert for winrm when needed

- CHANGELOG.md
- pre-docs/bolt_installing.md
As of 1.30.1 bolt is no-longer built and shipped for ubuntu 1404. Remove platform from install page.
> (maint) Remove installation instruction for deprecated platform

- CHANGELOG.md
- lib/bolt/transport/orch/connection.rb
- spec/bolt/transport/orch_spec.rb
Previously when the `token-file` or `cacert` file paths were used to construct a new orchestrator client instance, the paths were not expanded. Other paths in bolt expand and there are examples in the wild where paths need to be expanded (for example `token-file: ~/.puppetlabs/token`). This commit updates the orch transport to expand file paths before creeting an Orchestrator client object.
> (GH-1174) Expand file paths for orchestrator client config

- lib/bolt_server/transport_app.rb
- spec/bolt_server/app_integration_spec.rb
Prior to this commit, the bolt-server implementation of upload_file would
always attempt to download with a source location of cache_dir/job_id (i.e. a
top-level directory). This breaks downloads for single files, since a single
file download request could have a destination with a fully qualified
filename, in which case the download would make the destination filename in to
a directory and download the single file in to that directory.
This commit updates upload_file in transport_app.rb to special case the single
file scenario, so that the upload source is `cache_dir/job_id/relative_path`
(i.e. a fully qualified path to the single file).
> (ORCH-2317) Update upload_file in bolt-server to work with single files

- spec/bolt/transport/orch_spec.rb
The newest version of the orchestrator_client gem does file path validation for cacert. Pass an existing file in test setup.
> (maint) Update orch spec for orchestrator_client 0.4.3

- lib/bolt_server/transport_app.rb
The upload_file api in transport_app.rb (for bolt-server) uses
`@file_cache.download_file` to download files to a cachedir before actually
uploading them to hosts.
This is broken when more than one thread is in use, because download_file
should be wrapped in `@file_cache.serial_execute` so downloads only happen one
at a time (the download function itself is not thread safe).
This commit updates upload_file to use `serial_execute`
> (ORCH-2317) Update transport_app upload_file to use thread safe download

- developer-docs/bolt-api-servers.md
- lib/bolt_server/schemas/action-run_script.json
- lib/bolt_server/transport_app.rb
- spec/bolt_server/app_integration_spec.rb
- spec/fixtures/modules/upload_file/files/test-file.sh
- spec/lib/bolt_spec/bolt_server.rb
In cases where PXP Agent is not installed on a target node and thus
cannot run a script, SSH or WinRM should be used. This commit adds the
`POST /run_script` endpoint which will delegate either to SSH or to
WinRM accordingly.
> (ORCH-2339) Add `run_script` endpoint to bolt server

- CHANGELOG.md
- CODEOWNERS
Accidentally linked to a PR instead of the issue. This commit updates the CHANGELOG with the correct link.
> (docs) Link to issue # not PR # for GH-1164

- spec/Dockerfile.puppetdb
- spec/docker-compose.yml
- spec/fixtures/puppetdb/docker-entrypoint.sh
The ssl-setup.sh script is no longer used by the puppetdb container. This commit removes the curtom entrypoint for setting up docker-compose stack for testing to use the entrypoint defined by the base image. It also updates the destination for the ssl setup to the expected location.
> (maint) Update pdb container setup for new ssl setup

- README.md
This commit updates the Travis CI badge on the README to be correct.
> (maint) Fix badge for Travis build

- CHANGELOG.md
- lib/bolt/analytics.rb
- spec/bolt/analytics_spec.rb
Previously, we spun evaluation of the client OS into another thread to
avoid slowing down the main execution thread by needing to require
facter. This caused a race condition in facter between the thread
compting the OS and the main thread loading PAL which also needs to
evaluate some facts. As it turns out, by the time the analytics client
is instantiated we've already required facter anyway, so we don't have
to pay that cost. Evaluating the OS fact is negligible (~25ms), so we
now do it in the main thread to avoid the race condition.
> (maint) Eagerly evaluate OS in analytics client

- CHANGELOG.md
- lib/bolt/apply_result.rb
- spec/bolt/applicator_spec.rb
- spec/bolt/apply_result_spec.rb
- spec/fixtures/apply/apply_catalog.sh
- spec/fixtures/apply/basic/plans/init.pp
- spec/integration/apply_compile_spec.rb
Previously ApplyResult would create difficult to use objects when it got
unexpected reports back from the apply task. It will now treat those
results as errors. This may result in an apply erroring when a
misbehaved provider prints to stdout even when the application otherwise
appears successful.
@jpartlow do you want to test this with your use case.
> (GH-1241) Handle unexpect results from the apply task

- spec/lib/bolt_spec/puppetdb.rb
Previously, this code was using an invalid hash lookup instead of a hash
assignment. However, it was also trying to set this parameter in the
POST body instead of the URL where it belongs. We now correctly set it
as a query param.
> (maint) Properly set the `wait` argument on PuppetDB commands

- CHANGELOG.md
- lib/bolt/transport/powershell.rb
- lib/bolt/transport/winrm.rb
- spec/bolt/transport/winrm_spec.rb
- spec/lib/bolt_spec/integration.rb
Previously when running a task over winrm where a space was contained in a user defined `interpreter` path or the path to the temporary task executable the task could fail due to not quoting the paths to handle the spaces. This commit updates the winrm transport to quote both paths when `interpreters` is configured. Note that for the `interpreter` path, if the user has specified a quoted path, no additional quoting will be added.
closes https://github.com/puppetlabs/bolt/issues/1158
> (GH-1158) Quote paths for interpreter and task when using winrm

- lib/bolt/secret/base.rb
Changing the `encrypted-value` deprecation message to something that's more descriptive and user-friendly.
> Friendly deprecation error message

- lib/bolt/pal.rb
Ruby 2.3 does not support the `children` method for the `Dir` class. This commit updates the code to explicitly filter the `.` and `..` directories when loading resource types using the `Dir#entries` method.
> (GH-1140) Maintain ruby 2.3 compatibility by not using Dir.children

- lib/bolt_spec/plans.rb
- lib/bolt_spec/plans/mock_executor.rb
- lib/bolt_spec/plans/publish_stub.rb
- spec/bolt_spec/plan_spec.rb
- spec/fixtures/bolt_spec/plans/plans/out_message.pp
This commit updates the mock executor to allow users to mock out an event collector for capturing messages from `out::message` when stubbing out plans with BoltSpec::Plans.
> (maint) Stub publish_event in mock-executor

- pre-docs/plan_functions.md
- pre-docs/reference.md.erb
This commit updates the erb template for the rake docs task to format the plan runction names with unformatted names.
> (docs) Regenerate plan reference with unformatted function names

- lib/bolt/plugin/pkcs7.rb
- spec/bolt/plugin/pkcs7_spec.rb
Previously the `pkcs7` plugin was not able to resolve a path like so:
```yaml
plugins:
pkcs7:
public-key: ~/.puppetlabs/bolt/keys/public_key.pkcs7.pem
private-key: ~/.puppetlabs/bolt/keys/private_key.pkcs7.pem
```
When running it would produce an error:
```
Error executing plugin pkcs7 from resolve_reference in dev: No such file or directory @ rb_sysopen - /home/nmaludy/src/puppet-xxx/~/.puppetlabs/bolt/keys/private_key.pkcs7.pem
```
That's definitely not what we want.
Looking at the way we resolve paths in `config.rb` shows that we were using `File.expand_path()` where in `pkcs7.rb` we were using `File.absolute_path()`.
The fix was to simply make it `File.expand_path()` lookups and everything seems happy.
**NEED HELP  HERE**
On the testing side... i'm not sure how to create a spec test …
> Fix bug in pkcs7 plugin resolving home directories

- CHANGELOG.md
- lib/bolt/applicator.rb
- lib/bolt/executor.rb
- lib/bolt/outputter/human.rb
- lib/bolt/target.rb
- lib/bolt/transport/base.rb
- lib/bolt/transport/docker/connection.rb
- lib/bolt/transport/orch.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/transport/sudoable/connection.rb
- lib/bolt/transport/winrm.rb
- lib/bolt/transport/winrm/connection.rb
- spec/bolt/transport/local_spec.rb
- spec/bolt/transport/shared_examples.rb
- spec/bolt/transport/ssh_spec.rb
- spec/integration/apply_compile_spec.rb
- spec/integration/apply_spec.rb
- spec/integration/ssh_spec.rb
This commit updates all logging and outputters to refer to targets by their `safe_name`. For an `Target2` object this is the uri minus the password. For a `Target` object it is the host.
> (GH-1243) Refer to Targets by their safe name

- docs/_includes/lesson1-10/Boltdir/site-modules/exercise9/tasks/yesorno.py
The example code does not work on RHEL5. The Python 2.4 json module does not work correctly, but the simplejson module does.
Later versions of python are okay.
> python 2.4 json module does not work with this code, but the simplejson module does

- lib/bolt/target.rb
- spec/bolt/target_spec.rb
This commit adds the eql? method for the Target2 object. Given Target2 objects are singletons, we only need to compare the target name as an indication of equality.
> (maint) Add eql? method for Target2

- CODEOWNERS
Update `pre-docs` to `documentation` to reflect changes to docs build process. Add Kate Medred as codeowner for docs review.
> (maint) Updates to CODEOWNERS

- CHANGELOG.md
- lib/bolt/plugin.rb
- spec/bolt/inventory/group2_spec.rb
Now that we are shipping bundled module plugins we need to load them from the default modulepath.
> (maint) Load plugin modules from builtin modulepath

- documentation/bolt.ditamap
I'm assuming this file is used in building https://puppet.com/docs/bolt/latest/writing_tasks_and_plans.html where `Running tasks` currently appears twice under the `Tasks and plans` menu.
> (Docs) Remove duplicate entry in ditamap

- docs/_lab/04-running-scripts/index.md
This commit updates the path to the `bashcheck.sh` script in the example for
`bolt script run`. If you use the `curl` command above to download the script,
it get downloaded as `bashcheck.sh` in the top level of your current working
directory, NOT nested under `src`.
> (maint) Update script path in hands-on-lab

- CHANGELOG.md
- bolt-modules/boltlib/spec/functions/apply_prep_spec.rb
- lib/bolt/inventory/inventory2.rb
Previously the default plugin_hooks from config were not being set on a Target2 object. This was causing failures in apply prep https://github.com/puppetlabs/bolt/blob/345131e31c02a3047c1607ce3b6df0a484976542/bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb#L103 which assumes that `plugin_hooks` will have a value. This commit updates the inventory 2 update_target_state to consider the `plugin_hooks` set in config. The merge order in order of precedence is target level in inventory, group level in inventory, specified in bolt.yaml, default.
> (maint) Fix apply prep for inventory v2

- CHANGELOG.md
- bolt-modules/boltlib/lib/puppet/datatypes/result.rb
- documentation/bolt_configuration_options.md
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/result.rb
- lib/bolt/target.rb
- spec/fixtures/modules/results/plans/test_result.pp
- spec/integration/result_set_spec.rb
- spec/lib/bolt_spec/integration.rb
This commit standardizes the Result object interface in plans with the JSON representation. This involved exposing a new `status` method on the Puppet Type, removing the `node` key from the status hash (in favor of `target`), and renaming `result` to `value`. This change is able to be toggled on and off with the newly introduced `$future` global variable.
> (GH-1245) Standardize JSON and Puppet Result objects

- CHANGELOG.md
- bolt-modules/boltlib/lib/puppet/functions/run_task.rb
- documentation/plan_functions.md
- documentation/writing_tasks.md
- lib/bolt/cli.rb
- spec/fixtures/modules/sample/plans/noop.pp
- spec/integration/ssh_spec.rb
When running a task from a plan, the `run_task` function should respect
the `_noop` option. Now when the `run_task` function is called either
with an executor in noop mode or with the `_noop` option it will run in
noop.
Closes #1207
> (GH-1207) Run task function should respect _noop option

- CHANGELOG.md
- bolt-modules/boltlib/lib/puppet/functions/add_facts.rb
- documentation/plan_functions.md
- lib/bolt/inventory.rb
- lib/bolt/inventory/inventory2.rb
- spec/bolt/inventory/inventory2_spec.rb
- spec/bolt/inventory_spec.rb
In order to be more consistent with the other `set_*` plan methods for setting target data, this commit updates the `add_facts` function to return a `Target` where previously a `Hash` of the updated facts was returned. Given this is a breaking change it is gated with the `future` flag.
Closes https://github.com/puppetlabs/bolt/issues/1211
> (GH-1211) Return Target object with plan function `add_facts`

- bolt-modules/boltlib/lib/puppet/functions/add_facts.rb
- documentation/plan_functions.md
This rewords the `add_facts` documentation for better readability
Closes #1327
> (GH-1327) Reword add_facts return documentation

- documentation/bolt.ditamap
- documentation/inventory_file_generating.md
This removes documentation for the outdate `bolt-inventory-pdb` command
> (maint) Remove bolt-inventory-pdb documentation

- CHANGELOG.md
- lib/bolt/plugin/module.rb
- spec/fixtures/plugin_modules/task_conf_plug/bolt_plugin.json
- spec/fixtures/plugin_modules/task_conf_plug/tasks/init.json
- spec/fixtures/plugin_modules/task_conf_plug/tasks/linux.sh
- spec/fixtures/plugin_modules/task_conf_plug/tasks/value.json
- spec/fixtures/plugin_modules/task_conf_plug/tasks/value.sh
- spec/fixtures/plugin_modules/task_conf_plug/tasks/win.ps1
- spec/integration/plugin/module_spec.rb
Previously when a config section existed in a `bolt_plugin.json` specification any config that was set in `bolt.yaml` would be passed to the task as under the key `_config`. Tasks that expect values to be set in either `bolt.yaml` or `inventory.yaml` would have to handle munging the values gathered from either file. This commit begins to phase out the config section in `bolt_plugin.json`. If there is not a config section in that file config values are validated against the intersection of the parameter metadata for the tasks that implement each hook. Values set in `bolt.yaml` are merged with those in inventory.yaml and passed as parameters. No `_config` is passed along.
Closes https://github.com/puppetlabs/bolt/issues/1322
> (GH-1322) Validate plugin config against task metadata

- .rubocop.yml
- documentation/using_plugins.md
- lib/bolt/inventory.rb
- lib/bolt/inventory/group.rb
- lib/bolt/inventory/group2.rb
- lib/bolt/inventory/inventory2.rb
- lib/bolt/inventory/target.rb
- lib/bolt/target.rb
- lib/bolt/util.rb
- spec/bolt/inventory/group2_spec.rb
- spec/bolt/inventory/inventory2_spec.rb
- spec/integration/plugin/task_spec.rb
- spec/lib/bolt_spec/plugins.rb
Previously, resolve_reference plugins could only be used in the
inventory in select ways. Namely, they could only be used to lookup
targets or to set config on a group or target. They couldn't be used to
set any other attributes of a group (vars, facts, etc) or to set the
arguments to another plugin.
We now allow every value in the inventory to be specified using a plugin
reference, including the inventory itself. Keys are never allowed to be
plugin references.
Some references will be resolved as soon as the inventory is loaded.
For a group, these are `name`, `targets`, `groups`. For each target, we
will immediately resolve its `name`, uri`, and `alias`.
The other fields (`vars`, `facts`, `features`, `config`, `plugin_hooks`)
are termed "group/target data" and are resolved only when …
> (GH-1147) Allow resolve_reference plugins everywhere in inventory

- lib/bolt/module.rb
Ruby 2.3 does not support the `Dir#children` method. This commit updates
the `Bolt::Module` class to use `Dir#entries` and filter the `.` and
`..` directories instead.
> (maint) Maintain ruby 2.3 compatibility by not using Dir.children

- bolt.gemspec
Now that modules need to be shiped with a bolt_plugin.json, do not exclude that file when building bolt packages.
> (maint) Do not exclude bolt_plugin.json in gemspec

- .travis.yml
This commit updates the build script for Travis to run rubocop before
any tests. This is helpful to catch any failures caused by rubocop early
on before running tests, which can take a significant amount of time.
> (maint) Run rubocop before tests in Travis

- bolt.gemspec
With this commit the Puppetfile that defines module versions shipped with bolt system packages is included in the gem artifact. This enables consumers of the gem to be able to install the module versions shipped with the corresponding system package.
> (packaging) Ship Puppetfile with bolt gem

- documentation/writing_tasks.md
Working on a ruby task based on the `ruby_task_helper` in the Bolt docs and i found that if i copy/pasted the code i got the following rubocop errors:
```
convention: rubocop: tasks/mytask.rb:4:1: Style/Documentation: Missing top-level class documentation comment.
convention: rubocop: tasks/mytask.rb:4:26: Layout/TrailingWhitespace: Trailing whitespace detected.
warning: rubocop: tasks/mytask.rb:5:25: Lint/UnusedMethodArgument: Unused method argument - `kwargs`. If it's necessary, use `_` or `_kwargs` as an argument name to indicate that it won't be used.
convention: rubocop: tasks/mytask.rb:10:1: Layout/EmptyLines: Extra blank line detected.
convention: rubocop: tasks/mytask.rb:11:15: Style/YodaCondition: Reverse the order of the operands `__FILE__ == $0`.
convention: rubocop: …
```
> Fixing rubocop styling in the task helper docs

- CHANGELOG.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/plugin/prompt.rb
- spec/bolt/cli_spec.rb
- spec/bolt/plugin/prompt_spec.rb
This commit removes the optional argument for the `--password` and
`--sudo-password` options and replaces it with a required option.
Previously, if a password was omitted as an argument, the user would be
prompted to enter one.
This also updates the `prompt` plugin to print to `stderr` instead of
`stdout`.
> (GH-1269) Require argument for --password and --sudo-password options

- Puppetfile
- acceptance/setup/common/pre-suite/071_install_modules.rb
Previously we maintained a subset of modules needed for acceptance tests by statically defining module versions in acceptance test setup. This is prone to error because when modules are updated in the Puppetfile, there is a risk the acceptance test will not be updated. Also, the statically defined modules were installed into the default boltdir modulepath, not the modules dir in the gem path. Now that we ship the Puppetfile with the bolt gem, we can use it to simply install the modules in the expected bolt gem path with r10k to mirror modules shipped in system packages.
> (GH-1345) Install bundled modules on gem path in acceptance test

- CHANGELOG.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/outputter/human.rb
- lib/bolt/outputter/json.rb
- lib/bolt/target.rb
- spec/bolt/cli_spec.rb
This commit adds support for a `--detail` flag that shows resolved
inventory information when using the `inventory show` subcommand.
Closes #1200
> (GH-1200) Add --detail option to show resolved inventory information

- documentation/using_plugins.md
- lib/bolt/applicator.rb
- lib/bolt/bolt_option_parser.rb
- spec/integration/apply_spec.rb
This includes a few small improvements:
1. When using the [Boltdir
repository](https://github.com/puppetlabs/Boltdir) we provide an empty
hiera config. If left in place Bolt will try to load this which results
in a traceback when we try to access data from the file. This PR adds a
check which will ignore the hiera config if there's no data in it.
2. When using `--configfile` as a command line argument the parent
directory of the specified file is used as the Boltdir to load other
Bolt config, such as the inventory. This PR adds documentation to the
flag letting users know we do this.
3. Lastly, we had some plain URLs in the `using_plugins.md` file, which
in github markdown will render as links but in Dita don't get rendered
as links. This makes them have explicit links syntax, so they …
> (maint) Allow empty hiera config, plus docs fixes

- lib/bolt/outputter/human.rb
- lib/bolt/outputter/logger.rb
Logging and outputting target references in plan steps was missed in initial GH-1243 PR. This commit updates the human outputter and logger to use safe_name instead of URI when logging/outputting plan_step events.
> (GH-1243) Log/output safe name for plan steps

- CHANGELOG.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
This adds a `project init` subcommand that creates a new Bolt project. When
specifying a filepath using `bolt project init [filepath]`, the project
directory will be created at the filepath. Otherwise, the project
directory is created in the current working directory.
> (GH-1285) Add project init command

- CHANGELOG.md
- lib/bolt/cli.rb
- lib/bolt/inventory.rb
- spec/bolt/cli_spec.rb
- spec/bolt/inventory_spec.rb
With this commit a warning is logged when an inventory data source (environment, or inventoryfile) exists and the user has specified options that are configurable from the inventoryfile on the CLI.
Closes https://github.com/puppetlabs/bolt/issues/1341
> (GH-1341) Warn when CLI inventory options may be overridden

- CHANGELOG.md
- Puppetfile
- documentation/bolt_configuration_options.md
- documentation/configuring_bolt.md
- documentation/using_plugins.md
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/puppetdb/config.rb
- spec/bolt/config_spec.rb
- spec/bolt/inventory_spec.rb
- spec/bolt/puppetdb/config_spec.rb
- spec/fixtures/configs/future.yml
There are a number of config options for Bolt that accept filepaths.
Previously we expanded the path relative to where Bolt was run in some
cases, and relative to the Boltdir in others. This standardizes all
configurable paths to be expanded relative to the Boltdir if they are
defined in a config file, and relative to the current working directory
if they are specified on the CLI. This change doesn't affect absolute
paths.  This provides consistent and predictable behavior for users. New
path expansions are gated on the `future` option being set to `true`.
Closes #1162
> (GH-1162) Expand configured paths relative to Boltdir

- CHANGELOG.md
- CODEOWNERS
Somehow the GH-1200 issue was put back under 1.35.0 in the changelog. Luckily there has not been a production docs build and the public docs still reference the tagged (correct) 1.35.0 version of the changelog. This commit moves the issue to the (not yet tagged) 1.36.0 version.
> (docs) Move GH-1200 to correct version in changelog

- Puppetfile
We recently released a new version of the Vault module which makes the
`auth` parameter optional rather than required. This pulls in the latest
version.
> (maint) Pull in Vault 0.2.2

- documentation/bolt.ditamap
This fixes a formatting error in the docs dita file that prevents the
docs publishing pipeline from running successfully.
> (maint) Fix formatting in docs dita file

- CHANGELOG.md
- bolt-modules/boltlib/lib/puppet/functions/resolve_references.rb
- bolt-modules/boltlib/spec/fixtures/modules/test/tasks/references.rb
- bolt-modules/boltlib/spec/functions/resolve_references_spec.rb
- lib/bolt/inventory/group2.rb
- lib/bolt/plugin.rb
- spec/bolt/inventory/inventory2_spec.rb
This adds support for a `resolve_references` plan function that accepts
a hash of target data, resolves all references in the hash, and returns
the resolved target data.
Closes #1365
> (GH-1365) Add resolve_references plan function

- CHANGELOG.md
- lib/bolt/bolt_option_parser.rb
- spec/bolt/cli_spec.rb
The initial implementation of GH-1269 prematurely forbit optional parameters for cli opts that could expect a prompt. This PR re-allows them and issues a warning when there is no value provided for `--password` or `--sudo-password`. This is accompished by adding a new instance variable to `BoltOptionParser` that is available with an attr reader to collect a hash of warnings when parsing options and surface them once the logger is configured.
> (GH-1269) Warn when --{sudo}-password is empty

- CHANGELOG.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
This commit adds two new CLI flags: `password-prompt` and `sudo-password-prompt`. In order to make parsing commands simpler, moving forward all CLI options either expect a mandatory parameter or do not accept a parameter at all. The `password` and `sudo-password` options violate this by allowing users to optionally set the value on the CLI which, when no value is set a prompt is displayed and the user can enter a password. Currently we will only be warning when the user does not supply a value for `--password` or `--sudo-password`. In 2.0 supplying a value will cause an error.
Closes GH-1269
> (GH-1269) Add password-prompt CLI flags and deprecation warning for optional param

- CHANGELOG.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
This adds support for a `project migrate` command that migrates a Bolt
project to the newest version. Specifically, the inventory file for the
project will be migrated from an earlier version (`v1`) to the latest
version (`v2`). Changes to the inventory file are made in place and
comments/formatting are not preserved during migration.
Closes #1377
> (GH-1377) Add project migrate command

- spec/bolt/plugin/puppet_library_spec.rb
It appears that some print debugging got merged in when new tests were introduced. This commit removes the noise.
> (maint) Delete puts debuggng line in test

- CHANGELOG.md
- Puppetfile
- documentation/using_plugins.md
- documentation/writing_plugins.md
Ship a yaml plugin that reads yaml data from a specified file path and returns the contents. Enhance documentation with examples from this very simple concept.
Closes https://github.com/puppetlabs/bolt/issues/1358
> (GH-1358) Add yaml plugin

- CHANGELOG.md
- documentation/bolt_running_plans.md
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
- spec/fixtures/modules/sample/plans/single_task_targets.pp
- spec/fixtures/modules/sample/plans/targets_nodes.pp
When `--nodes` or `--targets` is provided on CLI, "magically" pass that arg to `$nodes` or `$targets` if there is a plan parameter with name `$targets` XOR `$nodes` of type `TargetSpec` AND there is not a plan argument specified on the CLI with name `nodes` or `targets`.
> (GH-1175) Populate $nodes and $targets with --targets and --nodes

- CHANGELOG.md
- bolt-modules/file/lib/puppet/functions/file/exists.rb
- bolt-modules/file/lib/puppet/functions/file/readable.rb
Previously, file::exists and file::readable could return nil in the case
where the file path was specified relative to a module and didn't exist.
That would cause the function (and in turn the plan) to fail with an
invalid return type.
We now ensure these functions always return a boolean.
> Always return boolean from file predicate functions

- lib/bolt/plugin.rb
We forgot to iniclude yaml in the BUNDLED_CONTENT list for bundled plugins. This commit adds it.
> (GH-1358) Track YAML plugin usage

- CHANGELOG.md
- bolt-modules/boltlib/spec/functions/apply_prep_spec.rb
- bolt-modules/boltlib/spec/functions/run_plan_spec.rb
- documentation/bolt_configuration_options.md
- documentation/using_plugins.md
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/inventory.rb
- lib/bolt/inventory/target.rb
- lib/bolt/plugin.rb
- lib/bolt/plugin/prompt.rb
- lib/bolt/util.rb
- spec/bolt/cli_spec.rb
- spec/bolt/inventory/group2_spec.rb
- spec/bolt/inventory/inventory2_spec.rb
- spec/bolt/inventory_spec.rb
- spec/bolt/plugin/module_spec.rb
- spec/bolt/plugin/prompt_spec.rb
- spec/bolt/plugin_spec.rb
- spec/bolt/target_spec.rb
- spec/integration/inventory2_spec.rb
Previously, the `plugins` section of `bolt.yaml` was required to be 
completely static. Now, plugin can use the same `_plugin` hashes as in
`inventory.yaml` to define their configuration. For example, this allows 
secrets for plugins to be encrypted or read from vault.
We now instantiate (and thus validate) all plugins that are configured in
`bolt.yaml` at the time the plugin system is initialized.
We also now support `_plugin` lookups under the `plugin_hooks` key for
similar reasons.
Closes GH-1350
> (GH-1350) Configure plugins using other plugins

- acceptance/setup/common/pre-suite/010_install_ruby.rb
The winrm-fs gem effectively dropped support for ruby 2.3 which is the system ruby version we use in the osx bolt controller for component acceptance tests. This commit pre-installs the last ruby 2.3 compatible version of the winrm-fs gem on osx.
> (maint) Pin winrm-fs in OSX component acceptance tests

- CHANGELOG.md
- lib/bolt/inventory/group2.rb
- lib/bolt/inventory/inventory2.rb
- spec/bolt/inventory/group2_spec.rb
- spec/bolt/inventory/inventory2_spec.rb
- spec/bolt/inventory_spec.rb
This commit fixes a bug where `inventory show --detail` only showed the
rightmost alias for a target. Now, all aliases for a given target will
be displayed in the output.
> (GH-1379) Show all aliases for a target in inventory show --detail

- lib/bolt/inventory/group2.rb
- spec/bolt/inventory/group2_spec.rb
This adds a check to ensure that the name of a target returned from a
plugin is a String before adding it to a group. Since plugins using the new
ruby plugin helper can populate target data with any type of data, setting 
the `name` or `uri` of a target as anything other than a String would raise 
an obscure error.
> Check that names of targets returned from plugins are strings

- CHANGELOG.md
- lib/bolt/plugin.rb
Previously, we passed the Bolt config through to the "empty" inventory
used by plugins. That meant that any bolt.yaml configuration for the
`local` transport and any CLI flags were used when running plugins.
For example, running bolt with `--run-as` would cause plugins to run as
the `run-as` user, which is clearly not intended.
We now bypass the standard Bolt config and just use the defaults,
which means that plugins will always run against a standard unconfigured
localhost transport.
> (GH-1382) Ignore settings for localhost target when running plugins

- CHANGELOG.md
- bolt-modules/boltlib/lib/puppet/functions/run_task.rb
- bolt-modules/boltlib/spec/fixtures/modules/test/tasks/params.json
- bolt-modules/boltlib/spec/functions/run_task_spec.rb
- documentation/writing_tasks.md
- lib/bolt/outputter/human.rb
- lib/bolt/task.rb
This adds a new "default" field to the parameter specification in task
metadata. If a parameter is not specified and has a default value defined, the
default value will be used in its place. The default will be validated against
the parameter type specification and rejected if invalid.
Fixes #1173.
> (GH-1173) Allow task parameters to have a "default"

- CHANGELOG.md
- lib/bolt/outputter/human.rb
- lib/bolt/pal.rb
- lib/bolt/pal/yaml_plan.rb
- lib/bolt/pal/yaml_plan/loader.rb
- lib/bolt/pal/yaml_plan/parameter.rb
- lib/bolt/pal/yaml_plan/transpiler.rb
- modules/canary/plans/init.pp
- spec/bolt/cli_spec.rb
- spec/bolt/pal/yaml_plan/transpiler_spec.rb
- spec/fixtures/modules/sample/plans/optional_params_task.pp
- spec/integration/parsing_spec.rb
Previously, the info we showed with `bolt plan show <plan>` was very basic
and only included some of the information that Puppet could load from the
plan object. We now use puppet strings to parse the docstrings for the plan
so we can show description for the plan and its parameters as well as
parameter defaults.
We also now show the same data for YAML plans, though not through Puppet 
strings.
> (GH-1409) Show plan info using puppet strings

- CHANGELOG.md
- documentation/using_plugins.md
- lib/bolt/plugin/puppetdb.rb
- spec/bolt/plugin/puppetdb_spec.rb
- spec/integration/inventory2_spec.rb
This updates the `puppetdb` inventory plugin to accept a
`target_mapping` field that is used to populate target configuration
values with facts loaded from PuppetDB. This is to match the behavior of
other inventory plugins that use the Ruby plugin helper.
> **Do not merge** until other inventory plugins have been updated to use the Ruby plugin helper
> (GH-1408) Update puppetdb plugin to use target_mapping field

- lib/bolt/inventory.rb
Previously, we used the concat operator `<<` to insert the
'puppet-agent' feature into the localhost features set. In some cases,
the features set could be a plain reference to group data from the
inventory, so modifying it in place could cause that modification to be
visible to any other target in the same group. We now use the `+=`
operator which will first make a copy of the original set, ensuring we
don't affect unintended targets with the change.
> (maint) Copy, don't modify, `features` for localhost_defaults

- .rubocop.yml
- bolt-modules/boltlib/lib/puppet/functions/catch_errors.rb
- lib/bolt/plugin.rb
- lib/bolt/util.rb
- spec/lib/bolt_spec/integration.rb
Rubocop updated some of the names of cops in its latest release. This
updates the rubocop config file to use the new names.
This also removes some redundant `return` statements that rubocop is now
picking up.
> (maint) Update rubocop cop names

- CHANGELOG.md
- Puppetfile
This updates Bolt's Puppetfile to include version 0.3.0 of both the
`terraform` and `aws_inventory` plugins, as well as the initial release
of the `ruby_plugin_helper`.
Closes #1404
> (GH-1404) Update bundled plugins to use ruby_plugin_helper

- CHANGELOG.md
- documentation/bolt_connect_puppetdb.md
- lib/bolt/puppetdb/config.rb
- spec/bolt/puppetdb/config_spec.rb
This updates how Bolt locates the puppetdb config file on Windows.
Previously, the path was hardcoded as `C:\ProgramData\`, which could
cause issues if the user redirected the folder or had a different system
drive. Bolt will now use the `win32-dir` constant
`Dir::COMMON_APPDATA` to get the known folder.
Fixes #1427
> (GH-1427) Use environment variable for puppetdb config path in Windows

- CHANGELOG.md
- bolt-modules/boltlib/lib/puppet/functions/remove_from_group.rb
- bolt-modules/boltlib/spec/functions/remove_from_group_spec.rb
- lib/bolt/inventory.rb
- lib/bolt/inventory/group2.rb
- lib/bolt/inventory/inventory2.rb
- spec/bolt/inventory/inventory2_spec.rb
- spec/bolt/inventory_spec.rb
This adds a new `remove_from_group` plan function that allows you to
remove a target from an inventory group during plan execution. The
removed target is removed from all child groups and all parent groups,
except when the parent group explicitly defines the target.
Closes #1418
> (GH-1418) Add remove_from_group plan function

- documentation/bolt_connect_puppetdb.md
Based on a conversation in Slack, i've added a more detailed example of how to use `puppetdb_query()` so new users understand that the plan function just returns the raw query results and needs to transform them into Targets to use them in `run_*()` functions.
> Added detailed example of puppetdb_query() usage

- CHANGELOG.md
- lib/bolt/bolt_option_parser.rb
- spec/bolt/cli_spec.rb
This updates the CLI help text so it has a more consistent format with
other Puppet tools like `p10k` and `pdk`.
Closes #1441
> (GH-1441) Update CLI help text to be consistent with other Puppet tools

- CHANGELOG.md
- documentation/bolt_installing.md
This updates the installation docs for installing Bolt on Debian 10.
Needs the following PRs reviewed and merged:
Closes #1444
> (GH-1444) Package Bolt for Debian 10

- lib/bolt/result.rb
Previously an `@exception` instance variable was set on a `Bolt::Result` object when constructed with the `from_exception` class method. The instance variable does not appear to be used by the `Bolt::Result` class and there is no `attr_reader` for it. This commit removes the instance variable.
> (maint) Do not set an exception instance variable on Bolt::Result

- CHANGELOG.md
- lib/bolt/transport/ssh/connection.rb
- spec/integration/transport/ssh_spec.rb
This sets the default value for `sudo-password` to the same value as
`password`. This feature is gated by `future`.
> (GH-1425) Set default value for sudo-password to value for password

- CHANGELOG.md
- lib/bolt/pal.rb
- spec/fixtures/modules/sample/plans/subdir/command.pp
- spec/fixtures/modules/yaml/plans/subdir/init.yaml
- spec/integration/plan_spec.rb
We now have to discover the language a plan is written in based on it's
filename, which requires constructing the file path from the plan name
(i.e. `foo::bar::baz`) and testing if the file exists with either `.pp`
or `.yaml` extensions. This search falsely assumed that the plan path
could have at most 2 values: the module name and the plan filename.
Instead, it can have the module name, and a path relative to the `plans`
directory. This modifies the logic to correctly load nested plans.
Still needs testing
> (maint) Search plan subdirectories for plan filename

- CHANGELOG.md
- documentation/bolt_configuration_options.md
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/sudoable/connection.rb
- spec/integration/transport/ssh_spec.rb
* In some cases you need to be able to predict where bolt
will write the script file to. Previously, this was dictated
by the value of tmpdir and a SecureRandom id.
* This adds a new script-dir option that allows the user to supply
the directory where the script will be placed.
```
---
ssh:
script-dir: 'bolt_script_dir'
tmpdir: /home/vagrant
```
would end up creating the script file under
/home/vagrant/bolt_script_dir
By default the previous behavior of creating a unique directory
per script run is preserved.
> (feat) Add script-dir option to ssh transport

- CHANGELOG.md
- documentation/bolt_configuration_options.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/config.rb
- lib/bolt/transport/local.rb
- lib/bolt/transport/local/shell.rb
- lib/bolt/transport/ssh.rb
- lib/bolt/transport/ssh/connection.rb
- spec/integration/transport/ssh_spec.rb
This adds support for a `sudo-executable` transport config
option. When using `run-as`, the `sudo-executable` option will specify
the executable to use when running as another user. It will run the
executable with the same options as sudo.
This feature is experimental.
Closes #1439
> (GH-1439) Add sudo-executable transport config option

- CHANGELOG.md
- bolt-modules/boltlib/lib/puppet/datatypes/target.rb
- bolt-modules/boltlib/lib/puppet/functions/get_target.rb
- bolt-modules/boltlib/lib/puppet/functions/get_targets.rb
- documentation/applying_manifest_blocks.md
- lib/bolt/applicator.rb
- lib/bolt/apply_inventory.rb
- lib/bolt/apply_result.rb
- lib/bolt/apply_target.rb
- lib/bolt/catalog.rb
- lib/bolt/result.rb
- lib/bolt/result_set.rb
- lib/bolt/target.rb
- spec/bolt/applicator_spec.rb
- spec/bolt/catalog_spec.rb
- spec/bolt/cli_spec.rb
- spec/bolt/outputter/human_spec.rb
- spec/fixtures/apply/puppet_types/plans/applyresult.pp
- spec/fixtures/apply/puppet_types/plans/error.pp
- spec/fixtures/apply/puppet_types/plans/get_target.pp
- spec/fixtures/apply/puppet_types/plans/get_targets.pp
- spec/fixtures/apply/puppet_types/plans/result.pp
- spec/fixtures/apply/puppet_types/plans/resultset.pp
- spec/fixtures/apply/puppet_types/plans/target.pp
- spec/fixtures/apply/puppet_types/plans/target_new.pp
- spec/integration/apply_compile_spec.rb
- spec/integration/apply_error_spec.rb
There are 4 custom types in the Bolt plan language that we want to make
available inside apply blocks: Target, Result, ResultSet, ApplyResult.
For each of the \*Result\* objects this is accomplished by serializing the
plan variables to the apply block as pcore instead of as json. We also
needed to add pcore_init methods to the implementation classes of the
objects, because the pcore deserializer will by default call
`initialize` on the class and pass in the values of the attributes of
the type, which doesn't match the signature of the actual
implementations. Using `_pcore_init_hash` and `_pcore_init_from_hash`
lets us define what data gets serialized and how it gets deserialized
for those types.
Target objects are trickier for a few reasons:
1. They must have an associate inventory
2. …
> (GH-1244) Serialize plan variables as pcore

- lib/bolt/outputter/json.rb
We introduced a breaking change to JSON formatted output without gating
it on future. This restores the previous keys in the JSON output if
`future` is not configured.
> (bug-fix) Gate key change in JSON formatted output on future

- CODEOWNERS
- spec/bolt_server/file_cache_spec.rb
The file cache test sets a purge timeout/interval to 1 second, then sleeps for 2 seconds to allow enough time for the purge timer to fire. In most cases this is enough time for the mocked mutex to recieve `with_write_lock` one time. In some cases the timer fires twice. Given the interval is 1 second and we wait for 2 this is not unreasonable. This commit expects the timer to fire at most 2 times in the 2 seconds.
> (maint) Fix bolt_server file_cache spec test

- documentation/running_bolt_commands.md
This adds an example of running a script using Bolt and passing in
arguments to the script prefixed with `--`.
Closes #1485
> (docs) Add example running a script with -- arguments

- documentation/inventory_file.md
- documentation/inventory_file_v2.md
This removes the experimental notice for inventory file v2 from the
inventory file docs. It also adds documentation for using `bolt project
migrate` to automatically migrate a v1 file to a v2 file.
Closes #1479
> (GH-1479) Remove experimental notice for inventory file v2

- CHANGELOG.md
- lib/bolt/config.rb
- spec/bolt/config_spec.rb
When attempting to expand paths in config, only do so for the `ssh` transport setting `private-key` when it is not a `Hash` (indicating that `key-data` is being used.).
Closes https://github.com/puppetlabs/bolt/issues/1504
> (GH-1504) Do not try to expand a file path when ssh private-key key-data is specified

- lib/bolt_server/transport_app.rb
With this commit, a puma status endpoint is added to our app.
(We already implement the gc_stats endpoint.)
Since this endpoint is served by our app, there will always be one
thread in use in the result: that thread is the status request itself.
This is not true with the default puma status endpoint,
as it runs within a separate server ... as per puma/lib/puma/runner.rb.
> (PE-27794) add a puma status endpoint

- CHANGELOG.md
- documentation/bolt_project_directories.md
- lib/bolt/boltdir.rb
- spec/bolt/boltdir_spec.rb
This adds support for the `.yml` extension for bolt config and inventory
files. Bolt will recognize either `bolt.yaml` or `bolt.yml` as the root
of a local Boltdir, with `bolt.yml` following the same behavior as
`bolt.yaml` with respect to project directory type precedence. If both
`.yaml` and `.yml` files are present for config or inventory, `.yaml` is
preferred. Any yaml files generated by bolt still have the `.yaml`
extension.
Closes #1500
> (GH-1500) Support .yml for bolt config and inventory

- CHANGELOG.md
- bolt-modules/file/lib/puppet/functions/file/join.rb
- bolt-modules/file/spec/functions/file/join_spec.rb
This adds a `file::join` plan function which joins paths using the
separator `/`. It accepts multiple parameters and returns a single
string that is the joined file path.
Closes #837
> (GH-837) Add `file::join` plan function

- lib/bolt/util.rb
When attempting to `deep_clone` an instance of a `Bolt::Config` class with a custom Logging appender that references a Jruby/Clojure logger as an instance variable an exception (`Java::JavaLang::CloneNotSupportedException`) is raised that is not handled by rescuing `TypeError`. This commit updates the method to handle `CloneNotSupportedException`s the same way `TypeError` exceptions are handled.
Stack trace
```
java.lang.Object.clone(Native Method)
java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:440)
org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:304)
RUBY.deep_clone(/opt/puppetlabs/server/apps/bolt-server/lib/ruby/gems/bolt-1.43.0 …
```
> (ORCH-2290) Allow `deep_clone` to handle Jruby/Java objects

- lib/bolt_server/pe/pal.rb
- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
This adds an endpoint, `/plans`, to bolt-server that calculates
plan metadata. In order to handle environments in puppet, a new PAL
class is needed, and since bolt runs standalone in PE, this environment
code should live in bolt for now.
If the query parameter `environment` is supplied, this environment-aware
PAL will be used.
> (PE-28010) Calculate plan metadata in bolt-server

- CHANGELOG.md
- lib/bolt/catalog.rb
- spec/fixtures/apply/basic/plans/node_default.pp
- spec/fixtures/apply/basic/plans/node_definition.pp
- spec/integration/apply_compile_spec.rb
- spec/integration/apply_spec.rb
This adds support for node definitions from both `bolt apply` and within
apply blocks in a plan. Node definitions are still not allowed directly
in plans outside an apply block however, as there is no meaningful
behavior for them.
Supporting node definitions in apply blocks (vs `bolt apply`) depends on
https://github.com/puppetlabs/puppet/pull/7909 and the corresponding tests are
marked `pending` accordingly.
Closed #1338
> (GH-1338) Support node definitions when applying manifests

- CHANGELOG.md
- acceptance/tests/apply_plan_ssh.rb
- acceptance/tests/bolt_apply.rb
- documentation/bolt_installing.md
This updates the installation docs for installing Bolt on Fedora 31.
The following PRs should be merged first:
> (GH-1373) Package Bolt for Fedora 31

- CHANGELOG.md
Node definitions in `apply()` blocks depends on a change in Puppet which is
not yet released and so is not yet functional.
Also moved that changelog entry into Bolt NEXT since it hasn't actually been
released yet. It was added to Bolt 1.44.0 as part of an automatic merge
resolution gone awry.
> Clarify that node definitions only work in `bolt apply`

- .rubocop.yml
- bolt-modules/boltlib/lib/puppet/functions/puppetdb_query.rb
- lib/bolt/apply_result.rb
- lib/bolt/inventory/group2.rb
- lib/bolt/transport/docker/connection.rb
Rubocop updated the line length cop to be under the Layout section
rather than the Metrics section of their cops. This updates Bolt to
silence warnings about the name switch.
> (maint) Metrics/LineLength cop is now Layout/LineLength

- lib/bolt_server/pe/pal.rb
Explicitly remove the modulepath to the modules shipped in the bolt gem when calculating plan metadata for environments as these will not be available for puppet-server.
> (PE-28010) Exclude built in bolt modules in PE::PAL

- CHANGELOG.md
- lib/bolt_ext/puppetdb_inventory.rb
This adds a deprecation message to the `bolt-inventory-pdb` command
warning users about support for the command and inventory file v1 being
dropped in the future.
This change should be shipped with the planned changes to the inventory docs: #1464
> (GH-1491) Add deprecation message for bolt-inventory-pdb

- CHANGELOG.md
- lib/bolt/inventory.rb
This adds a deprecation message for when a v1 inventory file is loaded
and how to migrate to a v2 inventory file.
This change should be shipped with the planned changes to the inventory docs: #1464
Closes #1480
> (GH-1480) Add deprecation message for v1 inventory files

- CHANGELOG.md
- documentation/bolt_configuration_options.md
- lib/bolt/applicator.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/pal.rb
- lib/bolt/transport/orch.rb
- spec/fixtures/scripts/trusted_external_facts.sh
- spec/integration/apply_compile_spec.rb
- spec/integration/transport/orch_spec.rb
This adds support for the new trusted external facts command. It adds a
configuration option `trusted-external-command` where users can
configure a path to their trusted external facts executable. We pass that
value through to the Puppet settings config of the same name. This
allows users to access trusted external facts in `$trusted['external']`.
Closes #1431
> (GH-1431) Add support for trusted external facts

- lib/bolt_server/transport_app.rb
- spec/bolt_server/transport_app_spec.rb
Previously when the plan metadata is requested for the special `init.pp` plan (with the same name as its parent module) the metadata endpoint would not trim the `init` from the name before calling in to get_plan_info. With this commit the endpoint has been updated to handle plans referenced only by `[module name]::init`.
> (PE-27909) Return plan metadata for `init` plan

- CHANGELOG.md
- lib/bolt/transport/ssh/connection.rb
- lib/bolt/transport/sudoable/connection.rb
- spec/integration/apply_compile_spec.rb
- spec/integration/transport/ssh_spec.rb
Previously, connecting as one user and running as a different user via 
run-as would cause the operation to execute in the home directory of the 
connected user instead of the run-as user. This difference doesn't usually
matter because the common run-as case involves escalating to root, in which
case root can read the directory anyway. However, when connecting as root
and then *dropping* to a less-privileged user, this would leave the process
in a situation where it might not have read access to its working
directory. This problem also arises when using NFS with the standard root
squash configuration, whereby root still can't read the home directories of
non-root users.
We now prepend a `cd` command with no argument before every command we 
execute when using run-as. This form of `cd` …
> (GH-1319) Execute in run-as user's home dir when using run-as with SSH

- acceptance/Rakefile
- acceptance/tests/apply_plan_ssh.rb
With #1518, we now execute `cd` before running any command when `run_as`
is specified, which changes into the `run_as` users home directory. In
the acceptance tests we create a user `apply_nonroot` using Puppet, which doesn't create
a homedir for that user. When Bolt tried to change into
apply_nonroot's home directory it would error, which wasn't what we were
trying to test.
Additionally, using `managehome=true` when creating the Puppet user
fails on OSX (I tried with 12 and 14). We now create the user's home
directory using Puppet so that there's a directory for the user to
change into. This uses the platform agnostic `$(echo ~apply_nonroot)`
which will get the homedir for the apply_nonroot user on both OSX and
Linux platforms (`/Users/apply_nonroot` and `/home/apply_nonroot` …
> (maint) Create user homedir for acceptance tests

- spec/fixtures/plugin_modules/identity/tasks/resolve_reference.json
- spec/fixtures/plugin_modules/identity/tasks/resolve_reference.ps1
This adds a powershell implementation for the `resolve_reference` task
used by some unit tests. Previously, a handful of tests would fail on
Windows since the tests would attempt to use a shell implementation of
the task.
> (maint) Add `resolve_reference` powershell implementation for tests

- CHANGELOG.md
- lib/bolt/inventory.rb
- lib/bolt/target.rb
This adds a deprecation message for when `Target.new(<uri>, <options>)`
is used in a plan. It also notifies the user to use `Target.new(<uri>)`
instead.
Closes #1481
> (GH-1481) Add deprecation message for Target.new(<uri>, <options>)

- acceptance/files/example_apply/plans/init.pp
- acceptance/tests/apply_plan_ssh.rb
- acceptance/tests/apply_plan_winrm.rb
- libexec/apply_catalog.rb
- libexec/custom_facts.rb
- libexec/query_resources.rb
There are 3 tasks defined in `libexec` that are used internally by Bolt
to perform tasks on remote hosts (when you have a hammer...). Each of
these tasks takes a 'plugins' argument which is the contents of a
tarball of plugins from modules that are available to Bolt, in order to
load custom facts. The 'plugins' argument contents are written to a tar
file, then unpacked by `Puppet::ModuleTool::Tar` into a tempdir. The
last step of the unpacking is to `chown -R` the untarred directory to
the user who is executing the task.
Previously we figured out which user to `chown` the directory to using
`Etc.getlogin`, because it works on both *nix and Windows platforms.
However when any task was run as a different user than the one Bolt
connected to the host with (using `run-as`), `Etc.getlogin` …
> (bug-fix) Prefer Etc.getpwuid.name to Etc.getlogin when available

- CHANGELOG.md
- lib/bolt/outputter/human.rb
- lib/bolt/result.rb
- spec/bolt/outputter/human_spec.rb
This changes the human outputter so that it does not display empty
strings or empty JSON objects. Previously, if a result only had an
`_output` key, the human outputter would dislay the value of `_output`,
even if it was an empty string or whitespace. If the only key present
was `_output`, the outputter would also display an empty JSON object
after the value of `_output`.
Now, if the result only contains an `_option` key and the value for that
key is an empty string or whitespace, the human outputter will display a
message stating the action completed successfully with no result.
Closes #1544
> (GH-1544) Remove empty strings and objects from results in human output

- CHANGELOG.md
- Puppetfile
- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- bolt-modules/boltlib/spec/functions/apply_prep_spec.rb
- spec/bolt_spec/run_spec.rb
- spec/integration/apply_spec.rb
This updates the `apply_prep` plan function to ensure the specified
version of the Puppet agent is installed on the target. Previously, the
`apply_prep` function would only install the agent if the target did not
have any version of the agent installed and did not have the
`puppet-agent` feature set. Now, `apply_prep` will attempt to install
the agent on any target that does not have the `puppet-agent` feature
set, even if the install would cause an upgrade or downgrade to an
already-installed agent.
The following PR in puppetlabs/puppetlabs-puppet_agent should be merged in first:
https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/463
Closes #1208
> (GH-1208) Ensure Puppet agent version with apply_prep

- Puppetfile
- spec/fixtures/apply/basic/plans/init.pp
- spec/integration/modules/facts_spec.rb
The facts module now uses facter if it's available when running the
`facts` task. Plans in the facts module now use the `targets` parameter
instead of `nodes`.
Closes #1195
> (GH-1195) Update facts module to 1.0.0

- CHANGELOG.md
- Rakefile
- documentation/bolt_configuration_reference.md.erb
- lib/bolt/applicator.rb
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/pal.rb
- libexec/apply_catalog.rb
- spec/bolt/applicator_spec.rb
- spec/fixtures/apply/settings/plans/show_diff.pp
- spec/integration/apply_spec.rb
Bolt creates it's own Puppet context when applying Puppet code, which
doesn't inherit config from the system it's running on. Thus, when
applying Puppet code using Bolt users are limited to the default Puppet
settings.
This makes the `show_diff` [Puppet configuration
setting](https://puppet.com/docs/puppet/latest/configuration.html#showdiff)
to be configurable in Bolt's configuration file. When set, Bolt will set
the correspondent setting in it's Puppet context when applying Puppet
code, both from apply blocks in plans and from standalone manifests.
Additionally, this fixes a missing option in the help text, where `noop`
was not listed as a flag for `bolt task run`.
Closes #1433
> (GH-1433) Expose show_diff option for applying Puppet code

- CHANGELOG.md
- lib/bolt/plugin/prompt.rb
This updates the `prompt` plugin to require a `message` option.
Previously, the plugin was not requiring a message, as
`validate_resolve_reference` was not recognized as a valid hook. This
hook has been added, so options are now validated as intended.
> (GH-1568) Require message in prompt plugin

- CHANGELOG.md
- documentation/applying_manifest_blocks.md
- lib/bolt/applicator.rb
This adds a `_description` parameter in `apply` blocks that gives an
apply block a description that is displayed in plan output.
Closes #1537
> (GH-1537) Add support for `_description` parameter in apply blocks

- documentation/inventory_file_v2.md
- documentation/using_plugins.md
This adds documentation for the `env_var` plugin.
> (docs) Add env_var plugin documentation

- CHANGELOG.md
- documentation/configuring_bolt.md
- lib/bolt/cli.rb
- lib/bolt/config.rb
- spec/bolt/config_spec.rb
This change adds support for two new configuration files. In order from
highest precedence to lowest, the configuration files are:
- Project configuration
`<boltdir>/bolt.yaml`
- User configuration
`~/.puppetlabs/etc/bolt/bolt.yaml`
- System-wide configuration
*nix: `/etc/puppetlabs/bolt/bolt.yaml`
Windows: `%PROGRAMDATA%\PuppetLabs\bolt\etc\bolt.yaml`
When multiple configuration files are found, Bolt will employ the
following merge strategy:
- Shallow merge options that accept hashes
- Overwrite options that do not accept hashes
- Deep merge transport configuration options (e.g. `ssh`, `winrm`)
- Shallow merge configuration for individual plugins configured under
the `plugins` option.
Closes #608
> (GH-608) Add support for multiple configuration files

- lib/bolt/inventory/target.rb
- lib/bolt/target.rb
- lib/bolt/transport/remote.rb
- spec/bolt/inventory/inventory2_spec.rb
- spec/bolt/target_spec.rb
In both the v1 and v2 inventory formats, we use the URI scheme as the
transport for the target. In v1 however, that was only true if the
target did not also separately have transport specified as "remote". In
that case, the URI scheme was used as simply a URI scheme (called
`protocol` when running a task) allowing it to therefore be arbitrary.
With the v2 inventory, we didn't respect that distinction and would a) fail
if the URI scheme did not correspond to a valid transport, and b)
override the "remote" transport specification with the one derived from
the scheme, preventing the use of remote targets with specific URI schemes.
We now vary the behavior of protocol and transport for v2 targets based
on whether or not they are remote. For remote targets, `transport` will
always be "remote" …
> (maint) Support arbitrary URI schemes for remote targets in v2 inventory

- lib/bolt/cli.rb
- lib/bolt/config.rb
- lib/bolt/inventory.rb
- lib/bolt/util.rb
- spec/bolt/cli_spec.rb
- spec/bolt/config_spec.rb
- spec/bolt/util_spec.rb
All config (inventory.yaml, bolt.yaml, etc...) should have a hash type (or be empty). It is possible to have valid YAML that is not a hash type. This commit re-names the `Bolt::Util#read_config_file` method to `read_yaml_hash`. This change also removes some of the complexity in the method by no longer accepting a list of "default" paths to check. Previously if a list of defaults was passed in actually finding a file to read became optional. Now a second util method `read_optional_yaml_hash` has been added which will return the results of `read_yaml_hash` if the file exists and an empty hash otherwise. This allows the caller to choose the appropriate method based on if the file is expected to exist or not.
> (maint) Refactor/rename Bolt::Util#read_config_file

- CHANGELOG.md
- lib/bolt/apply_result.rb
This fixes a regression introduced in #1544 that would show an apply
result hash as a JSON object when using human output. Now, if a plan
returns only an apply result, human output will display a metrics
message instead of the apply result hash.
Fixes #1585
> (GH-1585) Don't show apply result hash in human output

- CHANGELOG.md
- bolt.gemspec
- documentation/bolt_known_issues.md
- lib/bolt/transport/ssh.rb
The net-ssh-krb gem was previously licensed with an incompatible license
for use in Bolt, in addition to a dependency version conflict. The gem
was recently relicensed and updated, so can now be shipped out of the
box with Bolt and documented. This allows users to use Kerberos
authentication when connecting to targets over SSH by specifying
`gssapi-with-mic` as a `PreferredAuthenticationMethod` in their OpenSSH
config (typically `~/.ssh/config`).
> (maint) Support Kerberos authentication with SSH

- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/linux.yaml
- .github/workflows/modules.yaml
- .github/workflows/windows.yaml
As this file is where we actually specify our gem dependencies, we need to
include it in the cache key calculation or we will use a bundle that 
doesn't include all the gems we need.
This also includes a change to not run tests on .erb-only changes. We will
still run the docs workflow on .erb-only changes, as those could introduce
invalid syntax that would cause a build failure which we want to detect.
> (maint) Clear gem cache when bolt.gemspec changes

- documentation/bolt_configuration_reference.md.erb
This was at the same level as the actual transports, causing it to show
up as an entry in the table of contents under "Transport configuration
options".
> (maint) Don't include OpenSSH config section in table of contents

- Rakefile
- bolt-modules/boltlib/lib/puppet/functions/add_facts.rb
- bolt-modules/boltlib/lib/puppet/functions/add_to_group.rb
- bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
- bolt-modules/boltlib/lib/puppet/functions/catch_errors.rb
- bolt-modules/boltlib/lib/puppet/functions/fail_plan.rb
- bolt-modules/boltlib/lib/puppet/functions/get_resources.rb
- bolt-modules/boltlib/lib/puppet/functions/get_target.rb
- bolt-modules/boltlib/lib/puppet/functions/get_targets.rb
- bolt-modules/boltlib/lib/puppet/functions/puppetdb_fact.rb
- bolt-modules/boltlib/lib/puppet/functions/remove_from_group.rb
- bolt-modules/boltlib/lib/puppet/functions/resolve_references.rb
- bolt-modules/boltlib/lib/puppet/functions/run_command.rb
- bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
- bolt-modules/boltlib/lib/puppet/functions/run_script.rb
- bolt-modules/boltlib/lib/puppet/functions/run_task.rb
- bolt-modules/boltlib/lib/puppet/functions/set_config.rb
- bolt-modules/boltlib/lib/puppet/functions/set_feature.rb
- bolt-modules/boltlib/lib/puppet/functions/set_var.rb
- bolt-modules/boltlib/lib/puppet/functions/upload_file.rb
- bolt-modules/boltlib/lib/puppet/functions/wait_until_available.rb
- bolt-modules/boltlib/lib/puppet/functions/without_default_logging.rb
- bolt-modules/ctrl/lib/puppet/functions/ctrl/do_until.rb
- bolt-modules/file/lib/puppet/functions/file/exists.rb
- bolt-modules/file/lib/puppet/functions/file/join.rb
- bolt-modules/file/lib/puppet/functions/file/read.rb
- bolt-modules/file/lib/puppet/functions/file/readable.rb
- bolt-modules/out/lib/puppet/functions/out/message.rb
- bolt-modules/system/lib/puppet/functions/system/env.rb
- documentation/reference.md.erb
This adds documentation for the optional parameters and metaparameters
for Bolt's plan functions. It also updates the formatting of the plan
functions page to be more clear on what is a return value, parameter, or
additional option.
Closes #1584
> (GH-1584) Add options to Bolt plan functions documentation

- lib/bolt/inventory/group.rb
- spec/bolt/inventory/group_spec.rb
- spec/bolt/inventory_spec.rb
- spec/pal/vars_spec.rb
This adds an error when Bolt detects that a v1 inventory file is being
used. A v1 inventory file is identified by the use of a `nodes` key at
the group level, which is deprecated in v2 inventory files.
> (GH-1567) Error when using a v1 inventory

- CHANGELOG.md
- lib/bolt/bolt_option_parser.rb
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
This adds support for a `--filter FILTER` option when using the `task show` and
`plan show` commands. When using the `--filter` option, the list of
tasks and plans displayed by the outputter will be filtered to tasks and
plans whose names include the provided substring.
> (GH-1596) Filter tasks and plans by substring

- CHANGELOG.md
- Puppetfile
- lib/bolt/plugin/module.rb
- spec/fixtures/plugin_modules/my_plug/bolt_plugin.json
- spec/fixtures/plugin_modules/my_plug/tasks/resolve_reference.json
- spec/integration/plugin/module_spec.rb
This removes support for a `config` field in a plugin's
`bolt_plugin.json`. Plugins now infer config from task parameters and
pass config values as task parameters.
Blocked by https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/469
Closes #1598
> (GH-1598) Disallow config in bolt_plugin.json

- CHANGELOG.md
- Puppetfile
This bumps the versions of bundled modules with `resolve_reference`
tasks which are now set to private so they do not appear when using
`bolt task show`.
Closes #1599
> (GH-1599) Set bundled resolve_reference tasks to private

- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/linux.yaml
- .github/workflows/modules.yaml
- .github/workflows/windows.yaml
This updates the `paths-ignore` list to ignore changes to any markdown
or erb templates from any directory.
> (maint) Update paths-ignore for CI workflows

- spec/integration/apply_compile_spec.rb
The version of Puppet that supports this feature has been released so
these tests now pass.
> (maint) Mark node definition in plan tests as unpending

- acceptance/tests/plan_winrm.rb
This fixes a winrm acceptance test that is failing due to accessing a
non-existing field in a json object.
> (maint) Fix broken winrm acceptance test

- CHANGELOG.md
- documentation/bolt_installing.md
This removes installation documentation for platforms that Bolt will no
longer be supporting.
> (GH-1613) Remove install info for macOS 10.11-10.13, Fedora 28-29

- CHANGELOG.md
- lib/bolt/inventory/group.rb
The `resolve_string_targets` method was inefficient since it recomputed
the complete set of target names in the group for each target. We now
only compute the set once and keep it updated as we evaluate targets.
This saves ~0.5ms per target, which adds up when for users with
thousands or more targets.
> (maint) Load inventory more efficiently

- CHANGELOG.md
- lib/bolt/cli.rb
- spec/bolt/cli_spec.rb
This fixes a bug in the `project migrate` command that resulted in only
the first group in an array of groups having its `nodes` key replaced
with `targets`. The command now replaces `nodes` keys with `targets` in
*all* groups.
This also updates the `project migrate` command to remove any `version`
field that does not have a value of `2` from the inventory file.
Fixes #1623
> (GH-1623) Replace all 'nodes' keys with 'project migrate' command
